local _, ns = ...

-- Translations specific to my annual events AddOns
-- RWC = Remove When Complete
if ns.locale == "deDE" then
	ns.L["Achievement"] = "Erfolg"
	ns.L["Achievements"] = "Erfolge"
	ns.L["Achievements Acct"] = "Erfolge: Konto"
	ns.L["Achievements AcctDesc"] = "Die Kartenmarkierung wird nicht angezeigt, wenn ein Charakter den Erfolg abgeschlossen hat"
	ns.L["Achievements Char"] = "Erfolge: %up"
	ns.L["Achievements CharDesc"] = "Die Kartenmarkierung wird nicht angezeigt, wenn %up den Erfolg abgeschlossen hat"
	ns.L["aoaList"] = "Es ist schwierig, Charakterdaten für geteilte Erfolge zu erhalten. Insbesondere die folgenden Erfolge sind "
				.."problematisch"
	ns.L["Dailies"] = "Täglich"
	ns.L["Daily"] = "Täglich"
	ns.L["Daily Quests"] = "Tägliche Quests"
	ns.L["Daily QuestsDesc"] = "Die Kartenmarkierung wird nicht angezeigt, wenn %up die Quest heute abgeschlossen hat"
	ns.L["Guide"] = "Führung"
	ns.L["Level"] = "Stufe"
	ns.L["One Time"] = "Einmalig"
	ns.L["One Time Quests"] = "Einmalige Quests"
	ns.L["One Time QuestsDesc"] = "Die Kartenmarkierung wird nicht angezeigt, wenn %up die Quest abgeschlossen hat"
	ns.L["Quests"] = "Quests"
	ns.L["Remove When Completed"] = "Nach Abschluss Entfernen"
	ns.L["Seasonal"] = "Saisonal"
	ns.L["Seasonal Quests"] = "Saisonale Quests"
	ns.L["Seasonal QuestsDesc"] = "Die Kartenmarkierung wird nicht angezeigt, wenn %up die Quest in dieser Saison abgeschlossen hat"
	ns.L["Special"] = "Besonders"
	ns.L["Vendors"] = "Anbieter"
	ns.L["Weeklies"] = "Wöchentliche"
	ns.L["Weekly"] = "Wöchentliche"
	ns.L["Weekly Quests"] = "Wöchentliche Quests"
	ns.L["Weekly QuestsDesc"] = "Die Kartenmarkierung wird nicht angezeigt, wenn %up die Quest diese Woche abgeschlossen hat"

elseif ns.locale == "esES" or ns.locale == "esMX" then
	ns.L["Achievement"] = "Logro"
	ns.L["Achievements"] = "Logros"
	ns.L["Achievements Acct"] = "Logros: Cuenta"
	ns.L["Achievements AcctDesc"] = "El marcador del mapa no aparecerá cuando algún personaje haya completado el logro"
	ns.L["Achievements Char"] = "Logros: %up"
	ns.L["Achievements CharDesc"] = "El marcador del mapa no aparecerá cuando %up haya completado el logro"
	ns.L["aoaList"] = "Es difícil obtener datos de personajes para logros compartidos. En particular, los siguientes logros son "
				.."problemáticos."
	ns.L["Dailies"] = "Diarios"
	ns.L["Daily"] = "Diaria"
	ns.L["Daily Quests"] = "Misiones Diarias"
	ns.L["Daily QuestsDesc"] = "El marcador del mapa no aparecerá cuando %up haya completado la misión de hoy"
	ns.L["Guide"] = "Guía"
	ns.L["Level"] = "Nivel"
	ns.L["One Time"] = "Una vez"
	ns.L["One Time Quests"] = "Misiones Únicas"
	ns.L["One Time QuestsDesc"] = "El marcador del mapa no aparecerá cuando %up haya completado la misión"
	ns.L["Quests"] = "Misiones"
	ns.L["Remove When Completed"] = "Eliminar cuando se complete"
	ns.L["Seasonal"] = "Estacional"
	ns.L["Seasonal Quests"] = "Misiones de Temporada"
	ns.L["Seasonal QuestsDesc"] = "El pin del mapa no aparecerá cuando %up haya completado la misión esta temporada"
	ns.L["Special"] = "Especial"
	ns.L["Vendors"] = "Vendedores"
	ns.L["Weeklies"] = "Semanales"
	ns.L["Weekly"] = "Semanal"
	ns.L["Weekly Quests"] = "Misiones Semanal"
	ns.L["Weekly QuestsDesc"] = "El marcador del mapa no aparecerá cuando %up haya completado la misión de esta semana"

elseif ns.locale == "frFR" then
	ns.L["Achievement"] = "Réalisation"
	ns.L["Achievements"] = "Réalisations"
	ns.L["Achievements Acct"] = "Réalisations: Compte"
	ns.L["Achievements AcctDesc"] = "L'épingle de la carte n'apparaîtra pas lorsqu'un personnage aura terminé le succès"
	ns.L["Achievements Char"] = "Réalisations: %up"
	ns.L["Achievements CharDesc"] = "L'épingle de la carte n'apparaîtra pas lorsque %up aura terminé le succès"
	ns.L["aoaList"] = "Il est difficile d'obtenir des données de personnage pour les succès partagés. Les succès suivants sont "
				.."particulièrement problématiques."
	ns.L["Dailies"] = "Journalière"
	ns.L["Daily"] = "Journalière"
	ns.L["Daily Quests"] = "Quêtes Quotidiennes"
	ns.L["Daily QuestsDesc"] = "L'épingle de la carte n'apparaîtra pas lorsque %up aura terminé la quête aujourd'hui"
	ns.L["Guide"] = "Guide"
	ns.L["Level"] = "Niveau"
	ns.L["One Time"] = "Une fois"
	ns.L["One Time Quests"] = "Quêtes Uniques"
	ns.L["One Time QuestsDesc"] = "L'épingle de la carte n'apparaîtra pas lorsque %up aura terminé la quête"
	ns.L["Quests"] = "Quêtes"
	ns.L["Remove When Completed"] = "Supprimer une fois terminé"
	ns.L["Seasonal"] = "Saisonnier"
	ns.L["Seasonal Quests"] = "Quêtes Saisonnières"
	ns.L["Seasonal QuestsDesc"] = "L'épingle de la carte n'apparaîtra pas lorsque %up aura terminé la quête cette saison"
	ns.L["Special"] = "Spécial"
	ns.L["Vendors"] = "Vendeurs"
	ns.L["Weeklies"] = "Hebdomadaires"
	ns.L["Weekly"] = "Hebdomadaires"
	ns.L["Weekly Quests"] = "Quêtes Hebdomadaires"
	ns.L["Weekly QuestsDesc"] = "L'épingle de la carte n'apparaîtra pas lorsque %up aura terminé la quête cette semaine"

elseif ns.locale == "itIT" then
	ns.L["Achievement"] = "Risultato"
	ns.L["Achievements"] = "Risultati"
	ns.L["Achievements Acct"] = "Risultati: Account"
	ns.L["Achievements AcctDesc"] = "Il segnaposto sulla mappa non apparirà quando un personaggio avrà completato l'obiettivo"
	ns.L["Achievements Char"] = "Risultati: %up"
	ns.L["Achievements CharDesc"] = "Il segnaposto sulla mappa non apparirà quando %up avrà completato l'obiettivo"
	ns.L["aoaList"] = "È difficile ottenere dati sui personaggi per i risultati condivisi. In particolare, i seguenti risultati "
				.."sono problematici."
	ns.L["Dailies"] = "Giornaliera"
	ns.L["Daily"] = "Giornaliera"
	ns.L["Daily Quests"] = "Missioni Giornaliere"
	ns.L["Daily QuestsDesc"] = "Il segnaposto sulla mappa non apparirà quando %up avrà completato la missione oggi"
	ns.L["Guide"] = "Guida"
	ns.L["Level"] = "Livello"
	ns.L["One Time"] = "Una volta"
	ns.L["One Time Quests"] = "Missioni Una Tantum"
	ns.L["One Time QuestsDesc"] = "Il segnaposto sulla mappa non apparirà quando %up avrà completato la missione"
	ns.L["Quests"] = "Missioni"
	ns.L["Remove When Completed"] = "Rimuovi al termine"
	ns.L["Seasonal"] = "Stagionale"
	ns.L["Seasonal Quests"] = "Missioni Stagionali"
	ns.L["Seasonal QuestsDesc"] = "Il segnaposto sulla mappa non apparirà quando %up avrà completato la missione in questa stagione"
	ns.L["Special"] = "Speciale"
	ns.L["Vendors"] = "Venditori"
	ns.L["Weeklies"] = "Settimanali"
	ns.L["Weekly"] = "Settimanali"
	ns.L["Weekly Quests"] = "Missioni Settimanali"
	ns.L["Weekly QuestsDesc"] = "Il segnaposto sulla mappa non apparirà quando %up avrà completato la missione questa settimana"
	
elseif ns.locale == "koKR" then
	ns.L["Achievement"] = "성취"
	ns.L["Achievements"] = "업적"
	ns.L["Achievements Acct"] = "업적: 계정가"
	ns.L["Achievements AcctDesc"] = "캐릭터가 업적을 완료하면 지도 핀이 표시되지 않습니다."
	ns.L["Achievements Char"] = "업적: %up가"
	ns.L["Achievements CharDesc"] = "%up가 업적을 완료하면 지도 핀이 표시되지 않습니다."
	ns.L["aoaList"] = "공유 업적에 대한 캐릭터 데이터를 얻는 것이 어렵습니다. 특히 다음 업적은 문제가 있습니다."
	ns.L["Dailies"] = "일일"
	ns.L["Daily"] = "일일"
	ns.L["Daily Quests"] = "일일 퀘스트"
	ns.L["Daily QuestsDesc"] = "오늘 %up가 퀘스트를 완료하면 지도 핀이 표시되지 않습니다."
	ns.L["Guide"] = "가이드"
	ns.L["Level"] = "레벨"
	ns.L["One Time"] = "일회"
	ns.L["One Time Quests"] = "일회 퀘스트"
	ns.L["One Time QuestsDesc"] = "%up가 퀘스트를 완료하면 지도 핀이 표시되지 않습니다."
	ns.L["Quests"] = "퀘스트"
	ns.L["Remove When Completed"] = "완료되면 제거"
	ns.L["Seasonal"] = "계절"
	ns.L["Seasonal Quests"] = "계절 퀘스트"
	ns.L["Seasonal QuestsDesc"] = "이번 시즌 %up가 퀘스트를 완료하면 지도 핀이 표시되지 않습니다."
	ns.L["Special"] = "특별한"
	ns.L["Vendors"] = "공급업체"
	ns.L["Weeklies"] = "주간"
	ns.L["Weekly"] = "주간"
	ns.L["Weekly Quests"] = "주간 퀘스트"
	ns.L["Weekly QuestsDesc"] = "이번 주 %up가 퀘스트를 완료하면 지도 핀이 표시되지 않습니다."

elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	ns.L["Achievement"] = "Conquista"
	ns.L["Achievements"] = "Conquistas"
	ns.L["Achievements Acct"] = "Conquistas: Conta"
	ns.L["Achievements AcctDesc"] = "O pin do mapa não aparecerá quando algum personagem tiver concluído a conquista"
	ns.L["Achievements Char"] = "Conquistas: %up"
	ns.L["Achievements CharDesc"] = "O pin do mapa não aparecerá quando %up tiver concluído a conquista"
	ns.L["aoaList"] = "É difícil obter dados de personagens para conquistas compartilhadas. Em particular, as seguintes conquistas "
				.."são problemáticas"
	ns.L["Dailies"] = "Diários"
	ns.L["Daily"] = "Diário(a)"
	ns.L["Daily Quests"] = "Missões Diárias"
	ns.L["Daily QuestsDesc"] = "O pin do mapa não aparecerá quando %up completar a missão hoje"
	ns.L["Guide"] = "Guia"
	ns.L["Level"] = "Nível"
	ns.L["One Time"] = "Uma vez"
	ns.L["One Time Quests"] = "Missões Únicas"
	ns.L["One Time QuestsDesc"] = "O pin do mapa não aparecerá quando %up completar a missão"
	ns.L["Quests"] = "Missões"
	ns.L["Remove When Completed"] = "Remover quando concluído"
	ns.L["Seasonal"] = "Sazonal"
	ns.L["Seasonal Quests"] = "Missões Sazonais"
	ns.L["Seasonal QuestsDesc"] = "O pin do mapa não aparecerá quando %up completar a missão nesta temporada"
	ns.L["Special"] = "Especial"
	ns.L["Vendors"] = "Fornecedores"
	ns.L["Weeklies"] = "Semanais"
	ns.L["Weekly"] = "Semanais"
	ns.L["Weekly Quests"] = "Missões Semanais"
	ns.L["Weekly QuestsDesc"] = "O pin do mapa não aparecerá quando %up completar a missão esta semana"

elseif ns.locale == "ruRU" then
	ns.L["Achievement"] = "Достижение"
	ns.L["Achievements"] = "Достижения"
	ns.L["Achievements Acct"] = "Достижения: Счет"
	ns.L["Achievements AcctDesc"] = "Значок на карте не появится, если какой-либо персонаж выполнит достижение"
	ns.L["Achievements Char"] = "Достижения: %up"
	ns.L["Achievements CharDesc"] = "Значок на карте не появится, когда %up выполнит достижение"
	ns.L["aoaList"] = "Сложно получить данные о персонажах для общих достижений. В частности, следующие достижения являются "
				.."проблемными:"
	ns.L["Dailies"] = "Ежедневные газеты"
	ns.L["Daily"] = "Ежедневно"
	ns.L["Daily Quests"] = "Ежедневные Задания"
	ns.L["Daily QuestsDesc"] = "Значок на карте не появится, когда %up завершит квест сегодня"
	ns.L["Guide"] = "Гид"
	ns.L["Level"] = "Уровень"
	ns.L["One Time"] = "Один раз"
	ns.L["One Time Quests"] = "Разовые Задания"
	ns.L["One Time QuestsDesc"] = "Значок на карте не появится, когда %up завершит квест"
	ns.L["Quests"] = "Задания"
	ns.L["Remove When Completed"] = "Удалить По Завершении"
	ns.L["Seasonal"] = "Сезонно"
	ns.L["Seasonal Quests"] = "Сезонные Задания"
	ns.L["Seasonal QuestsDesc"] = "Значок на карте не появится, когда %up завершит квест в этом сезоне"
	ns.L["Special"] = "Особенный"
	ns.L["Vendors"] = "Продавцы"
	ns.L["Weeklies"] = "Еженедельники"
	ns.L["Weekly"] = "Еженедельно"
	ns.L["Weekly Quests"] = "Еженедельные Задания"
	ns.L["Weekly QuestsDesc"] = "Значок на карте не появится, когда %up завершит квест на этой неделе"

elseif ns.locale == "zhCN" then
	ns.L["Achievement"] = "成就"
	ns.L["Achievements"] = "成就"
	ns.L["Achievements Acct"] = "成就：帐户"
	ns.L["Achievements AcctDesc"] = "当任何角色完成成就时，地图图标将不会出现"
	ns.L["Achievements Char"] = "成就：%up"
	ns.L["Achievements CharDesc"] = "当 %up 完成成就时，地图图标将不会出现"
	ns.L["aoaList"] = "获取共享成就的角色数据比较困难。以下成就尤其容易出现问题"
	ns.L["Dailies"] = "日常"
	ns.L["Daily"] = "日常"
	ns.L["Daily Quests"] = "每日任务"
	ns.L["Daily QuestsDesc"] = "今天 %up 完成任务后，地图图标将不会出现"
	ns.L["Guide"] = "指南"
	ns.L["Level"] = "等级"
	ns.L["One Time"] = "一次性"
	ns.L["One Time Quests"] = "一次性任务"
	ns.L["One Time QuestsDesc"] = "%up 完成任务后，地图图标将不会出现"
	ns.L["Quests"] = "任务"
	ns.L["Remove When Completed"] = "完成后删除"
	ns.L["Seasonal"] = "季节性"
	ns.L["Seasonal Quests"] = "季度任务"
	ns.L["Seasonal QuestsDesc"] = "当 %up 完成本赛季的任务时，地图图标将不会出现"
	ns.L["Special"] = "特殊的"
	ns.L["Vendors"] = "商人"
	ns.L["Weeklies"] = "每周"
	ns.L["Weekly"] = "每周"
	ns.L["Weekly Quests"] = "每周任务"
	ns.L["Weekly QuestsDesc"] = "本周 %up 完成任务后，地图图标将不会出现"

elseif ns.locale == "zhTW" then
	ns.L["Achievement"] = "成就"
	ns.L["Achievements"] = "成就"
	ns.L["Achievements Acct"] = "成就：帳戶"
	ns.L["Achievements AcctDesc"] = "當任何角色完成成就時，地圖圖示將不會出現"
	ns.L["Achievements Char"] = "成就：%up"
	ns.L["Achievements CharDesc"] = "當 %up 完成成就時，地圖圖示將不會出現"
	ns.L["aoaList"] = "取得共享成就的角色資料比較困難。以下成就尤其容易出現問題"
	ns.L["Dailies"] = "日常"
	ns.L["Daily"] = "日常"
	ns.L["Daily Quests"] = "每日任務"
	ns.L["Daily QuestsDesc"] = "今天 %up 完成任務後，地圖圖示將不會出現"
	ns.L["Guide"] = "指南"
	ns.L["Level"] = "等級"
	ns.L["One Time"] = "一次性"
	ns.L["One Time Quests"] = "一次性任務"
	ns.L["One Time QuestsDesc"] = "%up 完成任務後，地圖圖示將不會出現"
	ns.L["Quests"] = "任務"
	ns.L["Remove When Completed"] = "完成後刪除"
	ns.L["Seasonal"] = "季節性"
	ns.L["Seasonal Quests"] = "季度任務"
	ns.L["Seasonal QuestsDesc"] = "當 %up 完成本賽季的任務時，地圖圖示將不會出現"
	ns.L["Special"] = "特殊的"
	ns.L["Vendors"] = "商人"
	ns.L["Weeklies"] = "每週"
	ns.L["Weekly"] = "每週"
	ns.L["Weekly Quests"] = "每週任務"
	ns.L["Weekly QuestsDesc"] = "本週 %up 完成任務後，地圖圖示將不會出現"

else
	ns.L["Achievements Acct"] = "Achievements: Account"
	ns.L["Achievements AcctDesc"] = "The map pin will not appear when any character has completed the achievement"
	ns.L["Achievements Char"] = "Achievements: %up"
	ns.L["Achievements CharDesc"] = "The map pin will not appear when %up has completed the achievement"
	ns.L["aoaList"] = "It is difficult to obtain character data for shared achievements. In particular, the following "
			.."achievements are problematic:\n\n"
	ns.L["Daily QuestsDesc"] = "The map pin will not appear when %up has completed the quest today"
	ns.L["One Time QuestsDesc"] = "The map pin will not appear when %up has completed the quest"
	ns.L["Seasonal QuestsDesc"] = "The map pin will not appear when %up has completed the quest this season"
	ns.L["Weekly QuestsDesc"] = "The map pin will not appear when %up has completed the quest this week"
end

-- ---------------------------------------------------------------------------------------------------------------------------------

function ns.MakeSetChatCommands( chatCommands )

	local commandStr = ns.L[ "ChatCommands" ]
	for i, c in ipairs( chatCommands ) do
		commandStr = commandStr ..NORMAL_FONT_COLOR_CODE ..c ..HIGHLIGHT_FONT_COLOR_CODE
		if i < #chatCommands then
			commandStr = commandStr ..", "
		end
	end
	commandStr = commandStr ..ns.L[ "ShowPanel" ]
	return { noteMenu = { type = "description", name = ns.L[ "MinimapMenu" ], order = 50, },
				separator1 = { type = "header", name = "", order = 51, },
				noteChat = { type = "description", name = commandStr, order = 52 }, }
end