local _, ns = ...

-- Translations specific to the Midsummer Fire Festival AddOn
if ns.locale == "deDE" then
	ns.L[ "A Light in Dark Places" ] = "Licht im Dunkeln"
	ns.L[ "A Thief's Reward" ] = "Der Lohn des Diebes"
	ns.L[ "AddOn Description" ] = "%eHilfe für Erfolge und Quests in %sSonnenwendfest"
	ns.L[ "Arcane" ] = "Arkan"
	ns.L[ "Blood" ] = "Blut"
	ns.L[ "Capital City Bonfires" ] = "Freudenfeuer in der Hauptstadt"
	ns.L[ "Desecrate/Extinguish" ] = "Entweihen/Löschen"
	ns.L[ "Fel" ] = "Teufels"
	ns.L[ "Fire" ] = "Feuer"
	ns.L[ "FFEK" ] = "Lodernde Flammen in den östlichen Königreichen"
	ns.L[ "FFK" ] = "Lodernde Flammen in Kalimdor"
	ns.L[ "Flickering Flames" ] = "Flackernde Flammen"
	ns.L[ "Frost" ] = "Frost"
	ns.L[ "Honor the Flames" ] = "Ehrt die Flammen"
	ns.L[ "Midsummer Fire Festival" ] = "Sonnenwendfest"
	ns.L[ "Symbol" ] = "Symbol"
	ns.L[ "The Festival of Fire" ] = "Das Fest des Feuers"
	ns.L[ "Thief's Reward" ] = "Der Lohn des Diebes"
	ns.L[ "WFEK" ] = "Glühende Feuer in den östlichen Königreichen"
	ns.L[ "WFK" ] = "Glühende Feuer in Kalimdor"
	ns.L[ "Wild Fires" ] = "Glühende Feuer"

elseif ns.locale == "esES" or ns.locale == "esMX" then
	ns.L[ "A Light in Dark Places" ] = "Una luz en la oscuridad"
	ns.L[ "A Thief's Reward" ] = "Una recompensa de ladrón"
	ns.L[ "AddOn Description" ] = "%eAyuda para logros y misiones en %sFestival del Fuego del Solsticio de Verano"
	ns.L[ "Arcane" ] = "Arcano"
	ns.L[ "Blood" ] = "Sangre"
	ns.L[ "Capital City Bonfires" ] = "Hogueras de la capital"
	ns.L[ "Desecrate/Extinguish" ] = "Profanar/Apagar"
	ns.L[ "Fel" ] = "Viles"
	ns.L[ "Fire" ] = "Fuego"
	ns.L[ "FFEK" ] = "La oscilación de las llamas de los Reinos del Este"
	ns.L[ "FFK" ] = "La oscilación de las llamas de Kalimdor"
	ns.L[ "Flickering Flames" ] = "Llamas chisporroteantes"
	ns.L[ "Frost" ] = "Escarcha"
	ns.L[ "Honor the Flames" ] = "Honra las llamas"
	ns.L[ "Midsummer Fire Festival" ] = "Festival del Fuego del Solsticio de Verano"
	ns.L[ "Symbol" ] = "Símbolo"
	ns.L[ "The Festival of Fire" ] = "El Festival del Fuego"
	ns.L[ "Thief's Reward" ] = "Una recompensa de ladrón"
	ns.L[ "WFEK" ] = "Los fuegos salvajes de los Reinos del Este"
	ns.L[ "WFK" ] = "Los fuegos salvajes de Kalimdor"
	ns.L[ "Wild Fires" ] = "Fuegos Salvajes"

elseif ns.locale == "frFR" then
	ns.L[ "A Light in Dark Places" ] = "Une lumière au sein des ombres"
	ns.L[ "A Thief's Reward" ] = "La récompense d'un voleur"
	ns.L[ "AddOn Description" ] = "%eAide pour les réalisations et les quêtes dans %sFête du Feu du solstice d'été"
	ns.L[ "Arcane" ] = "Arcane"
	ns.L[ "Blood" ] = "Sang"
	ns.L[ "Capital City Bonfires" ] = "Feux de joie dans la capitale"
	ns.L[ "Desecrate/Extinguish" ] = "Profaner/Éteindre"
	ns.L[ "Fel" ] = "Givre"
	ns.L[ "Fire" ] = "Feu"
	ns.L[ "FFEK" ] = "Flammes vacillantes dans les Royaumes de l'est"
	ns.L[ "FFK" ] = "Flammes vacillantes en Kalimdor"
	ns.L[ "Flickering Flames" ] = "Flammes vacillantes"
	ns.L[ "Frost" ] = "Grêle"
	ns.L[ "Honor the Flames" ] = "Honorer les flammes"
	ns.L[ "Midsummer Fire Festival" ] = "Fête du Feu du solstice d'été"
	ns.L[ "Symbol" ] = "Symbole"
	ns.L[ "The Festival of Fire" ] = "La fête du Feu"
	ns.L[ "Thief's Reward" ] = "La récompense d'un voleur"
	ns.L[ "WFEK" ] = "Feux sauvages dans les Royaumes de l'est"
	ns.L[ "WFK" ] = "Feux sauvages en Kalimdor"
	ns.L[ "Wild Fires" ] = "Feux sauvages"

elseif ns.locale == "itIT" then
	ns.L[ "A Light in Dark Places" ] = "Una luce al sole delle ombre"
	ns.L[ "A Thief's Reward" ] = "La Ricompensa del Ladro"
	ns.L[ "AddOn Description" ] = "%eAiuto per obiettivi e missioni in %sFuochi di Mezza Estate"
	ns.L[ "Arcane" ] = "Arcano"
	ns.L[ "Blood" ] = "Sangue"
	ns.L[ "Capital City Bonfires" ] = "Falò della capitale"
	ns.L[ "Desecrate/Extinguish" ] = "Profanare/Estinguere"
	ns.L[ "Fel" ] = "Vile"
	ns.L[ "Fire" ] = "Fuoco"
	ns.L[ "FFEK" ] = "Fiamme tremolanti nei Regni Orientali"
	ns.L[ "FFK" ] = "Fiamme tremolanti a Kalimdor"
	ns.L[ "Flickering Flames" ] = "Fiamme Lampeggianti"
	ns.L[ "Frost" ] = "Gelo"
	ns.L[ "Honor the Flames" ] = "Onora le Fiamme"
	ns.L[ "Midsummer Fire Festival" ] = "Fuochi di Mezza Estate"
	ns.L[ "Symbol" ] = "Simbolo"
	ns.L[ "The Festival of Fire" ] = "La Festa del Fuoco"
	ns.L[ "Thief's Reward" ] = "La Ricompensa del Ladro"
	ns.L[ "WFEK" ] = "Incendi boschivi nei Regni Orientali"
	ns.L[ "WFK" ] = "Incendi boschivi a Kalimdor"
	ns.L[ "Wild Fires" ] = "Incendi Selvaggi"

elseif ns.locale == "koKR" then
	ns.L[ "A Light in Dark Places" ] = "어둠을 밝히는 한 줄기 빛"
	ns.L[ "A Thief's Reward" ] = "도적의 보상"
	ns.L[ "AddOn Description" ] = "%s한여름 불꽃축제%e 업적 및 퀘스트에 대한 도움말"	
	ns.L[ "Arcane" ] = "비전"
	ns.L[ "Blood" ] = "혈기"
	ns.L[ "Capital City Bonfires" ] = "수도 모닥불"
	ns.L[ "Desecrate/Extinguish" ] = "신성모독/불꽃 끄기"
	ns.L[ "Fel" ] = "지옥"
	ns.L[ "Fire" ] = "불"
	ns.L[ "FFEK" ] = "동부 왕국의 가물거리는 불꽃"
	ns.L[ "FFK" ] = "칼림도어의 희미한 불꽃"
	ns.L[ "Flickering Flames" ] = "불꽃"
	ns.L[ "Frost" ] = "냉기"
	ns.L[ "Honor the Flames" ] = "Onora le fiamme"
	ns.L[ "Midsummer Fire Festival" ] = "한여름 불꽃축제"
	ns.L[ "Symbol" ] = "상징"
	ns.L[ "The Festival of Fire" ] = "불의 축제"
	ns.L[ "Thief's Reward" ] = "도적의 보상"
	ns.L[ "WFEK" ] = "동부 왕국의 거친 불꽃"
	ns.L[ "WFK" ] = "칼림도어의 거친 불꽃"
	ns.L[ "Wild Fires" ] = "거친 불꽃"
		
elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	ns.L[ "A Light in Dark Places" ] = "Uma luz na escuridão"
	ns.L[ "A Thief's Reward" ] = "A recompensa de um ladrão"
	ns.L[ "AddOn Description" ] = "%eAjuda para conquistas e missões em %sFestival do Fogo do Solstício"
	ns.L[ "Arcane" ] = "Arcano"
	ns.L[ "Blood" ] = "Sangue"
	ns.L[ "Capital City Bonfires" ] = "Fogueiras da Capital"
	ns.L[ "Desecrate/Extinguish" ] = "Profanar/Extinguir"
	ns.L[ "Fel" ] = "Vile"
	ns.L[ "Fire" ] = "Fogo"
	ns.L[ "FFEK" ] = "As chamas tremeluzentes dos Reinos do Leste"
	ns.L[ "FFK" ] = "As chamas tremeluzentes de Kalimdor"
	ns.L[ "Flickering Flames" ] = "Chamas Tremeluzentes"
	ns.L[ "Frost" ] = "Gelo"
	ns.L[ "Honor the Flames" ] = "Reverenciar as chamas"
	ns.L[ "Midsummer Fire Festival" ] = "Festival do Fogo do Solstício"
	ns.L[ "Symbol" ] = "Símbolo"
	ns.L[ "The Festival of Fire" ] = "O Festival do Fogo"
	ns.L[ "Thief's Reward" ] = "A recompensa de um ladrão"
	ns.L[ "WFEK" ] = "As chamas selvagens dos Reinos do Leste"
	ns.L[ "WFK" ] = "As chamas selvagens de Kalimdor"
	ns.L[ "Wild Fires" ] = "Chamas Selvagens"

elseif ns.locale == "ruRU" then
	ns.L[ "A Light in Dark Places" ] = "Свет в темных местах"
	ns.L[ "A Thief's Reward" ] = "Награда вора"
	ns.L[ "AddOn Description" ] = "%eСправка по достижениям и квестам в %sОгненный Солнцеворот"
	ns.L[ "Arcane" ] = "Тайный"
	ns.L[ "Blood" ] = "Кровь"
	ns.L[ "Capital City Bonfires" ] = "Столичные костры"
	ns.L[ "Desecrate/Extinguish" ] = "Осквернение/Потушить"
	ns.L[ "Fel" ] = "Скверна"
	ns.L[ "Fire" ] = "Огонь"
	ns.L[ "FFEK" ] = "Мерцающие огни Восточных Королевств"
	ns.L[ "FFK" ] = "Мерцающие огни Калимдора"
	ns.L[ "Flickering Flames" ] = "Вспышки Пламени"
	ns.L[ "Frost" ] = "Мороз"
	ns.L[ "Honor the Flames" ] = "Почтите огни"
	ns.L[ "Midsummer Fire Festival" ] = "Огненный Солнцеворот"
	ns.L[ "Symbol" ] = "Символ"
	ns.L[ "The Festival of Fire" ] = "Праздник Огня"
	ns.L[ "Thief's Reward" ] = "Награда вора"
	ns.L[ "WFEK" ] = "Костры Восточных Королевств"
	ns.L[ "WFK" ] = "Костры Калимдора"
	ns.L[ "Wild Fires" ] = "Костры"

elseif ns.locale == "zhCN" then
	ns.L[ "A Light in Dark Places" ] = "黑暗中的光明"
	ns.L[ "A Thief's Reward" ] = "盗贼的奖励"
	ns.L[ "AddOn Description" ] = "%e帮助%s仲夏火焰节%e的成就和任务"
	ns.L[ "Arcane" ] = "奥术"
	ns.L[ "Blood" ] = "鲜血"
	ns.L[ "Capital City Bonfires" ] = "首都篝火晚会"
	ns.L[ "Desecrate/Extinguish" ] = "亵渎/扑灭"
	ns.L[ "Fel" ] = "邪能"
	ns.L[ "Fire" ] = "火"
	ns.L[ "FFEK" ] = "东部王国的火焰"
	ns.L[ "FFK" ] = "卡利姆多的火焰"
	ns.L[ "Flickering Flames" ] = "闪烁火焰"
	ns.L[ "Frost" ] = "冰霜"
	ns.L[ "Honor the Flames" ] = "的火焰"
	ns.L[ "Midsummer Fire Festival" ] = "仲夏火焰节"
	ns.L[ "Symbol" ] = "象征"
	ns.L[ "The Festival of Fire" ] = "火焰的节日"
	ns.L[ "Thief's Reward" ] = "盗贼的奖励"
	ns.L[ "WFEK" ] = "东部王国的野火"
	ns.L[ "WFK" ] = "卡利姆多的野火"
	ns.L[ "Wild Fires" ] = "的野火"

elseif ns.locale == "zhTW" then
	ns.L[ "A Light in Dark Places" ] = "暗處之光"
	ns.L[ "A Thief's Reward" ] = "小偷的獎勵"
	ns.L[ "AddOn Description" ] = "%eHelp for the %s仲夏火焰節%e achievements and quests"
	ns.L[ "Arcane" ] = "奧術"
	ns.L[ "Blood" ] = "血"
	ns.L[ "Capital City Bonfires" ] = "首都篝火晚會"
	ns.L[ "Desecrate/Extinguish" ] = "褻瀆/撲滅"
	ns.L[ "Fel" ] = "邪能"
	ns.L[ "Fire" ] = "火"
	ns.L[ "FFEK" ] = "東部王國的閃爍火焰"
	ns.L[ "FFK" ] = "卡林多的閃爍火焰"
	ns.L[ "Flickering Flames" ] = "閃曳烈焰"
	ns.L[ "Frost" ] = "冰霜"
	ns.L[ "Honor the Flames" ] = "的火焰"
	ns.L[ "Midsummer Fire Festival" ] = "仲夏火焰節"
	ns.L[ "Symbol" ] = "象徵"
	ns.L[ "The Festival of Fire" ] = "火焰節慶"
	ns.L[ "Thief's Reward" ] = "盜賊的獎勵"
	ns.L[ "WFEK" ] = "東部王國的野火"
	ns.L[ "WFK" ] = "卡林多的野火"
	ns.L[ "Wild Fires" ] = "的野火"

else
	ns.L[ "AddOn Description" ] = "%eHelp for the %sMidsummer Fire Festival%e achievements and quests"
	ns.L[ "FFEK" ] = "Flickering Flames in the Eastern Kingdoms"
	ns.L[ "FFK" ] = "Flickering Flames in Kalimdor"
	ns.L[ "WFEK" ] = "Wild Fires in the Eastern Kingdoms"
	ns.L[ "WFK" ] = "Wild Fires in Kalimdor"
end