local lsm = LibStub("LibSharedMedia-3.0", true)

lsm:Register("font", "Augustus", "Interface\\AddOns\\SharedMedia_ClassicalFonts\\Fonts\\AUGUSTUS.TTF")
lsm:Register("font", "Caesar", "Interface\\AddOns\\SharedMedia_ClassicalFonts\\Fonts\\CAESAR.TTF")
lsm:Register("font", "Diogenes", "Interface\\AddOns\\SharedMedia_ClassicalFonts\\Fonts\\DIOGENES.ttf")
lsm:Register("font", "Capitalis Type Oasis", "Interface\\AddOns\\SharedMedia_ClassicalFonts\\Fonts\\CapitalisTypOasis.ttf")
lsm:Register("font", "Ancient Geek", "Interface\\AddOns\\SharedMedia_ClassicalFonts\\Fonts\\geek.ttf")
lsm:Register("font", "Marathon", "Interface\\AddOns\\SharedMedia_ClassicalFonts\\Fonts\\mara2v2.ttf")
lsm:Register("font", "Roman SD", "Interface\\AddOns\\SharedMedia_ClassicalFonts\\Fonts\\Roman SD.ttf")
lsm:Register("font", "Triatlhon In", "Interface\\AddOns\\SharedMedia_ClassicalFonts\\Fonts\\Triatlhon In.ttf")
lsm:Register("font", "Romanum Est", "Interface\\AddOns\\SharedMedia_ClassicalFonts\\Fonts\\Romanum Est.ttf")
lsm:Register("font", "Germanica Embossed", "Interface\\AddOns\\SharedMedia_ClassicalFonts\\Fonts\\Embossed Germanica.ttf")
lsm:Register("font", "Germanica Fluted", "Interface\\AddOns\\SharedMedia_ClassicalFonts\\Fonts\\Fluted Germanica.ttf")
lsm:Register("font", "King Arthur Legend", "Interface\\AddOns\\SharedMedia_ClassicalFonts\\Fonts\\King Arthur Legend.ttf")
lsm:Register("font", "Olde English", "Interface\\AddOns\\SharedMedia_ClassicalFonts\\Fonts\\OldeEnglish.ttf")
lsm:Register("font", "Germanica", "Interface\\AddOns\\SharedMedia_ClassicalFonts\\Fonts\\Plain Germanica.ttf")
lsm:Register("font", "Germanica Shadowed", "Interface\\AddOns\\SharedMedia_ClassicalFonts\\Fonts\\Shadowed Germanica.ttf")