
local LSM = LibStub("LibSharedMedia-3.0")
local MediaType_FONT = LSM.MediaType.FONT or "font"

LSM:Register(MediaType_FONT, "Augustus", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\AUGUSTUS.ttf]])
LSM:Register(MediaType_FONT, "Augustus Beveled", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\Augustus Beveled.ttf]])
LSM:Register(MediaType_FONT, "Caesar", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\CAESAR.ttf]])
LSM:Register(MediaType_FONT, "Diogenes", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\DIOGENES.ttf]])
LSM:Register(MediaType_FONT, "Capitalis Type Oasis", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\CapitalisTypOasis.ttf]])
LSM:Register(MediaType_FONT, "Ancient Geek", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\geek.ttf]])
LSM:Register(MediaType_FONT, "Marathon", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\mara2v2.ttf]])
LSM:Register(MediaType_FONT, "Roman SD", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\Roman SD.ttf]])
LSM:Register(MediaType_FONT, "Triatlhon In", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\Triatlhon In.ttf]])
LSM:Register(MediaType_FONT, "ROMANUM EST ALL CAPS", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\Romanum Est.ttf]])
LSM:Register(MediaType_FONT, "King Arthur Legend", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\King Arthur Legend.ttf]])
LSM:Register(MediaType_FONT, "Olde English", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\OldeEnglish.ttf]])
LSM:Register(MediaType_FONT, "Germanica", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\Plain Germanica.ttf]])
LSM:Register(MediaType_FONT, "Germanica Shadowed", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\Shadowed Germanica.ttf]])
LSM:Register(MediaType_FONT, "Germanica Embossed", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\Embossed Germanica.ttf]])
LSM:Register(MediaType_FONT, "Germanica Fluted", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\Fluted Germanica.ttf]])
LSM:Register(MediaType_FONT, "Cleopatra", [[Interface\AddOns\SharedMedia_ClassicalFonts\Fonts\Cleopatra.ttf]])