-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes-suramartelemancy/localization/

local myname, ns = ...

local L = LibStub("AceLocale-3.0"):NewLocale(myname, "ruRU")
if not L then return end

L["Astravar Harbor"] = "Гавань Астравар"
L["Evermoon Terrace"] = "Терраса Вечной Луны"
L["Falanaar"] = "Фаланаар"
L["Felsoul Hold"] = "Оплот Оскверненной Души"
L["Lunastre Estate"] = "Поместье Лунархов"
L["Moon Guard (entrance)"] = "Лунные стражи (вход)"
L["Moon Guard Stronghold"] = "Цитадель Лунных стражей"
L["Ruins of Elune'eth"] = "Руины Элун'ета"
L["Sanctum of Order"] = "Святилище Порядка"
L["Sanctum of Order (entrance)"] = "Святилище Порядка (вход)"
L["Tel'anor"] = "Тел'анор"
L["Twilight Vineyards"] = "Сумеречные виноградники"
L["Waning Crescent"] = "\"Лунный полумрак\""

