local _, ns = ...

-- Translations specific to my annual events AddOns
-- RWC = Remove When Complete
if ns.locale == "deDE" then
	ns.L["Achievement"] = "Leistung"
	ns.L["Dailies"] = "Täglich"
	ns.L["Daily"] = "Täglich"
	ns.L["Guide"] = "Führung"
	ns.L["Level"] = "Stufe"
	ns.L["One Time"] = "Einmal"
	ns.L["Quests"] = "Quests"
	ns.L["RWCQuestDailies"] = "Tägliche Quests: Entfernen, wenn %p sie abgeschlossen hat"
	ns.L["RWCQuestOneTime"] = "Einmalige Quests: Entfernen, wenn %p sie abgeschlossen hat"
	ns.L["RWCQuestSeasonal"] = "Saisonale Quests: Entfernen, wenn %p sie abgeschlossen hat"
	ns.L["RWCAchievements"] = "Erfolge: Entfernen, wenn %p sie abgeschlossen hat"
	ns.L["RWCQuestDailiesDesc"] = "Die Kartenmarkierung wird nicht angezeigt, wenn %p die Quest heute abgeschlossen hat"
	ns.L["RWCQuestOneTimeDesc"] = "Die Kartenmarkierung wird nicht angezeigt, wenn %p die Quest abgeschlossen hat"
	ns.L["RWCQuestSeasonalDesc"] = "Die Kartenmarkierung wird nicht angezeigt, wenn %p die Quest in dieser Saison abgeschlossen hat"
	ns.L["RWCAchievementsDesc"] = "Die Kartenmarkierung wird nicht angezeigt, wenn %p den Erfolg abgeschlossen hat"
	ns.L["RWCAchievementsDescAcct"] = "Die Kartenmarkierung wird nicht angezeigt, wenn ein Charakter den Erfolg abgeschlossen hat"
	ns.L["Seasonal"] = "Saisonal"
	ns.L["Special"] = "Besonders"
	ns.L["Vendors"] = "Anbieter"

elseif ns.locale == "esES" or ns.locale == "esMX" then
	ns.L["Achievement"] = "Logro"
	ns.L["Dailies"] = "Diarios"
	ns.L["Daily"] = "Diaria"
	ns.L["Guide"] = "Guía"
	ns.L["Level"] = "Nivel"
	ns.L["One Time"] = "Una vez"
	ns.L["Quests"] = "Misiones"
	ns.L["RWCQuestDailies"] = "Misiones diarias: eliminar cuando las complete %p"
	ns.L["RWCQuestOneTime"] = "Misiones únicas: eliminar cuando las complete %p"
	ns.L["RWCQuestSeasonal"] = "Misiones de temporada: eliminar cuando las complete %p"
	ns.L["RWCAchievements"] = "Logros: Eliminar cuando %p lo complete"
	ns.L["RWCQuestDailiesDesc"] = "El marcador del mapa no aparecerá cuando %p haya completado la misión de hoy"
	ns.L["RWCQuestOneTimeDesc"] = "El marcador del mapa no aparecerá cuando %p haya completado la misión"
	ns.L["RWCQuestSeasonalDesc"] = "El pin del mapa no aparecerá cuando %p haya completado la misión esta temporada"
	ns.L["RWCAchievementsDesc"] = "El marcador del mapa no aparecerá cuando %p haya completado el logro"
	ns.L["RWCAchievementsDescAcct"] = "El marcador del mapa no aparecerá cuando algún personaje haya completado el logro"
	ns.L["Seasonal"] = "Estacional"
	ns.L["Special"] = "Especial"
	ns.L["Vendors"] = "Vendedores"

elseif ns.locale == "frFR" then
	ns.L["Achievement"] = "Réalisation"
	ns.L["Dailies"] = "Journalière"
	ns.L["Daily"] = "Journalière"
	ns.L["Guide"] = "Guide"
	ns.L["Level"] = "Niveau"
	ns.L["One Time"] = "Une fois"
	ns.L["Quests"] = "Quêtes"
	ns.L["RWCQuestDailies"] = "Quêtes quotidiennes : supprimer une fois terminées par %p"
	ns.L["RWCQuestOneTime"] = "Quêtes uniques : supprimer une fois terminées par %p"
	ns.L["RWCQuestSeasonal"] = "Quêtes saisonnières : supprimer une fois terminées par %p"
	ns.L["RWCAchievements"] = "Réalisations : Supprimer une fois terminé par %p"
	ns.L["RWCQuestDailiesDesc"] = "L'épingle de la carte n'apparaîtra pas lorsque %p aura terminé la quête aujourd'hui"
	ns.L["RWCQuestOneTimeDesc"] = "L'épingle de la carte n'apparaîtra pas lorsque %p aura terminé la quête"
	ns.L["RWCQuestSeasonalDesc"] = "L'épingle de la carte n'apparaîtra pas lorsque %p aura terminé la quête cette saison"
	ns.L["RWCAchievementsDesc"] = "L'épingle de la carte n'apparaîtra pas lorsque %p aura terminé le succès"
	ns.L["RWCAchievementsDescAcct"] = "L'épingle de la carte n'apparaîtra pas lorsqu'un personnage aura terminé le succès"
	ns.L["Seasonal"] = "Saisonnier"
	ns.L["Special"] = "Spécial"
	ns.L["Vendors"] = "Vendeurs"

elseif ns.locale == "itIT" then
	ns.L["Achievement"] = "Risultato"
	ns.L["Dailies"] = "Giornaliera"
	ns.L["Daily"] = "Giornaliera"
	ns.L["Guide"] = "Guida"
	ns.L["Level"] = "Livello"
	ns.L["One Time"] = "Una volta"
	ns.L["Quests"] = "Missioni"
	ns.L["RWCQuestDailies"] = "Missioni giornaliere: vengono rimosse una volta completate da %p"
	ns.L["RWCQuestOneTime"] = "Missioni una tantum: vengono rimosse una volta completate da %p"
	ns.L["RWCQuestSeasonal"] = "Missioni stagionali: vengono rimosse una volta completate da %p"
	ns.L["RWCAchievements"] = "Risultati: rimuovi una volta completato da %p"
	ns.L["RWCQuestDailiesDesc"] = "Il segnaposto sulla mappa non apparirà quando %p avrà completato la missione oggi"
	ns.L["RWCQuestOneTimeDesc"] = "Il segnaposto sulla mappa non apparirà quando %p avrà completato la missione"
	ns.L["RWCQuestSeasonalDesc"] = "Il segnaposto sulla mappa non apparirà quando %p avrà completato la missione in questa stagione"
	ns.L["RWCAchievementsDesc"] = "Die Kartenmarkierung wird nicht angezeigt, wenn %p den Erfolg abgeschlossen hat"
	ns.L["RWCAchievementsDesc"] = "Il segnaposto sulla mappa non apparirà quando %p avrà completato l'obiettivo"
	ns.L["RWCAchievementsDescAcct"] = "Il segnaposto sulla mappa non apparirà quando un personaggio avrà completato l'obiettivo"
	ns.L["Seasonal"] = "Stagionale"
	ns.L["Special"] = "Speciale"
	ns.L["Vendors"] = "Venditori"
	
elseif ns.locale == "koKR" then
	ns.L["Achievement"] = "성취"
	ns.L["Dailies"] = "일일"
	ns.L["Daily"] = "일일"
	ns.L["Guide"] = "가이드"
	ns.L["Level"] = "레벨"
	ns.L["One Time"] = "일회"
	ns.L["Quests"] = "퀘스트"
	ns.L["RWCQuestDailies"] = "일일 퀘스트: %p가 완료 시 제거."
	ns.L["RWCQuestOneTime"] = "일회 퀘스트: %p가 완료 시 제거."
	ns.L["RWCQuestSeasonal"] = "계절 퀘스트: %p가 완료하면 제거됩니다."
	ns.L["RWCAchievements"] = "업적: %p가 완료하면 제거됩니다."
	ns.L["RWCQuestDailiesDesc"] = "오늘 %p가 퀘스트를 완료하면 지도 핀이 표시되지 않습니다."
	ns.L["RWCQuestOneTimeDesc"] = "%p가 퀘스트를 완료하면 지도 핀이 표시되지 않습니다."
	ns.L["RWCQuestSeasonalDesc"] = "이번 시즌 %p가 퀘스트를 완료하면 지도 핀이 표시되지 않습니다."
	ns.L["RWCAchievementsDesc"] = "%p가 업적을 완료하면 지도 핀이 표시되지 않습니다."
	ns.L["RWCAchievementsDescAcct"] = "캐릭터가 업적을 완료하면 지도 핀이 표시되지 않습니다."
	ns.L["Seasonal"] = "계절"
	ns.L["Special"] = "특별한"
	ns.L["Vendors"] = "공급업체"

elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	ns.L["Achievement"] = "Conquista"
	ns.L["Dailies"] = "Diários"
	ns.L["Daily"] = "Diário(a)"
	ns.L["Guide"] = "Guia"
	ns.L["Level"] = "Nível"
	ns.L["One Time"] = "Uma vez"
	ns.L["Quests"] = "Missões"
	ns.L["RWCQuestDailies"] = "Missões diárias: Remova quando concluída por %p"
	ns.L["RWCQuestOneTime"] = "Missões únicas: Remova quando concluída por %p"
	ns.L["RWCQuestSeasonal"] = "Missões sazonais: removidas quando concluídas por %p"
	ns.L["RWCAchievements"] = "Conquistas: Remover quando concluído por %p"
	ns.L["RWCQuestDailiesDesc"] = "O pin do mapa não aparecerá quando %p completar a missão hoje"
	ns.L["RWCQuestOneTimeDesc"] = "O pin do mapa não aparecerá quando %p completar a missão"
	ns.L["RWCQuestSeasonalDesc"] = "O pin do mapa não aparecerá quando %p completar a missão nesta temporada"
	ns.L["RWCAchievementsDesc"] = "O pin do mapa não aparecerá quando %p tiver concluído a conquista"
	ns.L["RWCAchievementsDescAcct"] = "O pin do mapa não aparecerá quando algum personagem tiver concluído a conquista"
	ns.L["Seasonal"] = "Sazonal"
	ns.L["Special"] = "Especial"
	ns.L["Vendors"] = "Fornecedores"

elseif ns.locale == "ruRU" then
	ns.L["Achievement"] = "Достижение"
	ns.L["Dailies"] = "Ежедневные газеты"
	ns.L["Daily"] = "Ежедневно"
	ns.L["Guide"] = "Гид"
	ns.L["Level"] = "Уровень"
	ns.L["One Time"] = "Один раз"
	ns.L["Quests"] = "Задания"
	ns.L["RWCQuestDailies"] = "Ежедневные квесты: удаляются после выполнения %p"
	ns.L["RWCQuestOneTime"] = "Одноразовые квесты: удаляются после выполнения %p"
	ns.L["RWCQuestSeasonal"] = "Сезонные квесты: удаляются после выполнения %p"
	ns.L["RWCAchievements"] = "Достижения: удалить после завершения %p"
	ns.L["RWCQuestDailiesDesc"] = "Значок на карте не появится, когда %p завершит квест сегодня"
	ns.L["RWCQuestOneTimeDesc"] = "Значок на карте не появится, когда %p завершит квест"
	ns.L["RWCQuestSeasonalDesc"] = "Значок на карте не появится, когда %p завершит квест в этом сезоне"
	ns.L["RWCAchievementsDesc"] = "Значок на карте не появится, когда %p выполнит достижение"
	ns.L["RWCAchievementsDescAcct"] = "Значок на карте не появится, если какой-либо персонаж выполнит достижение"
	ns.L["Seasonal"] = "Сезонно"
	ns.L["Special"] = "Особенный"
	ns.L["Vendors"] = "Продавцы"

elseif ns.locale == "zhCN" then
	ns.L["Achievement"] = "成就"
	ns.L["Dailies"] = "日常"
	ns.L["Daily"] = "日常"
	ns.L["Guide"] = "指南"
	ns.L["Level"] = "等级"
	ns.L["One Time"] = "一次性"
	ns.L["Quests"] = "任务"
	ns.L["RWCQuestDailies"] = "每日任务：%p 完成后屏蔽显示"
	ns.L["RWCQuestOneTime"] = "一次性任务：%p 完成后屏蔽显示"
	ns.L["RWCQuestSeasonal"] = "季节性任务：%p 完成后屏蔽显示"
	ns.L["RWCAchievements"] = "成就：%p 完成后屏蔽显示"
	ns.L["RWCQuestDailiesDesc"] = "今天 %p 完成任务后，地图图标将不会出现"
	ns.L["RWCQuestOneTimeDesc"] = "%p 完成任务后，地图图标将不会出现"
	ns.L["RWCQuestSeasonalDesc"] = "当 %p 完成本赛季的任务时，地图图标将不会出现"
	ns.L["RWCAchievementsDesc"] = "当 %p 完成成就时，地图图标将不会出现"
	ns.L["RWCAchievementsDescAcct"] = "当任何角色完成成就时，地图图标将不会出现"
	ns.L["Seasonal"] = "季节性"
	ns.L["Special"] = "特殊的"
	ns.L["Vendors"] = "商人"

elseif ns.locale == "zhTW" then
	ns.L["Achievement"] = "成就"
	ns.L["Dailies"] = "日常"
	ns.L["Daily"] = "日常"
	ns.L["Guide"] = "指南"
	ns.L["Level"] = "等級"
	ns.L["One Time"] = "一次性"
	ns.L["Quests"] = "任務"
	ns.L["RWCQuestDailies"] = "每日任務：%p 完成後屏蔽顯示"
	ns.L["RWCQuestOneTime"] = "一次任務：%p 完成後屏蔽顯示"
	ns.L["RWCQuestSeasonal"] = "季節性任務：%p 完成後屏蔽顯示"
	ns.L["RWCAchievements"] = "成就：%p 完成後屏蔽顯示"
	ns.L["RWCQuestDailiesDesc"] = "今天 %p 完成任務後，地圖圖示將不會出現"
	ns.L["RWCQuestOneTimeDesc"] = "%p 完成任務後，地圖圖示將不會出現"
	ns.L["RWCQuestSeasonalDesc"] = "當 %p 完成本賽季的任務時，地圖圖示將不會出現"
	ns.L["RWCAchievementsDesc"] = "當 %p 完成成就時，地圖圖示將不會出現"
	ns.L["RWCAchievementsDescAcct"] = "當任何角色完成成就時，地圖圖示將不會出現"
	ns.L["Seasonal"] = "季節性"
	ns.L["Special"] = "特殊的"
	ns.L["Vendors"] = "商人"

else
	ns.L["RWCQuestDailies"] = "Daily quests: Remove when completed by %p"
	ns.L["RWCQuestOneTime"] = "One Time quests: Remove when completed by %p"
	ns.L["RWCQuestSeasonal"] = "Seasonal quests: Remove when completed by %p"
	ns.L["RWCAchievements"] = "Achievements: Remove when completed by %p"
	ns.L["RWCQuestDailiesDesc"] = "The map pin will not appear when %p has completed the quest today"
	ns.L["RWCQuestOneTimeDesc"] = "The map pin will not appear when %p has completed the quest"
	ns.L["RWCQuestSeasonalDesc"] = "The map pin will not appear when %p has completed the quest this season"
	ns.L["RWCAchievementsDesc"] = "The map pin will not appear when %p has completed the achievement"
	ns.L["RWCAchievementsDescAcct"] = "The map pin will not appear when any character has completed the achievement"
end
