local _, ns = ...

-- Translations specific to the Love Is In The Air AddOn
if ns.locale == "deDE" then
--	ns.L["(Challenge)"] = ""
--	ns.L["(Nap)"] = ""
--	ns.L["(Tasty)"] = ""
	ns.L["AddOn Description"] = "%eHilfe für Erfolge und Quests in %sLiebe liegt in der Luft"
	ns.L["Crushing the Crown"] = "Die Krone zerschmettern"
	ns.L["Getaway to Scenic..."] = "Ausflug ins malerische..."
	ns.L["Getaway to Scenic Feralas"] = "Ausflug ins malerische Feralas!"
	ns.L["Getaway to Scenic Grizzly Hills"] = "Ausflug in die malerischen Grizzlyhügel!"
	ns.L["Getaway to Scenic Nagrand"] = "Ausflug ins malerische Nagrand!"
	ns.L["History"] = "Geschichte"
	ns.L["Love is in the Air"] = "Liebe liegt in der Luft"
	ns.L["Take a Look Around"] = "Einfach herumstöbern"
	ns.L["The Gift of..."] = "Die Gabe der..."
	ns.L["The Gift of Relaxation"] = "Die Gabe der Entspannung"
	ns.L["The Gift of Relief"] = "Die Gabe der Erholung"
	ns.L["The Gift of Self-Care"] = "Die Gabe der Selbstfürsorge"
	
--[[	ns.L["Angus Flagonshot"] = ""
	ns.L["Aurora Vabsley"] = ""
	ns.L["Beatrice Ripley"] = ""
	ns.L["Bratley Graston"] = ""
	ns.L["Bront Axecrusher"] = ""
	ns.L["Clarissa Buchannan"] = ""
	ns.L["Detective Snap Snagglebolt"] = ""
	ns.L["Gabbo Blinkwink"] = ""
	ns.L["Galvus Ironhammer"] = ""
	ns.L["Great White Elekk"] = ""
	ns.L["Fool For Love"] = ""
	ns.L["Halene Mistrunner"] = ""
	ns.L["Human Commoner"] = ""
	ns.L["Inspector Snip Snagglebolt"] = ""
	ns.L["Karn Goreshot"] = ""
	ns.L["Lost Puppy"] = ""
	ns.L["Lavenbloom"] = ""
	ns.L["Lovely Gifts"] = ""
	ns.L["Loving Yourself, Your Way "] = ""
	ns.L["Luciana Delgado"] = ""
	ns.L["Ning"] = ""
	ns.L["Orange Illicium"] = ""
	ns.L["Orc Commoner"] = ""
	ns.L["Rizzi"] = ""
	ns.L["Scenic Getaway Portal"] = ""
	ns.L["Simeon Griswold"] = ""
	ns.L["Soaring Windroc"] = ""
	ns.L["Sugar Orchid"] = ""
	ns.L["Swifthorn the Timid"] = ""
	ns.L["Sylandra Silverbreeze"] = ""
	ns.L["Theoderic Prescott"] = ""
	ns.L["Tokag Bonebreaker"] = ""
	ns.L["Toothy"] = ""
	ns.L["Torgando Featherhoof"] = ""
	ns.L["Troll Commoner"] = ""
	ns.L["Verilas Sunblood"] = ""
	ns.L["Vernon Whitlock"] = ""
	ns.L["Wilber Campbell"] = ""
	ns.L["Ying"] = ""
]]
elseif ns.locale == "esES" or ns.locale == "esMX" then
	ns.L["AddOn Description"] = "%eAyuda para los logros y misiones del %sAmor en el aire"
	ns.L["Crushing the Crown"] = "Aplasta La Corona"
	ns.L["Getaway to Scenic..."] = "¡Escapada a la bella..."
	ns.L["Getaway to Scenic Feralas"] = "¡Escapada a la bella Feralas!"
	ns.L["Getaway to Scenic Grizzly Hills"] = "¡Escapada a las bellas Colinas Pardas!"
	ns.L["Getaway to Scenic Nagrand"] = "¡Escapada a la bella Nagrand!"
	ns.L["History"] = "Historia"
	ns.L["Love is in the Air"] = "Amor en el aire"
	ns.L["Take a Look Around"] = "Echar un vistazo"
	ns.L["The Gift of..."] = "El regalo de..."
	ns.L["The Gift of Relaxation"] = "El regalo de la relajación"
	ns.L["The Gift of Relief"] = "El regalo del descanso"
	ns.L["The Gift of Self-Care"] = "El regalo de cuidarse a uno mismo"

elseif ns.locale == "frFR" then
	ns.L["AddOn Description"] = "%eAide pour les succès et quêtes du %sDe l’amour dans l’air"
	ns.L["Crushing the Crown"] = "Détrôner la Royale"
	ns.L["Getaway to Scenic..."] = "Portail vers la..."
	ns.L["Getaway to Scenic Feralas"] = "Vers la somptueuse Féralas !"
	ns.L["Getaway to Scenic Grizzly Hills"] = "Portail vers les somptueuses Grisonnes !"
	ns.L["Getaway to Scenic Nagrand"] = "Portail vers la somptueuse Nagrand !"
	ns.L["History"] = "Histoire"
	ns.L["Love is in the Air"] = "De l’amour dans l’air"
	ns.L["Take a Look Around"] = "Flânerie entre les étals"
	ns.L["The Gift of..."] = "Un don de..."
	ns.L["The Gift of Relaxation"] = "Un don de relaxation"
	ns.L["The Gift of Relief"] = "Un don de soulagement"
	ns.L["The Gift of Self-Care"] = "Un don pour soi"
	
elseif ns.locale == "itIT" then
	ns.L["AddOn Description"] = "%eAiuto per gli obiettivi e le missioni di %sAmore nell'Aria"
	ns.L["Crushing the Crown"] = "Distruggere le Industrie F.lli Corona"
	ns.L["Getaway to Scenic..."] = "Fuga panoramica..."
	ns.L["Getaway to Scenic Feralas"] = "Fuga panoramica a Feralas!"
	ns.L["Getaway to Scenic Grizzly Hills"] = "Fuga panoramica sui Colli Bradi!"
	ns.L["Getaway to Scenic Nagrand"] = "Fuga panoramica a Nagrand!"
	ns.L["History"] = "Storia"
	ns.L["Love is in the Air"] = "Amore nell'Aria"
	ns.L["Take a Look Around"] = "Dai un'occhiata in giro"
	ns.L["The Gift of..."] = "Il regalo del..."
	ns.L["The Gift of Relaxation"] = "Il regalo del rilassamento"
	ns.L["The Gift of Relief"] = "Il regalo del sollievo"
	ns.L["The Gift of Self-Care"] = "Il regalo della cura di sé"

elseif ns.locale == "koKR" then
	ns.L["AddOn Description"] = "%s온누리에 사랑을%e 업적 및 퀘스트에 대한 도움말"	
	ns.L["Crushing the Crown"] = "왕관사 무너뜨리기"
	ns.L["Getaway to Scenic..."] = "통하는 휴양지 차원문!..."
	ns.L["Getaway to Scenic Feralas"] =          "페랄라스로 통하는 휴양지 차원문!"
	ns.L["Getaway to Scenic Grizzly Hills"] = "회색 구릉지로 통하는 휴양지 차원문!"
	ns.L["Getaway to Scenic Nagrand"] =          "나그란드로 통하는 휴양지 차원문!"
	ns.L["History"] = "역사"
	ns.L["Love is in the Air"] = "온누리에 사랑을"
	ns.L["Take a Look Around"] = "둘러보기"
	ns.L["The Gift of..."] = "선물..."
	ns.L["The Gift of Relaxation"] = "휴식의 선물"
	ns.L["The Gift of Relief"] = "안도의 선물"
	ns.L["The Gift of Self-Care"] = "나를 위한 선물"

elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	ns.L["AddOn Description"] = "%eAjuda para conquistas e missões do %sO amor está no ar"
	ns.L["Crushing the Crown"] = "A crise da coroa"
	ns.L["Getaway to Scenic..."] = "Passeio na bela..."
	ns.L["Getaway to Scenic Feralas"] = "Passeio na bela Feralas!"
	ns.L["Getaway to Scenic Grizzly Hills"] = "Escapadinha para a bela Serra Gris!"
	ns.L["Getaway to Scenic Nagrand"] = "Passeio na bela Nagrand!"
	ns.L["History"] = "História"
	ns.L["Love is in the Air"] = "O amor está no ar"
	ns.L["Take a Look Around"] = "Dê uma olhadinha"
	ns.L["The Gift of..."] = "A dádiva do..."
	ns.L["The Gift of Relaxation"] = "A dádiva do relaxamento"
	ns.L["The Gift of Relief"] = "A dádiva do alívio"
	ns.L["The Gift of Self-Care"] = "A dádiva do autocuidado"

elseif ns.locale == "ruRU" then
	ns.L["AddOn Description"] = "%eПомощь в получении достижений и квестов %sЛюбовная лихорадка"
	ns.L["Crushing the Crown"] = "Конец Королевской компании"
	ns.L["Getaway to Scenic..."] = "ивописное место в..."
	ns.L["Getaway to Scenic Feralas"] = "Живописное место в Фераласе"
	ns.L["Getaway to Scenic Grizzly Hills"] = "Живописное место на Седых холмах"
	ns.L["Getaway to Scenic Nagrand"] = "Живописное место в Награнде"
	ns.L["History"] = "История"
	ns.L["Love is in the Air"] = "Любовная лихорадка"
	ns.L["Take a Look Around"] = "Осмотр товара"
	ns.L["The Gift of..."] = "Дар..."
	ns.L["The Gift of Relaxation"] = "Дар расслабления"
	ns.L["The Gift of Relief"] = "Дар легкого сердца"
	ns.L["The Gift of Self-Care"] = "Дар заботы о себе"

elseif ns.locale == "zhCN" then
	ns.L["AddOn Description"] = "%e帮助完成%s情人节%e成就和任务"
	ns.L["Crushing the Crown"] = "粉碎皇冠药剂公司"
	ns.L["Getaway to Scenic..."] = "前往风景秀丽的..."
	ns.L["Getaway to Scenic Feralas"] = "大美菲拉斯之旅！"
	ns.L["Getaway to Scenic Grizzly Hills"] = "大美灰熊丘陵之旅！"
	ns.L["Getaway to Scenic Nagrand"] = "大美纳格兰之旅！"
	ns.L["History"] = "历史"
	ns.L["Love is in the Air"] = "情人节"
	ns.L["Take a Look Around"] = "随意挑选"
	ns.L["The Gift of..."] = "之礼..."
	ns.L["The Gift of Relaxation"] = "闲适之礼"
	ns.L["The Gift of Relief"] = "释然之礼"
	ns.L["The Gift of Self-Care"] = "自我护理之礼"

elseif ns.locale == "zhTW" then
	ns.L["AddOn Description"] = "%e幫助完成%s情人節%e成就和任務"
	ns.L["Crushing the Crown"] = "粉碎皇冠藥劑公司"
	ns.L["Getaway to Scenic..."] = "前往風景優美的..."
	ns.L["Getaway to Scenic Feralas"] = "大美菲拉斯之旅！"
	ns.L["Getaway to Scenic Grizzly Hills"] = "大美灰熊丘陵之旅！"
	ns.L["Getaway to Scenic Nagrand"] = "大美納格蘭之旅！"
	ns.L["History"] = "歷史"
	ns.L["Love is in the Air"] = "情人節"
	ns.L["Take a Look Around"] = "隨意挑選"
	ns.L["The Gift of..."] = "之禮..."
	ns.L["The Gift of Relaxation"] = "閒適之禮"
	ns.L["The Gift of Relief"] = "釋然之禮"
	ns.L["The Gift of Self-Care"] = "自我照顧之禮"

else
	ns.L["AddOn Description"] = "%eHelp for the %sLove Is In The Air%e achievements and quests"
end