-- To update a translation please use the localization utility at:
-- http://wow.curseforge.com/addons/staggermeter/localization/

local addonName, a = ...
a.Localize = setmetatable({ }, { __index = function(_, key) return key end })
local L = a.Localize
local locale = GetLocale()
if locale == "ptBR" then -- Brazilian Portuguese
-- L["Blizzard's Configuration"] = ""
-- L["Boiling"] = ""
-- L["Current Health"] = ""
-- L["Custom Configuration"] = ""
-- L["d"] = ""
-- L["Damage Per Second"] = ""
-- L["Display Text"] = ""
-- L["d/s"] = ""
-- L["Fill Meters Based On"] = ""
-- L["Geen to Yellow at"] = ""
-- L["h"] = ""
-- L["Hide StaggerMeter when not Staggering Damage"] = ""
-- L["h/s"] = ""
-- L["Icon color may or may not coincide with %s. See Icon Color Setup."] = ""
-- L["Icon Color Setup"] = ""
-- L["Laser"] = ""
-- L["Lock StaggerMeter's Position"] = ""
-- L["Maximum Health"] = ""
-- L["Meter Height"] = ""
-- L["Meter Width"] = ""
-- L["mh"] = ""
-- L["mh/s"] = ""
-- L["None"] = ""
-- L["Note: To move the meter, hold Alt then drag the icon."] = ""
-- L["Percentage of Current Health"] = ""
-- L["Percentage of Current Health Per Second"] = ""
-- L["Percentage of Max Health"] = ""
-- L["Percentage of Max Health Per Second"] = ""
-- L["Per Second"] = ""
-- L["Red"] = ""
-- L["Right Click Icon to Show Options"] = ""
-- L["s"] = ""
-- L["Seconds Remaining"] = ""
-- L["Select Preset"] = ""
-- L["Set Values Based on Damage Staggered"] = ""
-- L["Set Values Based on % of"] = ""
-- L["Sound Played When Icon Turns %s"] = ""
-- L["StaggerMeter's Configuration"] = ""
-- L["Total"] = ""
-- L["Total Damage"] = ""
-- L["Yellow"] = ""
-- L["Yellow to Red at"] = ""

elseif locale == "frFR" then -- French
-- L["Blizzard's Configuration"] = ""
-- L["Boiling"] = ""
-- L["Current Health"] = ""
-- L["Custom Configuration"] = ""
-- L["d"] = ""
-- L["Damage Per Second"] = ""
-- L["Display Text"] = ""
-- L["d/s"] = ""
-- L["Fill Meters Based On"] = ""
-- L["Geen to Yellow at"] = ""
-- L["h"] = ""
-- L["Hide StaggerMeter when not Staggering Damage"] = ""
-- L["h/s"] = ""
-- L["Icon color may or may not coincide with %s. See Icon Color Setup."] = ""
-- L["Icon Color Setup"] = ""
-- L["Laser"] = ""
-- L["Lock StaggerMeter's Position"] = ""
-- L["Maximum Health"] = ""
-- L["Meter Height"] = ""
-- L["Meter Width"] = ""
-- L["mh"] = ""
-- L["mh/s"] = ""
-- L["None"] = ""
-- L["Note: To move the meter, hold Alt then drag the icon."] = ""
-- L["Percentage of Current Health"] = ""
-- L["Percentage of Current Health Per Second"] = ""
-- L["Percentage of Max Health"] = ""
-- L["Percentage of Max Health Per Second"] = ""
-- L["Per Second"] = ""
-- L["Red"] = ""
-- L["Right Click Icon to Show Options"] = ""
-- L["s"] = ""
-- L["Seconds Remaining"] = ""
-- L["Select Preset"] = ""
-- L["Set Values Based on Damage Staggered"] = ""
-- L["Set Values Based on % of"] = ""
-- L["Sound Played When Icon Turns %s"] = ""
-- L["StaggerMeter's Configuration"] = ""
-- L["Total"] = ""
-- L["Total Damage"] = ""
-- L["Yellow"] = ""
-- L["Yellow to Red at"] = ""

elseif locale == "deDE" then -- German
L["Blizzard's Configuration"] = "Blizzard's Configuration" -- Needs review
-- L["Boiling"] = ""
L["Current Health"] = "momentaner Gesundheit" -- Needs review
L["Custom Configuration"] = "persönliche Configuration" -- Needs review
L["d"] = "Schaden" -- Needs review
L["Damage Per Second"] = "Schaden pro Sekunde" -- Needs review
L["Display Text"] = "Text anzeigen" -- Needs review
L["d/s"] = "DpS" -- Needs review
L["Fill Meters Based On"] = "Füllt StaggerMeters basierend auf" -- Needs review
L["Geen to Yellow at"] = "Grün zu Gelb bei" -- Needs review
L["h"] = "Gesundheit" -- Needs review
L["Hide StaggerMeter when not Staggering Damage"] = "StaggerMeter wird ausgeblendet, wenn kein Schaden gestaffelt wird" -- Needs review
L["h/s"] = "Gesundheit (Dps)" -- Needs review
L["Icon color may or may not coincide with %s. See Icon Color Setup."] = "Iconfarbe kann oder kann nicht mit %s übereinstimmen. Siehe Icon-Farb-Setup." -- Needs review
L["Icon Color Setup"] = "Farb-Setup der Icons" -- Needs review
L["Laser"] = "Laser" -- Needs review
-- L["Lock StaggerMeter's Position"] = ""
L["Maximum Health"] = "maximaler Gesundheit" -- Needs review
L["Meter Height"] = "Höhe" -- Needs review
L["Meter Width"] = "Breite" -- Needs review
L["mh"] = "maximale Gesundheit" -- Needs review
L["mh/s"] = "maximale Gesundheit (Dps)" -- Needs review
L["None"] = "Keinen" -- Needs review
L["Note: To move the meter, hold Alt then drag the icon."] = "Hinweis: StaggerMeter wir durch das Icon und halten von ALT verschoben." -- Needs review
L["Percentage of Current Health"] = "Prozentsatz der momentanen Gesundheit (Total)" -- Needs review
L["Percentage of Current Health Per Second"] = "Prozentsatz der momentanen Gesundheit (Dps)" -- Needs review
L["Percentage of Max Health"] = "Prozentsatz der maximalen Gesundheit (Total)" -- Needs review
L["Percentage of Max Health Per Second"] = "Prozentsatz der maximalen Gesundheit (Dps)" -- Needs review
L["Per Second"] = "pro Sekunde" -- Needs review
L["Red"] = "Rot" -- Needs review
-- L["Right Click Icon to Show Options"] = ""
L["s"] = "s" -- Needs review
L["Seconds Remaining"] = "verbleidende Sekunden" -- Needs review
L["Select Preset"] = "Auswahl voreingestellte Profile" -- Needs review
L["Set Values Based on Damage Staggered"] = "Werte setzen, basierend auf gestaffelten Schaden" -- Needs review
L["Set Values Based on % of"] = "Festlegen von Werten auf der Grundlage von %" -- Needs review
L["Sound Played When Icon Turns %s"] = "Sound ab spielen bei gelbem Icon" -- Needs review
L["StaggerMeter's Configuration"] = "StaggerMeter's Configuration" -- Needs review
L["Total"] = "Total" -- Needs review
L["Total Damage"] = "Totaler Schaden" -- Needs review
L["Yellow"] = "Gelb" -- Needs review
L["Yellow to Red at"] = "Gelb zu Rot bei" -- Needs review

elseif locale == "itIT" then -- Italian
-- L["Blizzard's Configuration"] = ""
-- L["Boiling"] = ""
-- L["Current Health"] = ""
-- L["Custom Configuration"] = ""
-- L["d"] = ""
-- L["Damage Per Second"] = ""
-- L["Display Text"] = ""
-- L["d/s"] = ""
-- L["Fill Meters Based On"] = ""
-- L["Geen to Yellow at"] = ""
-- L["h"] = ""
-- L["Hide StaggerMeter when not Staggering Damage"] = ""
-- L["h/s"] = ""
-- L["Icon color may or may not coincide with %s. See Icon Color Setup."] = ""
-- L["Icon Color Setup"] = ""
-- L["Laser"] = ""
-- L["Lock StaggerMeter's Position"] = ""
-- L["Maximum Health"] = ""
-- L["Meter Height"] = ""
-- L["Meter Width"] = ""
-- L["mh"] = ""
-- L["mh/s"] = ""
-- L["None"] = ""
-- L["Note: To move the meter, hold Alt then drag the icon."] = ""
-- L["Percentage of Current Health"] = ""
-- L["Percentage of Current Health Per Second"] = ""
-- L["Percentage of Max Health"] = ""
-- L["Percentage of Max Health Per Second"] = ""
-- L["Per Second"] = ""
-- L["Red"] = ""
-- L["Right Click Icon to Show Options"] = ""
-- L["s"] = ""
-- L["Seconds Remaining"] = ""
-- L["Select Preset"] = ""
-- L["Set Values Based on Damage Staggered"] = ""
-- L["Set Values Based on % of"] = ""
-- L["Sound Played When Icon Turns %s"] = ""
-- L["StaggerMeter's Configuration"] = ""
-- L["Total"] = ""
-- L["Total Damage"] = ""
-- L["Yellow"] = ""
-- L["Yellow to Red at"] = ""

elseif locale == "koKR" then -- Korean
-- L["Blizzard's Configuration"] = ""
-- L["Boiling"] = ""
-- L["Current Health"] = ""
-- L["Custom Configuration"] = ""
-- L["d"] = ""
-- L["Damage Per Second"] = ""
-- L["Display Text"] = ""
-- L["d/s"] = ""
-- L["Fill Meters Based On"] = ""
-- L["Geen to Yellow at"] = ""
-- L["h"] = ""
-- L["Hide StaggerMeter when not Staggering Damage"] = ""
-- L["h/s"] = ""
-- L["Icon color may or may not coincide with %s. See Icon Color Setup."] = ""
-- L["Icon Color Setup"] = ""
-- L["Laser"] = ""
-- L["Lock StaggerMeter's Position"] = ""
-- L["Maximum Health"] = ""
-- L["Meter Height"] = ""
-- L["Meter Width"] = ""
-- L["mh"] = ""
-- L["mh/s"] = ""
-- L["None"] = ""
-- L["Note: To move the meter, hold Alt then drag the icon."] = ""
-- L["Percentage of Current Health"] = ""
-- L["Percentage of Current Health Per Second"] = ""
-- L["Percentage of Max Health"] = ""
-- L["Percentage of Max Health Per Second"] = ""
-- L["Per Second"] = ""
-- L["Red"] = ""
-- L["Right Click Icon to Show Options"] = ""
-- L["s"] = ""
-- L["Seconds Remaining"] = ""
-- L["Select Preset"] = ""
-- L["Set Values Based on Damage Staggered"] = ""
-- L["Set Values Based on % of"] = ""
-- L["Sound Played When Icon Turns %s"] = ""
-- L["StaggerMeter's Configuration"] = ""
-- L["Total"] = ""
-- L["Total Damage"] = ""
-- L["Yellow"] = ""
-- L["Yellow to Red at"] = ""

elseif locale == "esMX" then -- Latin American Spanish
-- L["Blizzard's Configuration"] = ""
-- L["Boiling"] = ""
-- L["Current Health"] = ""
-- L["Custom Configuration"] = ""
-- L["d"] = ""
-- L["Damage Per Second"] = ""
-- L["Display Text"] = ""
-- L["d/s"] = ""
-- L["Fill Meters Based On"] = ""
-- L["Geen to Yellow at"] = ""
-- L["h"] = ""
-- L["Hide StaggerMeter when not Staggering Damage"] = ""
-- L["h/s"] = ""
-- L["Icon color may or may not coincide with %s. See Icon Color Setup."] = ""
-- L["Icon Color Setup"] = ""
-- L["Laser"] = ""
-- L["Lock StaggerMeter's Position"] = ""
-- L["Maximum Health"] = ""
-- L["Meter Height"] = ""
-- L["Meter Width"] = ""
-- L["mh"] = ""
-- L["mh/s"] = ""
-- L["None"] = ""
-- L["Note: To move the meter, hold Alt then drag the icon."] = ""
-- L["Percentage of Current Health"] = ""
-- L["Percentage of Current Health Per Second"] = ""
-- L["Percentage of Max Health"] = ""
-- L["Percentage of Max Health Per Second"] = ""
-- L["Per Second"] = ""
-- L["Red"] = ""
-- L["Right Click Icon to Show Options"] = ""
-- L["s"] = ""
-- L["Seconds Remaining"] = ""
-- L["Select Preset"] = ""
-- L["Set Values Based on Damage Staggered"] = ""
-- L["Set Values Based on % of"] = ""
-- L["Sound Played When Icon Turns %s"] = ""
-- L["StaggerMeter's Configuration"] = ""
-- L["Total"] = ""
-- L["Total Damage"] = ""
-- L["Yellow"] = ""
-- L["Yellow to Red at"] = ""

elseif locale == "ruRU" then -- Russian
L["Blizzard's Configuration"] = "Стандартные настройки Blizzard"
L["Boiling"] = "Кипение"
L["Current Health"] = "текущего здоровья" -- Needs review
L["Custom Configuration"] = "Свои настройки"
L["d"] = "урона" -- Needs review
L["Damage Per Second"] = "Урон в секунду от Пошатывания" -- Needs review
L["Display Text"] = "Текст на линейке" -- Needs review
L["d/s"] = " в сек" -- Needs review
L["Fill Meters Based On"] = "Закрашивать линейку по"
L["Geen to Yellow at"] = "Зеленый к желтому на" -- Needs review
L["h"] = "здор." -- Needs review
L["Hide StaggerMeter when not Staggering Damage"] = "Скрывать линейку без Пошатывания"
L["h/s"] = "здор. (в сек)" -- Needs review
L["Icon color may or may not coincide with %s. See Icon Color Setup."] = "Цвет иконки может зависеть или не зависеть от %s. Смотри настройки в разделе \"Цвет\"." -- Needs review
L["Icon Color Setup"] = "Цвет"
L["Laser"] = "Лазер"
-- L["Lock StaggerMeter's Position"] = ""
L["Maximum Health"] = "максимального здоровья" -- Needs review
L["Meter Height"] = "Высота линейки"
L["Meter Width"] = "Длина линейки"
L["mh"] = "макс здор." -- Needs review
L["mh/s"] = "макс здор. (в сек)" -- Needs review
L["None"] = "Нет"
L["Note: To move the meter, hold Alt then drag the icon."] = "Чтобы передвинуть линейку - зажмите Alt и потащите за иконку."
L["Percentage of Current Health"] = "Процент от текущего здоровья (всего)" -- Needs review
L["Percentage of Current Health Per Second"] = "Процент от текущего здоровья (в сек)" -- Needs review
L["Percentage of Max Health"] = "Процент от максимального здоровья (всего)" -- Needs review
L["Percentage of Max Health Per Second"] = "Процент от максимального здоровья (в сек)" -- Needs review
L["Per Second"] = "в секунду" -- Needs review
L["Red"] = "Красный"
-- L["Right Click Icon to Show Options"] = ""
L["s"] = "c"
L["Seconds Remaining"] = "Секунд осталось"
L["Select Preset"] = "Выберите набор"
L["Set Values Based on Damage Staggered"] = "Значения для урона переведенного в Пошатывание" -- Needs review
L["Set Values Based on % of"] = "Значения для % от " -- Needs review
L["Sound Played When Icon Turns %s"] = "Проигрывать звук при закрашивании линейки в %s"
L["StaggerMeter's Configuration"] = "Стандартные настройки StaggerMeter"
L["Total"] = "всего" -- Needs review
L["Total Damage"] = "Общий урон в Пошатывании" -- Needs review
L["Yellow"] = "Желтый"
L["Yellow to Red at"] = "Желтый к красному на" -- Needs review

elseif locale == "zhCN" then -- Simplified Chinese
-- L["Blizzard's Configuration"] = ""
-- L["Boiling"] = ""
-- L["Current Health"] = ""
-- L["Custom Configuration"] = ""
-- L["d"] = ""
-- L["Damage Per Second"] = ""
-- L["Display Text"] = ""
-- L["d/s"] = ""
-- L["Fill Meters Based On"] = ""
-- L["Geen to Yellow at"] = ""
-- L["h"] = ""
-- L["Hide StaggerMeter when not Staggering Damage"] = ""
-- L["h/s"] = ""
-- L["Icon color may or may not coincide with %s. See Icon Color Setup."] = ""
-- L["Icon Color Setup"] = ""
-- L["Laser"] = ""
-- L["Lock StaggerMeter's Position"] = ""
-- L["Maximum Health"] = ""
-- L["Meter Height"] = ""
-- L["Meter Width"] = ""
-- L["mh"] = ""
-- L["mh/s"] = ""
-- L["None"] = ""
-- L["Note: To move the meter, hold Alt then drag the icon."] = ""
-- L["Percentage of Current Health"] = ""
-- L["Percentage of Current Health Per Second"] = ""
-- L["Percentage of Max Health"] = ""
-- L["Percentage of Max Health Per Second"] = ""
-- L["Per Second"] = ""
-- L["Red"] = ""
-- L["Right Click Icon to Show Options"] = ""
-- L["s"] = ""
-- L["Seconds Remaining"] = ""
-- L["Select Preset"] = ""
-- L["Set Values Based on Damage Staggered"] = ""
-- L["Set Values Based on % of"] = ""
-- L["Sound Played When Icon Turns %s"] = ""
-- L["StaggerMeter's Configuration"] = ""
-- L["Total"] = ""
-- L["Total Damage"] = ""
-- L["Yellow"] = ""
-- L["Yellow to Red at"] = ""

elseif locale == "esES" then -- Spanish
-- L["Blizzard's Configuration"] = ""
-- L["Boiling"] = ""
-- L["Current Health"] = ""
-- L["Custom Configuration"] = ""
-- L["d"] = ""
-- L["Damage Per Second"] = ""
-- L["Display Text"] = ""
-- L["d/s"] = ""
-- L["Fill Meters Based On"] = ""
-- L["Geen to Yellow at"] = ""
-- L["h"] = ""
-- L["Hide StaggerMeter when not Staggering Damage"] = ""
-- L["h/s"] = ""
-- L["Icon color may or may not coincide with %s. See Icon Color Setup."] = ""
-- L["Icon Color Setup"] = ""
-- L["Laser"] = ""
-- L["Lock StaggerMeter's Position"] = ""
-- L["Maximum Health"] = ""
-- L["Meter Height"] = ""
-- L["Meter Width"] = ""
-- L["mh"] = ""
-- L["mh/s"] = ""
-- L["None"] = ""
-- L["Note: To move the meter, hold Alt then drag the icon."] = ""
-- L["Percentage of Current Health"] = ""
-- L["Percentage of Current Health Per Second"] = ""
-- L["Percentage of Max Health"] = ""
-- L["Percentage of Max Health Per Second"] = ""
-- L["Per Second"] = ""
-- L["Red"] = ""
-- L["Right Click Icon to Show Options"] = ""
-- L["s"] = ""
-- L["Seconds Remaining"] = ""
-- L["Select Preset"] = ""
-- L["Set Values Based on Damage Staggered"] = ""
-- L["Set Values Based on % of"] = ""
-- L["Sound Played When Icon Turns %s"] = ""
-- L["StaggerMeter's Configuration"] = ""
-- L["Total"] = ""
-- L["Total Damage"] = ""
-- L["Yellow"] = ""
-- L["Yellow to Red at"] = ""

elseif locale == "zhTW" then -- Traditional Chinese
-- L["Blizzard's Configuration"] = ""
-- L["Boiling"] = ""
-- L["Current Health"] = ""
-- L["Custom Configuration"] = ""
-- L["d"] = ""
-- L["Damage Per Second"] = ""
-- L["Display Text"] = ""
-- L["d/s"] = ""
-- L["Fill Meters Based On"] = ""
-- L["Geen to Yellow at"] = ""
-- L["h"] = ""
-- L["Hide StaggerMeter when not Staggering Damage"] = ""
-- L["h/s"] = ""
-- L["Icon color may or may not coincide with %s. See Icon Color Setup."] = ""
-- L["Icon Color Setup"] = ""
-- L["Laser"] = ""
-- L["Lock StaggerMeter's Position"] = ""
-- L["Maximum Health"] = ""
-- L["Meter Height"] = ""
-- L["Meter Width"] = ""
-- L["mh"] = ""
-- L["mh/s"] = ""
-- L["None"] = ""
-- L["Note: To move the meter, hold Alt then drag the icon."] = ""
-- L["Percentage of Current Health"] = ""
-- L["Percentage of Current Health Per Second"] = ""
-- L["Percentage of Max Health"] = ""
-- L["Percentage of Max Health Per Second"] = ""
-- L["Per Second"] = ""
-- L["Red"] = ""
-- L["Right Click Icon to Show Options"] = ""
-- L["s"] = ""
-- L["Seconds Remaining"] = ""
-- L["Select Preset"] = ""
-- L["Set Values Based on Damage Staggered"] = ""
-- L["Set Values Based on % of"] = ""
-- L["Sound Played When Icon Turns %s"] = ""
-- L["StaggerMeter's Configuration"] = ""
-- L["Total"] = ""
-- L["Total Damage"] = ""
-- L["Yellow"] = ""
-- L["Yellow to Red at"] = ""

end