if not(GetLocale() == "zhTW") then
    return;
end

local L = WeakAuras.L

-- Options translation
L["<"] = "<"
L["<="] = "<="
L["="] = "="
L[">"] = ">"
L[">="] = ">="
L["!="] = "!="
L["10 Man Raid"] = "10人團隊"
L["25 Man Raid"] = "25人團隊"
L["5 Man Dungeon"] = "5人副本"
L["Absorb"] = "吸收"
L["Absorbed"] = "已吸收"
L["Action Usable"] = "動作可以使用"
L["Affected"] = "被影響"
L["Air"] = "風之"
L["Alive"] = "存活"
L["All Triggers"] = "全部觸發"
L["Alternate Power"] = "特殊能量"
L["Ambience"] = "環境"
L["Amount"] = "數量"
L["Any Triggers"] = "任意觸發"
L["Arena"] = "競技場"
L["Ascending"] = "升序"
L["At Least One Enemy"] = "至少一個敵人"
L["Attackable"] = "可攻擊"
L["Aura"] = "光環"
L["Aura:"] = "光環："
L["Aura Applied"] = "光環應用"
L["Aura Applied Dose"] = "光環堆疊"
L["Aura Broken"] = "光環被打破"
L["Aura Broken Spell"] = "打破光環的法術"
L["Aura Name"] = "光環名稱"
L["Aura Refresh"] = "光環刷新"
L["Aura Removed"] = "光環移除"
L["Aura Removed Dose"] = "光環效果降低"
L["Auras:"] = "光環："
L["Aura Stack"] = "光環堆疊"
L["Aura Type"] = "光環類型"
L["Automatic"] = "自動"
L["Back and Forth"] = "往返"
L["Battleground"] = "戰場"
L["Battle.net Whisper"] = "Battle.net 悄悄話"
L["BG>Raid>Party>Say"] = "戰場>團隊>小隊>說"
L["BG-System Alliance"] = "聯盟戰場機制"
L["BG-System Horde"] = "部落戰場機制"
L["BG-System Neutral"] = "中立戰場機制"
L["Blizzard Combat Text"] = "內建戰鬥文字"
L["Block"] = "格擋"
L["Blocked"] = "被格擋"
L["Blood Rune #1"] = "血魄符文 #1"
L["Blood Rune #2"] = "血魄符文 #2"
L["Blood runes"] = "血魄符文"
L["Boss Emote"] = "首領表情"
L["Bottom"] = "下"
L["Bottom Left"] = "左下"
L["Bottom Right"] = "右下"
L["Bottom to Top"] = "由下到上"
L["Bounce"] = "彈跳"
L["Bounce with Decay"] = "彈跳衰減"
L["Buff"] = "增益"
L["By |cFF69CCF0Mirrored|r of Dragonmaw(US) Horde"] = "由|cFF69CCF0Mirrored|r - Dragonmaw 部落(美服)開發"
L["Cast"] = "施法"
L["Cast Failed"] = "施法失敗"
L["Cast Start"] = "施法開始"
L["Cast Success"] = "施法成功"
L["Cast Type"] = "施法類型"
L["Center"] = "中間"
L["Centered Horizontal"] = "中間水平"
L["Centered Vertical"] = "中間垂直"
L["Channel"] = "頻道"
L["Channel (Spell)"] = "引導法術"
L["Character Type"] = "角色類型"
L["Chat Frame"] = "聊天框架"
L["Chat Message"] = "聊天訊息"
L["Children:"] = "子元素："
L["Circle"] = "圓形"
L["Circular"] = "圓形"
L["Class"] = "職業"
L["Click to close configuration"] = "點擊關閉設定"
L["Click to open configuration"] = "點擊開啟設定"
L["Combat Log"] = "戰鬥紀錄"
L["Combo Points"] = "連擊點數"
L["Conditions"] = "條件"
L["Contains"] = "包含"
L["Cooldown Progress (Item)"] = "冷卻進度(物品)"
L["Cooldown Progress (Spell)"] = "冷卻進度(法術)"
L["Cooldown Ready (Item)"] = "冷卻完成(物品)"
L["Cooldown Ready (Spell)"] = "冷卻完成(法術)"
L["Create"] = "創建物品"
L["Critical"] = "致命一擊"
L["Crowd Controlled"] = "群體控制"
L["Crushing"] = "碾壓"
L["Curse"] = "詛咒"
L["Custom"] = "自訂"
L["Custom Function"] = "自訂功能"
L["Damage"] = "傷害"
L["Damager"] = "傷害輸出"
L["Damage Shield"] = "傷害盾"
L["Damage Shield Missed"] = "傷害盾未命中"
L["Damage Split"] = "傷害分攤"
L["Death Knight"] = "死亡騎士"
L["Death Knight Rune"] = "死亡騎士符文"
L["Death Rune"] = "死亡符文"
L["Debuff"] = "減益"
L["Deflect"] = "偏斜"
L["Descending"] = "降序"
L["Destination Name"] = "目標名稱"
L["Destination Unit"] = "目標單位"
L["Disease"] = "疾病"
L["Dispel"] = "驅散"
L["Dispel Failed"] = "驅散失敗"
L["Dodge"] = "閃躲"
L["Done"] = "完成"
L["Down"] = "下"
L["Drain"] = "抽取資源"
L["Drowning"] = "溺水"
L["Druid"] = "德魯伊"
L["Dungeon Difficulty"] = "副本難度"
L["Durability Damage"] = "耐久度傷害"
L["Durability Damage All"] = "耐久性傷害所有"
L["Earth"] = "大地"
L["Eclipse Direction"] = "蝕星蔽月方向"
L["Eclipse Power"] = "蝕星蔽月能量"
L["Eclipse Type"] = "蝕星蔽月類型"
L["Emote"] = "表情"
L["Energize"] = "充能"
L["Energy"] = "能量"
L["Enrage"] = "狂怒"
L["Environmental"] = "環境"
L["Environment Type"] = "環境類型"
L["Evade"] = "閃躲"
L["Event"] = "事件"
L["Event(s)"] = "事件"
L["Every Frame"] = "所有框架"
L["Extra Amount"] = "額外數量"
L["Extra Attacks"] = "額外攻擊"
L["Extra Spell Name"] = "額外法術名稱"
L["Fade In"] = "淡入"
L["Fade Out"] = "淡出"
L["Falling"] = "掉落"
L["Fatigue"] = "疲勞"
L["Fire"] = "火焰"
L["First Tree"] = "第一個天賦"
L["Flash"] = "動畫"
L["Flip"] = "翻轉"
L["Focus"] = "專注目標/集中值"
L["Form"] = "形態"
L["Friendly"] = "友善"
L["From"] = "從"
L["Frost Rune #1"] = "冰霜符文 #1"
L["Frost Rune #2"] = "冰霜符文 #2"
L["Frost Runes"] = "冰霜符文"
L["Glancing"] = "偏斜"
L["Global Cooldown"] = "公共冷卻(GCD)"
L["Glow"] = "發光"
L["Gradient"] = "漸層"
L["Gradient Pulse"] = "漸層跳動"
L["Group"] = "群組"
L["Group %s"] = "群組%s"
L["Grow"] = "延伸"
L["Guild"] = "公會"
L["Happiness"] = "快樂值"
L["HasPet"] = "有寵物(活著)"
L["Heal"] = "治療"
L["Healer"] = "治療"
L["Health"] = "生命"
L["Health (%)"] = "生命 (%)"
L["Heroic"] = "英雄"
L["Hide"] = "隱藏"
L["Higher Than Tank"] = "高於坦克"
L["Holy Power"] = "神聖能量"
L["Hostile"] = "敵對"
L["Hostility"] = "敵意"
L["Humanoid"] = "人形態"
L["Hunter"] = "獵人"
L["Icon"] = "圖示"
L["Ignore Rune CD"] = "\"忽略符文CD\""
L["Immune"] = "免疫"
L["Include Bank"] = "包含銀行"
L["Include Charges"] = "包含使用次數"
L["Include Death Runes"] = "包括死亡符文"
L["In Combat"] = "戰鬥中"
L["Inherited"] = "繼承"
L["Inside"] = "裡面"
L["Instakill"] = "秒殺"
L["Instance Type"] = "副本類型"
L["Interrupt"] = "中斷"
L["Interruptible"] = "可中斷"
L["In Vehicle"] = "在載具"
L["Inverse"] = "反向"
L["Is Exactly"] = "完全相符"
L["Item"] = "物品"
L["Item Count"] = "物品數量"
L["Item Equipped"] = "物品已裝備"
L["Lava"] = "岩漿"
L["Leech"] = "吸取"
L["Left"] = "左"
L["Left to Right"] = "左到右"
L["Level"] = "等級"
L["Lower Than Tank"] = "低於坦克"
L["Lunar"] = "月亮"
L["Lunar Power"] = "月亮能量"
L["Mage"] = "法師"
L["Magic"] = "魔法"
L["Main Hand"] = "主手"
L["Mana"] = "法力"
L["Master"] = "主聲道"
L["Matches (Pattern)"] = "符合(表達式)"
L["Message"] = "訊息"
L["Message type:"] = "訊息類型："
L["Message Type"] = "訊息類型"
L["Miss"] = "未命中"
L["Missed"] = "未命中"
L["Missing"] = "缺少"
L["Miss Type"] = "未命中類型"
L["Monochrome"] = "單色"
L["Monster Yell"] = "怪物大喊"
L["Mounted"] = "在坐騎"
L["Multi-target"] = "多目標"
L["Music"] = "音樂"
L["Name"] = "名稱"
L["Never"] = "從不"
L["Next"] = "下一個"
L["No Children:"] = "無子元素："
L["No Instance"] = "無副本"
L["None"] = "無"
L["Non-player Character"] = "非玩家角色(NPC)"
L["Normal"] = "普通"
L["Not On Threat Table"] = "不在仇恨列表"
L["Number"] = "數字"
L["Number Affected"] = "被影響的數量"
L["Off Hand"] = "副手"
L["Officer"] = "幹部"
L["Opaque"] = "不透明"
L["Orbit"] = "軌道"
L["Outline"] = "輪廓"
L["Outside"] = "外面"
L["Overhealing"] = "過量治療"
L["Overkill"] = "過量擊殺"
L["Paladin"] = "聖騎士"
L["Parry"] = "招架"
L["Party"] = "隊伍"
L["Party Kill"] = "隊伍擊殺"
L["Paused"] = "已暫停"
L["Periodic Spell"] = "週期法術"
L["Pet"] = "寵物"
L["Player"] = "玩家"
L["Player Character"] = "玩家角色"
L["Player Class"] = "玩家職業"
L["Player Dungeon Role"] = "玩家在副本中的角色"
L["Player Level"] = "玩家等級"
L["Player Name"] = "玩家名稱"
L["Player(s) Affected"] = "玩家受影響"
L["Player(s) Not Affected"] = "玩家未被影響"
L["Poison"] = "中毒"
L["Power"] = "能量"
L["Power (%)"] = "能量(%)"
L["Power Type"] = "能量類型"
L["Preset"] = "預設"
L["Priest"] = "牧師"
L["Progress"] = "進度"
L["Pulse"] = "跳動"
L["PvP Flagged"] = "PvP 標幟"
L["Radius"] = "範圍"
L["Rage"] = "怒氣"
L["Raid"] = "團隊"
L["Raid Warning"] = "團隊警告"
L["Range"] = "距離"
L["Ranged"] = "距離"
L["Receiving display information"] = "從%s接收顯示訊息..."
L["Reference Spell"] = "參考法術"
L["Reflect"] = "反射"
L["Relative"] = "相對"
L["Remaining Time"] = "剩餘時間"
L["Requested display does not exist"] = "請求的特效不存在"
L["Requested display not authorized"] = "請求的特效無授權"
L["Require Valid Target"] = "需要有效目標"
L["Resist"] = "抵抗"
L["Resisted"] = "被抵抗"
L["Resolve collisions dialog"] = [=[你已經啟用插件定義|cFF8800FFWeakAuras|r顯示與你已存在的顯示有相同名稱。

你必須重新命名你的顯示讓插件顯示騰出空間。

已解決: |cFFFF0000]=]
L["Resolve collisions dialog singular"] = [=[你已經啟用插件定義|cFF8800FFWeakAuras|r顯示與你已存在的顯示有相同名稱。

你必須重新命名你的顯示讓插件顯示騰出空間。

已解決: |cFFFF0000]=]
L["Resolve collisions dialog startup"] = [=[你已經安裝插件定義|cFF8800FFWeakAuras|r顯示與你已存在的顯示有相同名稱。

你必須重新命名你的顯示讓插件顯示騰出空間。

已解決: |cFFFF0000]=]
L["Resolve collisions dialog startup singular"] = [=[你已經安裝插件定義|cFF8800FFWeakAuras|r顯示與你已存在的顯示有相同名稱。

你必須重新命名你的顯示讓插件顯示騰出空間。

已解決: |cFFFF0000]=]
L["Resting"] = "在休息"
L["Resurrect"] = "復活"
L["Right"] = "右"
L["Right to Left"] = "右到左"
L["Rogue"] = "盜賊"
L["Rotate Left"] = "向左旋轉"
L["Rotate Right"] = "向右旋轉"
L["Rune"] = "符文"
L["Runic Power"] = "符能"
L["Say"] = "說"
L["Seconds"] = "秒數"
L["Second Tree"] = "第二個天賦"
L["Shake"] = "震動"
L["Shaman"] = "薩滿"
L["Shards"] = "碎片"
L["Shift-Click to pause"] = "Shift點擊暫停"
L["Shift-Click to resume"] = "Shift-點擊 重新開始"
L["Show"] = "顯示"
L["Shrink"] = "收縮"
L["Slide from Bottom"] = "從下面滑動"
L["Slide from Left"] = "從左邊滑動"
L["Slide from Right"] = "從右邊滑動"
L["Slide from Top"] = "從上面滑動"
L["Slide to Bottom"] = "滑動到下面"
L["Slide to Left"] = "滑動到左邊"
L["Slide to Right"] = "滑動到右邊"
L["Slide to Top"] = "滑動到上面"
L["Slime"] = "黏液"
L["Solar"] = "太陽"
L["Solar Power"] = "太陽能量"
L["Sound Effects"] = "音效效果"
L["Source Name"] = "來源名稱"
L["Source Unit"] = "來源單位"
L["Spacing"] = "空間"
L["Specific Unit"] = "具體單位"
L["Spell"] = "法術"
L["Spell (Building)"] = "法術(創建中)"
L["Spell Name"] = "法術名稱"
L["Spin"] = "旋轉"
L["Spiral"] = "螺旋"
L["Spiral In And Out"] = "轉進和轉出"
L["Stacks"] = "堆疊"
L["Stance/Form/Aura"] = "姿態/形態/光環"
L["Status"] = "狀態"
L["Stolen"] = "被偷竊"
L["Summon"] = "召喚"
L["Swing"] = "揮動"
L["Swing Timer"] = "揮動時間"
L["Talent Specialization"] = "天賦專業"
L["Tank"] = "坦克"
L["Tanking And Highest"] = "坦怪中並且是最高"
L["Tanking But Not Highest"] = "坦怪中但不是最高"
L["Target"] = "目標"
L["Thick Outline"] = "粗輪廓"
L["Third Tree"] = "第三個天賦"
L["Threat Situation"] = "仇恨狀況"
L["Thrown"] = "投擲"
L["Timed"] = "時間"
L["Top"] = "上"
L["Top Left"] = "上左"
L["Top Right"] = "上右"
L["Top to Bottom"] = "由上到下"
L["Total"] = "總共"
L["Totem"] = "圖騰"
L["Totem Name"] = "圖騰名稱"
L["Totem Type"] = "圖騰類型"
L["Transmission error"] = "傳輸錯誤"
L["Trigger:"] = "觸發："
L["Trigger Update"] = "觸發更新"
L["Undefined"] = "未定義"
L["Unholy Rune #1"] = "穢邪符文 #1"
L["Unholy Rune #2"] = "穢邪符文 #2"
L["Unholy Runes"] = "穢邪符文"
L["Unit"] = "單位"
L["Unit Characteristics"] = "單位特徵"
L["Unit Destroyed"] = "單位破壞"
L["Unit Died"] = "單位死亡"
L["Up"] = "上"
L["Version error recevied higher"] = "顯示不相容你目前的WeakAuras版本 - 被版本%s創建，但是你是%s。請更新你的WeakAuras版本。"
L["Version error recevied lower"] = "顯示不相容你目前的WeakAuras版本 - 被版本%s創建，但是你是%s。請告知你接收的人更新到他們的WeakAuras版本。"
L["Warlock"] = "術士"
L["Warrior"] = "戰士"
L["Water"] = "水之"
L["WeakAuras"] = "WeakAuras"
L["WeakAurasModelPaths"] = "WeakAuras - 3D 模組路徑"
L["WeakAurasModelPaths .toc Notes"] = "WeakAuras的教程"
L["WeakAurasOptions"] = "WeakAuras設定"
L["WeakAurasOptions .toc Notes"] = "WeakAuras的設定"
L["WeakAuras .toc Notes"] = "強大且實用的顯示增益，減益和其它觸發的圖形和訊息。"
L["WeakAurasTutorials"] = "WeakAuras - 教程"
L["WeakAurasTutorials .toc Notes"] = "WeakAuras的模組路徑"
L["Weapon"] = "武器"
L["Weapon Enchant"] = "武器附魔"
L["Whisper"] = "悄悄話"
L["Wobble"] = "搖晃"
L["Yell"] = "大喊"
L["Zone"] = "地區"
L["Options/1 Match"] = "1符合"
L["Options/Actions"] = "動作"
L["Options/Activate when the given aura(s) |cFFFF0000can't|r be found"] = "指定的光環|cFFFF0000無法找到時|r激活"
L["Options/Add a new display"] = "新增特效"
L["Options/Add Dynamic Text"] = "新增動態文字"
L["Options/Addon"] = "插件"
L["Options/Addons"] = "插件"
L["Options/Add to group %s"] = "新增到群組%s"
L["Options/Add to new Dynamic Group"] = "新增動態群組"
L["Options/Add to new Group"] = "新增群組"
L["Options/Add Trigger"] = "新增觸發"
L["Options/A group that dynamically controls the positioning of its children"] = "可動態控制子元素位置的群組"
L["Options/Align"] = "置中"
L["Options/Allow Full Rotation"] = "允許完整旋轉"
L["Options/Alpha"] = "透明度"
L["Options/Anchor"] = "錨點"
L["Options/Anchor Point"] = "錨點指向"
L["Options/Angle"] = "角度"
L["Options/Animate"] = "閃爍"
L["Options/Animated Expand and Collapse"] = "動畫擴展和摺疊"
L["Options/Animation relative duration description"] = [=[動畫的持續時間相對持續時間的顯示，表示為一小部分(1 / 2)，百分比(50％)，或十進制(0.5)。
|cFFFF0000注意：|r 如果顯示沒有進度(它沒有時間事件觸發，是光環沒有持續時間，或其他)，動畫將不會撥放。

|cFF4444FF舉例：|r
如果動畫的持續時間設定為 |cFF00CC0010%|r，然後顯示觸發的增益持續20秒，開始動畫將會撥放2秒。
如果動畫的持續時間設定為 |cFF00CC0010%|r，然後顯示觸發的增益沒有設定持續時間，將不會撥放開始動畫(儘管這樣如果你指定動畫在數秒內)。"]=]
L["Options/Animations"] = "動畫"
L["Options/Animation Sequence"] = "動畫序列"
L["Options/Aquatic"] = "水中"
L["Options/Aura (Paladin)"] = "光環"
L["Options/Aura(s)"] = "光環"
L["Options/Auto"] = "自動"
L["Options/Auto-cloning enabled"] = "自動複製啟用"
L["Options/Automatic Icon"] = "自動圖示"
L["Options/Backdrop Color"] = "背景顏色"
L["Options/Backdrop Style"] = "背景類型"
L["Options/Background"] = "背景"
L["Options/Background Color"] = "背景顏色"
L["Options/Background Inset"] = "背景小圖"
L["Options/Background Offset"] = "背景位移"
L["Options/Background Texture"] = "背景材質"
L["Options/Bar Alpha"] = "條透明度"
L["Options/Bar Color"] = "條顏色"
L["Options/Bar Color Settings"] = "狀態條顏色設定"
L["Options/Bar in Front"] = "狀態條置頂"
L["Options/Bar Texture"] = "條材質"
L["Options/Battle"] = "戰鬥"
L["Options/Bear"] = "承受"
L["Options/Berserker"] = "狂暴"
L["Options/Blend Mode"] = "混合模式"
L["Options/Blood"] = "血魄"
L["Options/Border"] = "邊框"
L["Options/Border Color"] = "邊框顏色"
L["Options/Border Inset"] = "邊框插頁"
L["Options/Border Offset"] = "邊框位移"
L["Options/Border Settings"] = "邊框設定"
L["Options/Border Size"] = "邊框大小"
L["Options/Border Style"] = "邊框類型"
L["Options/Bottom Text"] = "底部文字"
L["Options/Button Glow"] = "按鈕發光"
L["Options/Can be a name or a UID (e.g., party1). Only works on friendly players in your group."] = "可能是名稱或是用戶名稱(例如，隊伍1)。只在你群組裡的友善玩家作用。"
L["Options/Cancel"] = "取消"
L["Options/Cat"] = "貓"
L["Options/Change the name of this display"] = "改變特效名稱"
L["Options/Channel Number"] = "頻道編號"
L["Options/Check On..."] = "檢查..."
L["Options/Choose"] = "選擇"
L["Options/Choose Trigger"] = "選擇觸發"
L["Options/Choose whether the displayed icon is automatic or defined manually"] = "選擇在特效顯示的圖示是自動或手動定義"
L["Options/Clone option enabled dialog"] = [=[你已經啟用一項設定來使用|cFFFF0000自動複製|r。

|cFFFF0000自動複製|r造成顯示自動重複來顯示多個訊息來源。
直到你讓顯示在|cFF22AA22動態群組|r，所有複製被顯示在其它所有的一大堆的上面。

你想要讓顯示被放到新的|cFF22AA22動態群組|r？]=]
L["Options/Close"] = "關閉"
L["Options/Collapse"] = "摺疊"
L["Options/Collapse all loaded displays"] = "摺疊所有已載入的特效"
L["Options/Collapse all non-loaded displays"] = "摺疊所有未載入的特效"
L["Options/Color"] = "顏色"
L["Options/Compress"] = "精簡"
L["Options/Concentration"] = "集中值"
L["Options/Constant Factor"] = "常數因子"
L["Options/Control-click to select multiple displays"] = "Ctrl點擊選擇多個特效"
L["Options/Controls the positioning and configuration of multiple displays at the same time"] = "同時控制多個特效的位置和設定"
L["Options/Convert to..."] = "轉換成..."
L["Options/Cooldown"] = "冷卻時鐘"
L["Options/Copy"] = "複製"
L["Options/Copy settings from..."] = "複製設定從..."
L["Options/Copy settings from another display"] = "從其它特效複製設定"
L["Options/Copy settings from %s"] = "從%s複製設定"
L["Options/Count"] = "計數"
L["Options/Creating buttons: "] = "創建按鈕："
L["Options/Creating options: "] = "創建設定："
L["Options/Crop X"] = "裁剪X"
L["Options/Crop Y"] = "裁剪Y"
L["Options/Crusader"] = "十字軍"
L["Options/Custom Code"] = "自訂編碼"
L["Options/Custom Trigger"] = "自訂觸發"
L["Options/Custom trigger event tooltip"] = [=[選擇用於自訂觸發檢查的事件。
多事件可以使用逗號或空格分隔開。

|cFF4444FF舉例：|r
UNIT_POWER, UNIT_AURA PLAYER_TARGET_CHANGED]=]
L["Options/Custom trigger status tooltip"] = [=[選擇用於自訂觸發檢查的事件。
這是狀態類型的觸發器，指定的事件不需預計參數就可以被WeakAuras調用。
多事件可以使用逗號或空格分隔開。

|cFF4444FF舉例：|r
UNIT_POWER, UNIT_AURA PLAYER_TARGET_CHANGED]=]
L["Options/Custom Untrigger"] = "自訂無效觸發"
L["Options/Custom untrigger event tooltip"] = [=[選擇用於自訂無效觸發檢查的事件。
它與事件觸發定義不同。
多個事件可以使用逗號或空格分隔開。

|cFF4444FF舉例：|r
UNIT_POWER, UNIT_AURA PLAYER_TARGET_CHANGED]=]
L["Options/Death"] = "死亡"
L["Options/Death Rune"] = "死亡符文"
L["Options/Debuff Type"] = "減益類型"
L["Options/Defensive"] = "防護"
L["Options/Delete"] = "刪除"
L["Options/Delete all"] = "刪除全部"
L["Options/Delete children and group"] = "刪除子元素和群組"
L["Options/Deletes this display - |cFF8080FFShift|r must be held down while clicking"] = "刪除特效 - 在點擊的時候必須按住|cFF8080FFShift|r "
L["Options/Delete Trigger"] = "刪除觸發"
L["Options/Desaturate"] = "去色"
L["Options/Devotion"] = "虔誠"
L["Options/Disabled"] = "禁用"
L["Options/Discrete Rotation"] = "分離旋轉"
L["Options/Display"] = "特效"
L["Options/Display Icon"] = "特效圖示"
L["Options/Display Text"] = "特效文字"
L["Options/Distribute Horizontally"] = "水平分佈"
L["Options/Distribute Vertically"] = "垂直分佈"
L["Options/Do not copy any settings"] = "不複製任何設定"
L["Options/Do not group this display"] = "該特效不分組"
L["Options/Duplicate"] = "複製"
L["Options/Duration Info"] = "持續時間訊息"
L["Options/Duration (s)"] = "持續時間(秒)"
L["Options/Dynamic Group"] = "動態群組"
L["Options/Dynamic text tooltip"] = [=[這裡有幾個特別的編碼允許用到文字動畫：

|cFFFF0000%p|r - 進度 - 剩餘時間的時間條或是不是時間條的數值
|cFFFF0000%t|r - 總共 - 最大時間條的持續時間或是最大不是時間條的數值
|cFFFF0000%n|r - 名稱 - 顯示名稱(通常是光環名稱)或是顯示編號如果沒有動態名稱
|cFFFF0000%i|r - 圖示 - 圖示關連到顯示
|cFFFF0000%s|r - 堆疊 - 光環堆疊數量(通常)
|cFFFF0000%c|r - 自訂 - 允許你定義一個自訂的Lua回傳字傳數值到顯示的函數]=]
L["Options/Enabled"] = "啟用"
L["Options/Enter an aura name, partial aura name, or spell id"] = "輸入光環名稱，部分光環名稱，或是法術編號"
L["Options/Event Type"] = "事件類型"
L["Options/Expand"] = "擴展"
L["Options/Expand all loaded displays"] = "展開所有已載入的特效"
L["Options/Expand all non-loaded displays"] = "展開所有未載入的特效"
L["Options/Expand Text Editor"] = "擴展文字編輯"
L["Options/Expansion is disabled because this group has no children"] = "擴展被禁用因為群組沒有子元素"
L["Options/Export"] = "匯出"
L["Options/Export to Lua table..."] = "匯出到Lua表..."
L["Options/Export to string..."] = "匯出到字串..."
L["Options/Fade"] = "淡化"
L["Options/Finish"] = "結束"
L["Options/Fire Resistance"] = "火焰抗性"
L["Options/Flight(Non-Feral)"] = "飛行(非野性)"
L["Options/Font"] = "字型"
L["Options/Font Flags"] = "字型標記"
L["Options/Font Size"] = "字型大小"
L["Options/Font Type"] = "字型類型"
L["Options/Foreground Color"] = "前景顏色"
L["Options/Foreground Texture"] = "前景材質"
L["Options/Form (Druid)"] = "形態"
L["Options/Form (Priest)"] = "形態"
L["Options/Form (Shaman)"] = "形態"
L["Options/Form (Warlock)"] = "形態"
L["Options/Frame"] = "框架"
L["Options/Frame Strata"] = "框架層級"
L["Options/Frost"] = "冰霜"
L["Options/Frost Resistance"] = "冰霜抗性"
L["Options/Full Scan"] = "完整掃描"
L["Options/Ghost Wolf"] = "鬼魂之狼"
L["Options/Glow Action"] = "發光動作"
L["Options/Group aura count description"] = [=[%s的成員總數必須受到一個或多個給予的光環為顯示觸發。
如果輸入的數字是一個整數(如5)，受影響的團隊成員數量將與輸入的數字相比。
如果輸入的數字是一個小數(如0.5)，分數(例如1/ 2)，或百分比(例如50%%)，那麼這部分的%s必須受到影響。

|cFF4444FF舉例：|r
|cFF00CC00> 0|r 會觸發當任何人在%s已被影響
|cFF00CC00= 100%%|r 會觸發當所有人在%s已被影響
|cFF00CC00!= 2|r 會觸發當%s人員數量已被影響不完全2
|cFF00CC00<= 0.8|r 會觸發當%s已被影響的少於80% (4 of 5 隊伍成員， 8 of 10 or 20 of 25 團隊成員)
|cFF00CC00> 1/2|r 會觸發當超過一半以上的%s已被影響
|cFF00CC00>= 0|r 總是觸發，不管怎樣]=]
L["Options/Group Member Count"] = "群組成員總數"
L["Options/Group (verb)"] = "群組"
L["Options/Height"] = "高度"
L["Options/Hide this group's children"] = "隱藏群組的子元素"
L["Options/Hide When Not In Group"] = "不再群組裡隱藏"
L["Options/Horizontal Align"] = "水平對齊"
L["Options/Icon Info"] = "圖示訊息"
L["Options/Ignored"] = "忽略"
L["Options/Ignore GCD"] = "忽略公共冷卻(GCD)"
L["Options/%i Matches"] = "%i符合"
L["Options/Import"] = "匯入"
L["Options/Import a display from an encoded string"] = "從編碼字串匯入特效"
L["Options/Justify"] = "對齊"
L["Options/Left Text"] = "左邊文字"
L["Options/Load"] = "載入"
L["Options/Loaded"] = "已載入"
L["Options/Main"] = "主要"
L["Options/Main Trigger"] = "主要觸發"
L["Options/Mana (%)"] = "法力(%)"
L["Options/Manage displays defined by Addons"] = "由插件管理已定義的特效"
L["Options/Message Prefix"] = "訊息字首"
L["Options/Message Suffix"] = "訊息字尾"
L["Options/Metamorphosis"] = "變形"
L["Options/Mirror"] = "鏡像"
L["Options/Model"] = "模組"
L["Options/Moonkin/Tree/Flight(Feral)"] = "梟獸/樹/飛行(野性)"
L["Options/Move Down"] = "向下移動"
L["Options/Move this display down in its group's order"] = "讓該特效的群組排序向下移動"
L["Options/Move this display up in its group's order"] = "讓該特效的群組排序向上移動"
L["Options/Move Up"] = "向上移動"
L["Options/Multiple Displays"] = "多個特效"
L["Options/Multiple Triggers"] = "多觸發"
L["Options/Multiselect ignored tooltip"] = [=[|cFFFF0000忽略|r - |cFF777777單一|r - |cFF777777多個|r
這設定將不會被使用來判斷當顯示應該載入]=]
L["Options/Multiselect multiple tooltip"] = [=[|cFFFF0000忽略|r - |cFF777777單一|r - |cFF777777多個|r
任何數量的匹配值可以被挑選]=]
L["Options/Multiselect single tooltip"] = [=[|cFFFF0000忽略|r - |cFF777777單一|r - |cFF777777多個|r
只有單一的匹配值可以被挑選]=]
L["Options/Must be spelled correctly!"] = "必須拼寫正確!"
L["Options/Name Info"] = "名稱訊息"
L["Options/Negator"] = "不"
L["Options/New"] = "新增"
L["Options/Next"] = "下一頁"
L["Options/No"] = "取消"
L["Options/No Children"] = "無子元素"
L["Options/Not all children have the same value for this option"] = "並非所有子元素對這項設定有相同的數值"
L["Options/Not Loaded"] = "未載入"
L["Options/No tooltip text"] = "取消提示資訊文字"
L["Options/% of Progress"] = "進度%"
L["Options/Okay"] = "確認"
L["Options/On Hide"] = "事件隱藏視窗時觸發"
L["Options/Only match auras cast by people other than the player"] = "只匹配其他玩家施放的光環"
L["Options/Only match auras cast by the player"] = "只匹配玩家自己施放的光環"
L["Options/On Show"] = "顯示時觸發"
L["Options/Operator"] = "運算符"
L["Options/or"] = "或"
L["Options/Orientation"] = "方向"
L["Options/Other"] = "其它"
L["Options/Outline"] = "輪廓"
L["Options/Own Only"] = "只顯示自己的"
L["Options/Player Character"] = "玩家角色"
L["Options/Play Sound"] = "播放音效"
L["Options/Presence (DK)"] = "存在"
L["Options/Presence (Rogue)"] = "存在"
L["Options/Prevents duration information from decreasing when an aura refreshes. May cause problems if used with multiple auras with different durations."] = "當光環刷新防止持續時間下降的訊息。如果使用多個光環用不同持續時間，可能會造成問題。"
L["Options/Primary"] = "主天賦"
L["Options/Progress Bar"] = "進度條"
L["Options/Progress Texture"] = "進度材質"
L["Options/Put this display in a group"] = "將其放入到某個群組中"
L["Options/Ready For Use"] = "準備使用"
L["Options/Re-center X"] = "重新置中X"
L["Options/Re-center Y"] = "重新置中Y"
L["Options/Remaining Time Precision"] = "精確剩餘時間"
L["Options/Remove this display from its group"] = "將其從群組裡移除"
L["Options/Rename"] = "重新命名"
L["Options/Requesting display information"] = "請求顯示訊息從%s..."
L["Options/Required For Activation"] = "需激活"
L["Options/Retribution"] = "懲戒"
L["Options/Right-click for more options"] = "右鍵點擊顯示更多設定"
L["Options/Right Text"] = "右邊文字"
L["Options/Rotate"] = "旋轉"
L["Options/Rotate In"] = "旋轉進入"
L["Options/Rotate Out"] = "旋轉退出"
L["Options/Rotate Text"] = "旋轉文字"
L["Options/Rotation"] = "旋轉"
L["Options/Same"] = "相同"
L["Options/Search"] = "搜尋"
L["Options/Secondary"] = "第二天賦"
L["Options/Send To"] = "發送到"
L["Options/Set tooltip description"] = "設定提示資訊文字"
L["Options/Shadow Dance"] = "暗影之舞"
L["Options/Shadowform"] = "暗影型態"
L["Options/Shadow Resistance"] = "暗影抗性"
L["Options/Shift-click to create chat link"] = "Shift-點擊 創建一個|cFF8800FF[聊天連結]"
L["Options/Show all matches (Auto-clone)"] = "顯示所有相符的(自動複製)"
L["Options/Show players that are |cFFFF0000not affected"] = "顯示|cFFFF0000未被影響|r的玩家"
L["Options/Shows a 3D model from the game files"] = "顯示遊戲檔案中的3D模組"
L["Options/Shows a custom texture"] = "顯示自訂材質"
L["Options/Shows a progress bar with name, timer, and icon"] = "顯示一個包含名稱，時間和圖示的進度條"
L["Options/Shows a spell icon with an optional a cooldown overlay"] = "顯示可選的法術圖示有冷卻時間重疊"
L["Options/Shows a texture that changes based on duration"] = "顯示根據時間變動的材質"
L["Options/Shows one or more lines of text, which can include dynamic information such as progress or stacks"] = "顯示包含動態訊息文字(例如進度或是堆疊數量,允許一行或多行)"
L["Options/Shows the remaining or expended time for an aura or timed event"] = "顯示光環或是時間事件的剩餘或是用掉時間"
L["Options/Show this group's children"] = "顯示群組的子元素"
L["Options/Size"] = "大小"
L["Options/Slide"] = "滑動"
L["Options/Slide In"] = "滑入"
L["Options/Slide Out"] = "滑出"
L["Options/Sort"] = "排序"
L["Options/Sound"] = "音效"
L["Options/Sound Channel"] = "聲道"
L["Options/Sound File Path"] = "音效檔案路徑"
L["Options/Space"] = "間隔"
L["Options/Space Horizontally"] = "橫向間隔"
L["Options/Space Vertically"] = "縱向間隔"
L["Options/Spell ID"] = "法術編號"
L["Options/Spell ID dialog"] = [=[你使用|cFFFF0000法術編號|r指定了光環。

預設情況下,|cFF8800FFWeakAuras|r無法區分相同名稱的光環名稱(這個有別於|cFFFF0000法術編號|r)。 
不過在啟用完整掃描設定後，|cFF8800FFWeakAuras|r可以搜尋指定的|cFFFF0000法術編號|r。

你確定要啟用完整掃描來匹配該cFFFF0000法術編號|r嗎？]=]
L["Options/Stack Count"] = "堆疊數量"
L["Options/Stack Count Position"] = "堆疊數量位置"
L["Options/Stack Info"] = "堆疊訊息"
L["Options/Stacks Settings"] = "堆疊設定"
L["Options/Stagger"] = "交錯"
L["Options/Stance (Warrior)"] = "姿態"
L["Options/Start"] = "開始"
L["Options/Stealable"] = "可法術竊取"
L["Options/Stealthed"] = "潛行"
L["Options/Sticky Duration"] = "置頂時間"
L["Options/Temporary Group"] = "臨時群組"
L["Options/Text"] = "文字"
L["Options/Text Color"] = "文字顏色"
L["Options/Text Position"] = "文字定位"
L["Options/Text Settings"] = "文字設定"
L["Options/Texture"] = "材質"
L["Options/The children of this group have different display types, so their display options cannot be set as a group."] = "群組的子元素有不同的特效類型，所以特效的選項無法設定到群組。"
L["Options/The duration of the animation in seconds."] = "動畫的持續時間(秒)。"
L["Options/The type of trigger"] = "觸發類型"
L["Options/This condition will not be tested"] = "該條件不會被測試"
L["Options/This display is currently loaded"] = "目前已載入的特效"
L["Options/This display is not currently loaded"] = "目前未載入的特效"
L["Options/This display will only show when |cFF00FF00%s"] = "該特效僅在|cFF00FF00 %s 時才會顯示"
L["Options/This display will only show when |cFFFF0000 Not %s"] = "該特效僅在|cFF00FF00不是%s 時才會顯示"
L["Options/This region of type \"%s\" has no configuration options."] = "這地區類型\"%s\"沒有設定選項。"
L["Options/Time in"] = "時間"
L["Options/Timer"] = "計時器"
L["Options/Timer Settings"] = "計時器設定"
L["Options/Toggle the visibility of all loaded displays"] = "切換所有已載入特效的可見狀態"
L["Options/Toggle the visibility of all non-loaded displays"] = "切換所有未載入特效的可見狀態"
L["Options/Toggle the visibility of this display"] = "切換特效的可見狀態"
L["Options/to group's"] = "到群組"
L["Options/Tooltip"] = "提示資訊"
L["Options/Tooltip on Mouseover"] = "滑鼠經過提示"
L["Options/Top Text"] = "頂部文字"
L["Options/to screen's"] = "到螢幕"
L["Options/Total Time Precision"] = "總共時間精度"
L["Options/Tracking"] = "追蹤"
L["Options/Travel"] = "旅行形態"
L["Options/Trigger"] = "觸發"
L["Options/Trigger %d"] = "觸發%d"
L["Options/Triggers"] = "觸發"
L["Options/Type"] = "類型"
L["Options/Ungroup"] = "移出群組"
L["Options/Unholy"] = "穢邪"
L["Options/Unit Exists"] = "單位存在"
L["Options/Unlike the start or finish animations, the main animation will loop over and over until the display is hidden."] = "不同於開始或結束的動畫，主要動畫將重複循環直到特效被隱藏。"
L["Options/Unstealthed"] = "未潛行"
L["Options/Update Custom Text On..."] = "更新自訂文字在..."
L["Options/Use Full Scan (High CPU)"] = "使用完整掃描(高CPU)"
L["Options/Use tooltip \"size\" instead of stacks"] = "使用提示資訊中的數字代替堆疊數量"
L["Options/Vertical Align"] = "垂直對齊"
L["Options/View"] = "檢視"
L["Options/Width"] = "寬度"
L["Options/X Offset"] = "X位移"
L["Options/X Scale"] = "X比例"
L["Options/Yes"] = "是的"
L["Options/Y Offset"] = "Y位移"
L["Options/Y Scale"] = "Y 刻度"
L["Options/Z Offset"] = "Z位移"
L["Options/Zoom"] = "縮放"
L["Options/Zoom In"] = "放大"
L["Options/Zoom Out"] = "縮小"
L["Tutorials/Actions and Animations: 1/7"] = "動作和動畫：1/7"
L["Tutorials/Actions and Animations: 2/7"] = "動作和動畫：2/7"
L["Tutorials/Actions and Animations: 3/7"] = "動作和動畫：3/7"
L["Tutorials/Actions and Animations: 4/7"] = "動作和動畫：4/7"
L["Tutorials/Actions and Animations: 5/7"] = "動作和動畫：5/7"
L["Tutorials/Actions and Animations: 6/7"] = "動作和動畫：6/7"
L["Tutorials/Actions and Animations: 7/7"] = "動作和動畫：7/7"
L["Tutorials/Actions and Animations Text"] = [=[你可以使用側欄的檢視按鈕測試特效的動畫，可以選擇隱藏或者重新顯示。

點擊它可以看到動畫開始。]=]
L["Tutorials/Activation Settings: 1/5"] = "激活設定：1/5"
L["Tutorials/Activation Settings: 2/5"] = "激活設定：2/5"
L["Tutorials/Activation Settings: 3/5"] = "激活設定：3/5"
L["Tutorials/Activation Settings: 4/5"] = "激活設定：4/5"
L["Tutorials/Activation Settings: 5/5"] = "激活設定：5/5"
L["Tutorials/Activation Settings Text"] = "當你是%s，你可以啟用玩家職業設定並選擇%s。"
L["Tutorials/Auto-cloning: 1/10"] = "自動複製：1/10"
-- L["Tutorials/Auto-cloning 1/10 Text"] = ""
-- L["Tutorials/Beginners Finished Text"] = ""
L["Tutorials/Beginners Guide Desc"] = "新手指南"
L["Tutorials/Beginners Guide Desc Text"] = "透過WeakAuras的基礎設定選項教程"
L["Tutorials/Create a Display: 1/5"] = "創建一個特效: 1/5"
L["Tutorials/Create a Display: 2/5"] = "創建一個特效: 2/5"
L["Tutorials/Create a Display: 3/5"] = "創建一個特效: 3/5"
L["Tutorials/Create a Display: 4/5"] = "創建一個特效: 4/5"
L["Tutorials/Create a Display: 5/5"] = "創建一個特效: 5/5"
-- L["Tutorials/Create a Display Text"] = ""
L["Tutorials/Display Options: 1/4"] = "特效設定: 1/4"
L["Tutorials/Display Options 1/4 Text"] = "現在,選擇一個進度條特效(或創建一個新的)."
L["Tutorials/Display Options: 2/4"] = "特效設定: 2/4"
L["Tutorials/Display Options 2/4 Text"] = [=[現在有一個選項，開啟滑鼠停留於特效的|cFFFFFFFF進度條|r和|cFFFFFFFF圖示|r時顯示相關的提示資訊。

該選項僅在你的特效使用一個基於光環/物品/法術的觸發器時可用。]=]
L["Tutorials/Display Options: 4/4"] = "特效設定: 4/4"
L["Tutorials/Display Options 4/4 Text"] = "最後,這是一個新的特效類型,|cFFFFFFFF模組|r,允許你使用來自遊戲檔案的任意3D模組."
L["Tutorials/Dynamic Group Options: 2/4"] = "動態群組設定：2/4"
-- L["Tutorials/Dynamic Group Options 2/4 Text"] = ""
L["Tutorials/Dynamic Group Options: 3/4"] = "動態群組設定：3/4"
-- L["Tutorials/Dynamic Group Options 3/4 Text"] = ""
L["Tutorials/Dynamic Group Options: 4/4"] = "動態群組設定：4/4"
-- L["Tutorials/Dynamic Group Options 4/4 Text"] = ""
L["Tutorials/Finished"] = "已結束"
L["Tutorials/Full-scan Auras: 2/10"] = "完整掃描光環：2/10"
L["Tutorials/Full-scan Auras 2/10 Text"] = "首先，啟用完整掃描設定。"
L["Tutorials/Full-scan Auras: 3/10"] = "完整掃描光環：3/10"
-- L["Tutorials/Full-scan Auras 3/10 Text"] = ""
L["Tutorials/Full-scan Auras: 4/10"] = "完整掃描光環：4/10"
-- L["Tutorials/Full-scan Auras 4/10 Text"] = ""
L["Tutorials/Full-scan Auras: 5/10"] = "完整掃描光環：5/10"
L["Tutorials/Full-scan Auras 5/10 Text"] = "禁用完整掃描來重新啟用其它單位設定選項。"
L["Tutorials/Group Auras 6/10"] = "群組光環：6/10"
L["Tutorials/Group Auras 6/10 Text"] = "現在，選擇\"群組\"進行單位設定。"
L["Tutorials/Group Auras: 7/10"] = "群組光環：7/10"
-- L["Tutorials/Group Auras 7/10 Text"] = ""
L["Tutorials/Group Auras: 8/10"] = "群組光環：8/10"
-- L["Tutorials/Group Auras 8/10 Text"] = ""
L["Tutorials/Home"] = "首頁"
L["Tutorials/Multi-target Auras: 10/10"] = "多目標光環：10/10"
-- L["Tutorials/Multi-target Auras 10/10 Text"] = ""
L["Tutorials/Multi-target Auras: 9/10"] = "多目標光環：9/10"
L["Tutorials/Multi-target Auras 9/10 Text"] = "最後，為單位設定選擇\"多個目標\"。"
L["Tutorials/New in 1.4:"] = "在 1.4 版的新東西："
L["Tutorials/New in 1.4 Desc:"] = "在1.4版的新東西："
L["Tutorials/New in 1.4 Desc Text"] = "看WeakAuras 1.4 的新功能"
-- L["Tutorials/New in 1.4 Finnished Text"] = ""
L["Tutorials/New in 1.4 Text1"] = [=[|cFF8800FFWeakAuras|r 1.4版新功能介紹。

本教程將詳細介紹重要的新功能以及如何使用它們。]=]
L["Tutorials/New in 1.4 Text2"] = "首先，建立一個用於示範目的的新顯示 。"
L["Tutorials/Previous"] = "上一頁"
L["Tutorials/Trigger Options: 1/4"] = "觸發設定：1/4"
-- L["Tutorials/Trigger Options 1/4 Text"] = ""
L["Tutorials/Trigger Options: 2/4"] = "觸發設定：2/4"
-- L["Tutorials/Trigger Options 2/4 Text"] = ""
L["Tutorials/Trigger Options: 3/4"] = "觸發設定：3/4"
-- L["Tutorials/Trigger Options 3/4 Text"] = ""
L["Tutorials/Trigger Options: 4/4"] = "觸發設定：4/4"
-- L["Tutorials/Trigger Options 4/4 Text"] = ""
L["Tutorials/WeakAuras Tutorials"] = "WeakAuras 教程"
L["Tutorials/Welcome"] = "歡迎"
L["Tutorials/Welcome Text"] = [=[歡迎使用 |cFF8800FFWeakAuras|r 入門指南。

本指南將顯示如何使用WeakAuras，並解釋基本的設定選項。

]=]



