if not(GetLocale() == "ruRU") then
    return;
end

local L = WeakAuras.L

-- Options translation
L["<"] = "<"
L["<="] = "<="
L["="] = "="
L[">"] = ">"
L[">="] = ">="
L["!="] = "!="
L["10 Man Raid"] = "Рейд на 10 человек"
L["25 Man Raid"] = "Рейд на 25 человек"
L["5 Man Dungeon"] = "Подземелье на 5 человек"
L["Absorb"] = "Поглощение"
L["Absorbed"] = "Поглощено"
L["Action Usable"] = "Действие возможно"
L["Affected"] = "Задействовано"
L["Air"] = "Воздух"
L["Alive"] = "Живой"
L["All Triggers"] = "Все Триггеры"
L["Alternate Power"] = "Альтернативная Энергия"
L["Ambience"] = "Окружение"
L["Amount"] = "Количество"
L["Any Triggers"] = "Любые Тригеры"
L["Arena"] = "Арена"
L["Ascending"] = "По Возрастанию"
L["At Least One Enemy"] = "По Крайней Мере Один Враг"
L["Attackable"] = "Уязвимый"
L["Aura"] = "Аура"
L["Aura:"] = "Эффект:"
L["Aura Applied"] = "Эффект Наложен"
L["Aura Applied Dose"] = "Стак Эффекта Наложен"
L["Aura Broken"] = "Эффект Прерван"
L["Aura Broken Spell"] = "Эффект Прерван Заклинанием"
L["Aura Name"] = "Название Эффекта"
L["Aura Refresh"] = "Эффект обновлен"
L["Aura Removed"] = "Эффект Закончился"
L["Aura Removed Dose"] = "Стак Эффекта Спал"
L["Auras:"] = "Эффекты:"
L["Aura Stack"] = "Стак Эффекта"
L["Aura Type"] = "Тип Эффекта"
L["Automatic"] = "Автоматически"
L["Back and Forth"] = "Назад и Вперед"
L["Battleground"] = "Поле Боя"
L["Battle.net Whisper"] = "Шепот Battle.net"
L["BG>Raid>Party>Say"] = "ПБ>Рейд>Группа>Сказать"
-- L["BG-System Alliance"] = ""
-- L["BG-System Horde"] = ""
-- L["BG-System Neutral"] = ""
L["Blizzard Combat Text"] = "Журнал Боя Blizzard"
L["Block"] = "Блок"
L["Blocked"] = "Заблокированно"
L["Blood Rune #1"] = "Руна Крови #1"
L["Blood Rune #2"] = "Руна Крови #2"
L["Blood runes"] = "Руны Крови"
L["Boss Emote"] = "Эмоция Босса"
L["Bottom"] = "Снизу"
L["Bottom Left"] = "Снизу Слева"
L["Bottom Right"] = "Снизу Справа"
L["Bottom to Top"] = "Снизу Вверх"
L["Bounce"] = "Отскок"
L["Bounce with Decay"] = "Отскок с затуханием"
L["Buff"] = "Бафф"
L["By |cFF69CCF0Mirrored|r of Dragonmaw(US) Horde"] = "Автор |cFF69CCF0Mirrored|r с Dragonmaw(US) Орда"
L["Cast"] = "Каст"
L["Cast Failed"] = "Каст Прерван"
L["Cast Start"] = "Начало Каста"
L["Cast Success"] = "Каст Завершен"
L["Cast Type"] = "Тип Каста"
L["Center"] = "Центр"
L["Centered Horizontal"] = "Горизонтально по Центру"
L["Centered Vertical"] = "Вертикально по Центру"
L["Channel"] = "Канал"
L["Channel (Spell)"] = "Потоковое"
L["Character Type"] = "Тип персонажа"
L["Chat Frame"] = "Окно Чата"
L["Chat Message"] = "Сообщение в Чат"
L["Children:"] = "Дети:"
L["Circle"] = "Круг"
L["Circular"] = "Круговой"
L["Class"] = "Класс"
L["Click to close configuration"] = "Нажмите чтобы закрыть настройки"
L["Click to open configuration"] = "Нажмите чтобы открыть настройки"
L["Combat Log"] = "Журнал Боя"
L["Combo Points"] = "Серия Приемов"
L["Conditions"] = "Условия"
L["Contains"] = "Содержит"
L["Cooldown Progress (Item)"] = "Время Перезарядки (Предмет)"
L["Cooldown Progress (Spell)"] = "Время Перезарядки (Заклинание)"
L["Cooldown Ready (Item)"] = "Перезарядка завершена (предмет)"
L["Cooldown Ready (Spell)"] = "Перезарядка завершена (заклинание)"
L["Create"] = "Создать"
L["Critical"] = "Критический"
L["Crowd Controlled"] = "Массовый Контроль"
L["Crushing"] = "Сокрушение"
L["Curse"] = "Проклятие"
L["Custom"] = "Самостоятельно"
L["Custom Function"] = "Своя Функция"
L["Damage"] = "Урон"
L["Damager"] = "Атакующий"
L["Damage Shield"] = "Урон в Щит"
L["Damage Shield Missed"] = "Урон в Щит Мимо"
L["Damage Split"] = "Разделенный Урон"
L["Death Knight"] = "Рыцарь Смерти"
L["Death Knight Rune"] = "Руна Рыцаря Смерти"
L["Death Rune"] = "Руна Смерти"
L["Debuff"] = "Дебафф"
L["Deflect"] = "Отражено"
L["Descending"] = "По убыванию"
L["Destination Name"] = "Имя Цели"
L["Destination Unit"] = "Цель Приемник"
L["Disease"] = "Болезнь"
L["Dispel"] = "Рассеять"
L["Dispel Failed"] = "Рассеивание безуспешно"
L["Dodge"] = "Уклонение"
L["Done"] = "Сделано"
L["Down"] = "Вниз"
L["Drain"] = "Похищение"
L["Drowning"] = "Утопление"
L["Druid"] = "Друид"
L["Dungeon Difficulty"] = "Сложность Подземелья"
L["Durability Damage"] = "Повреждение Экипировки"
L["Durability Damage All"] = "Повреждение Всей Экипировки"
L["Earth"] = "Земля"
L["Eclipse Direction"] = "Длительность Затмения"
L["Eclipse Power"] = "Энергия Затмения"
L["Eclipse Type"] = "Тип Затмения"
L["Emote"] = "Эмоция"
L["Energize"] = "Восполнение"
L["Energy"] = "Энергия"
L["Enrage"] = "Исступление"
L["Environmental"] = "Окружающая среда"
L["Environment Type"] = "Тип Среды(окружения)"
L["Evade"] = "Избежать"
L["Event"] = "Событие"
L["Event(s)"] = "События"
L["Every Frame"] = "Каждый Кадр"
L["Extra Amount"] = "Дополнительное Значение"
L["Extra Attacks"] = "Дополнительные атаки"
L["Extra Spell Name"] = "Дополнительное Имя Заклинания"
L["Fade In"] = "Появление"
L["Fade Out"] = "Угасание"
L["Falling"] = "Падение"
L["Fatigue"] = "Усталость"
L["Fire"] = "Огонь"
L["First Tree"] = "Первая Специализация"
L["Flash"] = "Вспышка"
L["Flip"] = "Кувырок"
L["Focus"] = "Фокус"
L["Form"] = "Форма"
L["Friendly"] = "Дружественный"
L["From"] = "Из"
L["Frost Rune #1"] = "Руна Льда #1"
L["Frost Rune #2"] = "Руна Льда #2"
L["Frost Runes"] = "Руны Льда"
L["Glancing"] = "Вскользь"
L["Global Cooldown"] = "ГКД"
L["Glow"] = "Свечение"
L["Gradient"] = "Градиент"
L["Gradient Pulse"] = "Пульсирующий Градиент"
L["Group"] = "Группа"
L["Group %s"] = "Группа %s"
L["Grow"] = "Рост"
L["Guild"] = "Гильдия"
L["Happiness"] = "Настроение питомца"
L["HasPet"] = "Питомец вызван (Жив)"
L["Heal"] = "Исцеление"
L["Healer"] = "Исцеляющий"
L["Health"] = "Здоровье"
L["Health (%)"] = "Здоровье (%)"
L["Heroic"] = "Героический"
L["Hide"] = "Скрыть"
L["Higher Than Tank"] = "Выше Чем Танк"
L["Holy Power"] = "Энергия Света"
L["Hostile"] = "Враждебный"
L["Hostility"] = "Враждебность"
L["Humanoid"] = "Гуманоид"
L["Hunter"] = "Охотник"
L["Icon"] = "Иконка"
L["Ignore Rune CD"] = "Игнорировать задержку руны"
L["Immune"] = "Невосприимчивость"
L["Include Bank"] = "Включая Банк"
L["Include Charges"] = "Включая Расходы"
L["Include Death Runes"] = "Включая Руны Смерти"
L["In Combat"] = "В Бою"
L["Inherited"] = "Вложенный"
L["Inside"] = "Внутри"
L["Instakill"] = "Момент. Убийство"
L["Instance Type"] = "Тип Подземелья"
L["Interrupt"] = "Прерывание"
L["Interruptible"] = "Прерываемый"
L["In Vehicle"] = "На Транспорте"
L["Inverse"] = "Инвертировать"
L["Is Exactly"] = "Точное Совпадение"
L["Item"] = "Предмет"
L["Item Count"] = "Кол-во предметов"
L["Item Equipped"] = "Вещь Надета"
L["Lava"] = "Лава"
L["Leech"] = "Высасывание"
L["Left"] = "Слева"
L["Left to Right"] = "Слева направо"
L["Level"] = "Уровень"
L["Lower Than Tank"] = "Ниже Чем Танк"
L["Lunar"] = "Лунное"
L["Lunar Power"] = "Лунная энергия"
L["Mage"] = "Маг"
L["Magic"] = "Магия"
L["Main Hand"] = "Основная рука"
L["Mana"] = "Мана"
L["Master"] = "Главный"
L["Matches (Pattern)"] = "Совпадения (По Шаблону)"
L["Message"] = "Сообщение"
L["Message type:"] = "Тип Сообщения:"
L["Message Type"] = "Тип Сообщения"
L["Miss"] = "Промах"
L["Missed"] = "Пропустил"
L["Missing"] = "Пропущенный"
L["Miss Type"] = "Тип Промаха"
L["Monochrome"] = "Монохромный"
L["Monster Yell"] = "Крик Моба"
L["Mounted"] = "Верхом"
L["Multi-target"] = "Несколько Целей"
L["Music"] = "Музыка"
L["Name"] = "Название"
L["Never"] = "Никогда"
L["Next"] = "Следующий"
L["No Children:"] = "Нет Детей:"
L["No Instance"] = "Не в Подземелье"
L["None"] = "Нет"
L["Non-player Character"] = "Не Игровой Персонаж"
L["Normal"] = "Обычно(ая)"
L["Not On Threat Table"] = "Не В Агро Листе"
L["Number"] = "Число"
L["Number Affected"] = "Кол-во Затронутых"
L["Off Hand"] = "В левой руке"
L["Officer"] = "Офицер"
L["Opaque"] = "Непрозрачность"
L["Orbit"] = "По Орбите"
-- L["Outline"] = ""
L["Outside"] = "Снаружи"
L["Overhealing"] = "Избыточное Исцеление"
L["Overkill"] = "Фатальный урон"
L["Paladin"] = "Паладин"
L["Parry"] = "Парирование"
L["Party"] = "Группа"
L["Party Kill"] = "Все Мертвы"
L["Paused"] = "Приостановлено"
L["Periodic Spell"] = "Периодическое заклинание"
L["Pet"] = "Питомец"
L["Player"] = "Игрок"
L["Player Character"] = "Игровой Персонаж"
L["Player Class"] = "Класс Игрока"
L["Player Dungeon Role"] = "Роль Игрока"
L["Player Level"] = "Уровень Игрока"
L["Player Name"] = "Имя Игрока"
L["Player(s) Affected"] = "Человек подвержено"
L["Player(s) Not Affected"] = "Игрок(и) Не Подвержены"
L["Poison"] = "Яд"
L["Power"] = "Энергия"
L["Power (%)"] = "Энергия (%)"
L["Power Type"] = "Тип Энергии"
L["Preset"] = "Предустановка"
L["Priest"] = "Жрец"
L["Progress"] = "Прогресс"
L["Pulse"] = "Пульс"
L["PvP Flagged"] = "В Режиме ПвП"
L["Radius"] = "Радиус"
L["Rage"] = "Ярость"
L["Raid"] = "Рейд"
L["Raid Warning"] = "Оповещение Рейда"
L["Range"] = "Дальний"
L["Ranged"] = "Оружие дальнего боя"
L["Receiving display information"] = "Получение информации об индикации из %s..."
L["Reference Spell"] = "Ссылка заклинания"
L["Reflect"] = "Отражение"
L["Relative"] = "Относительно"
L["Remaining Time"] = "Оставшееся Время"
L["Requested display does not exist"] = "Запрошенная индикация не существует"
L["Requested display not authorized"] = "Запрошенная индикация не разрешена"
L["Require Valid Target"] = "Требуется Допустимая Цель"
L["Resist"] = "Сопротивление"
L["Resisted"] = "Резист"
L["Resolve collisions dialog"] = [=[Вы включили аддон в котором определены индикации |cFF8800FFWeakAuras|r которые имеют те же имена, что и существующие.

Вы должны переименовать ваши индикации, чтобы не было конфликта.

Resolved: |cFFFF0000]=]
L["Resolve collisions dialog singular"] = [=[Вы включили аддон в котором определена индикация |cFF8800FFWeakAuras|r которая имеет то же имя, что и существующая.

Вы должны переименовать вашу индикацию, чтобы не было конфликта.

Resolved: |cFFFF0000]=]
L["Resolve collisions dialog startup"] = [=[Вы включили аддон в котором определены индикации |cFF8800FFWeakAuras|r которые имеют те же имена, что и существующие.


Вы должны переименовать ваши индикации, чтобы не было конфликта.

Resolved: |cFFFF0000]=]
L["Resolve collisions dialog startup singular"] = [=[Вы включили аддон в котором определена индикация |cFF8800FFWeakAuras|r которая имеет то же имя, что и существующая.

Вы должны переименовать вашу индикацию, чтобы не было конфликта.

Resolved: |cFFFF0000]=]
L["Resting"] = "Отдых"
L["Resurrect"] = "Воскрешение"
L["Right"] = "Справа"
L["Right to Left"] = "Справа налево"
L["Rogue"] = "Разбойник"
L["Rotate Left"] = "Вращение Влево"
L["Rotate Right"] = "Вращение Вправо"
L["Rune"] = "Руна"
L["Runic Power"] = "Энергия Рун"
L["Say"] = "Сказать"
L["Seconds"] = "Секунды"
L["Second Tree"] = "Вторая Специализация"
L["Shake"] = "Дрожь"
L["Shaman"] = "Шаман"
L["Shards"] = "Осколки"
L["Shift-Click to pause"] = "Shift+Клик для паузы"
L["Shift-Click to resume"] = "Shift+Клик возобновить"
L["Show"] = "Показать"
L["Shrink"] = "Обрезать"
L["Slide from Bottom"] = "Скользить Снизу"
L["Slide from Left"] = "Скользить Слева"
L["Slide from Right"] = "Скользить Справа"
L["Slide from Top"] = "Скользить Сверху"
L["Slide to Bottom"] = "Скользить Вниз"
L["Slide to Left"] = "Скользить Влево"
L["Slide to Right"] = "Скользить Вправо"
L["Slide to Top"] = "Скользить Вверх"
L["Slime"] = "Слизь"
L["Solar"] = "Солнечная"
L["Solar Power"] = "Солнечная Энергия"
L["Sound Effects"] = "Звуковые эффекты"
L["Source Name"] = "Имя Источника"
L["Source Unit"] = "Источник"
L["Spacing"] = "Интервал"
L["Specific Unit"] = "Специфическая Единица"
L["Spell"] = "Заклинание"
L["Spell (Building)"] = "Заклинание (Строение)"
L["Spell Name"] = "Название Заклинания"
L["Spin"] = "Штопор"
L["Spiral"] = "Спираль"
L["Spiral In And Out"] = "Спирально Туда-Сюда"
L["Stacks"] = "Стаки"
L["Stance/Form/Aura"] = "Стойка/Форма/Аура"
L["Status"] = "Статус"
L["Stolen"] = "Украденный"
L["Summon"] = "Призыв"
L["Swing"] = "Размах"
L["Swing Timer"] = "Таймер Взмаха"
L["Talent Specialization"] = "Специализация"
L["Tank"] = "Танк"
L["Tanking And Highest"] = "Танкует и макс. агро"
L["Tanking But Not Highest"] = "Танкует, но не макс. агро"
L["Target"] = "Цель"
-- L["Thick Outline"] = ""
L["Third Tree"] = "Третья Специализация"
L["Threat Situation"] = "Положение в Аггро"
L["Thrown"] = "Метательное"
L["Timed"] = "Временная"
L["Top"] = "Вверх"
L["Top Left"] = "Вверх Слева"
L["Top Right"] = "Вверх Справа"
L["Top to Bottom"] = "Сверху Вниз"
L["Total"] = "Всего"
L["Totem"] = "Тотем"
L["Totem Name"] = "Название Тотема"
L["Totem Type"] = "Тип Тотема"
L["Transmission error"] = "Ошибка Передачи"
L["Trigger:"] = "Триггер:"
L["Trigger Update"] = "Триггер Обновлен"
L["Undefined"] = "Неопределено"
L["Unholy Rune #1"] = "Руна Нечестивости #1"
L["Unholy Rune #2"] = "Руна Нечестивости #2"
L["Unholy Runes"] = "Руны Нечестивости"
L["Unit"] = "Цель"
L["Unit Characteristics"] = "Характеристики единицы"
L["Unit Destroyed"] = "Цель Уничтожена"
L["Unit Died"] = "Цель Мертва"
L["Up"] = "Вверх"
L["Version error recevied higher"] = "Эта индикация несовместима с вашей версией WeakAuras - она создана в версии %s, а у вас версия %s. Пожалуста обновите вашу версию WeakAuras."
L["Version error recevied lower"] = "Эта индикация несовместима с вашей версией WeakAuras - она создана в версии %s, а у вас версия %s. Пожалуста посоветуйте человеку, от которого вы это получили, обновить его версию WeakAuras."
L["Warlock"] = "Чернокнижник"
L["Warrior"] = "Воин"
L["Water"] = "Вода"
-- L["WeakAuras"] = ""
-- L["WeakAurasModelPaths"] = ""
L["WeakAurasModelPaths .toc Notes"] = "Предоставляет список большинства 3D моделей игры, для использования в WA."
L["WeakAurasOptions"] = "Настройки WeakAuras"
L["WeakAurasOptions .toc Notes"] = "Интерфейс настроек WeakAuras"
L["WeakAuras .toc Notes"] = "Мощный, многосторонний инструмент для отображения графики и информации, основанной на баффах, дебаффах и других триггерах."
L["WeakAurasTutorials"] = "Обучение WeakAuras"
L["WeakAurasTutorials .toc Notes"] = "Представление и дополнительное обучение по WeakAuras."
L["Weapon"] = "Оружие"
L["Weapon Enchant"] = "Улучшение Оружия (зачарование)"
L["Whisper"] = "Шепот"
L["Wobble"] = "Колебание"
L["Yell"] = "Крик"
L["Zone"] = "Зона"
L["Options/1 Match"] = "1 Совпадение"
L["Options/Actions"] = "Действия"
L["Options/Activate when the given aura(s) |cFFFF0000can't|r be found"] = "Активировать когда заданная аура(ы) |cFFFF0000не|r найдена"
L["Options/Add a new display"] = "Добавить новую индикацию"
L["Options/Add Dynamic Text"] = "Добавить Динамический Текст"
L["Options/Addon"] = "Аддон"
L["Options/Addons"] = "Аддоны"
L["Options/Add to group %s"] = "Добавить в группу %s"
L["Options/Add to new Dynamic Group"] = "Добавить в новую динамическую группу"
L["Options/Add to new Group"] = "Добавить в новую группу"
L["Options/Add Trigger"] = "Добавить Триггер"
L["Options/A group that dynamically controls the positioning of its children"] = "Группа, позволяющая динамично изменять позиции своих элементов"
L["Options/Align"] = "Выровнять"
L["Options/Allow Full Rotation"] = "Разрешить полное вращение"
L["Options/Alpha"] = "Прозрачность"
L["Options/Anchor"] = "Крепление"
L["Options/Anchor Point"] = "Точка Крепления"
L["Options/Angle"] = "Угол"
L["Options/Animate"] = "Анимация"
L["Options/Animated Expand and Collapse"] = "Анимированное Сворачивание и Разворачивание"
L["Options/Animation relative duration description"] = [=[Длительность анимации по отношению к индикации, выраженная в виде дроби (1/2), процентах (50%), или десятично (0.5).
|cFFFF0000Примечание:|r Если индикация не имеет таймера (например аура без длительности и т.д.), то анимация не проигрывается.
|cFF4444FFДля Примера:|r
Если длительность анимации установлена в |cFF00CC0010%|r и триггер индикации это бафф длительностью 20 секунд, стартовая анимация проиграется за 2 секунды.
Если длительность анимации установлена в |cFF00CC0010%|r и триггер индикации это бесконечная аура, стартовая анимация не будет проигрываться (но проигралась бы, если установить длительность в секундах) .]=]
L["Options/Animations"] = "Анимация"
L["Options/Animation Sequence"] = "Цепочка Анимации"
L["Options/Aquatic"] = "Водная форма"
L["Options/Aura (Paladin)"] = "Аура (паладин)"
L["Options/Aura(s)"] = "Эффекты"
L["Options/Auto"] = "Авто"
L["Options/Auto-cloning enabled"] = "Авто-клонирование включено"
L["Options/Automatic Icon"] = "Автоматическая Иконка"
-- L["Options/Backdrop Color"] = ""
-- L["Options/Backdrop Style"] = ""
L["Options/Background"] = "Подложка"
L["Options/Background Color"] = "Цвет Подложки"
L["Options/Background Inset"] = "Вложенная подложка"
L["Options/Background Offset"] = "Смещение Подложки"
L["Options/Background Texture"] = "Текстура Подложки"
L["Options/Bar Alpha"] = "Прозрачность Полосы"
L["Options/Bar Color"] = "Цвет Полосы"
-- L["Options/Bar Color Settings"] = ""
-- L["Options/Bar in Front"] = ""
L["Options/Bar Texture"] = "Текстура Полосы"
L["Options/Battle"] = "Сражение"
L["Options/Bear"] = "Медведь"
L["Options/Berserker"] = "Берсерк"
L["Options/Blend Mode"] = "Режим Наложения"
L["Options/Blood"] = "Кровь"
L["Options/Border"] = "Граница"
L["Options/Border Color"] = "Цвет Границы"
-- L["Options/Border Inset"] = ""
L["Options/Border Offset"] = "Смещение Границы"
L["Options/Border Settings"] = "Настройки Границы"
L["Options/Border Size"] = "Размер Границы"
L["Options/Border Style"] = "Стиль Границы"
L["Options/Bottom Text"] = "Нижний текст"
L["Options/Button Glow"] = "Подсветка кнопки"
L["Options/Can be a name or a UID (e.g., party1). Only works on friendly players in your group."] = "Может быть именем или UID (н.п. party1). Работает только с дружественными целями в вашей группе."
L["Options/Cancel"] = "Отмена"
L["Options/Cat"] = "Кошка"
L["Options/Change the name of this display"] = "Изменить имя индикации"
L["Options/Channel Number"] = "Номер Канала"
L["Options/Check On..."] = "Проверять..."
L["Options/Choose"] = "Выбрать"
L["Options/Choose Trigger"] = "Выбор Триггера"
L["Options/Choose whether the displayed icon is automatic or defined manually"] = "Выберите, будет ли значок определен автоматически или вручную"
L["Options/Clone option enabled dialog"] = [=[Вы активировали опцию |cFFFF0000Авто-клонирования|r.

|cFFFF0000Авто-клонирование|r заставляет индикацию автоматически дубироватся для отображения нескольких источников информации.
Если вы поместите эту индикацию в |cFF22AA22Динамическую Группу|r, все клоны будут смещаться вверх этой большой кучи.

Вы хотите поместить эту индикацию в новую |cFF22AA22Динамическую Группу|r?]=]
L["Options/Close"] = "Закрыть"
L["Options/Collapse"] = "Свернуть"
L["Options/Collapse all loaded displays"] = "Свернуть все активные индикации"
L["Options/Collapse all non-loaded displays"] = "Свернуть все неактивные индикации"
L["Options/Color"] = "Цвет"
L["Options/Compress"] = "Сжать"
L["Options/Concentration"] = "Концентрация"
L["Options/Constant Factor"] = "Постоянный множитель"
L["Options/Control-click to select multiple displays"] = "Ctrl+клик для выбора нескольких индикаций"
L["Options/Controls the positioning and configuration of multiple displays at the same time"] = "Управление позиционированием и настройка нескольких индикаций одновременно"
L["Options/Convert to..."] = "Преобразовать в..."
L["Options/Cooldown"] = "Кулдаун"
L["Options/Copy"] = "Копировать"
L["Options/Copy settings from..."] = "Копировать настройки из..."
L["Options/Copy settings from another display"] = "Копировать настройки из другой индикации"
L["Options/Copy settings from %s"] = "Копировать настройки из %s"
L["Options/Count"] = "Кол-во"
L["Options/Creating buttons: "] = "Создание кнопок:"
L["Options/Creating options: "] = "Создание настроек:"
L["Options/Crop X"] = "Обрезать по X"
L["Options/Crop Y"] = "Обрезать по Y"
L["Options/Crusader"] = "Рыцарь"
L["Options/Custom Code"] = "Свой Код"
L["Options/Custom Trigger"] = "Свой Триггер"
L["Options/Custom trigger event tooltip"] = [=[Напишите какие события должны проверятся для активации триггера.
Несколько событий должны разделятся запятыми или пробелами.

|cFF4444FFДля Примера:|r
UNIT_POWER, UNIT_AURA PLAYER_TARGET_CHANGED
]=]
L["Options/Custom trigger status tooltip"] = [=[Напишите какие события должны проверятся для активации триггера.
Поскольку это триггер состояния, указанные события могут быть вызваны WeakAuras без ожидаемых аргументов.
Несколько событий должны разделятся запятыми или пробелами.

|cFF4444FFДля Примера:|r
UNIT_POWER, UNIT_AURA PLAYER_TARGET_CHANGED
]=]
L["Options/Custom Untrigger"] = "Свой Детриггер"
L["Options/Custom untrigger event tooltip"] = [=[Напишите какие события должны проверятся для деакивации триггера.
Эти события могут быть отличны от описанных для срабатывания триггера.
Несколько событий должны разделятся запятыми или пробелами.

|cFF4444FFДля Примера:|r
UNIT_POWER, UNIT_AURA PLAYER_TARGET_CHANGED
]=]
L["Options/Death"] = "Смерть"
L["Options/Death Rune"] = "Руна Смерти"
L["Options/Debuff Type"] = "Тип Дебафа"
L["Options/Defensive"] = "Защита"
L["Options/Delete"] = "Удалить"
L["Options/Delete all"] = "Удалить всё"
L["Options/Delete children and group"] = "Удалить группу и ее элементы"
L["Options/Deletes this display - |cFF8080FFShift|r must be held down while clicking"] = "Удаляя эту индикацию - зажмите |cFF8080FFShift|r и кликните мышью."
L["Options/Delete Trigger"] = "Удалить Триггер"
-- L["Options/Desaturate"] = ""
L["Options/Devotion"] = "Благочестие"
L["Options/Disabled"] = "Выключено"
L["Options/Discrete Rotation"] = "Вращать Дискретно"
L["Options/Display"] = "Индикация"
L["Options/Display Icon"] = "Отображать Значек"
L["Options/Display Text"] = "Отобразить Текст"
L["Options/Distribute Horizontally"] = "Распределить по Горизонтали"
L["Options/Distribute Vertically"] = "Распределить по Вертикали"
L["Options/Do not copy any settings"] = "Не копировать какие-либо настройки"
L["Options/Do not group this display"] = "Не группировать эту индикацию"
L["Options/Duplicate"] = "Дублировать"
L["Options/Duration Info"] = "Информация о продолжительности"
L["Options/Duration (s)"] = "Длительность"
L["Options/Dynamic Group"] = "Динамическая Группа"
L["Options/Dynamic text tooltip"] = [=[Несколько специальных кодов для отображения динамического текста:

|cFFFF0000%p|r - Прогресс - Оставшееся время таймера или без таймерная величина
|cFFFF0000%t|r - Всего - Максимальная длительность таймера или максимальная без таймерная величина
|cFFFF0000%n|r - Название - Название индикации (обычно название задействованной ауры) или ID индикатора
|cFFFF0000%i|r - Иконка - Иконка связанная с индикацией
|cFFFF0000%s|r - Стаки - Кол-во стаков (обычно для ауры)
|cFFFF0000%c|r - В ручную - Позволяет написать функцию на Lua, возвращаемое значение которой и будет отображено ]=]
L["Options/Enabled"] = "Включено"
L["Options/Enter an aura name, partial aura name, or spell id"] = "Введите полное название эффекта, часть его названия или ID заклинания."
L["Options/Event Type"] = "Тип События"
L["Options/Expand"] = "Развернуть"
L["Options/Expand all loaded displays"] = "Развернуть все загруженные индикации"
L["Options/Expand all non-loaded displays"] = "Развернуть все не загруженные индикации"
L["Options/Expand Text Editor"] = "Расширенный редактор текста"
L["Options/Expansion is disabled because this group has no children"] = "Развертывание не возможно, потому что группа не имеет элементов"
L["Options/Export"] = "Экспортировать"
L["Options/Export to Lua table..."] = "Экспортировать в таблицу Lua"
L["Options/Export to string..."] = "Экспортировать в строку..."
L["Options/Fade"] = "Скрыть"
L["Options/Finish"] = "Завершение"
L["Options/Fire Resistance"] = "Сопротивление Огню"
L["Options/Flight(Non-Feral)"] = "Полет(не ферал)"
L["Options/Font"] = "Шрифт"
-- L["Options/Font Flags"] = ""
L["Options/Font Size"] = "Размер Шрифта"
L["Options/Font Type"] = "Тип Шрифта"
L["Options/Foreground Color"] = "Основной Цвет"
L["Options/Foreground Texture"] = "Основная Текстура"
L["Options/Form (Druid)"] = "Форма (друид)"
L["Options/Form (Priest)"] = "Форма (жрец)"
L["Options/Form (Shaman)"] = "Форма (шаман)"
L["Options/Form (Warlock)"] = "Форма (чернокнижник)"
L["Options/Frame"] = "Кадр"
L["Options/Frame Strata"] = "Слой Кадра"
L["Options/Frost"] = "Лед"
L["Options/Frost Resistance"] = "Сопротивление Льду"
L["Options/Full Scan"] = "Полное Сканирование"
L["Options/Ghost Wolf"] = "Призрачный волк"
L["Options/Glow Action"] = "Действия для подсвечивания"
L["Options/Group aura count description"] = [=[Кол-во из %s человек, к которым должен быть применен один или более данных эффектов, чтобы индикатор сработал.
Если введено целое число (напр. 5), то число людей с этим эффектом, будет сравниваться с введеным значением.
Если введено не целое (напр. 0.5), дробь (напр. 1/2) или процент (напр. 50%%), то эта часть из %s человек и будет в расчетах.

|cFF4444FFДля Примера:|r
|cFF00CC00> 0|r сработает когда любой из %s попал под воздействие
|cFF00CC00= 100%%|r сработает когда любой из %s попал под воздействие
|cFF00CC00!= 2|r будет срабатывать когда %s человек под воздействием и их кол-во не равно 2
|cFF00CC00<= 0.8|r сработает когда менее 80%% из %s, под воздействием (4 из 5 сопартийцев, 8 из 10 или 20 из 25 членов рейда)
|cFF00CC00> 1/2|r сработает если затронуто больше половины из %s человек
|cFF00CC00>= 0|r всегда срабатывает, несмотря ни на что]=]
L["Options/Group Member Count"] = "Кол-во Элементов Группы"
L["Options/Group (verb)"] = "Группировать"
L["Options/Height"] = "Высота"
L["Options/Hide this group's children"] = "Скрыть элементы этой группы"
L["Options/Hide When Not In Group"] = "Скрыть Когда Не в Группе"
L["Options/Horizontal Align"] = "Выравнивание по Горизонтали"
L["Options/Icon Info"] = "Информация о значке"
L["Options/Ignored"] = "Игнорируется"
L["Options/Ignore GCD"] = "Игнорировать ГКД"
L["Options/%i Matches"] = "%i Совпадений"
L["Options/Import"] = "Импорт"
L["Options/Import a display from an encoded string"] = "Импортировать индикацию из закодированной строки"
L["Options/Justify"] = "Выравнивание"
L["Options/Left Text"] = "Текст Слева"
L["Options/Load"] = "Загрузить"
L["Options/Loaded"] = "Загружено"
L["Options/Main"] = "Главный"
L["Options/Main Trigger"] = "Главный Триггер"
L["Options/Mana (%)"] = "Мана (%)"
L["Options/Manage displays defined by Addons"] = "Управление индикациями, определенными Аддонами"
L["Options/Message Prefix"] = "Префикс Сообщения"
L["Options/Message Suffix"] = "Суффикс Сообщения"
L["Options/Metamorphosis"] = "Метаморфоза"
L["Options/Mirror"] = "Отразить"
L["Options/Model"] = "Модель"
L["Options/Moonkin/Tree/Flight(Feral)"] = "Сова/Дерево/Полет(Ферал)"
L["Options/Move Down"] = "Опустить"
L["Options/Move this display down in its group's order"] = "Переместить индикацию вниз в групповом порядке"
L["Options/Move this display up in its group's order"] = "Переместить индикацию вверх, в групповом порядке"
L["Options/Move Up"] = "Поднять"
L["Options/Multiple Displays"] = "Множество Индикаций"
L["Options/Multiple Triggers"] = "Множественные Триггеры"
L["Options/Multiselect ignored tooltip"] = [=[
|cFFFF0000Игнор|r - |cFF777777Одиночная|r - |cFF777777Множественная|r
Эта опция не определяет, когда индикация должна быть загружена]=]
L["Options/Multiselect multiple tooltip"] = [=[
|cFFFF0000Игнор|r - |cFF777777Одиночная|r - |cFF777777Множественная|r
Любое количество совпадающих значений могут быть получены]=]
L["Options/Multiselect single tooltip"] = [=[
|cFFFF0000Игнор|r - |cFF777777Одиночная|r - |cFF777777Множественная|r
Только одно совпадение может быть получено]=]
L["Options/Must be spelled correctly!"] = "Должно быть написано правильно!"
L["Options/Name Info"] = "Название Инфо"
L["Options/Negator"] = "Не"
L["Options/New"] = "Новая Индикация"
L["Options/Next"] = "Следующий"
L["Options/No"] = "Нет"
L["Options/No Children"] = "Нет Элементов"
L["Options/Not all children have the same value for this option"] = "Не все элементы имеют схожее значение для этой опции"
L["Options/Not Loaded"] = "Не Загружено"
L["Options/No tooltip text"] = "Без подсказки"
L["Options/% of Progress"] = "% Прогресса"
L["Options/Okay"] = "Ок"
L["Options/On Hide"] = "При Скрытии"
L["Options/Only match auras cast by people other than the player"] = "Совпадение для эффектов других людей, но не игрока"
L["Options/Only match auras cast by the player"] = "Совпадение только для эффектов игрока"
L["Options/On Show"] = "При Появлении"
L["Options/Operator"] = "Оператор"
L["Options/or"] = "или"
L["Options/Orientation"] = "Ориентация"
L["Options/Other"] = "Другой(ие)"
L["Options/Outline"] = "Обводка"
L["Options/Own Only"] = "Только своё"
L["Options/Player Character"] = "Игровой Персонаж"
L["Options/Play Sound"] = "Проиграть Звук"
L["Options/Presence (DK)"] = "Власть"
L["Options/Presence (Rogue)"] = "Дух"
L["Options/Prevents duration information from decreasing when an aura refreshes. May cause problems if used with multiple auras with different durations."] = "Не позволяет снижать информацию о длительности эффекта, при его обновлении. Может вызвать проблемы при использовании с несколькими эффектами разной длительности."
L["Options/Primary"] = "Основной"
L["Options/Progress Bar"] = "Полоса Прогресса"
L["Options/Progress Texture"] = "Текстура Прогресса"
L["Options/Put this display in a group"] = "Поместить эту индикацию в группу"
L["Options/Ready For Use"] = "Готово Для Использования"
L["Options/Re-center X"] = "Рецентровать X"
L["Options/Re-center Y"] = "Рецентровать Y"
L["Options/Remaining Time Precision"] = "Точность оставшегося времени"
L["Options/Remove this display from its group"] = "Удалить эту индикацию из её группы"
L["Options/Rename"] = "Переименовать"
L["Options/Requesting display information"] = "Запрос информации о индикации из %s..."
L["Options/Required For Activation"] = "Необходимо для Активации"
L["Options/Retribution"] = "Воздаяние"
L["Options/Right-click for more options"] = "Правый клик для дополнительных опций"
L["Options/Right Text"] = "Текст Справа"
L["Options/Rotate"] = "Вращать"
L["Options/Rotate In"] = "Вращение В"
L["Options/Rotate Out"] = "Вращение Из"
L["Options/Rotate Text"] = "Вращать Текст"
L["Options/Rotation"] = "Поворот"
L["Options/Same"] = "Похожие"
L["Options/Search"] = "Поиск"
L["Options/Secondary"] = "Вторичная"
L["Options/Send To"] = "Отправить"
L["Options/Set tooltip description"] = "Установить всплывающую подсказку"
L["Options/Shadow Dance"] = "Танец Теней"
L["Options/Shadowform"] = "Облик Тьмы"
L["Options/Shadow Resistance"] = "Сопротивление Темной Магии"
L["Options/Shift-click to create chat link"] = "Shift+Клик чтобы создать |cFF8800FF[Ссылку в чат]"
L["Options/Show all matches (Auto-clone)"] = "Показать все совпадения (Авто-клонирование)"
L["Options/Show players that are |cFFFF0000not affected"] = "Показать |cFFFF0000не затронутых игроков"
L["Options/Shows a 3D model from the game files"] = "Показать 3D модель из файлов игры"
L["Options/Shows a custom texture"] = "Показывает свою текстуру"
L["Options/Shows a progress bar with name, timer, and icon"] = "Показать полосу прогресса с названием, таймером и иконкой"
L["Options/Shows a spell icon with an optional a cooldown overlay"] = "Показать значек заклинания с наложением обратного отсчета"
L["Options/Shows a texture that changes based on duration"] = "Показать текстуру, меняющуюся в зависимости от длительности"
L["Options/Shows one or more lines of text, which can include dynamic information such as progress or stacks"] = "Показать одну или несколько строк текста, которые могут включать в себя информацию о длительности или стаках"
L["Options/Shows the remaining or expended time for an aura or timed event"] = "Показывает оставшееся или потраченное время эффекта или приуроченного события"
L["Options/Show this group's children"] = "Показать индикации этой группы"
L["Options/Size"] = "Размер"
L["Options/Slide"] = "Скольжение"
L["Options/Slide In"] = "Задвинуть"
L["Options/Slide Out"] = "Выдвинуть"
L["Options/Sort"] = "Сортировка"
L["Options/Sound"] = "Звук"
L["Options/Sound Channel"] = "Звуковой канал"
L["Options/Sound File Path"] = "Путь к Звуковому Файлу"
L["Options/Space"] = "Отступ"
L["Options/Space Horizontally"] = "Отступ по Горизонтали"
L["Options/Space Vertically"] = "Отступ по Вертикали"
L["Options/Spell ID"] = "ID Заклинания"
L["Options/Spell ID dialog"] = [=[По умолчанию |cFF8800FFWeakAuras|r не может различать ауры с тем же названием, но с разными |cFFFF0000ИД заклинаний|r.
Однако, если использовать Полное Сканирование, |cFF8800FFWeakAuras|r сможет обнаружить специфические |cFFFF0000ИД заклинаний|r.
Вы желаете задействовать Полное Сканирование, что бы онаружить эти |cFFFF0000ИД заклинаний|r.]=]
L["Options/Stack Count"] = "Кол-во Стаков"
L["Options/Stack Count Position"] = "Позиция Кол-ва Стаков"
L["Options/Stack Info"] = "Информация о стаках"
L["Options/Stacks Settings"] = "Настройки Стаков"
L["Options/Stagger"] = "Шатание"
L["Options/Stance (Warrior)"] = "Стойка"
L["Options/Start"] = "Начало"
L["Options/Stealable"] = "Возможно Украсть"
L["Options/Stealthed"] = "Невидимость"
L["Options/Sticky Duration"] = "Липкая Длительность"
L["Options/Temporary Group"] = "Временная Группа"
L["Options/Text"] = "Текст"
L["Options/Text Color"] = "Цвет Текста"
L["Options/Text Position"] = "Позиция Текста"
L["Options/Text Settings"] = "Настройки Текста"
L["Options/Texture"] = "Текстура"
L["Options/The children of this group have different display types, so their display options cannot be set as a group."] = "Элементы этой группы содержат разные типы индикаций, по этому их настройки не могут быть групповыми"
L["Options/The duration of the animation in seconds."] = "Длительность анимации в секугдах"
L["Options/The type of trigger"] = "Тип Триггера"
L["Options/This condition will not be tested"] = "Это условие не может быть протестировано"
L["Options/This display is currently loaded"] = "Эта индикация уже загружена"
L["Options/This display is not currently loaded"] = "Эта индикация еще не загружена"
L["Options/This display will only show when |cFF00FF00%s"] = "Эта индикация будет отображена когда |cFF00FF00%s"
L["Options/This display will only show when |cFFFF0000 Not %s"] = "Эта индикация будет отображена когда |cFFFF0000 Не %s"
L["Options/This region of type \"%s\" has no configuration options."] = "Эта зона типа \"%s\" не имеет настроек."
L["Options/Time in"] = "Время В"
L["Options/Timer"] = "Таймер"
L["Options/Timer Settings"] = "Настройки Таймера"
L["Options/Toggle the visibility of all loaded displays"] = "Переключить видимость всех загруженных индикаций"
L["Options/Toggle the visibility of all non-loaded displays"] = "Переключить видимость всех не загруженных индикаций"
L["Options/Toggle the visibility of this display"] = "Переключить видимость этой индикации"
L["Options/to group's"] = "в группы"
L["Options/Tooltip"] = "Подсказка"
L["Options/Tooltip on Mouseover"] = "Подсказка при наведении мыши"
L["Options/Top Text"] = "Текст Вверху"
L["Options/to screen's"] = "к экранам"
L["Options/Total Time Precision"] = "Точность Общего Времени"
L["Options/Tracking"] = "Отслеживание"
L["Options/Travel"] = "Походная"
L["Options/Trigger"] = "Триггер"
L["Options/Trigger %d"] = "Триггер %d"
L["Options/Triggers"] = "Триггеры"
L["Options/Type"] = "Тип"
L["Options/Ungroup"] = "Разгруппировать"
L["Options/Unholy"] = "Нечистивость"
L["Options/Unit Exists"] = "Объект существует"
L["Options/Unlike the start or finish animations, the main animation will loop over and over until the display is hidden."] = "В отличие от начальной или конечной анимации, главная анимация зациклена и будет повторятся пока индикация не пропадет."
L["Options/Unstealthed"] = "Не скрытный"
L["Options/Update Custom Text On..."] = "Обновить Свой Текст На..."
L["Options/Use Full Scan (High CPU)"] = "Использовать Полное Сканирование (Загрузка ЦП)"
L["Options/Use tooltip \"size\" instead of stacks"] = "Использовать подсказку размер вместо стаков"
L["Options/Vertical Align"] = "Выравнивание по Вертикали"
L["Options/View"] = "Вид"
L["Options/Width"] = "Ширина"
L["Options/X Offset"] = "Смещение по X"
L["Options/X Scale"] = "Масштаб по X"
L["Options/Yes"] = "Да"
L["Options/Y Offset"] = "Смещение по Y"
L["Options/Y Scale"] = "Масштаб по Y"
L["Options/Z Offset"] = "Смещение по Z"
L["Options/Zoom"] = "Увеличение"
L["Options/Zoom In"] = "Увеличить"
L["Options/Zoom Out"] = "Уменьшить"
L["Tutorials/Actions and Animations: 1/7"] = "Действия и анимации: 1/7"
L["Tutorials/Actions and Animations: 2/7"] = "Действия и анимации: 2/7"
L["Tutorials/Actions and Animations: 3/7"] = "Действия и анимации: 3/7"
L["Tutorials/Actions and Animations: 4/7"] = "Действия и анимации: 4/7"
L["Tutorials/Actions and Animations: 5/7"] = "Действия и анимации: 5/7"
L["Tutorials/Actions and Animations: 6/7"] = "Действия и анимации: 6/7"
L["Tutorials/Actions and Animations: 7/7"] = "Действия и анимации: 7/7"
L["Tutorials/Actions and Animations Text"] = "Текст действий и анимаций"
L["Tutorials/Activation Settings: 1/5"] = "Установки активации: 1/5"
L["Tutorials/Activation Settings: 2/5"] = "Установки активации: 2/5"
L["Tutorials/Activation Settings: 3/5"] = "Установки активации: 3/5"
L["Tutorials/Activation Settings: 4/5"] = "Установки активации: 4/5"
L["Tutorials/Activation Settings: 5/5"] = "Установки активации: 5/5"
L["Tutorials/Activation Settings Text"] = "Так как Вы %s, Вы можете включить опция класса игрока и выбрать %s."
L["Tutorials/Auto-cloning: 1/10"] = "Авто-клонирование: 1/10"
L["Tutorials/Auto-cloning 1/10 Text"] = [=[Крупнейшая возможность, добавленная в |cFF8800FF1.4|r - |cFFFF0000авто-клонирование|r. |cFFFF0000Авто-клонирование|r позволяет вашим индикациям автоматически дублировать себя для показа нескольких источников информации. При размещении в Динамической группе, это позволяет создать расширенный динамический набор информации.

Три типа триггеров поддерживают |cFFFF0000авто-клонирование|r: Full Scan Auras, Group Auras и Multi-target Auras.]=]
L["Tutorials/Beginners Finished Text"] = [=[Вот и все руководство для начинающих. Однако Вы едва ощутили силу |cFF8800FFWeakAuras|r.

В будущем будет выпущено |cFFFFFF00больше|r |cFFFF7F00продвинутых|r |cFFFF0000руководств|r для погружения в бесконечные возможности |cFF8800FFWeakAuras|r.]=]
L["Tutorials/Beginners Guide Desc"] = "Руководство для начинающих"
L["Tutorials/Beginners Guide Desc Text"] = "Руководство по основным настройкам"
L["Tutorials/Create a Display: 1/5"] = "Создать Индикацию: 1/5"
L["Tutorials/Create a Display: 2/5"] = "Создать Индикацию: 2/5"
L["Tutorials/Create a Display: 3/5"] = "Создать Индикацию: 3/5"
L["Tutorials/Create a Display: 4/5"] = "Создать Индикацию: 4/5"
L["Tutorials/Create a Display: 5/5"] = "Создать Индикацию: 5/5"
L["Tutorials/Create a Display Text"] = [=[Несмотря на то, что вкладка Индикация имеет ползунки для управления положением и размером, существует более простой способ сделать это.

Вы можете просто щелкнуть и перетащить Вашу индикацию куда угодно на экране, и щелкнуть и перетащить края для изменения размера

Вы также можете нажать Shift для скрытия рамки положения/размера для более точного размещения.]=]
L["Tutorials/Display Options: 1/4"] = "Опции индикации: 1/4"
L["Tutorials/Display Options 1/4 Text"] = "А теперь выберите индикацию Полосы прогресса (или создайте новую)."
L["Tutorials/Display Options: 2/4"] = "Опции индикации: 2/4"
L["Tutorials/Display Options 2/4 Text"] = [=[Индикации |cFFFFFFFFПолоса прогресса|r и |cFFFFFFFFЗначок|r теперь имеют опцию показывать подсказку при наведении курсора поверх них.

This option is only available if your display uses a trigger based on an aura, item, or spell.]=]
L["Tutorials/Display Options: 4/4"] = "Опции индикации: 4/4"
L["Tutorials/Display Options 4/4 Text"] = "Наконец, новый тип индикации |cFFFFFFFFМодель|r позволяет Вам использовать любую 3D-модель из файлов игры."
-- L["Tutorials/Dynamic Group Options: 2/4"] = ""
-- L["Tutorials/Dynamic Group Options 2/4 Text"] = ""
-- L["Tutorials/Dynamic Group Options: 3/4"] = ""
-- L["Tutorials/Dynamic Group Options 3/4 Text"] = ""
-- L["Tutorials/Dynamic Group Options: 4/4"] = ""
-- L["Tutorials/Dynamic Group Options 4/4 Text"] = ""
-- L["Tutorials/Finished"] = ""
-- L["Tutorials/Full-scan Auras: 2/10"] = ""
-- L["Tutorials/Full-scan Auras 2/10 Text"] = ""
-- L["Tutorials/Full-scan Auras: 3/10"] = ""
-- L["Tutorials/Full-scan Auras 3/10 Text"] = ""
-- L["Tutorials/Full-scan Auras: 4/10"] = ""
-- L["Tutorials/Full-scan Auras 4/10 Text"] = ""
-- L["Tutorials/Full-scan Auras: 5/10"] = ""
-- L["Tutorials/Full-scan Auras 5/10 Text"] = ""
-- L["Tutorials/Group Auras 6/10"] = ""
-- L["Tutorials/Group Auras 6/10 Text"] = ""
-- L["Tutorials/Group Auras: 7/10"] = ""
-- L["Tutorials/Group Auras 7/10 Text"] = ""
-- L["Tutorials/Group Auras: 8/10"] = ""
-- L["Tutorials/Group Auras 8/10 Text"] = ""
-- L["Tutorials/Home"] = ""
-- L["Tutorials/Multi-target Auras: 10/10"] = ""
-- L["Tutorials/Multi-target Auras 10/10 Text"] = ""
L["Tutorials/Multi-target Auras: 9/10"] = "Многоцелевые Эффекты: 9/10"
-- L["Tutorials/Multi-target Auras 9/10 Text"] = ""
-- L["Tutorials/New in 1.4:"] = ""
L["Tutorials/New in 1.4 Desc:"] = "Новое в 1.4"
L["Tutorials/New in 1.4 Desc Text"] = "Посмотреть новые функции WeakAuras 1.4"
-- L["Tutorials/New in 1.4 Finnished Text"] = ""
-- L["Tutorials/New in 1.4 Text1"] = ""
-- L["Tutorials/New in 1.4 Text2"] = ""
-- L["Tutorials/Previous"] = ""
L["Tutorials/Trigger Options: 1/4"] = "Опции Триггера: 1/4"
-- L["Tutorials/Trigger Options 1/4 Text"] = ""
L["Tutorials/Trigger Options: 2/4"] = "Опции Триггера: 2/4"
-- L["Tutorials/Trigger Options 2/4 Text"] = ""
L["Tutorials/Trigger Options: 3/4"] = "Опции Триггера: 3/4"
L["Tutorials/Trigger Options 3/4 Text"] = [=[|cFF8800FFWeakAuras 1.4|r также добавляет некоторые новые типы Триггеров.

Выберите пункт Статус, чтобы посмотреть на них.]=]
L["Tutorials/Trigger Options: 4/4"] = "Опции Триггера: 4/4"
L["Tutorials/Trigger Options 4/4 Text"] = [=[|cFFFFFFFFUnit Characteristics|r триггер позволяет вам протестировать

|cFFFFFFFFGlobal Cooldown|r and |cFFFFFFFFSwing Timer|r triggers complement the Cast trigger.]=]
L["Tutorials/WeakAuras Tutorials"] = "Обучение WeakAuras"
L["Tutorials/Welcome"] = "Добро пожаловать"
L["Tutorials/Welcome Text"] = [=[Добро пожаловать в |cFF8800FFWeakAuras|r Руководство Новичка.

Это руководство покажет, как использовать WeakAuras и объяснит основные опции настроек.]=]



