local _, ns = ...

-- Translations specific to the Hallows End AddOn
if ns.locale == "deDE" then
	ns.L["AddOn Description"] = "%eHilfe für Erfolge und Quests in %sNoblegarten-Feiertage"
	ns.L["AnywhereC"] = "Überall im Lager"
	ns.L["AnywhereE"] = "Überall im Lage"
	ns.L["AnywhereS"] = "Überall auf dem Platz"
	ns.L["AnywhereT"] = "Überall im Dorf"
	ns.L["AnywhereZR"] = "Überall in der Zone.\nVerwende das Spielzeug \"Frühlingsfloristen\".\n"
			.."(Nobelgartenverkäufer/Nobelgartenhändler - 50x Nobelgartenschokolade)"
	ns.L["AnywhereZW"] = "Überall in der Zone.\nVerwende die \"Frühlingsrobe\".\n"
			.."(Nobelgartenverkäufer/Nobelgartenhändler - 50x Nobelgartenschokolade)"
	ns.L["Brightly Colored Egg"] = "Bunt gefärbtes Ei"
	ns.L["Cenarion Hold"] = "Burg Cenarius"
	ns.L["Daetan Swiftplume"] = "Daetan Flinkfeder"
	ns.L["Golakka Hot Springs"] = "Die Heißen Quellen von Golakka"
	ns.L["hb1"] = "(1) Ändern Sie Ihr \"Zuhause\" in Marschalls Wehr\n(2) Holen Sie sich den "
			.."Nobelgartenhäschen-stärkungszauber\n(3) Herd ---> Marschalls Wehr"
	ns.L["hb2"] = "(4) Lauf hierher\n(5) Hier stehen und warten\n(6) Nicht reiten\n(7) Nehmen sie keinen schaden"
	ns.L["hb3"] = "(1) Ändern Sie Ihr \"Zuhause\" in Burg Cenarius\n(2) Holen Sie sich den "
			.."Nobelgartenhäschen-stärkungszauber\n(3) Herd ---> Burg Cenarius"
	ns.L["hide"] = "(1) Kaufen Sie ein Nobelgartenei\n(2) Platziere es irgendwo in der Stadt.\nVerwenden Sie kein Bunt gefärbtes Ei!"
	ns.L["Light Green"] = "Hellgrün"
	ns.L["Magenta"] = "Magenta"
	ns.L["Marshall's Stand"] = "Marschalls Wehr"
	ns.L["Noblegarden"] = "Nobelgarten Erfolge"
	ns.L["Orange"] = "Orange"
	ns.L["Quacking Down"] = "Quakende Maßnahmen"
	ns.L["Turquoise"] = "Türkis"

elseif ns.locale == "esES" or ns.locale == "esMX" then
	ns.L["AddOn Description"] = "%eAyuda para logros y misiones en %sJardín Noble"
	ns.L["AnywhereC"] = "En cualquier lugar del campamento"
	ns.L["AnywhereE"] = "En cualquier lugar del campamento"
	ns.L["AnywhereS"] = "En cualquier lugar de la plaza"
	ns.L["AnywhereT"] = "En cualquier lugar del pueblo"
	ns.L["AnywhereZR"] = "En cualquier lugar de la zona.\nUsa el juguete \"Faltriquera de florista primaveral\".\n"
			.."(Vendedor/Mercader del Jardín Noble - 50x Chocolate del Jardín Noble)"
	ns.L["AnywhereZW"] = "En cualquier lugar de la zona.\nUsa la \"Togas primaverales\".\n"
			.."(Vendedor/Mercader del Jardín Noble - 50x Chocolate del Jardín Noble)"
	ns.L["Brightly Colored Egg"] = "Huevo de colores vivos"
	ns.L["Cenarion Hold"] = "Fuerte Cenarion"
	ns.L["Daetan Swiftplume"] = "Daetan Plumapresta"
	ns.L["Golakka Hot Springs"] = "Baños de Golakka"
	ns.L["hb1"] = "(1) Cambia tu \"hogar\" a Alto de Marshal\n(2) Consigue el mejora Conejito del Jardín "
			.."Noble\n(3) Hogar ---> Alto de Marshal"
	ns.L["hb2"] = "(4) Corre hasta aqui\n(5) Quédate aquí y espera\n(6) No montar\n(7) No te dañes"
	ns.L["hb3"] = "(1) Cambia tu \"hogar\" a Fuerte Cenarion\n(2) Consigue el mejora Conejito del Jardín "
			.."Noble\n(3) Hogar ---> Fuerte Cenarion"
	ns.L["hide"] = "(1) Compra un Huevo del Jardín Noble\n(2) Colócalo en cualquier lugar de la ciudad.\n"
			.."¡No uses un Huevo de colores vivos!"
	ns.L["Light Green"] = "Verde claro"
	ns.L["Magenta"] = "Magenta"
	ns.L["Marshall's Stand"] = "Alto de Marshal"
	ns.L["Noblegarden"] = "Jardín Noble"
	ns.L["Orange"] = "Naranja"
--	ns.L["Quacking Down"] = ""
	ns.L["Turquoise"] = "Turquesa"

elseif ns.locale == "frFR" then
	ns.L["AddOn Description"] = "%eAide pour les réalisations et les quêtes dans %sJardin des nobles"
	ns.L["AnywhereC"] = "Partout dans le camp"
	ns.L["AnywhereE"] = "Partout dans le campement"
	ns.L["AnywhereS"] = "Partout dans la Place"
	ns.L["AnywhereT"] = "Partout dans la ville"
	ns.L["AnywhereZR"] = "Partout dans la zone.\nUtilisez le jouet Bourse printanière de fleuriste.\n"
			.."(Vendeur/Marchand du Jardin des nobles - 50x Chocolat du Jardin des nobles)"
	ns.L["AnywhereZW"] = "Partout dans la zone.\nUtilisez la \"Robe de printemps\".\n"
			.."(Vendeur/Marchand du Jardin des nobles - 50x Chocolat du Jardin des nobles)"
	ns.L["Brightly Colored Egg"] = "Œuf vivement coloré"
	ns.L["Cenarion Hold"] = "Fort Cénarien"
	ns.L["Daetan Swiftplume"] = "Daëtan Vifpanache"
	ns.L["Golakka Hot Springs"] = "Sources de Golakka"
	ns.L["hb1"] = "(1) Changez votre \"maison\" en Camp retranché des Marshal\n(2) Obtenez le buff "
			.."Lapin du Jardin des nobles\n(3) Foyer ---> Camp retranché des Marshal"
	ns.L["hb2"] = "(4) Courez jusqu'ici\n(5) Tenez-vous ici et attendez\n(6) Ne roule "
			.."pas\n(7) Ne pas prendre de dégâts"
	ns.L["hb3"] = "(1) Changez votre \"maison\" en Fort Cénarien\n(2) Obtenez le buff "
			.."Lapin du Jardin des nobles\n(3) Foyer ---> Fort Cénarien"
	ns.L["hide"] = "(1) Acheter un Oeuf du Jardin des nobles\n(2) Placez-le n'importe où dans la ville.\n"
			.."N'utilisez pas de Œuf vivement coloré !"
	ns.L["Light Green"] = "Vert clair"
	ns.L["Magenta"] = "Magenta"
	ns.L["Marshall's Stand"] = "Camp retranché des Marshal"
	ns.L["Noblegarden"] = "Jardin des nobles"
	ns.L["Orange"] = "Orange"
	ns.L["Quacking Down"] = "Canardage"
	ns.L["Turquoise"] = "Turquoise"

elseif ns.locale == "itIT" then
	ns.L["AddOn Description"] = "%eAiuto per obiettivi e missioni in %sFesta di Nobiluova"
	ns.L["AnywhereC"] = "Ovunque nel campo"
	ns.L["AnywhereE"] = "Ovunque nell'accampamento"
	ns.L["AnywhereS"] = "Ovunque in piazza"
	ns.L["AnywhereT"] = "Ovunque nel villaggio"
	ns.L["AnywhereZW"] = "Ovunque nella zona.\nUsa le \"vesti primaverili\".\n"
			.."(Mercante di Nobiluova - 50x Cioccolatino di Nobiluova)"
	ns.L["AnywhereZR"] = "Ovunque nella zona.\nUsa il giocattolo \"Borsa del Fiorista Primaverile\".\n"
			.."(Mercante di Nobiluova - 50x Cioccolatino di Nobiluova)"
	ns.L["Brightly Colored Egg"] = "Uovo Decorato"
	ns.L["Cenarion Hold"] = "Fortezza Cenariana"
	ns.L["Daetan Swiftplume"] = "Daetan Piumasvelta"
	ns.L["Golakka Hot Springs"] = "Sorgenti Calde di Golakka"
	ns.L["hb1"] = "(1) Cambia la tua \"casa\" in Accampamento dei Grant\n(2) Ottieni il beneficio "
			.."Noblegarden Bunny\n(3) Cuore ---> Accampamento dei Grant"
	ns.L["hb2"] = "(4) Corri qui\n(5) Stai qui e aspetta\n(6) Non guidare\n(7) Non subire danni"
	ns.L["hb3"] = "(1) Cambia la tua \"casa\" in Cenarion Hold\n(2) Ottieni il beneficio "
			.."Noblegarden Bunny\n(3) Cuore ---> Cenarion Hold"
	ns.L["hide"] = "(1) Acquista un Noblegarden Egg\n(2) Posizionalo ovunque in città.\nNon usare un Uovo Decorato!"
	ns.L["Light Green"] = "Verde chiaro"
	ns.L["Magenta"] = "Magenta"
	ns.L["Marshall's Stand"] = "Accampamento dei Grant"
	ns.L["Noblegarden"] = "Festa di Nobiluova"
	ns.L["Orange"] = "Arancione"
--	ns.L["Quacking Down"] = ""
	ns.L["Turquoise"] = "Turchese"

elseif ns.locale == "koKR" then
	ns.L["AddOn Description"] = "%s귀족의 정원%e 업적 및 퀘스트에 대한 도움말"	
	ns.L["AnywhereC"] = "캠프 어디에서나"
	ns.L["AnywhereE"] = "야영지 어디든"
	ns.L["AnywhereS"] = "광장 어디에서나"
	ns.L["AnywhereT"] = "마을 어디든"
	ns.L["AnywhereZR"] = "영역의 아무 곳이나.\n\"봄꽃 상인의 주머니\" 장난감을 사용하세요.\n(귀족의 정원 상인/판매원 - 50x 귀족의 정원 초콜릿)"
	ns.L["AnywhereZW"] = "영역의 아무 곳이나.\n\"새봄맞이 로브\"를 사용하세요.\n(귀족의 정원 상인/판매원 - 50x 귀족의 정원 초콜릿)"
	ns.L["Brightly Colored Egg"] = "알록달록한 알"
	ns.L["Cenarion Hold"] = "세나리온 요새"
	ns.L["Daetan Swiftplume"] = "대탄 스위프트플룸"
	ns.L["Golakka Hot Springs"] = "골락카 간헐천"
	ns.L["hb1"] = "(1) \"집\"을 마샬의 격전지로 변경\n(2) 귀족의 정원 토끼 버프 받기\n(3) 화덕 ---> 마샬의 격전지"
	ns.L["hb2"] = "(4) 여기까지 달려\n(5) 여기 서서 기다려\n(6) 타지마\n(7) 피해를 입지 않는다"
	ns.L["hb3"] = "(1) \"집\"을 세나리온 요새로 변경\n(2) 귀족의 정원 토끼 버프 받기\n(3) 화덕 ---> 세나리온 요새"
	ns.L["hide"] = "(1) 귀족의 정원 알 구매\n(2) 도시 어디에서나 배치.\n알록달록한 알는 사용하지 마세요!"
	ns.L["Light Green"] = "라이트 그린"
	ns.L["Magenta"] = "마젠타"
	ns.L["Marshall's Stand"] = "마샬의 격전지"
	ns.L["Noblegarden"] = "귀족의 정원"
	ns.L["Orange"] = "오렌지"
--	ns.L["Quacking Down"] = ""
	ns.L["Turquoise"] = "터키석"
		
elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	ns.L["AddOn Description"] = "%eAjuda para conquistas e missões em %sJardinova"
	ns.L["AnywhereC"] = "Em qualquer lugar do acampamento"
	ns.L["AnywhereE"] = "Em qualquer lugar do acampamento"
	ns.L["AnywhereS"] = "Em qualquer lugar da praça"
	ns.L["AnywhereT"] = "Em qualquer lugar da vila"
	ns.L["AnywhereZR"] = "Em qualquer lugar da zona.\nUse o brinquedo \"Bolsa de Florista da Primavera\".\n"
			.."(Comerciante/Mercador de Jardinova - 50x Chocolate de Jardinova)"
	ns.L["AnywhereZW"] = "Em qualquer lugar da zona.\nUse os \"Vestes Primaveris\".\n"
			.."(Comerciante/Mercador de Jardinova - 50x Chocolate de Jardinova)"
	ns.L["Brightly Colored Egg"] = "Ovo Colorido Brilhante"
	ns.L["Cenarion Hold"] = "Forte Cenariano"
	ns.L["Daetan Swiftplume"] = "Daetan Plumaveloz"
	ns.L["Golakka Hot Springs"] = "Fontes Termais Golakka"
	ns.L["hb1"] = "(1) Altere sua \"casa\" para Posto Avançado do Marshal\n(2) Obtenha o bônus "
			.."Coelhinho de Jardinova\n(3) Lar ---> Posto Avançado do Marshal"
	ns.L["hb2"] = "(4) Corre pra cá\n(5) Fique aqui e espere\n(6) Não monte\n(7) Não tome nenhum dano"
	ns.L["hb3"] = "(1) Altere sua \"casa\" para Forte Cenariano\n(2) Obtenha o bônus "
			.."Coelhinho de Jardinova\n(3) Lar ---> Forte Cenariano"
	ns.L["hide"] = "(1) Compre um Ovo de Jardinova\n(2) Coloque-o em qualquer lugar da cidade.\nNão use um Ovo Colorido Brilhante!"
	ns.L["Light Green"] = "Verde Claro"
	ns.L["Magenta"] = "Magenta"
	ns.L["Marshall's Stand"] = "Posto Avançado do Marshal"
	ns.L["Noblegarden"] = "Jardinova"
	ns.L["Orange"] = "Laranja"
--	ns.L["Quacking Down"] = ""
	ns.L["Turquoise"] = "Turquesa"

elseif ns.locale == "ruRU" then
	ns.ns.L["AddOn Description"] = "%eСправка по достижениям и квестам в %sСада Чудес"
	ns.L["AnywhereC"] = "Где угодно в лагере"
	ns.L["AnywhereE"] = "Где угодно в лагере"
	ns.L["AnywhereS"] = "Где угодно на площади"
	ns.L["AnywhereT"] = "Где угодно в деревне"
	ns.L["AnywhereZR"] = "Где угодно в зоне.\nИспользуйте игрушку \"Весенний мешочек садовода\".\n"
			.."(Продавец/Торговец Сада чудес - 50x Праздничное шоколадное яйцо)"
	ns.L["AnywhereZW"] = "Где угодно в зоне.\nИспользуйте \"Весеннее убранство\".\n"
			.."(Продавец/Торговец Сада чудес - 50x Праздничное шоколадное яйцо)"
	ns.L["Brightly Colored Egg"] = "Раскрашенное яйцо"
	ns.L["Cenarion Hold"] = "Крепости Кенария"
	ns.L["Daetan Swiftplume"] = "Даэтан Скорое Перо"
	ns.L["Golakka Hot Springs"] = "Горячие источники Голакка"
	ns.L["hb1"] = "(1) Измените свой «дом» на Застава Маршалла\n(2) Получите aура Зайчик "
			.."Сада чудес\n(3) Очаг ---> Застава Маршалла"
	ns.L["hb2"] = "(4) Беги сюда\n(5) Стой здесь и жди\n(6) Не ездить\n(7) Не получить урона"
	ns.L["hb3"] = "(1) Измените свой «дом» на Крепости Кенария\n(2) Получите aура Зайчик "
			.."Сада чудес\n(3) Очаг ---> Крепости Кенария"
	ns.L["hide"] = "(1) Купить Праздничное яйцо\n(2) Разместите в любом месте города.\nНе используйте Раскрашенное яйцо!"
	ns.L["Light Green"] = "Светло-зеленый"
	ns.L["Magenta"] = "Маджента"
	ns.L["Marshall's Stand"] = "Застава Маршалла"
	ns.L["Noblegarden"] = "Сад Чудес"
	ns.L["Orange"] = "Оранжевый"
	ns.L["Quacking Down"] = "Полный кряк"
	ns.L["Turquoise"] = "Бирюзовый"

elseif ns.locale == "zhCN" then
	ns.L["AddOn Description"] = "%e帮助%s复活节%e的成就和任务"
	ns.L["AnywhereC"] = "在营地的任何地方"
	ns.L["AnywhereE"] = "在营地的任何地方"
	ns.L["AnywhereS"] = "广场上的任何地方"
	ns.L["AnywhereT"] = "村子里的任何地方"
	ns.L["AnywhereZR"] = "区域内的任何地方.\n使用 \"春日花袋\" 玩具.\n(复活节小贩/复活节商人 - 50x 复活节巧克力)"
	ns.L["AnywhereZW"] = "区域内的任何地方.\n使用 \"春季长袍\".\n(复活节小贩/复活节商人 - 50x 复活节巧克力)"
	ns.L["Brightly Colored Egg"] = "鲜艳的彩蛋"
	ns.L["Cenarion Hold"] = "塞纳里奥要塞"
	ns.L["Daetan Swiftplume"] = "戴坦·迅羽"
	ns.L["Golakka Hot Springs"] = "葛拉卡温泉"
	ns.L["hb1"] = "(1) 将您的“家”更改为 马绍尔哨站\n(2) 获得 复活节小兔 增益\n(3) 炉石 ---> 马绍尔哨站"
	ns.L["hb2"] = "(4) 跑到这里\n(5) 站在这里等待\n(6) 不要骑\n(7) 不受伤害"
	ns.L["hb3"] = "(1) 将您的“家”更改为 塞纳里奥要塞\n(2) 获得 复活节小兔 增益\n(3) 炉石 ---> 塞纳里奥要塞"
	ns.L["hide"] = "(1) 购买 复活节彩蛋\n(2) 把它放在城市的任何地方.\n不要使用鲜艳的彩蛋!"
	ns.L["Light Green"] = "浅绿色"
	ns.L["Magenta"] = "洋红色"
	ns.L["Marshall's Stand"] = "马绍尔哨站"
	ns.L["Noblegarden"] = "贵族的花园"
	ns.L["Orange"] = "橙色"
--	ns.L["Quacking Down"] = ""
	ns.L["Turquoise"] = "青绿色"

elseif ns.locale == "zhTW" then
	ns.L["AddOn Description"] = "%e幫助%s復活節%e的成就和任務"
	ns.L["AnywhereC"] = "在營地的任何地方"
	ns.L["AnywhereE"] = "在營地的任何地方"
	ns.L["AnywhereS"] = "廣場上的任何地方"
	ns.L["AnywhereT"] = "村子裡的任何地方"
	ns.L["AnywhereZR"] = "區域內的任何地方.\n使用 \"春日花袋\" 玩具.\n(復活節小販/復活節商人 - 50x 復活節巧克力)"
	ns.L["AnywhereZW"] = "區域內的任何地方.\n使用 \"春季長袍\".\n(復活節小販/復活節商人 - 50x 復活節巧克力)"
	ns.L["Brightly Colored Egg"] = "鮮豔的彩蛋"
	ns.L["Cenarion Hold"] = "塞纳里奥要塞"
	ns.L["Daetan Swiftplume"] = "戴坦·迅羽"
	ns.L["Golakka Hot Springs"] = "葛拉卡溫泉"
	ns.L["hb1"] = "(1) 將您的“家”更改為 馬紹爾哨站\n(2) 獲得 復活節小兔 增益\n(3) 爐石 ---> 馬紹爾哨站"
	ns.L["hb2"] = "(4) 跑到這裡\n(5) 站在這裡等待\n(6) 不要騎\n(7) 不受傷害"
	ns.L["hb3"] = "(1) 將您的“家”更改為 塞納里奧要塞\n(2) 獲得 復活節小兔 增益\n(3) 爐石 ---> 塞納里奧要塞"
	ns.L["hide"] = "(1) 購買 復活節彩蛋\n(2) 把它放在城市的任何地方.\n不要使用鮮豔的彩蛋!"
	ns.L["Light Green"] = "淺綠色"
	ns.L["Magenta"] = "品紅"
	ns.L["Marshall's Stand"] = "馬紹爾哨站"
	ns.L["Noblegarden"] = "貴族的花園"
	ns.L["Orange"] = "橘子"
--	ns.L["Quacking Down"] = ""
	ns.L["Turquoise"] = "綠松石"
	
else
	ns.L["AddOn Description"] = "%eHelp for the %sNoblegarden%e achievements and quests"
	ns.L["AnywhereC"] = "Anywhere in the camp"
	ns.L["AnywhereE"] = "Anywhere in the encampment"
	ns.L["AnywhereS"] = "Anywhere in the square"
	ns.L["AnywhereT"] = "Anywhere in the village"
	ns.L["AnywhereZR"] = "Anywhere in the zone.\nUse the \"Spring Florist's Pouch\" toy.\n"
					.."(Noblegarden Vendor/Merchant - 50x Noblegarden Chocolate)"
	ns.L["AnywhereZW"] = "Anywhere in the zone.\nUse the \"Spring Robes\".\n"
					.."(Noblegarden Vendor/Merchant - 50x Noblegarden Chocolate)"
	ns.L["hb1"] = "(1) Change your \"home\" to Marshall's Stand\n(2) Get the Noblegarden Bunny "
				.."buff\n(3) Hearth ---> Marshall's Stand"
	ns.L["hb2"] = "(4) Run to here\n(5) Stand here and wait\n(6) Do not ride\n(7) Take no damage"
	ns.L["hb3"] = "(1) Change your \"home\" to Cenarion Hold\n(2) Get the Noblegarden Bunny "
				.."buff\n(3) Hearth ---> Cenarion Hold"
	ns.L["hide"] = "(1) Purchase a Noblegarden egg\n(2) Place it anywhere in the city.\nDo not use a Brightly Colored Egg!"
end