-- JUST DO IT YES YOU CAN NOTHING IS IMPOSSIBLE DO IT
hopAddon_Subregions = {
	-- US
	{ "Oceania", "Pacific", "Mountain", "Central", "Eastern", "3", "4" },
	
	-- Korea
	{ "격노의 전장", "징벌의 전장" },
	
	-- EU
	{ "English", "French", "German", "Russian", "Spanish", "Portuguese", "Italian" },
	  
	-- Taiwan
	{ "殺戮", "嗜血", "暴怒" },
	
	-- China
	{ "Battle Group 1",  "Battle Group 2",  "Battle Group 3",  "Battle Group 4",  "Battle Group 5",  "Battle Group 6",  "Battle Group 7",  "Battle Group 8",  "Battle Group 9",  "Battle Group 10",
	  "Battle Group 11", "Battle Group 12", "Battle Group 13", "Battle Group 14", "Battle Group 15", "Battle Group 16", "Battle Group 17", "Battle Group 18", "Battle Group 19", "Battle Group 20",
	  "Battle Group 21" },
};

hopAddon_Realmlist = {
	-- US
		{ name = "Dreadmaul", region = 1, pvp = true, lang = 2}, 
		{ name = "Caelestrasz", region = 1, pvp = false, lang = 2}, 
		{ name = "Nagrand", region = 1, pvp = false, lang = 2}, 
		{ name = "Aman'Thul", region = 1, pvp = false, lang = 2}, 
		{ name = "Barthilas", region = 1, pvp = true, lang = 2}, 
		{ name = "Thaurissan", region = 1, pvp = true, lang = 2}, 
		{ name = "Dath'Remar", region = 1, pvp = false, lang = 2}, 
		{ name = "Frostmourne", region = 1, pvp = true, lang = 2}, 
		{ name = "Khaz'goroth", region = 1, pvp = false, lang = 2}, 
		{ name = "Jubei'Thos", region = 1, pvp = true, lang = 2}, 
		{ name = "Gundrak", region = 1, pvp = true, lang = 2}, 
		{ name = "Saurfang", region = 1, pvp = false, lang = 2}, 
		{ name = "Eldre'Thalas", region = 1, pvp = false, lang = 1}, 
		{ name = "Spirestone", region = 1, pvp = true, lang = 1}, 
		{ name = "Shadow Council", region = 1, pvp = false, lang = 1}, 
		{ name = "Scarlet Crusade", region = 1, pvp = false, lang = 1}, 
		{ name = "Firetree", region = 1, pvp = true, lang = 1}, 
		{ name = "Frostmane", region = 1, pvp = true, lang = 1}, 
		{ name = "Gurubashi", region = 1, pvp = true, lang = 1}, 
		{ name = "Smolderthorn", region = 1, pvp = true, lang = 1}, 
		{ name = "Skywall", region = 1, pvp = false, lang = 1}, 
		{ name = "Windrunner", region = 1, pvp = false, lang = 1}, 
		{ name = "Nathrezim", region = 1, pvp = true, lang = 1}, 
		{ name = "Terenas", region = 1, pvp = false, lang = 1}, 
		{ name = "Arathor", region = 1, pvp = false, lang = 1}, 
		{ name = "Bonechewer", region = 1, pvp = true, lang = 1}, 
		{ name = "Dragonmaw", region = 1, pvp = true, lang = 1}, 
		{ name = "Shadowsong", region = 1, pvp = false, lang = 1}, 
		{ name = "Silvermoon", region = 1, pvp = false, lang = 1}, 
		{ name = "Crushridge", region = 1, pvp = true, lang = 1}, 
		{ name = "Stonemaul", region = 1, pvp = true, lang = 1}, 
		{ name = "Daggerspine", region = 1, pvp = true, lang = 1}, 
		{ name = "Stormscale", region = 1, pvp = true, lang = 1}, 
		{ name = "Dunemaul", region = 1, pvp = true, lang = 1}, 
		{ name = "Boulderfist", region = 1, pvp = true, lang = 1}, 
		{ name = "Suramar", region = 1, pvp = false, lang = 1}, 
		{ name = "Dragonblight", region = 1, pvp = false, lang = 1}, 
		{ name = "Draenor", region = 1, pvp = false, lang = 1}, 
		{ name = "Uldum", region = 1, pvp = false, lang = 1}, 
		{ name = "Bronzebeard", region = 1, pvp = false, lang = 1}, 
		{ name = "Feathermoon", region = 1, pvp = false, lang = 1}, 
		{ name = "Bloodscalp", region = 1, pvp = true, lang = 1}, 
		{ name = "Darkspear", region = 1, pvp = true, lang = 1}, 
		{ name = "Azjol-Nerub", region = 1, pvp = false, lang = 1}, 
		{ name = "Perenolde", region = 1, pvp = false, lang = 1}, 
		{ name = "Argent Dawn", region = 1, pvp = false, lang = 1}, 
		{ name = "Azgalor", region = 1, pvp = true, lang = 1}, 
		{ name = "Magtheridon", region = 1, pvp = true, lang = 1}, 
		{ name = "Trollbane", region = 1, pvp = false, lang = 1}, 
		{ name = "Gallywix", region = 1, pvp = false, lang = 4}, 
		{ name = "Madoran", region = 1, pvp = false, lang = 1}, 
		{ name = "Stormrage", region = 1, pvp = false, lang = 1}, 
		{ name = "Zul'jin", region = 1, pvp = false, lang = 1}, 
		{ name = "Medivh", region = 1, pvp = false, lang = 1}, 
		{ name = "Durotan", region = 1, pvp = false, lang = 1}, 
		{ name = "Bloodhoof", region = 1, pvp = false, lang = 1}, 
		{ name = "Elune", region = 1, pvp = false, lang = 1}, 
		{ name = "Lothar", region = 1, pvp = false, lang = 1}, 
		{ name = "Arthas", region = 1, pvp = true, lang = 1}, 
		{ name = "Mannoroth", region = 1, pvp = true, lang = 1}, 
		{ name = "Warsong", region = 1, pvp = true, lang = 1}, 
		{ name = "Shattered Hand", region = 1, pvp = true, lang = 1}, 
		{ name = "Bleeding Hollow", region = 1, pvp = true, lang = 1}, 
		{ name = "Skullcrusher", region = 1, pvp = true, lang = 1}, 
		{ name = "Burning Blade", region = 1, pvp = true, lang = 1}, 
		{ name = "Gorefiend", region = 1, pvp = true, lang = 1}, 
		{ name = "Eredar", region = 1, pvp = true, lang = 1}, 
		{ name = "Shadowmoon", region = 1, pvp = true, lang = 1}, 
		{ name = "Lightning's Blade", region = 1, pvp = true, lang = 1}, 
		{ name = "Eonar", region = 1, pvp = false, lang = 1}, 
		{ name = "Gilneas", region = 1, pvp = false, lang = 1}, 
		{ name = "Kargath", region = 1, pvp = false, lang = 1}, 
		{ name = "Llane", region = 1, pvp = false, lang = 1}, 
		{ name = "Earthen Ring", region = 1, pvp = false, lang = 1}, 
		{ name = "Laughing Skull", region = 1, pvp = true, lang = 1}, 
		{ name = "Burning Legion", region = 1, pvp = true, lang = 1}, 
		{ name = "Thunderlord", region = 1, pvp = true, lang = 1}, 
		{ name = "Malygos", region = 1, pvp = false, lang = 1}, 
		{ name = "Drakkari", region = 1, pvp = true, lang = 3}, 
		{ name = "Aggramar", region = 1, pvp = false, lang = 1}, 
		{ name = "Thunderhorn", region = 1, pvp = false, lang = 1}, 
		{ name = "Ragnaros", region = 1, pvp = true, lang = 3}, 
		{ name = "Quel'Thalas", region = 1, pvp = false, lang = 3}, 
		{ name = "Kilrogg", region = 1, pvp = false, lang = 1}, 
		{ name = "Proudmoore", region = 1, pvp = false, lang = 1}, 
		{ name = "Frostwolf", region = 1, pvp = true, lang = 1}, 
		{ name = "Ner'zhul", region = 1, pvp = true, lang = 1}, 
		{ name = "Kil'jaeden", region = 1, pvp = true, lang = 1}, 
		{ name = "Blackrock", region = 1, pvp = true, lang = 1}, 
		{ name = "Tichondrius", region = 1, pvp = true, lang = 1}, 
		{ name = "Silver Hand", region = 1, pvp = false, lang = 1}, 
		{ name = "Vek'nilash", region = 1, pvp = false, lang = 1}, 
		{ name = "Sen'jin", region = 1, pvp = false, lang = 1}, 
		{ name = "Aegwynn", region = 1, pvp = true, lang = 1}, 
		{ name = "Akama", region = 1, pvp = true, lang = 1}, 
		{ name = "Chromaggus", region = 1, pvp = true, lang = 1}, 
		{ name = "Draka", region = 1, pvp = false, lang = 1}, 
		{ name = "Drak'thul", region = 1, pvp = false, lang = 1}, 
		{ name = "Garithos", region = 1, pvp = true, lang = 1}, 
		{ name = "Hakkar", region = 1, pvp = true, lang = 1}, 
		{ name = "Khaz Modan", region = 1, pvp = false, lang = 1}, 
		{ name = "Mug'thol", region = 1, pvp = true, lang = 1}, 
		{ name = "Korgath", region = 1, pvp = true, lang = 1}, 
		{ name = "Kul Tiras", region = 1, pvp = false, lang = 1}, 
		{ name = "Malorne", region = 1, pvp = true, lang = 1}, 
		{ name = "Eitrigg", region = 1, pvp = false, lang = 1}, 
		{ name = "Rexxar", region = 1, pvp = false, lang = 1}, 
		{ name = "Muradin", region = 1, pvp = false, lang = 1}, 
		{ name = "Thorium Brotherhood", region = 1, pvp = false, lang = 1}, 
		{ name = "Runetotem", region = 1, pvp = false, lang = 1}, 
		{ name = "Garona", region = 1, pvp = false, lang = 1}, 
		{ name = "Alleria", region = 1, pvp = false, lang = 1}, 
		{ name = "Hellscream", region = 1, pvp = false, lang = 1}, 
		{ name = "Blackhand", region = 1, pvp = false, lang = 1}, 
		{ name = "Whisperwind", region = 1, pvp = false, lang = 1}, 
		{ name = "Cho'gall", region = 1, pvp = true, lang = 1}, 
		{ name = "Illidan", region = 1, pvp = true, lang = 1}, 
		{ name = "Stormreaver", region = 1, pvp = true, lang = 1}, 
		{ name = "Gul'dan", region = 1, pvp = true, lang = 1}, 
		{ name = "Kael'thas", region = 1, pvp = false, lang = 1}, 
		{ name = "Alexstrasza", region = 1, pvp = false, lang = 1}, 
		{ name = "Kirin Tor", region = 1, pvp = false, lang = 1}, 
		{ name = "Ravencrest", region = 1, pvp = false, lang = 1}, 
		{ name = "Goldrinn", region = 1, pvp = false, lang = 4}, 
		{ name = "Nemesis", region = 1, pvp = true, lang = 4}, 
		{ name = "Balnazzar", region = 1, pvp = true, lang = 1}, 
		{ name = "Destromath", region = 1, pvp = true, lang = 1}, 
		{ name = "Gorgonnash", region = 1, pvp = true, lang = 1}, 
		{ name = "Dethecus", region = 1, pvp = true, lang = 1}, 
		{ name = "Spinebreaker", region = 1, pvp = true, lang = 1}, 
		{ name = "Moonrunner", region = 1, pvp = false, lang = 1}, 
		{ name = "Sargeras", region = 1, pvp = true, lang = 1}, 
		{ name = "Kalecgos", region = 1, pvp = true, lang = 1}, 
		{ name = "Ursin", region = 1, pvp = true, lang = 1}, 
		{ name = "Dark Iron", region = 1, pvp = true, lang = 1}, 
		{ name = "Greymane", region = 1, pvp = false, lang = 1}, 
		{ name = "Wildhammer", region = 1, pvp = true, lang = 1}, 
		{ name = "Detheroc", region = 1, pvp = true, lang = 1}, 
		{ name = "Staghelm", region = 1, pvp = false, lang = 1}, 
		{ name = "Emerald Dream", region = 1, pvp = true, lang = 1}, 
		{ name = "Maelstrom", region = 1, pvp = true, lang = 1}, 
		{ name = "Twisting Nether", region = 1, pvp = true, lang = 1}, 
		{ name = "Azshara", region = 1, pvp = true, lang = 1}, 
		{ name = "Agamaggan", region = 1, pvp = true, lang = 1}, 
		{ name = "Lightninghoof", region = 1, pvp = true, lang = 1}, 
		{ name = "Nazjatar", region = 1, pvp = true, lang = 1}, 
		{ name = "Malfurion", region = 1, pvp = false, lang = 1}, 
		{ name = "Baelgun", region = 1, pvp = false, lang = 1}, 
		{ name = "Azralon", region = 1, pvp = true, lang = 4}, 
		{ name = "Tol Barad", region = 1, pvp = true, lang = 4}, 
		{ name = "Duskwood", region = 1, pvp = false, lang = 1}, 
		{ name = "Zuluhed", region = 1, pvp = true, lang = 1}, 
		{ name = "Steamwheedle Cartel", region = 1, pvp = false, lang = 1}, 
		{ name = "Mal'Ganis", region = 1, pvp = true, lang = 1}, 
		{ name = "Norgannon", region = 1, pvp = false, lang = 1}, 
		{ name = "Archimonde", region = 1, pvp = true, lang = 1}, 
		{ name = "Anetheron", region = 1, pvp = true, lang = 1}, 
		{ name = "Turalyon", region = 1, pvp = false, lang = 1}, 
		{ name = "Haomarush", region = 1, pvp = true, lang = 1}, 
		{ name = "Scilla", region = 1, pvp = true, lang = 1}, 
		{ name = "Ysondre", region = 1, pvp = true, lang = 1}, 
		{ name = "Thrall", region = 1, pvp = false, lang = 1}, 
		{ name = "Ysera", region = 1, pvp = false, lang = 1}, 
		{ name = "Dentarg", region = 1, pvp = false, lang = 1}, 
		{ name = "Khadgar", region = 1, pvp = false, lang = 1}, 
		{ name = "Dalaran", region = 1, pvp = false, lang = 1}, 
		{ name = "Dalvengyr", region = 1, pvp = true, lang = 1}, 
		{ name = "Black Dragonflight", region = 1, pvp = true, lang = 1}, 
		{ name = "Andorhal", region = 1, pvp = true, lang = 1}, 
		{ name = "Executus", region = 1, pvp = true, lang = 1}, 
		{ name = "Doomhammer", region = 1, pvp = false, lang = 1}, 
		{ name = "Icecrown", region = 1, pvp = false, lang = 1}, 
		{ name = "Deathwing", region = 1, pvp = true, lang = 1}, 
		{ name = "Kel'Thuzad", region = 1, pvp = true, lang = 1}, 
		{ name = "Altar of Storms", region = 1, pvp = true, lang = 1}, 
		{ name = "Uldaman", region = 1, pvp = false, lang = 1}, 
		{ name = "Aerie Peak", region = 1, pvp = false, lang = 1}, 
		{ name = "Onyxia", region = 1, pvp = true, lang = 1}, 
		{ name = "Demon Soul", region = 1, pvp = true, lang = 1}, 
		{ name = "Gnomeregan", region = 1, pvp = false, lang = 1}, 
		{ name = "Anvilmar", region = 1, pvp = false, lang = 1}, 
		{ name = "The Venture Co", region = 1, pvp = true, lang = 1}, 
		{ name = "Sentinels", region = 1, pvp = false, lang = 1}, 
		{ name = "Jaedenar", region = 1, pvp = true, lang = 1}, 
		{ name = "Tanaris", region = 1, pvp = false, lang = 1}, 
		{ name = "Alterac Mountains", region = 1, pvp = true, lang = 1}, 
		{ name = "Undermine", region = 1, pvp = false, lang = 1}, 
		{ name = "Lethon", region = 1, pvp = true, lang = 1}, 
		{ name = "Blackwing Lair", region = 1, pvp = true, lang = 1}, 
		{ name = "Arygos", region = 1, pvp = false, lang = 1}, 
		{ name = "Lightbringer", region = 1, pvp = false, lang = 1}, 
		{ name = "Cenarius", region = 1, pvp = false, lang = 1}, 
		{ name = "Uther", region = 1, pvp = false, lang = 1}, 
		{ name = "Cenarion Circle", region = 1, pvp = false, lang = 1}, 
		{ name = "Echo Isles", region = 1, pvp = false, lang = 1}, 
		{ name = "Hyjal", region = 1, pvp = false, lang = 1}, 
		{ name = "The Forgotten Coast", region = 1, pvp = true, lang = 1}, 
		{ name = "Fenris", region = 1, pvp = false, lang = 1}, 
		{ name = "Anub'arak", region = 1, pvp = true, lang = 1}, 
		{ name = "Blackwater Raiders", region = 1, pvp = false, lang = 1}, 
		{ name = "Vashj", region = 1, pvp = true, lang = 1}, 
		{ name = "Korialstrasz", region = 1, pvp = false, lang = 1}, 
		{ name = "Misha", region = 1, pvp = false, lang = 1}, 
		{ name = "Darrowmere", region = 1, pvp = false, lang = 1}, 
		{ name = "Ravenholdt", region = 1, pvp = true, lang = 1}, 
		{ name = "Bladefist", region = 1, pvp = false, lang = 1}, 
		{ name = "Shu'halo", region = 1, pvp = false, lang = 1}, 
		{ name = "Winterhoof", region = 1, pvp = false, lang = 1}, 
		{ name = "Sisters of Elune", region = 1, pvp = false, lang = 1}, 
		{ name = "Maiev", region = 1, pvp = true, lang = 1}, 
		{ name = "Rivendare", region = 1, pvp = true, lang = 1}, 
		{ name = "Nordrassil", region = 1, pvp = false, lang = 1}, 
		{ name = "Tortheldrin", region = 1, pvp = true, lang = 1}, 
		{ name = "Cairne", region = 1, pvp = false, lang = 1}, 
		{ name = "Drak'Tharon", region = 1, pvp = true, lang = 1}, 
		{ name = "Antonidas", region = 1, pvp = false, lang = 1}, 
		{ name = "Shandris", region = 1, pvp = false, lang = 1}, 
		{ name = "Moon Guard", region = 1, pvp = false, lang = 1}, 
		{ name = "Nazgrel", region = 1, pvp = false, lang = 1}, 
		{ name = "Hydraxis", region = 1, pvp = false, lang = 1}, 
		{ name = "Wyrmrest Accord", region = 1, pvp = false, lang = 1}, 
		{ name = "Farstriders", region = 1, pvp = false, lang = 1}, 
		{ name = "Borean Tundra", region = 1, pvp = false, lang = 1}, 
		{ name = "Quel'dorei", region = 1, pvp = false, lang = 1}, 
		{ name = "Garrosh", region = 1, pvp = false, lang = 1}, 
		{ name = "Mok'Nathal", region = 1, pvp = false, lang = 1}, 
		{ name = "Nesingwary", region = 1, pvp = false, lang = 1}, 
		{ name = "Drenden", region = 1, pvp = false, lang = 1}, 
		{ name = "Terokkar", region = 1, pvp = false, lang = 1}, 
		{ name = "Blade's Edge", region = 1, pvp = false, lang = 1}, 
		{ name = "Exodar", region = 1, pvp = false, lang = 1}, 
		{ name = "Area 52", region = 1, pvp = false, lang = 1}, 
		{ name = "Velen", region = 1, pvp = false, lang = 1}, 
		{ name = "Azuremyst", region = 1, pvp = false, lang = 1}, 
		{ name = "Auchindoun", region = 1, pvp = true, lang = 1}, 
		{ name = "The Scryers", region = 1, pvp = false, lang = 1}, 
		{ name = "Coilfang", region = 1, pvp = true, lang = 1}, 
		{ name = "Zangarmarsh", region = 1, pvp = false, lang = 1}, 
		{ name = "Shattered Halls", region = 1, pvp = true, lang = 1}, 
		{ name = "Blood Furnace", region = 1, pvp = true, lang = 1}, 
		{ name = "The Underbog", region = 1, pvp = true, lang = 1}, 
		{ name = "Fizzcrank", region = 1, pvp = false, lang = 1}, 
		{ name = "Ghostlands", region = 1, pvp = false, lang = 1}, 
		{ name = "Grizzly Hills", region = 1, pvp = false, lang = 1}, 
		{ name = "Galakrond", region = 1, pvp = false, lang = 1}, 
		{ name = "Dawnbringer", region = 1, pvp = false, lang = 1},
	-- Korea
		{ name = "불타는 군단", region = 2, pvp = false, lang = 1}, 
		{ name = "헬스크림", region = 2, pvp = true, lang = 1}, 
		{ name = "하이잘", region = 2, pvp = true, lang = 1}, 
		{ name = "데스윙", region = 2, pvp = true, lang = 1}, 
		{ name = "세나리우스", region = 2, pvp = true, lang = 1}, 
		{ name = "윈드러너", region = 2, pvp = false, lang = 1}, 
		{ name = "아즈샤라", region = 2, pvp = true, lang = 1}, 
		{ name = "듀로탄", region = 2, pvp = true, lang = 1}, 
		{ name = "줄진", region = 2, pvp = true, lang = 1}, 			
	-- EU
		{ name = "Aggramar", region = 3, pvp = false, lang = 1}, 
		{ name = "Arathor", region = 3, pvp = false, lang = 1}, 
		{ name = "Aszune", region = 3, pvp = false, lang = 1}, 
		{ name = "Azjol-Nerub", region = 3, pvp = false, lang = 1}, 
		{ name = "Bloodhoof", region = 3, pvp = false, lang = 1}, 
		{ name = "Doomhammer", region = 3, pvp = false, lang = 1}, 
		{ name = "Draenor", region = 3, pvp = false, lang = 1}, 
		{ name = "Dragonblight", region = 3, pvp = false, lang = 1}, 
		{ name = "Emerald Dream", region = 3, pvp = false, lang = 1}, 
		{ name = "Sunstrider", region = 3, pvp = true, lang = 1}, 
		{ name = "Twilight's Hammer", region = 3, pvp = true, lang = 1}, 
		{ name = "Zenedar", region = 3, pvp = true, lang = 1}, 
		{ name = "Aggra (Português)", region = 3, pvp = true, lang = 1}, 
		{ name = "Agamaggan", region = 3, pvp = true, lang = 1}, 
		{ name = "Al'Akir", region = 3, pvp = true, lang = 1}, 
		{ name = "Bladefist", region = 3, pvp = true, lang = 1}, 
		{ name = "Bloodscalp", region = 3, pvp = true, lang = 1}, 
		{ name = "Burning Blade", region = 3, pvp = true, lang = 1}, 
		{ name = "Burning Legion", region = 3, pvp = true, lang = 1}, 
		{ name = "Crushridge", region = 3, pvp = true, lang = 1}, 
		{ name = "Daggerspine", region = 3, pvp = true, lang = 1}, 
		{ name = "Deathwing", region = 3, pvp = true, lang = 1}, 
		{ name = "Dragonmaw", region = 3, pvp = true, lang = 1}, 
		{ name = "Dunemaul", region = 3, pvp = true, lang = 1}, 
		{ name = "Sinstralis", region = 3, pvp = true, lang = 2}, 
		{ name = "Argent Dawn", region = 3, pvp = false, lang = 1}, 
		{ name = "Kirin Tor", region = 3, pvp = false, lang = 2}, 
		{ name = "Dalaran", region = 3, pvp = false, lang = 2}, 
		{ name = "Archimonde", region = 3, pvp = true, lang = 2}, 
		{ name = "Elune", region = 3, pvp = false, lang = 2}, 
		{ name = "Illidan", region = 3, pvp = true, lang = 2}, 
		{ name = "Hyjal", region = 3, pvp = false, lang = 2}, 
		{ name = "Kael'thas", region = 3, pvp = true, lang = 2}, 
		{ name = "Ner'zhul", region = 3, pvp = true, lang = 2}, 
		{ name = "Cho'gall", region = 3, pvp = true, lang = 2}, 
		{ name = "Sargeras", region = 3, pvp = true, lang = 2}, 
		{ name = "Runetotem", region = 3, pvp = false, lang = 1}, 
		{ name = "Shadowsong", region = 3, pvp = false, lang = 1}, 
		{ name = "Silvermoon", region = 3, pvp = false, lang = 1}, 
		{ name = "Stormrage", region = 3, pvp = false, lang = 1}, 
		{ name = "Terenas", region = 3, pvp = false, lang = 1}, 
		{ name = "Thunderhorn", region = 3, pvp = false, lang = 1}, 
		{ name = "Turalyon", region = 3, pvp = false, lang = 1}, 
		{ name = "Ravencrest", region = 3, pvp = true, lang = 1}, 
		{ name = "Shattered Hand", region = 3, pvp = true, lang = 1}, 
		{ name = "Skullcrusher", region = 3, pvp = true, lang = 1}, 
		{ name = "Spinebreaker", region = 3, pvp = true, lang = 1}, 
		{ name = "Stormreaver", region = 3, pvp = true, lang = 1}, 
		{ name = "Stormscale", region = 3, pvp = true, lang = 1}, 
		{ name = "Earthen Ring", region = 3, pvp = false, lang = 1}, 
		{ name = "Alexstrasza", region = 3, pvp = false, lang = 3}, 
		{ name = "Alleria", region = 3, pvp = false, lang = 3}, 
		{ name = "Antonidas", region = 3, pvp = false, lang = 3}, 
		{ name = "Baelgun", region = 3, pvp = false, lang = 3}, 
		{ name = "Blackhand", region = 3, pvp = false, lang = 3}, 
		{ name = "Madmortem", region = 3, pvp = false, lang = 3}, 
		{ name = "Malfurion", region = 3, pvp = false, lang = 3}, 
		{ name = "Zuluhed", region = 3, pvp = true, lang = 3}, 
		{ name = "Nozdormu", region = 3, pvp = false, lang = 3}, 
		{ name = "Perenolde", region = 3, pvp = false, lang = 3}, 
		{ name = "Die Silberne Hand", region = 3, pvp = false, lang = 3}, 
		{ name = "Aegwynn", region = 3, pvp = true, lang = 3}, 
		{ name = "Destromath", region = 3, pvp = true, lang = 3}, 
		{ name = "Eredar", region = 3, pvp = true, lang = 3}, 
		{ name = "Frostmourne", region = 3, pvp = true, lang = 3}, 
		{ name = "Frostwolf", region = 3, pvp = true, lang = 3}, 
		{ name = "Gorgonnash", region = 3, pvp = true, lang = 3}, 
		{ name = "Gul'dan", region = 3, pvp = true, lang = 3}, 
		{ name = "Kel'Thuzad", region = 3, pvp = true, lang = 3}, 
		{ name = "Kil'jaeden", region = 3, pvp = true, lang = 3}, 
		{ name = "Mal'Ganis", region = 3, pvp = true, lang = 3}, 
		{ name = "Mannoroth", region = 3, pvp = true, lang = 3}, 
		{ name = "Zirkel des Cenarius", region = 3, pvp = false, lang = 3}, 
		{ name = "Proudmoore", region = 3, pvp = false, lang = 3}, 
		{ name = "Nathrezim", region = 3, pvp = true, lang = 3}, 
		{ name = "Dun Morogh", region = 3, pvp = false, lang = 3}, 
		{ name = "Aman'Thul", region = 3, pvp = false, lang = 3}, 
		{ name = "Sen'jin", region = 3, pvp = false, lang = 3}, 
		{ name = "Theradras", region = 3, pvp = true, lang = 3}, 
		{ name = "Genjuros", region = 3, pvp = true, lang = 1}, 
		{ name = "Balnazzar", region = 3, pvp = true, lang = 1}, 
		{ name = "Anub'arak", region = 3, pvp = true, lang = 3}, 
		{ name = "Wrathbringer", region = 3, pvp = true, lang = 3}, 
		{ name = "Onyxia", region = 3, pvp = true, lang = 3}, 
		{ name = "Nera'thor", region = 3, pvp = true, lang = 3}, 
		{ name = "Kult der Verdammten", region = 3, pvp = true, lang = 3}, 
		{ name = "Das Syndikat", region = 3, pvp = true, lang = 3}, 
		{ name = "Terrordar", region = 3, pvp = true, lang = 3}, 
		{ name = "Krag'jin", region = 3, pvp = true, lang = 3}, 
		{ name = "Der Rat von Dalaran", region = 3, pvp = false, lang = 3}, 
		{ name = "Nordrassil", region = 3, pvp = false, lang = 1}, 
		{ name = "Hellscream", region = 3, pvp = false, lang = 1}, 
		{ name = "Laughing Skull", region = 3, pvp = true, lang = 1}, 
		{ name = "Magtheridon", region = 3, pvp = false, lang = 1}, 
		{ name = "Quel'Thalas", region = 3, pvp = false, lang = 1}, 
		{ name = "Neptulon", region = 3, pvp = true, lang = 1}, 
		{ name = "Twisting Nether", region = 3, pvp = true, lang = 1}, 
		{ name = "Ragnaros", region = 3, pvp = true, lang = 1}, 
		{ name = "The Maelstrom", region = 3, pvp = true, lang = 1}, 
		{ name = "Sylvanas", region = 3, pvp = true, lang = 1}, 
		{ name = "Vashj", region = 3, pvp = true, lang = 1}, 
		{ name = "Bloodfeather", region = 3, pvp = true, lang = 1}, 
		{ name = "Darksorrow", region = 3, pvp = true, lang = 1}, 
		{ name = "Frostwhisper", region = 3, pvp = true, lang = 1}, 
		{ name = "Defias Brotherhood", region = 3, pvp = true, lang = 1}, 
		{ name = "The Venture Co", region = 3, pvp = true, lang = 1}, 
		{ name = "Lightning's Blade", region = 3, pvp = true, lang = 1}, 
		{ name = "Haomarush", region = 3, pvp = true, lang = 1}, 
		{ name = "Khaz Modan", region = 3, pvp = false, lang = 2}, 
		{ name = "Drek'Thar", region = 3, pvp = false, lang = 2}, 
		{ name = "Rashgarroth", region = 3, pvp = true, lang = 2}, 
		{ name = "Throk'Feroth", region = 3, pvp = true, lang = 2}, 
		{ name = "Conseil des Ombres", region = 3, pvp = true, lang = 2}, 
		{ name = "Varimathras", region = 3, pvp = false, lang = 2}, 
		{ name = "Les Sentinelles", region = 3, pvp = false, lang = 2}, 
		{ name = "Khadgar", region = 3, pvp = false, lang = 1}, 
		{ name = "Bronzebeard", region = 3, pvp = false, lang = 1}, 
		{ name = "Kul Tiras", region = 3, pvp = false, lang = 1}, 
		{ name = "Chromaggus", region = 3, pvp = true, lang = 1}, 
		{ name = "Dentarg", region = 3, pvp = true, lang = 1}, 
		{ name = "Moonglade", region = 3, pvp = false, lang = 1}, 
		{ name = "Executus", region = 3, pvp = true, lang = 1}, 
		{ name = "Trollbane", region = 3, pvp = true, lang = 1}, 
		{ name = "Mazrigos", region = 3, pvp = false, lang = 1}, 
		{ name = "Talnivarr", region = 3, pvp = true, lang = 1}, 
		{ name = "Emeriss", region = 3, pvp = true, lang = 1}, 
		{ name = "Drak'thul", region = 3, pvp = true, lang = 1}, 
		{ name = "Ahn'Qiraj", region = 3, pvp = true, lang = 1}, 
		{ name = "Ysera", region = 3, pvp = false, lang = 3}, 
		{ name = "Malygos", region = 3, pvp = false, lang = 3}, 
		{ name = "Rexxar", region = 3, pvp = false, lang = 3}, 
		{ name = "Gilneas", region = 3, pvp = false, lang = 3}, 
		{ name = "Kargath", region = 3, pvp = false, lang = 3}, 
		{ name = "Khaz'goroth", region = 3, pvp = false, lang = 3}, 
		{ name = "Lothar", region = 3, pvp = false, lang = 3}, 
		{ name = "Anetheron", region = 3, pvp = true, lang = 3}, 
		{ name = "Nazjatar", region = 3, pvp = true, lang = 3}, 
		{ name = "Tichondrius", region = 3, pvp = false, lang = 3}, 
		{ name = "Thrall", region = 3, pvp = false, lang = 3}, 
		{ name = "Terokkar", region = 3, pvp = false, lang = 1}, 
		{ name = "Nefarian", region = 3, pvp = true, lang = 3}, 
		{ name = "Durotan", region = 3, pvp = false, lang = 3}, 
		{ name = "Arthas", region = 3, pvp = true, lang = 3}, 
		{ name = "Azshara", region = 3, pvp = true, lang = 3}, 
		{ name = "Blackmoore", region = 3, pvp = true, lang = 3}, 
		{ name = "Blackrock", region = 3, pvp = true, lang = 3}, 
		{ name = "Hakkar", region = 3, pvp = true, lang = 1}, 
		{ name = "Xavius", region = 3, pvp = true, lang = 1}, 
		{ name = "Steamwheedle Cartel", region = 3, pvp = false, lang = 1}, 
		{ name = "Die ewige Wacht", region = 3, pvp = false, lang = 3}, 
		{ name = "Die Todeskrallen", region = 3, pvp = true, lang = 3}, 
		{ name = "Scarshield Legion", region = 3, pvp = true, lang = 1}, 
		{ name = "Die Arguswacht", region = 3, pvp = true, lang = 3}, 
		{ name = "Blade's Edge", region = 3, pvp = false, lang = 1}, 
		{ name = "Azuremyst", region = 3, pvp = false, lang = 1}, 
		{ name = "Vek'nilash", region = 3, pvp = false, lang = 1}, 
		{ name = "Boulderfist", region = 3, pvp = true, lang = 1}, 
		{ name = "Frostmane", region = 3, pvp = true, lang = 1}, 
		{ name = "Outland", region = 3, pvp = true, lang = 1}, 
		{ name = "Grim Batol", region = 3, pvp = true, lang = 1}, 
		{ name = "Jaedenar", region = 3, pvp = true, lang = 1}, 
		{ name = "Kazzak", region = 3, pvp = true, lang = 1}, 
		{ name = "Tarren Mill", region = 3, pvp = true, lang = 1}, 
		{ name = "Chamber of Aspects", region = 3, pvp = false, lang = 1}, 
		{ name = "Ravenholdt", region = 3, pvp = true, lang = 1}, 
		{ name = "Pozzo dell'Eternità", region = 3, pvp = false, lang = 4}, 
		{ name = "Eonar", region = 3, pvp = false, lang = 1}, 
		{ name = "Kilrogg", region = 3, pvp = false, lang = 1}, 
		{ name = "Aerie Peak", region = 3, pvp = false, lang = 1}, 
		{ name = "Wildhammer", region = 3, pvp = false, lang = 1}, 
		{ name = "Saurfang", region = 3, pvp = false, lang = 1}, 
		{ name = "Nemesis", region = 3, pvp = true, lang = 4}, 
		{ name = "Vek'lor", region = 3, pvp = true, lang = 3}, 
		{ name = "Mug'thol", region = 3, pvp = true, lang = 3}, 
		{ name = "Taerar", region = 3, pvp = true, lang = 3}, 
		{ name = "Dalvengyr", region = 3, pvp = true, lang = 3}, 
		{ name = "Rajaxx", region = 3, pvp = true, lang = 3}, 
		{ name = "Ulduar", region = 3, pvp = false, lang = 3}, 
		{ name = "Malorne", region = 3, pvp = false, lang = 3}, 
		{ name = "Der abyssische Rat", region = 3, pvp = true, lang = 3}, 
		{ name = "Lordaeron", region = 3, pvp = false, lang = 3}, 
		{ name = "Tirion", region = 3, pvp = false, lang = 3}, 
		{ name = "Ambossar", region = 3, pvp = false, lang = 3}, 
		{ name = "Krasus", region = 3, pvp = false, lang = 2}, 
		{ name = "Die Nachtwache", region = 3, pvp = false, lang = 3}, 
		{ name = "Arathi", region = 3, pvp = true, lang = 2}, 
		{ name = "Ysondre", region = 3, pvp = true, lang = 2}, 
		{ name = "Eldre'Thalas", region = 3, pvp = true, lang = 2}, 
		{ name = "Culte de la Rive noire", region = 3, pvp = true, lang = 2}, 
		{ name = "Dun Modr", region = 3, pvp = true, lang = 6}, 
		{ name = "Zul'jin", region = 3, pvp = true, lang = 6}, 
		{ name = "Uldum", region = 3, pvp = true, lang = 6}, 
		{ name = "C'Thun", region = 3, pvp = true, lang = 6}, 
		{ name = "Sanguino", region = 3, pvp = true, lang = 6}, 
		{ name = "Shen'dralar", region = 3, pvp = true, lang = 6}, 
		{ name = "Tyrande", region = 3, pvp = false, lang = 6}, 
		{ name = "Exodar", region = 3, pvp = false, lang = 6}, 
		{ name = "Minahonda", region = 3, pvp = false, lang = 6}, 
		{ name = "Los Errantes", region = 3, pvp = false, lang = 6}, 
		{ name = "Lightbringer", region = 3, pvp = false, lang = 1}, 
		{ name = "Darkspear", region = 3, pvp = false, lang = 1}, 
		{ name = "Darkmoon Faire", region = 3, pvp = false, lang = 1}, 
		{ name = "Alonsus", region = 3, pvp = false, lang = 1}, 
		{ name = "Burning Steppes", region = 3, pvp = true, lang = 1}, 
		{ name = "Bronze Dragonflight", region = 3, pvp = false, lang = 1}, 
		{ name = "Anachronos", region = 3, pvp = false, lang = 1}, 
		{ name = "Spirestone", region = 3, pvp = false, lang = 6}, 
		{ name = "Kor'gall", region = 3, pvp = true, lang = 1}, 
		{ name = "Forscherliga", region = 3, pvp = false, lang = 3}, 
		{ name = "Dethecus", region = 3, pvp = true, lang = 3}, 
		{ name = "Un'Goro", region = 3, pvp = false, lang = 3}, 
		{ name = "Garrosh", region = 3, pvp = false, lang = 3}, 
		{ name = "Area 52", region = 3, pvp = false, lang = 3}, 
		{ name = "Todeswache", region = 3, pvp = false, lang = 3}, 
		{ name = "Arygos", region = 3, pvp = false, lang = 3}, 
		{ name = "Teldrassil", region = 3, pvp = false, lang = 3}, 
		{ name = "Norgannon", region = 3, pvp = false, lang = 3}, 
		{ name = "Der Mithrilorden", region = 3, pvp = false, lang = 3}, 
		{ name = "Garona", region = 3, pvp = true, lang = 2}, 
		{ name = "Vol'jin", region = 3, pvp = false, lang = 2}, 
		{ name = "Arak-arahm", region = 3, pvp = true, lang = 2}, 
		{ name = "Medivh", region = 3, pvp = false, lang = 2}, 
		{ name = "La Croisade écarlate", region = 3, pvp = true, lang = 2}, 
		{ name = "Confrérie du Thorium", region = 3, pvp = false, lang = 2}, 
		{ name = "Uldaman", region = 3, pvp = false, lang = 2}, 
		{ name = "Eitrigg", region = 3, pvp = false, lang = 2}, 
		{ name = "Hellfire", region = 3, pvp = false, lang = 1}, 
		{ name = "Ghostlands", region = 3, pvp = false, lang = 1}, 
		{ name = "Nagrand", region = 3, pvp = false, lang = 1}, 
		{ name = "Азурегос", region = 3, pvp = false, lang = 5}, 
		{ name = "Ясеневый лес", region = 3, pvp = true, lang = 5}, 
		{ name = "Пиратская бухта", region = 3, pvp = true, lang = 5}, 
		{ name = "Вечная Песня", region = 3, pvp = false, lang = 5}, 
		{ name = "Термоштепсель", region = 3, pvp = true, lang = 5}, 
		{ name = "The Sha'tar", region = 3, pvp = false, lang = 1}, 
		{ name = "Karazhan", region = 3, pvp = true, lang = 1}, 
		{ name = "Auchindoun", region = 3, pvp = true, lang = 1}, 
		{ name = "Shattered Halls", region = 3, pvp = true, lang = 1}, 
		{ name = "Гром", region = 3, pvp = true, lang = 5}, 
		{ name = "Голдринн", region = 3, pvp = false, lang = 5}, 
		{ name = "Черный Шрам", region = 3, pvp = true, lang = 5}, 
		{ name = "Гордунни", region = 3, pvp = true, lang = 5}, 
		{ name = "Король-лич", region = 3, pvp = true, lang = 5}, 
		{ name = "Свежеватель Душ", region = 3, pvp = true, lang = 5}, 
		{ name = "Страж Смерти", region = 3, pvp = true, lang = 5}, 
		{ name = "Sporeggar", region = 3, pvp = true, lang = 1}, 
		{ name = "Nethersturm", region = 3, pvp = false, lang = 3}, 
		{ name = "Shattrath", region = 3, pvp = false, lang = 3}, 
		{ name = "Галакронд", region = 3, pvp = false, lang = 5}, 
		{ name = "Седогрив", region = 3, pvp = true, lang = 5}, 
		{ name = "Festung der Stürme", region = 3, pvp = true, lang = 3}, 
		{ name = "Echsenkessel", region = 3, pvp = true, lang = 3}, 
		{ name = "Blutkessel", region = 3, pvp = true, lang = 3}, 
		{ name = "Подземье", region = 3, pvp = true, lang = 5}, 
		{ name = "Ревущий фьорд", region = 3, pvp = true, lang = 5}, 
		{ name = "Разувий", region = 3, pvp = true, lang = 5}, 
		{ name = "Ткач Смерти", region = 3, pvp = true, lang = 5}, 
		{ name = "Die Aldor", region = 3, pvp = false, lang = 3}, 
		{ name = "Das Konsortium", region = 3, pvp = true, lang = 3}, 
		{ name = "Chants éternels", region = 3, pvp = false, lang = 2}, 
		{ name = "Marécage de Zangar", region = 3, pvp = false, lang = 2}, 
		{ name = "Temple noir", region = 3, pvp = true, lang = 2}, 
		{ name = "Дракономор", region = 3, pvp = false, lang = 5}, 
		{ name = "Naxxramas", region = 3, pvp = true, lang = 2}, 
		{ name = "Борейская тундра", region = 3, pvp = false, lang = 5}, 
		{ name = "Les Clairvoyants", region = 3, pvp = false, lang = 2}, 
		
	-- Taiwan
		{ name = "暗影之月", region = 4, pvp = false, lang = 1}, 
		{ name = "世界之樹", region = 4, pvp = false, lang = 1}, 
		{ name = "天空之牆", region = 4, pvp = false, lang = 1}, 
		{ name = "尖石", region = 4, pvp = true, lang = 1}, 
		{ name = "日落沼澤", region = 4, pvp = true, lang = 1}, 
		{ name = "狂熱之刃", region = 4, pvp = true, lang = 1}, 
		{ name = "巨龍之喉", region = 4, pvp = true, lang = 1}, 
		{ name = "冰霜之刺", region = 4, pvp = true, lang = 1}, 
		{ name = "地獄吼", region = 4, pvp = true, lang = 1}, 
		{ name = "水晶之刺", region = 4, pvp = true, lang = 1}, 
		{ name = "冰風崗哨", region = 4, pvp = true, lang = 1}, 
		{ name = "雷鱗", region = 4, pvp = true, lang = 1}, 
		{ name = "米奈希爾", region = 4, pvp = true, lang = 1}, 
		{ name = "亞雷戈斯", region = 4, pvp = false, lang = 1}, 
		{ name = "語風", region = 4, pvp = false, lang = 1}, 
		{ name = "眾星之子", region = 4, pvp = false, lang = 1}, 
		{ name = "聖光之願", region = 4, pvp = false, lang = 1}, 
		{ name = "屠魔山谷", region = 4, pvp = true, lang = 1}, 
		{ name = "銀翼要塞", region = 4, pvp = true, lang = 1}, 
		{ name = "夜空之歌", region = 4, pvp = true, lang = 1}, 
		{ name = "血之谷", region = 4, pvp = true, lang = 1}, 
		{ name = "憤怒使者", region = 4, pvp = true, lang = 1}, 
		{ name = "寒冰皇冠", region = 4, pvp = true, lang = 1}, 
		{ name = "阿薩斯", region = 4, pvp = true, lang = 1}, 
		{ name = "雲蛟衛", region = 4, pvp = false, lang = 1}, 		
	-- China
		{ name = "阿格拉玛", region = 5, pvp = true, lang = 1}, 
		{ name = "丽丽 (四川)", region = 5, pvp = true, lang = 1}, 
		{ name = "晴日峰 (江苏)", region = 5, pvp = true, lang = 1}, 
		{ name = "艾苏恩", region = 5, pvp = true, lang = 1}, 
		{ name = "安威玛尔", region = 5, pvp = true, lang = 1}, 
		{ name = "奥达曼", region = 5, pvp = true, lang = 1}, 
		{ name = "奥蕾莉亚", region = 5, pvp = false, lang = 1}, 
		{ name = "白银之手", region = 5, pvp = false, lang = 1}, 
		{ name = "暴风祭坛", region = 5, pvp = true, lang = 1}, 
		{ name = "藏宝海湾", region = 5, pvp = true, lang = 1}, 
		{ name = "尘风峡谷", region = 5, pvp = true, lang = 1}, 
		{ name = "达纳斯", region = 5, pvp = true, lang = 1}, 
		{ name = "迪托马斯", region = 5, pvp = true, lang = 1}, 
		{ name = "国王之谷", region = 5, pvp = true, lang = 1}, 
		{ name = "黑龙军团", region = 5, pvp = true, lang = 1}, 
		{ name = "黑石尖塔", region = 5, pvp = true, lang = 1}, 
		{ name = "红龙军团", region = 5, pvp = true, lang = 1}, 
		{ name = "回音山", region = 5, pvp = false, lang = 1}, 
		{ name = "基尔罗格", region = 5, pvp = true, lang = 1}, 
		{ name = "卡德罗斯", region = 5, pvp = true, lang = 1}, 
		{ name = "卡扎克", region = 5, pvp = true, lang = 1}, 
		{ name = "库德兰", region = 5, pvp = true, lang = 1}, 
		{ name = "蓝龙军团", region = 5, pvp = true, lang = 1}, 
		{ name = "雷霆之王", region = 5, pvp = true, lang = 1}, 
		{ name = "烈焰峰", region = 5, pvp = true, lang = 1}, 
		{ name = "辛达苟萨", region = 5, pvp = true, lang = 1}, 
		{ name = "罗宁", region = 5, pvp = true, lang = 1}, 
		{ name = "洛萨", region = 5, pvp = true, lang = 1}, 
		{ name = "玛多兰", region = 5, pvp = false, lang = 1}, 
		{ name = "玛瑟里顿", region = 5, pvp = true, lang = 1}, 
		{ name = "奈萨里奥", region = 5, pvp = true, lang = 1}, 
		{ name = "诺莫瑞根", region = 5, pvp = true, lang = 1}, 
		{ name = "普瑞斯托", region = 5, pvp = false, lang = 1}, 
		{ name = "燃烧平原", region = 5, pvp = true, lang = 1}, 
		{ name = "萨格拉斯", region = 5, pvp = true, lang = 1}, 
		{ name = "山丘之王", region = 5, pvp = true, lang = 1}, 
		{ name = "死亡之翼", region = 5, pvp = true, lang = 1}, 
		{ name = "索拉丁", region = 5, pvp = true, lang = 1}, 
		{ name = "索瑞森", region = 5, pvp = true, lang = 1}, 
		{ name = "铜龙军团", region = 5, pvp = true, lang = 1}, 
		{ name = "图拉扬", region = 5, pvp = false, lang = 1}, 
		{ name = "伊瑟拉", region = 5, pvp = false, lang = 1}, 
		{ name = "时光之穴", region = 5, pvp = true, lang = 1}, 
		{ name = "阿比迪斯", region = 5, pvp = true, lang = 1}, 
		{ name = "阿曼尼", region = 5, pvp = true, lang = 1}, 
		{ name = "安苏", region = 5, pvp = true, lang = 1}, 
		{ name = "生态船", region = 5, pvp = true, lang = 1}, 
		{ name = "阿斯塔洛", region = 5, pvp = true, lang = 1}, 
		{ name = "白骨荒野", region = 5, pvp = true, lang = 1}, 
		{ name = "布鲁塔卢斯", region = 5, pvp = true, lang = 1}, 
		{ name = "达尔坎", region = 5, pvp = true, lang = 1}, 
		{ name = "末日行者", region = 5, pvp = true, lang = 1}, 
		{ name = "达基萨斯", region = 5, pvp = true, lang = 1}, 
		{ name = "熵魔", region = 5, pvp = true, lang = 1}, 
		{ name = "能源舰", region = 5, pvp = true, lang = 1}, 
		{ name = "菲米丝", region = 5, pvp = true, lang = 1}, 
		{ name = "加尔", region = 5, pvp = true, lang = 1}, 
		{ name = "迦顿", region = 5, pvp = true, lang = 1}, 
		{ name = "血吼", region = 5, pvp = true, lang = 1}, 
		{ name = "戈提克", region = 5, pvp = true, lang = 1}, 
		{ name = "盖斯", region = 5, pvp = true, lang = 1}, 
		{ name = "壁炉谷", region = 5, pvp = true, lang = 1}, 
		{ name = "贫瘠之地", region = 5, pvp = false, lang = 1}, 
		{ name = "霍格", region = 5, pvp = true, lang = 1}, 
		{ name = "奎尔丹纳斯", region = 5, pvp = true, lang = 1}, 
		{ name = "萨洛拉丝", region = 5, pvp = true, lang = 1}, 
		{ name = "沙怒", region = 5, pvp = true, lang = 1}, 
		{ name = "嚎风峡湾", region = 5, pvp = true, lang = 1}, 
		{ name = "迦拉克隆", region = 5, pvp = false, lang = 1}, 
		{ name = "奥杜尔", region = 5, pvp = false, lang = 1}, 
		{ name = "奥尔加隆", region = 5, pvp = true, lang = 1}, 
		{ name = "安格博达", region = 5, pvp = true, lang = 1}, 
		{ name = "安加萨", region = 5, pvp = true, lang = 1}, 
		{ name = "织亡者", region = 5, pvp = true, lang = 1}, 
		{ name = "亡语者", region = 5, pvp = true, lang = 1}, 
		{ name = "达克萨隆", region = 5, pvp = true, lang = 1}, 
		{ name = "黑锋哨站", region = 5, pvp = true, lang = 1}, 
		{ name = "古达克", region = 5, pvp = true, lang = 1}, 
		{ name = "洛肯", region = 5, pvp = true, lang = 1}, 
		{ name = "玛洛加尔", region = 5, pvp = true, lang = 1}, 
		{ name = "影之哀伤", region = 5, pvp = true, lang = 1}, 
		{ name = "风暴峭壁", region = 5, pvp = true, lang = 1}, 
		{ name = "远古海滩", region = 5, pvp = true, lang = 1}, 
		{ name = "瓦拉纳", region = 5, pvp = true, lang = 1}, 
		{ name = "冬拥湖", region = 5, pvp = true, lang = 1}, 
		{ name = "阿迦玛甘", region = 5, pvp = true, lang = 1}, 
		{ name = "阿克蒙德", region = 5, pvp = true, lang = 1}, 
		{ name = "埃加洛尔", region = 5, pvp = true, lang = 1}, 
		{ name = "埃苏雷格", region = 5, pvp = true, lang = 1}, 
		{ name = "艾萨拉", region = 5, pvp = true, lang = 1}, 
		{ name = "艾森娜", region = 5, pvp = false, lang = 1}, 
		{ name = "爱斯特纳", region = 5, pvp = true, lang = 1}, 
		{ name = "暗影之月", region = 5, pvp = true, lang = 1}, 
		{ name = "奥拉基尔", region = 5, pvp = true, lang = 1}, 
		{ name = "冰霜之刃", region = 5, pvp = true, lang = 1}, 
		{ name = "达斯雷玛", region = 5, pvp = true, lang = 1}, 
		{ name = "地狱咆哮", region = 5, pvp = true, lang = 1}, 
		{ name = "地狱之石", region = 5, pvp = true, lang = 1}, 
		{ name = "风暴之怒", region = 5, pvp = true, lang = 1}, 
		{ name = "风行者", region = 5, pvp = true, lang = 1}, 
		{ name = "弗塞雷迦", region = 5, pvp = true, lang = 1}, 
		{ name = "戈古纳斯", region = 5, pvp = true, lang = 1}, 
		{ name = "毁灭之锤", region = 5, pvp = true, lang = 1}, 
		{ name = "火焰之树", region = 5, pvp = true, lang = 1}, 
		{ name = "卡德加", region = 5, pvp = true, lang = 1}, 
		{ name = "拉文凯斯", region = 5, pvp = true, lang = 1}, 
		{ name = "玛法里奥", region = 5, pvp = true, lang = 1}, 
		{ name = "麦维影歌", region = 5, pvp = true, lang = 1}, 
		{ name = "梅尔加尼", region = 5, pvp = true, lang = 1}, 
		{ name = "梦境之树", region = 5, pvp = false, lang = 1}, 
		{ name = "耐普图隆", region = 5, pvp = true, lang = 1}, 
		{ name = "海加尔", region = 5, pvp = true, lang = 1}, 
		{ name = "轻风之语", region = 5, pvp = false, lang = 1}, 
		{ name = "夏维安", region = 5, pvp = true, lang = 1}, 
		{ name = "塞纳里奥", region = 5, pvp = false, lang = 1}, 
		{ name = "闪电之刃", region = 5, pvp = true, lang = 1}, 
		{ name = "石爪峰", region = 5, pvp = true, lang = 1}, 
		{ name = "泰兰德", region = 5, pvp = false, lang = 1}, 
		{ name = "屠魔山谷", region = 5, pvp = true, lang = 1}, 
		{ name = "伊利丹", region = 5, pvp = true, lang = 1}, 
		{ name = "月光林地", region = 5, pvp = false, lang = 1}, 
		{ name = "月神殿", region = 5, pvp = false, lang = 1}, 
		{ name = "战歌", region = 5, pvp = true, lang = 1}, 
		{ name = "主宰之剑", region = 5, pvp = true, lang = 1}, 
		{ name = "埃德萨拉", region = 5, pvp = true, lang = 1}, 
		{ name = "血环", region = 5, pvp = true, lang = 1}, 
		{ name = "布莱克摩", region = 5, pvp = true, lang = 1}, 
		{ name = "杜隆坦", region = 5, pvp = true, lang = 1}, 
		{ name = "符文图腾", region = 5, pvp = true, lang = 1}, 
		{ name = "鬼雾峰", region = 5, pvp = true, lang = 1}, 
		{ name = "黑暗之矛", region = 5, pvp = true, lang = 1}, 
		{ name = "红龙女王", region = 5, pvp = true, lang = 1}, 
		{ name = "红云台地", region = 5, pvp = true, lang = 1}, 
		{ name = "黄金之路", region = 5, pvp = false, lang = 1}, 
		{ name = "火羽山", region = 5, pvp = true, lang = 1}, 
		{ name = "迦罗娜", region = 5, pvp = true, lang = 1}, 
		{ name = "凯恩血蹄", region = 5, pvp = true, lang = 1}, 
		{ name = "狂风峭壁", region = 5, pvp = true, lang = 1}, 
		{ name = "雷斧堡垒", region = 5, pvp = true, lang = 1}, 
		{ name = "雷霆号角", region = 5, pvp = true, lang = 1}, 
		{ name = "雷克萨", region = 5, pvp = true, lang = 1}, 
		{ name = "玛里苟斯", region = 5, pvp = true, lang = 1}, 
		{ name = "纳沙塔尔", region = 5, pvp = true, lang = 1}, 
		{ name = "诺兹多姆", region = 5, pvp = false, lang = 1}, 
		{ name = "普罗德摩", region = 5, pvp = true, lang = 1}, 
		{ name = "千针石林", region = 5, pvp = true, lang = 1}, 
		{ name = "燃烧之刃", region = 5, pvp = true, lang = 1}, 
		{ name = "萨尔", region = 5, pvp = true, lang = 1}, 
		{ name = "圣火神殿", region = 5, pvp = true, lang = 1}, 
		{ name = "甜水绿洲", region = 5, pvp = true, lang = 1}, 
		{ name = "沃金", region = 5, pvp = true, lang = 1}, 
		{ name = "熊猫酒仙", region = 5, pvp = true, lang = 1}, 
		{ name = "血牙魔王", region = 5, pvp = true, lang = 1}, 
		{ name = "勇士岛", region = 5, pvp = true, lang = 1}, 
		{ name = "羽月", region = 5, pvp = false, lang = 1}, 
		{ name = "蜘蛛王国", region = 5, pvp = true, lang = 1}, 
		{ name = "自由之风", region = 5, pvp = true, lang = 1}, 
		{ name = "阿尔萨斯", region = 5, pvp = true, lang = 1}, 
		{ name = "阿拉索", region = 5, pvp = true, lang = 1}, 
		{ name = "埃雷达尔", region = 5, pvp = true, lang = 1}, 
		{ name = "艾欧纳尔", region = 5, pvp = true, lang = 1}, 
		{ name = "安东尼达斯", region = 5, pvp = false, lang = 1}, 
		{ name = "暗影议会", region = 5, pvp = true, lang = 1}, 
		{ name = "奥特兰克", region = 5, pvp = true, lang = 1}, 
		{ name = "巴尔古恩", region = 5, pvp = true, lang = 1}, 
		{ name = "冰风岗", region = 5, pvp = true, lang = 1}, 
		{ name = "达隆米尔", region = 5, pvp = true, lang = 1}, 
		{ name = "耳语海岸", region = 5, pvp = false, lang = 1}, 
		{ name = "古尔丹", region = 5, pvp = true, lang = 1}, 
		{ name = "寒冰皇冠", region = 5, pvp = true, lang = 1}, 
		{ name = "基尔加丹", region = 5, pvp = true, lang = 1}, 
		{ name = "激流堡", region = 5, pvp = true, lang = 1}, 
		{ name = "巨龙之吼", region = 5, pvp = true, lang = 1}, 
		{ name = "暗影裂口", region = 5, pvp = true, lang = 1}, 
		{ name = "拉格纳洛斯", region = 5, pvp = true, lang = 1}, 
		{ name = "利刃之拳", region = 5, pvp = true, lang = 1}, 
		{ name = "玛诺洛斯", region = 5, pvp = true, lang = 1}, 
		{ name = "麦迪文", region = 5, pvp = false, lang = 1}, 
		{ name = "凯尔萨斯", region = 5, pvp = true, lang = 1}, 
		{ name = "耐奥祖", region = 5, pvp = true, lang = 1}, 
		{ name = "克尔苏加德", region = 5, pvp = true, lang = 1}, 
		{ name = "瑞文戴尔", region = 5, pvp = true, lang = 1}, 
		{ name = "霜狼", region = 5, pvp = true, lang = 1}, 
		{ name = "霜之哀伤", region = 5, pvp = false, lang = 1}, 
		{ name = "斯坦索姆", region = 5, pvp = true, lang = 1}, 
		{ name = "提瑞斯法", region = 5, pvp = true, lang = 1}, 
		{ name = "通灵学院", region = 5, pvp = true, lang = 1}, 
		{ name = "希尔瓦娜斯", region = 5, pvp = true, lang = 1}, 
		{ name = "血色十字军", region = 5, pvp = true, lang = 1}, 
		{ name = "遗忘海岸", region = 5, pvp = false, lang = 1}, 
		{ name = "银松森林", region = 5, pvp = false, lang = 1}, 
		{ name = "银月", region = 5, pvp = false, lang = 1}, 
		{ name = "鹰巢山", region = 5, pvp = true, lang = 1}, 
		{ name = "影牙要塞", region = 5, pvp = true, lang = 1}, 
		{ name = "狂热之刃", region = 5, pvp = true, lang = 1}, 
		{ name = "卡珊德拉", region = 5, pvp = true, lang = 1}, 
		{ name = "迅捷微风", region = 5, pvp = true, lang = 1}, 
		{ name = "守护之剑", region = 5, pvp = true, lang = 1}, 
		{ name = "斩魔者", region = 5, pvp = true, lang = 1}, 
		{ name = "布兰卡德", region = 5, pvp = true, lang = 1}, 
		{ name = "世界之树", region = 5, pvp = false, lang = 1}, 
		{ name = "恶魔之翼", region = 5, pvp = true, lang = 1}, 
		{ name = "万色星辰", region = 5, pvp = false, lang = 1}, 
		{ name = "激流之傲", region = 5, pvp = true, lang = 1}, 
		{ name = "加兹鲁维", region = 5, pvp = true, lang = 1}, 
		{ name = "苏塔恩", region = 5, pvp = true, lang = 1}, 
		{ name = "雏龙之翼", region = 5, pvp = true, lang = 1}, 
		{ name = "黑暗魅影", region = 5, pvp = true, lang = 1}, 
		{ name = "大地之怒", region = 5, pvp = true, lang = 1}, 
		{ name = "伊森利恩", region = 5, pvp = true, lang = 1}, 
		{ name = "神圣之歌", region = 5, pvp = false, lang = 1}, 
		{ name = "暮色森林", region = 5, pvp = true, lang = 1}, 
		{ name = "元素之力", region = 5, pvp = true, lang = 1}, 
		{ name = "日落沼泽", region = 5, pvp = true, lang = 1}, 
		{ name = "踏梦者", region = 5, pvp = true, lang = 1}, 
		{ name = "密林游侠", region = 5, pvp = true, lang = 1}, 
		{ name = "芬里斯", region = 5, pvp = true, lang = 1}, 
		{ name = "伊萨里奥斯", region = 5, pvp = true, lang = 1}, 
		{ name = "风暴之眼", region = 5, pvp = true, lang = 1}, 
		{ name = "提尔之手", region = 5, pvp = true, lang = 1}, 
		{ name = "永夜港", region = 5, pvp = false, lang = 1}, 
		{ name = "金色平原", region = 5, pvp = true, lang = 1}, 
		{ name = "朵丹尼尔", region = 5, pvp = true, lang = 1}, 
		{ name = "法拉希姆", region = 5, pvp = true, lang = 1}, 
		{ name = "安其拉", region = 5, pvp = true, lang = 1}, 
		{ name = "安纳塞隆", region = 5, pvp = true, lang = 1}, 
		{ name = "阿努巴拉克", region = 5, pvp = true, lang = 1}, 
		{ name = "阿拉希", region = 5, pvp = true, lang = 1}, 
		{ name = "瓦里玛萨斯", region = 5, pvp = false, lang = 1}, 
		{ name = "巴纳扎尔", region = 5, pvp = true, lang = 1}, 
		{ name = "黑手军团", region = 5, pvp = true, lang = 1}, 
		{ name = "血羽", region = 5, pvp = true, lang = 1}, 
		{ name = "燃烧军团", region = 5, pvp = true, lang = 1}, 
		{ name = "克洛玛古斯", region = 5, pvp = true, lang = 1}, 
		{ name = "破碎岭", region = 5, pvp = true, lang = 1}, 
		{ name = "克苏恩", region = 5, pvp = true, lang = 1}, 
		{ name = "阿纳克洛斯", region = 5, pvp = true, lang = 1}, 
		{ name = "雷霆之怒", region = 5, pvp = true, lang = 1}, 
		{ name = "桑德兰", region = 5, pvp = true, lang = 1}, 
		{ name = "黑翼之巢", region = 5, pvp = true, lang = 1}, 
		{ name = "德拉诺", region = 5, pvp = true, lang = 1}, 
		{ name = "龙骨平原", region = 5, pvp = true, lang = 1}, 
		{ name = "卡拉赞", region = 5, pvp = true, lang = 1}, 
		{ name = "熔火之心", region = 5, pvp = true, lang = 1}, 
		{ name = "格瑞姆巴托", region = 5, pvp = true, lang = 1}, 
		{ name = "古拉巴什", region = 5, pvp = true, lang = 1}, 
		{ name = "哈卡", region = 5, pvp = true, lang = 1}, 
		{ name = "海克泰尔", region = 5, pvp = true, lang = 1}, 
		{ name = "库尔提拉斯", region = 5, pvp = true, lang = 1}, 
		{ name = "洛丹伦", region = 5, pvp = true, lang = 1}, 
		{ name = "奈法利安", region = 5, pvp = true, lang = 1}, 
		{ name = "奎尔萨拉斯", region = 5, pvp = true, lang = 1}, 
		{ name = "拉贾克斯", region = 5, pvp = true, lang = 1}, 
		{ name = "拉文霍德", region = 5, pvp = true, lang = 1}, 
		{ name = "森金", region = 5, pvp = true, lang = 1}, 
		{ name = "范达尔鹿盔", region = 5, pvp = true, lang = 1}, 
		{ name = "泰拉尔", region = 5, pvp = true, lang = 1}, 
		{ name = "瓦拉斯塔兹", region = 5, pvp = true, lang = 1}, 
		{ name = "永恒之井", region = 5, pvp = true, lang = 1}, 
		{ name = "海达希亚", region = 5, pvp = false, lang = 1}, 
		{ name = "萨菲隆", region = 5, pvp = true, lang = 1}, 
		{ name = "纳克萨玛斯", region = 5, pvp = true, lang = 1}, 
		{ name = "无尽之海", region = 5, pvp = true, lang = 1}, 
		{ name = "莱索恩", region = 5, pvp = true, lang = 1}, 
		{ name = "阿卡玛", region = 5, pvp = true, lang = 1}, 
		{ name = "阿扎达斯", region = 5, pvp = true, lang = 1}, 
		{ name = "灰谷", region = 5, pvp = true, lang = 1}, 
		{ name = "艾维娜", region = 5, pvp = false, lang = 1}, 
		{ name = "巴瑟拉斯", region = 5, pvp = true, lang = 1}, 
		{ name = "血顶", region = 5, pvp = true, lang = 1}, 
		{ name = "恐怖图腾", region = 5, pvp = true, lang = 1}, 
		{ name = "古加尔", region = 5, pvp = true, lang = 1}, 
		{ name = "达文格尔", region = 5, pvp = true, lang = 1}, 
		{ name = "黑铁", region = 5, pvp = true, lang = 1}, 
		{ name = "恶魔之魂", region = 5, pvp = true, lang = 1}, 
		{ name = "迪瑟洛克", region = 5, pvp = true, lang = 1}, 
		{ name = "丹莫德", region = 5, pvp = true, lang = 1}, 
		{ name = "艾莫莉丝", region = 5, pvp = true, lang = 1}, 
		{ name = "埃克索图斯", region = 5, pvp = true, lang = 1}, 
		{ name = "菲拉斯", region = 5, pvp = true, lang = 1}, 
		{ name = "加基森", region = 5, pvp = true, lang = 1}, 
		{ name = "加里索斯", region = 5, pvp = true, lang = 1}, 
		{ name = "格雷迈恩", region = 5, pvp = true, lang = 1}, 
		{ name = "布莱恩", region = 5, pvp = false, lang = 1}, 
		{ name = "天谴之门", region = 5, pvp = true, lang = 1}, 
		{ name = "伊莫塔尔", region = 5, pvp = true, lang = 1}, 
		{ name = "大漩涡", region = 5, pvp = true, lang = 1}, 
		{ name = "诺森德", region = 5, pvp = true, lang = 1}, 
		{ name = "奥妮克希亚", region = 5, pvp = true, lang = 1}, 
		{ name = "奥斯里安", region = 5, pvp = true, lang = 1}, 
		{ name = "外域", region = 5, pvp = true, lang = 1}, 
		{ name = "天空之墙", region = 5, pvp = true, lang = 1}, 
		{ name = "风暴之鳞", region = 5, pvp = true, lang = 1}, 
		{ name = "荆棘谷", region = 5, pvp = true, lang = 1}, 
		{ name = "逐日者", region = 5, pvp = false, lang = 1}, 
		{ name = "塔纳利斯", region = 5, pvp = true, lang = 1}, 
		{ name = "瑟莱德丝", region = 5, pvp = true, lang = 1}, 
		{ name = "塞拉赞恩", region = 5, pvp = true, lang = 1}, 
		{ name = "托塞德林", region = 5, pvp = true, lang = 1}, 
		{ name = "黑暗虚空", region = 5, pvp = true, lang = 1}, 
		{ name = "安戈洛", region = 5, pvp = true, lang = 1}, 
		{ name = "祖尔金", region = 5, pvp = true, lang = 1}, 
		{ name = "冰川之拳", region = 5, pvp = true, lang = 1}, 
		{ name = "刺骨利刃", region = 5, pvp = true, lang = 1}, 
		{ name = "深渊之巢", region = 5, pvp = true, lang = 1}, 
		{ name = "埃基尔松", region = 5, pvp = true, lang = 1}, 
		{ name = "火烟之谷", region = 5, pvp = true, lang = 1}, 
		{ name = "伊兰尼库斯", region = 5, pvp = true, lang = 1}, 
		{ name = "火喉", region = 5, pvp = true, lang = 1}, 
		{ name = "迦玛兰", region = 5, pvp = true, lang = 1}, 
		{ name = "金度", region = 5, pvp = true, lang = 1}, 
		{ name = "巫妖之王", region = 5, pvp = true, lang = 1}, 
		{ name = "米奈希尔", region = 5, pvp = true, lang = 1}, 
		{ name = "幽暗沼泽", region = 5, pvp = true, lang = 1}, 
		{ name = "烈焰荆棘", region = 5, pvp = true, lang = 1}, 
		{ name = "夺灵者", region = 5, pvp = true, lang = 1}, 
		{ name = "石锤", region = 5, pvp = true, lang = 1}, 
		{ name = "塞拉摩", region = 5, pvp = true, lang = 1}, 
		{ name = "厄祖玛特", region = 5, pvp = true, lang = 1}, 
		{ name = "冬泉谷", region = 5, pvp = true, lang = 1}, 
		{ name = "伊森德雷", region = 5, pvp = true, lang = 1}, 
		{ name = "扎拉赞恩", region = 5, pvp = true, lang = 1}, 
		{ name = "亚雷戈斯", region = 5, pvp = false, lang = 1}, 
		{ name = "深渊之喉", region = 5, pvp = true, lang = 1}, 
		{ name = "凤凰之神", region = 5, pvp = true, lang = 1}, 
		{ name = "阿古斯", region = 5, pvp = true, lang = 1}, 
		{ name = "鲜血熔炉", region = 5, pvp = true, lang = 1}, 
		{ name = "黑暗之门", region = 5, pvp = true, lang = 1}, 
		{ name = "死亡熔炉", region = 5, pvp = true, lang = 1}, 
		{ name = "无底海渊", region = 5, pvp = true, lang = 1}, 
		{ name = "格鲁尔", region = 5, pvp = true, lang = 1}, 
		{ name = "哈兰", region = 5, pvp = true, lang = 1}, 
		{ name = "军团要塞", region = 5, pvp = true, lang = 1}, 
		{ name = "麦姆", region = 5, pvp = true, lang = 1}, 
		{ name = "艾露恩", region = 5, pvp = false, lang = 1}, 
		{ name = "穆戈尔", region = 5, pvp = true, lang = 1}, 
		{ name = "摩摩尔", region = 5, pvp = true, lang = 1}, 
		{ name = "试炼之环", region = 5, pvp = true, lang = 1}, 
		{ name = "希雷诺斯", region = 5, pvp = true, lang = 1}, 
		{ name = "塞泰克", region = 5, pvp = true, lang = 1}, 
		{ name = "暗影迷宫", region = 5, pvp = true, lang = 1}, 
		{ name = "托尔巴拉德", region = 5, pvp = true, lang = 1}, 
		{ name = "太阳之井", region = 5, pvp = true, lang = 1}, 
		{ name = "末日祷告祭坛", region = 5, pvp = true, lang = 1}, 
		{ name = "范克里夫", region = 5, pvp = true, lang = 1}, 
		{ name = "瓦丝琪", region = 5, pvp = true, lang = 1}, 
		{ name = "祖阿曼", region = 5, pvp = true, lang = 1}, 
		{ name = "祖达克", region = 5, pvp = true, lang = 1}, 
		{ name = "翡翠梦境", region = 5, pvp = false, lang = 1}, 
}