-- Libraries
local L = LibStub("AceLocale-3.0"):NewLocale("DoomShards", "koKR", false)
if not L then return end


-- Translations
L["\"Overcap Shards\" Bar Color"] = "\"초과 조각\" 바 색상"
L["\"Overcap Shards\" Color"] = "\"초과 조각\" 색상"
L["Add. HoG Shards"] = "굴손 조각 추가"
L["Additional Doom Indicators"] = "추가 파멸 지시기"
L["Affliction"] = "고통"
L["Always show borders"] = "항상 테두리 표시"
L["Anchor"] = "고정"
L["Anchor Frame"] = "고정 프레임"
L["Anchor Point"] = "고정 지점"
L["Animations"] = "애니메이션"
L["Arena"] = "투기장"
L["Background Color"] = "배경 색상"
L["Bar Color"] = "바 색상"
L["Battleground"] = "전장"
L["Border Color"] = "테두리 색상"
L["Borders"] = "테두리"
L["Cancelled Test Mode"] = "|cFF814eaaDoom Shards|r: 테스트 모드 취소됨!"
L["Change color of all Shards when reaching cap"] = "최대치에 도달하면 모든 조각의 색상 변경"
L["Color of additional indicators for overcapping with Doom ticks"] = "파멸 틱으로 초과될 추가 지시기의 색상"
L["Color of Depleted Shards"] = "고갈된 조각의 색상"
L["Color Shard 1"] = "조각 1 색상"
L["Color Shard 2"] = "조각 2 색상"
L["Color Shard 3"] = "조각 3 색상"
L["Color Shard 4"] = "조각 4 색상"
L["Color Shard 5"] = "조각 5 색상"
L["Color the text will change to if doom will tick before next possible Hand of Gul'dan cast."] = "다음 굴단의 손 시전이 가능하기 전에 파멸 틱이 발생하면 문자 색상을 변경합니다."
L["Color When Shard Capped"] = "조각이 가득 찼을 때 색상"
L["Colors"] = "색상"
L["Consolidate individual ticks to full expected shards"] = "개별 틱을 전체 예상 조각으로 통합시킵니다. 예를 들면, 고통의 경우 틱마다 영혼의 조각을 100%로 생성하지 않습니다."
L["Consolidate Ticks"] = "틱 통합"
L["Copy string for later import"] = "나중에 가져오기 할 문자열 복사"
L["Demonology"] = "악마"
L["Destruction"] = "파괴"
L["Dimensions"] = "크기"
L["Direction"] = "방향"
L["Display"] = "디스플레이"
L["Documentation"] = "문서"
L["Doom Shards locked!"] = "|cFF814eaaDoom Shards|r 잠금!"
L["Doom Shards reset!"] = "|cFF814eaaDoom Shards|r 초기화!"
L["Doom Shards unlocked!"] = "|cFF814eaaDoom Shards|r 잠금 해제!"
L["Doom Shards: Profile import completed"] = "|cFF814eaaDoom Shards|r: 프로필 가져오기 성공"
L["Doom Tick Indicator Bars"] = "파멸 틱 지시기 바"
L["dragFrameTooltip"] = [=[|cFFcc0060마우스 왼쪽 버튼|r으로 드래그합니다.
|cFFcc0060마우스 오른쪽 버튼|r으로 잠급니다.
|cFFcc0060마우스 휠|r과 |cFFcc0060Shift + 마우스 휠|r로 미세하게 조절합니다.]=]
L["Dungeon"] = "던전"
L["Enable"] = "사용"
L["Enable bars for incoming Doom ticks"] = "들어오는 파멸 틱 바 사용"
L["Export"] = "내보내기"
L["Export/Import"] = "내보내기/가져오기"
L["Fade Duration"] = "사라짐 지속시간"
L["Failed to import profile: "] = "프로필 가져오기 실패:"
L["File to play."] = "재생할 파일입니다."
L["Fill indicator from right to left"] = "지시기를 오른쪽에서 왼쪽으로 채우기"
L["Flash on Shard Gain"] = "조각 획득 시 반짝이기"
L["Font"] = "글꼴"
L["Font Color"] = "글꼴 색상"
L["Font Color for Hand of Gul'dan Prediction"] = "굴단의 손 예상 글꼴 색상"
L["Font Flags"] = "글꼴 효과"
L["Font Size"] = "글꼴 크기"
L["Functionality"] = "기능"
L["General"] = "일반"
L["Growth direction"] = "성장 방향"
L["Height"] = "높이"
L["Horizontal"] = "수평"
L["Import"] = "가져오기"
L["Include Doom tick indicator in Hand of Gul'dan casts. (Demonology only)"] = "굴단의 손 시전에 파멸 틱 지시기를 포함시킵니다. (악마 특성만)"
L["Indicate Shard Building"] = "조각 생성 표시"
L["Indicate Shard Spending"] = "조각 소비 표시"
L["Instance Type"] = "인스턴스 유형"
L["Interval"] = "주기"
L["MONOCHROMEOUTLINE"] = "모노크롬 외곽선"
L["No Instance"] = "인스턴스 없음"
L["None"] = "없음"
L["not a table"] = "table이 아닙니다"
L["Offset"] = "좌표"
L["Order in which Shards get filled in"] = "조각이 채워질 순서"
L["Orientation"] = "방향"
L["OUTLINE"] = "외곽선"
L["Overcapping"] = "초과"
L["Paste import string here"] = "여기에 가져오기 문자열을 붙여넣기"
L["Play Warning Sound when about to cap."] = "최대치일 때 경고 소리를 재생합니다."
L["Position"] = "위치"
L["Positioning"] = "배치"
L["Raid"] = "공격대"
L["Really import profile?"] = "프로필을 정말 가져올까요?"
L["Regular"] = "보통"
L["Regulate display visibility with macro conditionals"] = [=[
매크로 상태 조건으로 디스플레이 표시를 조절합니다
show - 디스플레이 표시
hide - 디스플레이 숨기기
fade - 디스플레이 페이드 아웃]=]
L["Reset Position"] = "위치 초기화"
L["Reset to Defaults"] = "기본값으로 초기화"
L["Reverse Direction"] = "반대 방향"
L["Reversed"] = "반대로"
L["Scale"] = "크기"
L["Scenario"] = "시나리오"
L["Shadow"] = "그림자"
L["Shard Cap Color Change"] = "최대치 색상 변경"
L["Shard Colors"] = "조각 색상"
L["Shard Gain Color"] = "조각 획득 색상"
L["Shard Spend Color"] = "조각 소비 색상"
L["Show Depleted Shards"] = "고갈된 조각 표시"
L["Show prediction for gaining shards through casts"] = "시전을 통해 획득할 조각의 예상 시점을 표시합니다"
L["Show prediction for spending shards through casts"] = "시전을 통해 소비할 조각의 예상 시점을 표시합니다"
L["Shows the frame and toggles it for repositioning."] = "위치 변경을 위해 프레임을 표시합니다."
L["Soul Shard Bars"] = "영혼의 조각 바"
L["Sound"] = "소리"
L["Spacing"] = "간격"
L["Specializations"] = "전문화"
L["Starting Test Mode"] = "|cFF814eaaDoom Shards|r: 테스트 모드 시작"
L["Test Mode"] = "테스트 모드"
L["Text"] = "문자"
L["Texture"] = "무늬"
L["Textures"] = "무늬"
L["THICKOUTLINE"] = "두꺼운 외곽선"
L["Threshold when text begins showing first decimal place"] = "소수로 표시하기 시작할 남은 시간(초)"
L["Time between warning sounds"] = "경고 소리 간격"
L["Time Threshold"] = "소수 표시 제한"
L["Toggle Lock"] = "잠금 전환"
L["Track Agony"] = "고통 추적"
L["Track Doom"] = "파멸 추적"
L["Track Shadowburn"] = "어둠의 연소 추적"
L["Track Unstable Affliction"] = "불안정한 고통 추적"
L["Use Texture for Shards"] = "조각에 무늬 사용"
L["Version"] = "버전"
L["Vertical"] = "수직"
L["Visibility"] = "표시"
L["Visibility Conditionals"] = "표시 상태"
L["WeakAuras Example Strings"] = "WeakAuras 예제 구문"
L["WeakAuras Import String 1"] = "WeakAuras 가져오기 구문 1"
L["WeakAuras Import String 2"] = "WeakAuras 가져오기 구문 2"
L["WeakAuras Interface"] = "WeakAuras 인터페이스"
L["WeakAuras String to use when \"WeakAuras\" Display is selected. Copy & paste into WeakAuras to import."] = "\"WeakAuras\" 디스플레이를 선택했을 때 사용 할 WeakAuras 구문 입니다. WeakAuras의 가져오기에 복사 & 붙여넣기 하세요."
L["WeakAurasDocumentation"] = [=[WeakAuras 이벤트
  DOOM_SHARDS_DISPLAY_UPDATE
    참고: 디스플레이가 활성화 되었을 때만 발생합니다. 이 이벤트를 사용하려면 대신 디스플레이의 일부를 비활성하세요.

DoomShards methods
  DoomShards:GetPrediction(index)
    변수들
      index (숫자) : 예측 틱의 순서
    return nextTick, resourceGenerationChance
      nextTick (숫자) : 다음 틱의 발생 시간
      resourceGenerationChance (숫자) : 다음 틱의 영혼의 조각 생성 확률]=]
L["Width"] = "너비"
L["Will change to UIParent when manually dragging frame."] = "수동으로 프레임을 드래그하면 UIParent로 변경됩니다."
L["X Offset"] = "X 좌표"
L["X Position"] = "X 위치"
L["Y Offset"] = "Y 좌표"
L["Y Position"] = "Y 위치"

