local _, ns = ...

ns.mt = {}
ns.mt.__index = function( table, key )
	return key
end
ns.L = {}
setmetatable( ns.L, ns.mt )

-- Translations I often use in all my AddOns
if ns.locale == "deDE" then
	ns.L["Character"] = "Charakter"
	ns.L["Account"] = "Accountweiter"
	ns.L["Completed"] = "Abgeschlossen"
	ns.L["Not Completed"] = "Nicht Abgeschlossen"
	ns.L["Try again"] = "Versuchen Sie es erneut. Server keine Antwort"
	ns.L["ZidormiWrongPhase"] = "Auf Ihrer Karte wird im Verlauf der Zone der falsche Zeitpunkt angezeigt. Wenn Sie sich derzeit "
		.."in der Zone befinden, müssen Sie zuerst mit Zidormi sprechen"

	ns.L["Options"] = "Optionen"
	ns.L["Map Pin Size"] = "Pin-Größe"
	ns.L["The Map Pin Size"] = "Die Größe der Karten-Pins"
	ns.L["Map Pin Alpha"] = "Kartenpin Alpha"
	ns.L["The alpha transparency of the map pins"] = "Die Alpha-Transparenz der Karten-Pins"
	ns.L["Show Coordinates"] = "Koordinaten anzeigen"
	ns.L["Show Coordinates Description"] = "Zeigen sie die koordinaten in QuickInfos auf "
		.."der Weltkarte und auf der Minikarte an"
	ns.L["Map Pin Selections"] = "Karten-Pin-Auswahl"
	ns.L["Left"] = "Links"
	ns.L["Right"] = "Rechts"
	ns.L["Notes"] = "Notizen"
	ns.L["MinimapMenu"] = "Eine Verknüpfung zum Öffnen dieses Bereichs erfolgt über das Minimap-Add-On-Menü, das sich direkt "
		.."unter dem Kalendersymbol befindet. Klicken Sie einfach mit der Maus\n\n"
	ns.L["ChatCommands"] = "Chat-Befehlsverknüpfungen werden ebenfalls unterstützt. "
	ns.L["ShowPanel"] = " - Dieses Panel anzeigen\n"
	ns.L["TryMinimapMenu"] = "Probieren Sie das Minimap-Add-On-Menü (unter dem Kalender) aus"
	
	ns.L["Blue"] = "Blau"
	ns.L["Brown"] = "Braun"
	ns.L["Dark Blue"] = "Dunkelblau"
	ns.L["Gold"] = "Gold"
	ns.L["Green"] = "Grün"
	ns.L["Grey"] = "Grau"
	ns.L["Light Blue"] = "Hellblau"
	ns.L["Light Green"] = "Hellgrün"
	ns.L["Pink"] = "Rosa"
	ns.L["Purple"] = "Lila"
	ns.L["Red"] = "Rot"
	ns.L["Teal"] = "Blaugrün"
	ns.L["Turquoise"] = "Türkis"	
	ns.L["White"] = "Weiß"
	ns.L["Yellow"] = "Gelb"

	ns.L["Ring"] = "Ring"
	ns.L["Cross"] = "Kreuz"
	ns.L["Diamond"] = "Diamant"
	ns.L["Frost"] = "Frost"
	ns.L["Cogwheel"] = "Zahnrad"
	ns.L["Mana Orb"] = "Manakugel"
	ns.L["Phasing"] = "Synchronisieren"
	ns.L["Raptor egg"] = "Raptor-Ei"
	ns.L["Stars"] = "Sternen"
	ns.L["Screw"] = "Schraube"
	
elseif ns.locale == "esES" or ns.locale == "esMX" then
	ns.L["Character"] = "Personaje"
	ns.L["Account"] = "la Cuenta"
	ns.L["Completed"] = "Completado"
	ns.L["Not Completed"] = ( ns.locale == "esES" ) and "Sin Completar" or "Incompleto"
	ns.L["Options"] = "Opciones"
	ns.L["Try again"] = "Intentar otra vez. Servidor sin respuesta"
	ns.L["ZidormiWrongPhase"] = "Tu mapa muestra el momento equivocado en el historial de la zona. Si te encuentras actualmente "
		.."en la zona, primero debes hablar con Zidormi."

	ns.L["Map Pin Size"] = "Tamaño de alfiler"
	ns.L["The Map Pin Size"] = "Tamaño de los pines del mapa"
	ns.L["Map Pin Alpha"] = "Alfa de los pines del mapa"
	ns.L["The alpha transparency of the map pins"] = "La transparencia alfa de los pines del mapa"
	ns.L["Show Coordinates"] = "Mostrar coordenadas"
	ns.L["Show Coordinates Description"] = "Mostrar coordenadas en información sobre "
		.."herramientas en el mapa del mundo y en el minimapa"
	ns.L["Map Pin Selections"] = "Selecciones de pines de mapa"
	ns.L["Left"] = "Izquierda"
	ns.L["Right"] = "Derecha"
	ns.L["Notes"] = "Notas"
	ns.L["MinimapMenu"] = "Un atajo para abrir este panel es a través del menú adicional Minimap, que se encuentra inmediatamente "
		.."debajo del ícono Calendario. Simplemente haz clic con el mouse\n\n"
	ns.L["ChatCommands"] = "También se admiten atajos de comandos de chat. "
	ns.L["ShowPanel"] = " - Mostrar este panel\n"
	ns.L["TryMinimapMenu"] = "Pruebe el menú complementario Minimap (debajo del Calendario)"

	ns.L["Blue"] = "Azul"
	ns.L["Brown"] = "Marrón"
	ns.L["Dark Blue"] = "Azul oscuro"
	ns.L["Gold"] = "Oro"
	ns.L["Green"] = "Verde"
	ns.L["Grey"] = "Gris"
	ns.L["Light Blue"] = "Azul claro"
	ns.L["Light Green"] = "Verde claro"
	ns.L["Pink"] = "Rosa"
	ns.L["Purple"] = "Púrpura"
	ns.L["Red"] = "Rojo"
	ns.L["Teal"] = "Verde azulado"
	ns.L["Turquoise"] = "Turquesa"	
	ns.L["White"] = "Blanco"
	ns.L["Yellow"] = "Amarillo"
	
	ns.L["Ring"] = "Anillo"
	ns.L["Cross"] = "Cruz"
	ns.L["Diamond"] = "Diamante"
	ns.L["Frost"] = "Escarcha"
	ns.L["Cogwheel"] = "Rueda dentada"
	ns.L["Mana Orb"] = "Orbe de maná"
	ns.L["Phasing"] = "Sincronización"	
	ns.L["Raptor egg"] = "Huevo de raptor"	
	ns.L["Stars"] = "Estrellas"
	ns.L["Screw"] = "Tornillo"
	
elseif ns.locale == "frFR" then
	ns.L["Character"] = "Personnage"
	ns.L["Account"] = "le Compte"
	ns.L["Completed"] = "Achevé"
	ns.L["Not Completed"] = "Non achevé"
	ns.L["Try again"] = "Essayer à nouveau. Serveur aucune réponse"
	ns.L["ZidormiWrongPhase"] = "Votre carte affiche le mauvais moment dans l'historique de la zone. Si vous êtes actuellement "
		.."dans la zone, vous devez d'abord parler à Zidormi."

	ns.L["Options"] = "Options"
	ns.L["Map Pin Size"] = "Taille des épingles"
	ns.L["The Map Pin Size"] = "La taille des épingles de carte"
	ns.L["Map Pin Alpha"] = "Alpha des épingles de carte"
	ns.L["The alpha transparency of the map pins"] = "La transparence alpha des épingles de la carte"
	ns.L["Show Coordinates"] = "Afficher les coordonnées"
	ns.L["Show Coordinates Description"] = "Afficher les coordonnées\124r dans les info-bulles sur "
		.."la carte du monde et la mini-carte"
	ns.L["Map Pin Selections"] = "Sélections de broches de carte"
	ns.L["Left"] = "Gauche"
	ns.L["Right"] = "Droite"
	ns.L["Notes"] = "Remarques"
	ns.L["MinimapMenu"] = "Un raccourci pour ouvrir ce panneau se fait via le menu Minimap AddOn, qui se trouve immédiatement sous "
		.."l'icône du calendrier. Cliquez simplement avec votre souris\n\n"
	ns.L["ChatCommands"] = "Les raccourcis des commandes de chat sont également pris en charge. "
	ns.L["ShowPanel"] = " - Afficher ce panneau\n"
	ns.L["TryMinimapMenu"] = "Essayez le menu complémentaire Minimap (sous le calendrier)"

	ns.L["Blue"] = "Bleue"
	ns.L["Brown"] = "Marron"
	ns.L["Dark Blue"] = "Bleu foncé"
	ns.L["Gold"] = "Or"
	ns.L["Green"] = "Vert"
	ns.L["Grey"] = "Gris"
	ns.L["Light Blue"] = "Bleu clair"
	ns.L["Light Green"] = "Vert clair"
	ns.L["Pink"] = "Rose"
	ns.L["Purple"] = "Violet"
	ns.L["Red"] = "Rouge"
	ns.L["Teal"] = "Bleu sarcelle"
	ns.L["Turquoise"] = "Turquoise"	
	ns.L["White"] = "Blanc"
	ns.L["Yellow"] = "Jaune"

	ns.L["Ring"] = "Bague"
	ns.L["Cross"] = "Traverser"
	ns.L["Diamond"] = "Diamant"
	ns.L["Frost"] = "Givre"
	ns.L["Cogwheel"] = "Roue dentée"
	ns.L["Mana Orb"] = "Orbe de mana"
	ns.L["Phasing"] = "Synchronisation"
	ns.L["Raptor egg"] = "Œuf de Rapace"
	ns.L["Stars"] = "Étoiles"
	ns.L["Screw"] = "Vis"

elseif ns.locale == "itIT" then
	ns.L["Character"] = "Personaggio"
	ns.L["Account"] = "Account"
	ns.L["Completed"] = "Completo"
	ns.L["Not Completed"] = "Non Compiuto"
	ns.L["Try again"] = "Riprova. Il server nessuna risposta"
	ns.L["ZidormiWrongPhase"] = "La tua mappa sta guardando l'ora sbagliata nella cronologia della zona. Se ti trovi attualmente "
		.."nella zona, devi prima parlare con Zidormi"

	ns.L["Options"] = "Opzioni"
	ns.L["Map Pin Size"] = "Dimensione del pin"
	ns.L["The Map Pin Size"] = "La dimensione dei Pin della mappa"
	ns.L["Map Pin Alpha"] = "Mappa pin alfa"
	ns.L["The alpha transparency of the map pins"] = "La trasparenza alfa dei pin della mappa"
	ns.L["Show Coordinates"] = "Mostra coordinate"
	ns.L["Show Coordinates Description"] = "Visualizza le coordinate\124r nelle descrizioni "
		.."comandi sulla mappa del mondo e sulla minimappa"
	ns.L["Map Pin Selections"] = "Selezioni pin mappa"
	ns.L["Left"] = "Sinistra"
	ns.L["Right"] = "Destra"
	ns.L["Notes"] = "Note"
	ns.L["MinimapMenu"] = "Una scorciatoia per aprire questo pannello è tramite il menu Minimappa AddOn, che si trova "
		.."immediatamente sotto l'icona del Calendario. Basta fare clic con il mouse\n\n"
	ns.L["ChatCommands"] = "Sono supportate anche le scorciatoie dei comandi di chat. "
	ns.L["ShowPanel"] = " - Mostra questo pannello\n"
	ns.L["TryMinimapMenu"] = "Prova il menu aggiuntivo della minimappa (sotto il calendario)"

	ns.L["Blue"] = "Blu"
	ns.L["Brown"] = "Marrone"
	ns.L["Dark Blue"] = "Blu scuro"
	ns.L["Gold"] = "Oro"
	ns.L["Red"] = "Rosso"
	ns.L["Green"] = "Verde"
	ns.L["Grey"] = "Grigio"
	ns.L["Light Blue"] = "Azzurro"
	ns.L["Light Green"] = "Verde chiaro"
	ns.L["Pink"] = "Rosa"
	ns.L["Purple"] = "Viola"
	ns.L["Teal"] = "Verde acqua"
	ns.L["Turquoise"] = "Turchese"	
	ns.L["White"] = "Bianca"
	ns.L["Yellow"] = "Giallo"

	ns.L["Ring"] = "Squillo"
	ns.L["Cross"] = "Attraverso"
	ns.L["Diamond"] = "Diamante"
	ns.L["Frost"] = "Gelo"
	ns.L["Cogwheel"] = "Ruota dentata"
	ns.L["Mana Orb"] = "Globo di Mana"
	ns.L["Phasing"] = "Sincronizzazione"
	ns.L["Raptor egg"] = "Raptor Uovo"
	ns.L["Stars"] = "Stelle"
	ns.L["Screw"] = "Vite"

elseif ns.locale == "koKR" then
	ns.L["Character"] = "캐릭터"
	ns.L["Account"] = "계정"
	ns.L["Completed"] = "완료"
	ns.L["Not Completed"] = "미완료"
	ns.L["Try again"] = "다시 시도해 보세요. 서버가 응답하지 않습니다"
	ns.L["ZidormiWrongPhase"] = "지도가 해당 구역 기록에서 잘못된 시간을 보고 있습니다. 현재 해당 구역에 있다면 먼저 지도르미와 대화해야 합니다."

	ns.L["Options"] = "설정"
	ns.L["Map Pin Size"] = "지도 핀의 크기"
	ns.L["The Map Pin Size"] = "지도 핀의 크기"
	ns.L["Map Pin Alpha"] = "지도 핀의 알파"
	ns.L["The alpha transparency of the map pins"] = "지도 핀의 알파 투명도"
	ns.L["Show Coordinates"] = "좌표 표시"
	ns.L["Show Coordinates Description"] = "세계지도 및 미니지도의 도구 설명에 좌표를 표시합니다."
	ns.L["Map Pin Selections"] = "지도 핀 선택"
	ns.L["Left"] = "왼쪽"
	ns.L["Right"] = "오른쪽"
	ns.L["Notes"] = "메모"
	ns.L["MinimapMenu"] = "이 패널을 여는 바로가기는 달력 아이콘 바로 아래에 있는 미니맵 애드온 메뉴를 통해 가능합니다. 마우스를 클릭하세요\n\n"
	ns.L["ChatCommands"] = "채팅 명령 단축키도 지원됩니다. "
	ns.L["ShowPanel"] = " - 이 패널 표시\n"
	ns.L["TryMinimapMenu"] = "미니맵 추가 메뉴를 사용해 보세요(캘린더 아래)"

	ns.L["Blue"] = "푸른"
	ns.L["Brown"] = "갈색"
	ns.L["Dark Blue"] = "진한 파란색"
	ns.L["Gold"] = "금"
	ns.L["Green"] = "녹색"
	ns.L["Grey"] = "회색"
	ns.L["Light Blue"] = "하늘색"
	ns.L["Light Green"] = "라이트 그린"
	ns.L["Pink"] = "분홍색"
	ns.L["Purple"] = "보라색"
	ns.L["Red"] = "빨간"
	ns.L["Teal"] = "푸른 청록색"
	ns.L["Turquoise"] = "청록색"	
	ns.L["White"] = "화이트"
	ns.L["Yellow"] = "노랑"

	ns.L["Ring"] = "반지"
	ns.L["Cross"] = "십자가"
	ns.L["Diamond"] = "다이아몬드"
	ns.L["Frost"] = "냉기"
	ns.L["Cogwheel"] = "톱니 바퀴"
	ns.L["Mana Orb"] = "마나 보주"
	ns.L["Phasing"] = "동기화 중"
	ns.L["Raptor egg"] = "랩터의 알"
	ns.L["Stars"] = "별"
	ns.L["Screw"] = "나사"

elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	ns.L["Character"] = "Personagem"
	ns.L["Account"] = "à Conta"
	ns.L["Completed"] = "Concluído"
	ns.L["Not Completed"] = "Não Concluído"
	ns.L["Try again"] = "Tente novamente. Servidor sem resposta"
	ns.L["ZidormiWrongPhase"] = "Seu mapa está na hora errada no histórico da zona. Se você estiver na zona, primeiro você deve "
		.."falar com Zidormi"

	ns.L["Options"] = "Opções"
	ns.L["Map Pin Size"] = "Tamanho do pino"
	ns.L["The Map Pin Size"] = "O tamanho dos pinos do mapa"
	ns.L["Map Pin Alpha"] = "Alfa dos pinos do mapa"
	ns.L["The alpha transparency of the map pins"] = "A transparência alfa dos pinos do mapa"
	ns.L["Show Coordinates"] = "Mostrar coordenadas"
	ns.L["Show Coordinates Description"] = "Exibir coordenadas\124r em dicas de ferramentas "
		.."no mapa mundial e no minimapa"
	ns.L["Map Pin Selections"] = "Seleções de pinos de mapa"
	ns.L["Left"] = "Esquerda"
	ns.L["Right"] = "Direita"
	ns.L["Notes"] = "Notas"
	ns.L["MinimapMenu"] = "Um atalho para abrir este painel é através do menu Minimap AddOn, que fica imediatamente abaixo do "
		.."ícone do Calendário. Basta clicar com o mouse\n\n"
	ns.L["ChatCommands"] = "Atalhos de comando de bate-papo também são compatíveis. "
	ns.L["ShowPanel"] = " - Mostrar este painel\n"
	ns.L["TryMinimapMenu"] = "Experimente o menu AddOn do Minimapa (abaixo do Calendário)"

	ns.L["Blue"] = "Azul"
	ns.L["Brown"] = "Marrom"
	ns.L["Dark Blue"] = "Azul-escuro"
	ns.L["Gold"] = "Ouro"
	ns.L["Green"] = "Verde"
	ns.L["Grey"] = "Cinzento"
	ns.L["Light Blue"] = "Azul-claro"
	ns.L["Light Green"] = "Verde Claro"
	ns.L["Pink"] = "Rosa"
	ns.L["Purple"] = "Roxa"
	ns.L["Red"] = "Vermelho"
	ns.L["Teal"] = "Azul-petróleo"
	ns.L["Turquoise"] = "Turquesa"	
	ns.L["White"] = "Branco"
	ns.L["Yellow"] = "Amarelo"

	ns.L["Ring"] = "Anel"
	ns.L["Cross"] = "Cruz"
	ns.L["Diamond"] = "Diamante"
	ns.L["Frost"] = "Gélido"
	ns.L["Cogwheel"] = "Roda dentada"
	ns.L["Mana Orb"] = "Orbe de Mana"
	ns.L["Phasing"] = "Sincronização"
	ns.L["Raptor egg"] = "Ovo de raptor"
	ns.L["Stars"] = "Estrelas"
	ns.L["Screw"] = "Parafuso"

elseif ns.locale == "ruRU" then
	ns.L["Character"] = "Персонажа"
	ns.L["Account"] = "Счет"
	ns.L["Completed"] = "Выполнено"
	ns.L["Not Completed"] = "Не Выполнено"
	ns.L["Try again"] = "Попробуйте еще раз. Сервер нет ответа"
	ns.L["ZidormiWrongPhase"] = "Ваша карта смотрит не на то время в истории зоны. Если вы сейчас находитесь в зоне, сначала вам "
		.."необходимо поговорить с Зидорми."

	ns.L["Options"] = "Параметры"
	ns.L["Map Pin Size"] = "Размер булавки"
	ns.L["The Map Pin Size"] = "Размер булавок на карте"
	ns.L["Map Pin Alpha"] = "Альфа булавок карты"
	ns.L["The alpha transparency of the map pins"] = "Альфа-прозрачность булавок карты"
	ns.L["Show Coordinates"] = "Показать Координаты"
	ns.L["Show Coordinates Description"] = "Отображает координаты\124r во всплывающих "
		.."подсказках на карте мира и мини-карте"
	ns.L["Map Pin Selections"] = "Выбор булавки карты"
	ns.L["Left"] = "Налево"
	ns.L["Right"] = "Направо"
	ns.L["Notes"] = "Примечания"
	ns.L["MinimapMenu"] = "Ярлык для открытия этой панели — через меню надстройки мини-карты, которое находится сразу под значком "
		.."календаря. Просто щелкните мышью\n\n"
	ns.L["ChatCommands"] = "Также поддерживаются сочетания клавиш чата. "
	ns.L["ShowPanel"] = " - Показать эту панель\n"
	ns.L["TryMinimapMenu"] = "Попробуйте меню дополнений на мини-карте (под календарем)"

	ns.L["Blue"] = "Синий"
	ns.L["Brown"] = "Коричневый"
	ns.L["Dark Blue"] = "Темно-синий"
	ns.L["Gold"] = "Золото"
	ns.L["Green"] = "Зеленый"
	ns.L["Grey"] = "Серый"
	ns.L["Light Blue"] = "Светло-голубой"
	ns.L["Light Green"] = "Светло-зеленый"
	ns.L["Pink"] = "Розовый"
	ns.L["Purple"] = "Пурпурный"
	ns.L["Red"] = "Красный"
	ns.L["Teal"] = "Голубой бирюзовый"
	ns.L["Turquoise"] = "Бирюзовый"	
	ns.L["White"] = "белый"
	ns.L["Yellow"] = "Желтый"

	ns.L["Ring"] = "Звенеть"
	ns.L["Cross"] = "Крест"
	ns.L["Diamond"] = "Ромб"
	ns.L["Frost"] = "Лед"
	ns.L["Cogwheel"] = "Зубчатое колесо"
	ns.L["Mana Orb"] = "Cфера маны"
	ns.L["Phasing"] = "Синхронизация"
	ns.L["Raptor egg"] = "Яйцо ящера"
	ns.L["Stars"] = "Звезды"
	ns.L["Screw"] = "Винт"

elseif ns.locale == "zhCN" then
	ns.L["Character"] = "角色"
	ns.L["Account"] = "账号"
	ns.L["Completed"] = "已完成"
	ns.L["Not Completed"] = "未完成"
	ns.L["Try later"] = "目前不可能。稍后再试"
	ns.L["Try again"] = "再试一次。服务器无响应"
	ns.L["ZidormiWrongPhase"] = "你的地图显示区域的时间线不对。如果你现在 在区域内，那么你必须去找希多尔米对话。"								

	ns.L["Options"] = "选项"
	ns.L["Map Pin Size"] = "地图图标大小"
	ns.L["The Map Pin Size"] = "地图图标大小"
	ns.L["Map Pin Alpha"] = "地图图标透明度"
	ns.L["The alpha transparency of the map pins"] = "地图图标透明度"
	ns.L["Show Coordinates"] = "显示坐标"
	ns.L["Show Coordinates Description"] = "在世界地图和小地图上的鼠标提示中显示坐标"
	ns.L["Map Pin Selections"] = "地图图标选择"
	ns.L["Left"] = "左"
	ns.L["Right"] = "右"
	ns.L["Notes"] = "简介"
	ns.L["MinimapMenu"] = "打开该界面的快捷方式可以通过原生暴雪小地图插件"
		    .."菜单，它就在原生暴雪日历图标的下方。只需点击鼠标\n\n"
	ns.L["ChatCommands"] = "还支持输入命令打开方式，输入。 "
	ns.L["ShowPanel"] = "- 显示设置界面\n"
	ns.L["TryMinimapMenu"] = "也可以在暴雪原生插件收纳菜单打开（小地图日历图标下方）"

	ns.L["Blue"] = "蓝"
	ns.L["Brown"] = "棕色"
	ns.L["Dark Blue"] = "深蓝色"
	ns.L["Gold"] = "金子"
	ns.L["Green"] = "绿色"
	ns.L["Grey"] = "灰色"
	ns.L["Light Blue"] = "浅蓝色"
	ns.L["Light Green"] = "浅绿色"
	ns.L["Pink"] = "粉色"
	ns.L["Purple"] = "紫色"
	ns.L["Red"] = "红"
	ns.L["Teal"] = "青绿色"
	ns.L["Turquoise"] = "绿松石色"	
	ns.L["White"] = "白色"
	ns.L["Yellow"] = "黄色"

	ns.L["Ring"] = "戒指"
	ns.L["Cross"] = "叉"
	ns.L["Diamond"] = "钻石"
	ns.L["Frost"] = "冰霜"
	ns.L["Cogwheel"] = "齿轮"
	ns.L["Mana Orb"] = "法力球"
	ns.L["Phasing"] = "同步"
	ns.L["Raptor egg"] = "迅猛龙蛋"
	ns.L["Stars"] = "星星"
	ns.L["Screw"] = "拧"

elseif ns.locale == "zhTW" then
	ns.L["Character"] = "角色"
	ns.L["Account"] = "賬號"
	ns.L["Completed"] = "完成"
	ns.L["Not Completed"] = "未完成"
	ns.L["Try again"] = "再試一次。 伺服器無回應"
	ns.L["ZidormiWrongPhase"] = "你的地圖顯示區域的時間線不對。如果你現在 在區域內，那麼你必須去找希多爾米對話。"

	ns.L["Options"] = "選項"
	ns.L["Map Pin Size"] = "地圖圖示大小"
	ns.L["The Map Pin Size"] = "地圖圖示大小"
	ns.L["Map Pin Alpha"] = "地圖圖標透明度"
	ns.L["The alpha transparency of the map pins"] = "地圖圖標透明度"
	ns.L["Show Coordinates"] = "顯示座標"
	ns.L["Show Coordinates Description"] = "在世界地圖和小地圖上的滑鼠提示中顯示座標"
	ns.L["Map Pin Selections"] = "地圖圖示選擇"
	ns.L["Left"] = "左"
	ns.L["Right"] = "右"
	ns.L["Notes"] = "簡介"
	ns.L["MinimapMenu"] = "打開該介面的快捷方式可以通過原生暴雪小地圖外掛程式"
		    .." 功能表，它就在原生暴雪日曆圖示的下方。 只需點擊滑鼠\n\n"
	ns.L["ChatCommands"] = "還支援輸入命令打開方式，輸入。 "
	ns.L["ShowPanel"] = " - 顯示設置介面\n"
	ns.L["TryMinimapMenu"] = "也可以在暴雪原生外掛程式收納功能表打開（小地圖日曆圖示下方）"

	ns.L["Blue"] = "藍"
	ns.L["Brown"] = "棕色的"
	ns.L["Dark Blue"] = "深藍色"
	ns.L["Gold"] = "金子"
	ns.L["Green"] = "綠色"
	ns.L["Grey"] = "灰色"
	ns.L["Light Blue"] = "淺藍色"
	ns.L["Light Green"] = "淺綠色"
	ns.L["Pink"] = "粉紅色的"
	ns.L["Purple"] = "紫色"
	ns.L["Red"] = "紅"
	ns.L["Teal"] = "青色"
	ns.L["Turquoise"] = "綠松石"	
	ns.L["White"] = "白色"
	ns.L["Yellow"] = "黃色"

	ns.L["Ring"] = "戒指"
	ns.L["Cross"] = "叉"
	ns.L["Diamond"] = "钻石"
	ns.L["Frost"] = "霜"
	ns.L["Cogwheel"] = "齒輪"
	ns.L["Mana Orb"] = "法力球"
	ns.L["Phasing"] = "同步"
	ns.L["Raptor egg"] = "迅猛龍蛋"
	ns.L["Stars"] = "星星"
	ns.L["Screw"] = "擰"

else
	ns.L["Try again"] = "Try again. Server no response"
	ns.L["ZidormiWrongPhase"] = "Your map is looking at the wrong time in the zone's history. If you are presently "
		.."in the zone then you must first speak to Zidormi"
	ns.L["ChatCommands"] = "Chat command shortcuts are also supported. "
	ns.L["ShowPanel"] = " - Show this panel\n"
	ns.L["TryMinimapMenu"] = "Try the Minimap AddOn Menu (below the Calendar)"

	ns.L["Grey"] = ( ( ns.locale == "enUS" ) and "Gray" or "Grey" )

	ns.L["Show Coordinates Description"] = "Display coordinates in tooltips on the world map and the mini map"
	ns.L["MinimapMenu"] = "A shortcut to open this panel is via the Minimap AddOn menu, which is immediately below the "
		.."Calendar icon. Just click your mouse\n\n"
end