local _, ns = ...
local L = {}
ns.L = L

setmetatable( L, { __index = function( L, key ) return key end } )

ns.locale = GetLocale()

ns.realm = GetNormalizedRealmName() -- On a fresh login this will return null
ns.oceania = { AmanThul = true, Barthilas = true, Caelestrasz = true, DathRemar = true,
			Dreadmaul = true, Frostmourne = true, Gundrak = true, JubeiThos = true, 
			Khazgoroth = true, Nagrand = true, Saurfang = true, Thaurissan = true,
			-- The following are Classic Era 1.15.x
			Yojamba = true, Remulos = true, Arugal = true, Felstriker = true,
			-- The following are Classic Seasonal (SoD) 1.15.x
			Penance = true, Shadowstrike = true,
			-- Classic Anniversary from 1.15.5
			Maladath = true, }
if ns.oceania[ ns.realm ] then
	ns.locale = "enGB"
end

ns.name = UnitName( "player" ) or "Character"
ns.faction = UnitFactionGroup( "player" )

-- Translations I often use in all my AddOns
if ns.locale == "deDE" then
	L["Character"] = "Charakter"
	L["Account"] = "Accountweiter"
	L["Completed"] = "Abgeschlossen"
	L["Not Completed"] = "Nicht Abgeschlossen"
	L["Try again"] = "Versuchen Sie es erneut. Server keine Antwort"
	L["ZidormiWrongPhase"] = "Auf Ihrer Karte wird im Verlauf der Zone der falsche Zeitpunkt angezeigt. Wenn Sie sich derzeit "
		.."in der Zone befinden, müssen Sie zuerst mit Zidormi sprechen"
	L["Options"] = "Optionen"
	L["Map Pin Size"] = "Pin-Größe"
	L["The Map Pin Size"] = "Die Größe der Karten-Pins"
	L["Map Pin Alpha"] = "Kartenpin Alpha"
	L["The alpha transparency of the map pins"] = "Die Alpha-Transparenz der Karten-Pins"
	L["Show Coordinates"] = "Koordinaten anzeigen"
	L["Show Coordinates Description"] = "Zeigen sie die koordinaten in QuickInfos auf "
		.."der Weltkarte und auf der Minikarte an"
	L["Map Pin Selections"] = "Karten-Pin-Auswahl"
	L["Gold"] = "Gold"
	L["Red"] = "Rot"
	L["Blue"] = "Blau"
	L["Green"] = "Grün"
	L["Ring"] = "Ring"
	L["Cross"] = "Kreuz"
	L["Diamond"] = "Diamant"
	L["Frost"] = "Frost"
	L["Cogwheel"] = "Zahnrad"
	L["White"] = "Weiß"
	L["Purple"] = "Lila"
	L["Yellow"] = "Gelb"
	L["Grey"] = "Grau"
	L["Mana Orb"] = "Manakugel"
	L["Phasing"] = "Synchronisieren"
	L["Raptor egg"] = "Raptor-Ei"
	L["Stars"] = "Sternen"
	L["Screw"] = "Schraube"
	L["Left"] = "Links"
	L["Right"] = "Rechts"
	L["Notes"] = "Notizen"
	L["MinimapMenu"] = "Eine Verknüpfung zum Öffnen dieses Bereichs erfolgt über das Minimap-Add-On-Menü, das sich direkt "
		.."unter dem Kalendersymbol befindet. Klicken Sie einfach mit der Maus\n\n"
	L["ChatCommands"] = "Chat-Befehlsverknüpfungen werden ebenfalls unterstützt. "
	L["ShowPanel"] = " - Dieses Panel anzeigen\n"
	L["TryMinimapMenu"] = "Probieren Sie das Minimap-Add-On-Menü (unter dem Kalender) aus"

elseif ns.locale == "esES" or ns.locale == "esMX" then
	L["Character"] = "Personaje"
	L["Account"] = "la Cuenta"
	L["Completed"] = "Completado"
	L["Not Completed"] = ( ns.locale == "esES" ) and "Sin Completar" or "Incompleto"
	L["Options"] = "Opciones"
	L["Try again"] = "Intentar otra vez. Servidor sin respuesta"
	L["ZidormiWrongPhase"] = "Tu mapa muestra el momento equivocado en el historial de la zona. Si te encuentras actualmente "
		.."en la zona, primero debes hablar con Zidormi."
	L["Map Pin Size"] = "Tamaño de alfiler"
	L["The Map Pin Size"] = "Tamaño de los pines del mapa"
	L["Map Pin Alpha"] = "Alfa de los pines del mapa"
	L["The alpha transparency of the map pins"] = "La transparencia alfa de los pines del mapa"
	L["Show Coordinates"] = "Mostrar coordenadas"
	L["Show Coordinates Description"] = "Mostrar coordenadas en información sobre "
		.."herramientas en el mapa del mundo y en el minimapa"
	L["Map Pin Selections"] = "Selecciones de pines de mapa"
	L["Gold"] = "Oro"
	L["Red"] = "Rojo"
	L["Blue"] = "Azul"
	L["Green"] = "Verde"
	L["Ring"] = "Anillo"
	L["Cross"] = "Cruz"
	L["Diamond"] = "Diamante"
	L["Frost"] = "Escarcha"
	L["Cogwheel"] = "Rueda dentada"
	L["White"] = "Blanco"
	L["Purple"] = "Púrpura"
	L["Yellow"] = "Amarillo"
	L["Grey"] = "Gris"
	L["Mana Orb"] = "Orbe de maná"
	L["Phasing"] = "Sincronización"	
	L["Raptor egg"] = "Huevo de raptor"	
	L["Stars"] = "Estrellas"
	L["Screw"] = "Tornillo"
	L["Left"] = "Izquierda"
	L["Right"] = "Derecha"
	L["Notes"] = "Notas"
	L["MinimapMenu"] = "Un atajo para abrir este panel es a través del menú adicional Minimap, que se encuentra inmediatamente "
		.."debajo del ícono Calendario. Simplemente haz clic con el mouse\n\n"
	L["ChatCommands"] = "También se admiten atajos de comandos de chat. "
	L["ShowPanel"] = " - Mostrar este panel\n"
	L["TryMinimapMenu"] = "Pruebe el menú complementario Minimap (debajo del Calendario)"

elseif ns.locale == "frFR" then
	L["Character"] = "Personnage"
	L["Account"] = "le Compte"
	L["Completed"] = "Achevé"
	L["Not Completed"] = "Non achevé"
	L["Try again"] = "Essayer à nouveau. Serveur aucune réponse"
	L["ZidormiWrongPhase"] = "Votre carte affiche le mauvais moment dans l'historique de la zone. Si vous êtes actuellement "
		.."dans la zone, vous devez d'abord parler à Zidormi."
	L["Options"] = "Options"
	L["Map Pin Size"] = "Taille des épingles"
	L["The Map Pin Size"] = "La taille des épingles de carte"
	L["Map Pin Alpha"] = "Alpha des épingles de carte"
	L["The alpha transparency of the map pins"] = "La transparence alpha des épingles de la carte"
	L["Show Coordinates"] = "Afficher les coordonnées"
	L["Show Coordinates Description"] = "Afficher les coordonnées\124r dans les info-bulles sur "
		.."la carte du monde et la mini-carte"
	L["Map Pin Selections"] = "Sélections de broches de carte"
	L["Gold"] = "Or"
	L["Red"] = "Rouge"
	L["Blue"] = "Bleue"
	L["Green"] = "Vert"
	L["Ring"] = "Bague"
	L["Cross"] = "Traverser"
	L["Diamond"] = "Diamant"
	L["Frost"] = "Givre"
	L["Cogwheel"] = "Roue dentée"
	L["White"] = "Blanc"
	L["Purple"] = "Violet"
	L["Yellow"] = "Jaune"
	L["Grey"] = "Gris"
	L["Mana Orb"] = "Orbe de mana"
	L["Phasing"] = "Synchronisation"
	L["Raptor egg"] = "Œuf de Rapace"
	L["Stars"] = "Étoiles"
	L["Screw"] = "Vis"
	L["Left"] = "Gauche"
	L["Right"] = "Droite"
	L["Notes"] = "Remarques"
	L["MinimapMenu"] = "Un raccourci pour ouvrir ce panneau se fait via le menu Minimap AddOn, qui se trouve immédiatement sous "
		.."l'icône du calendrier. Cliquez simplement avec votre souris\n\n"
	L["ChatCommands"] = "Les raccourcis des commandes de chat sont également pris en charge. "
	L["ShowPanel"] = " - Afficher ce panneau\n"
	L["TryMinimapMenu"] = "Essayez le menu complémentaire Minimap (sous le calendrier)"

elseif ns.locale == "itIT" then
	L["Character"] = "Personaggio"
	L["Account"] = "Account"
	L["Completed"] = "Completo"
	L["Not Completed"] = "Non Compiuto"
	L["Try again"] = "Riprova. Il server nessuna risposta"
	L["ZidormiWrongPhase"] = "La tua mappa sta guardando l'ora sbagliata nella cronologia della zona. Se ti trovi attualmente "
		.."nella zona, devi prima parlare con Zidormi"
	L["Options"] = "Opzioni"
	L["Map Pin Size"] = "Dimensione del pin"
	L["The Map Pin Size"] = "La dimensione dei Pin della mappa"
	L["Map Pin Alpha"] = "Mappa pin alfa"
	L["The alpha transparency of the map pins"] = "La trasparenza alfa dei pin della mappa"
	L["Show Coordinates"] = "Mostra coordinate"
	L["Show Coordinates Description"] = "Visualizza le coordinate\124r nelle descrizioni "
		.."comandi sulla mappa del mondo e sulla minimappa"
	L["Map Pin Selections"] = "Selezioni pin mappa"
	L["Gold"] = "Oro"
	L["Red"] = "Rosso"
	L["Blue"] = "Blu"
	L["Green"] = "Verde"
	L["Ring"] = "Squillo"
	L["Cross"] = "Attraverso"
	L["Diamond"] = "Diamante"
	L["Frost"] = "Gelo"
	L["Cogwheel"] = "Ruota dentata"
	L["White"] = "Bianca"
	L["Purple"] = "Viola"
	L["Yellow"] = "Giallo"
	L["Grey"] = "Grigio"
	L["Mana Orb"] = "Globo di Mana"
	L["Phasing"] = "Sincronizzazione"
	L["Raptor egg"] = "Raptor Uovo"
	L["Stars"] = "Stelle"
	L["Screw"] = "Vite"
	L["Left"] = "Sinistra"
	L["Right"] = "Destra"
	L["Notes"] = "Note"
	L["MinimapMenu"] = "Una scorciatoia per aprire questo pannello è tramite il menu Minimappa AddOn, che si trova "
		.."immediatamente sotto l'icona del Calendario. Basta fare clic con il mouse\n\n"
	L["ChatCommands"] = "Sono supportate anche le scorciatoie dei comandi di chat. "
	L["ShowPanel"] = " - Mostra questo pannello\n"
	L["TryMinimapMenu"] = "Prova il menu aggiuntivo della minimappa (sotto il calendario)"

elseif ns.locale == "koKR" then
	L["Character"] = "캐릭터"
	L["Account"] = "계정"
	L["Completed"] = "완료"
	L["Not Completed"] = "미완료"
	L["Try again"] = "다시 시도해 보세요. 서버가 응답하지 않습니다"
	L["ZidormiWrongPhase"] = "지도가 해당 구역 기록에서 잘못된 시간을 보고 있습니다. 현재 해당 구역에 있다면 먼저 지도르미와 대화해야 합니다."
	L["Options"] = "설정"
	L["Map Pin Size"] = "지도 핀의 크기"
	L["The Map Pin Size"] = "지도 핀의 크기"
	L["Map Pin Alpha"] = "지도 핀의 알파"
	L["The alpha transparency of the map pins"] = "지도 핀의 알파 투명도"
	L["Show Coordinates"] = "좌표 표시"
	L["Show Coordinates Description"] = "세계지도 및 미니지도의 도구 설명에 좌표를 표시합니다."
	L["Map Pin Selections"] = "지도 핀 선택"
	L["Gold"] = "금"
	L["Red"] = "빨간"
	L["Blue"] = "푸른"
	L["Green"] = "녹색"
	L["Ring"] = "반지"
	L["Cross"] = "십자가"
	L["Diamond"] = "다이아몬드"
	L["Frost"] = "냉기"
	L["Cogwheel"] = "톱니 바퀴"
	L["White"] = "화이트"
	L["Purple"] = "보라색"
	L["Yellow"] = "노랑"
	L["Grey"] = "회색"
	L["Mana Orb"] = "마나 보주"
	L["Phasing"] = "동기화 중"
	L["Raptor egg"] = "랩터의 알"
	L["Stars"] = "별"
	L["Screw"] = "나사"
	L["Left"] = "왼쪽"
	L["Right"] = "오른쪽"
	L["Notes"] = "메모"
	L["MinimapMenu"] = "이 패널을 여는 바로가기는 달력 아이콘 바로 아래에 있는 미니맵 애드온 메뉴를 통해 가능합니다. 마우스를 클릭하세요\n\n"
	L["ChatCommands"] = "채팅 명령 단축키도 지원됩니다. "
	L["ShowPanel"] = " - 이 패널 표시\n"
	L["TryMinimapMenu"] = "미니맵 추가 메뉴를 사용해 보세요(캘린더 아래)"

elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	L["Character"] = "Personagem"
	L["Account"] = "à Conta"
	L["Completed"] = "Concluído"
	L["Not Completed"] = "Não Concluído"
	L["Try again"] = "Tente novamente. Servidor sem resposta"
	L["ZidormiWrongPhase"] = "Seu mapa está na hora errada no histórico da zona. Se você estiver na zona, primeiro você deve "
		.."falar com Zidormi"
	L["Options"] = "Opções"
	L["Map Pin Size"] = "Tamanho do pino"
	L["The Map Pin Size"] = "O tamanho dos pinos do mapa"
	L["Map Pin Alpha"] = "Alfa dos pinos do mapa"
	L["The alpha transparency of the map pins"] = "A transparência alfa dos pinos do mapa"
	L["Show Coordinates"] = "Mostrar coordenadas"
	L["Show Coordinates Description"] = "Exibir coordenadas\124r em dicas de ferramentas "
		.."no mapa mundial e no minimapa"
	L["Map Pin Selections"] = "Seleções de pinos de mapa"
	L["Gold"] = "Ouro"
	L["Red"] = "Vermelho"
	L["Blue"] = "Azul"
	L["Green"] = "Verde"
	L["Ring"] = "Anel"
	L["Cross"] = "Cruz"
	L["Diamond"] = "Diamante"
	L["Frost"] = "Gélido"
	L["Cogwheel"] = "Roda dentada"
	L["White"] = "Branco"
	L["Purple"] = "Roxa"
	L["Yellow"] = "Amarelo"
	L["Grey"] = "Cinzento"
	L["Mana Orb"] = "Orbe de Mana"
	L["Phasing"] = "Sincronização"
	L["Raptor egg"] = "Ovo de raptor"
	L["Stars"] = "Estrelas"
	L["Screw"] = "Parafuso"
	L["Left"] = "Esquerda"
	L["Right"] = "Direita"
	L["Notes"] = "Notas"
	L["MinimapMenu"] = "Um atalho para abrir este painel é através do menu Minimap AddOn, que fica imediatamente abaixo do "
		.."ícone do Calendário. Basta clicar com o mouse\n\n"
	L["ChatCommands"] = "Atalhos de comando de bate-papo também são compatíveis. "
	L["ShowPanel"] = " - Mostrar este painel\n"
	L["TryMinimapMenu"] = "Experimente o menu AddOn do Minimapa (abaixo do Calendário)"

elseif ns.locale == "ruRU" then
	L["Character"] = "Персонажа"
	L["Account"] = "Счет"
	L["Completed"] = "Выполнено"
	L["Not Completed"] = "Не Выполнено"
	L["Try again"] = "Попробуйте еще раз. Сервер нет ответа"
	L["ZidormiWrongPhase"] = "Ваша карта смотрит не на то время в истории зоны. Если вы сейчас находитесь в зоне, сначала вам "
		.."необходимо поговорить с Зидорми."
	L["Options"] = "Параметры"
	L["Map Pin Size"] = "Размер булавки"
	L["The Map Pin Size"] = "Размер булавок на карте"
	L["Map Pin Alpha"] = "Альфа булавок карты"
	L["The alpha transparency of the map pins"] = "Альфа-прозрачность булавок карты"
	L["Show Coordinates"] = "Показать Координаты"
	L["Show Coordinates Description"] = "Отображает координаты\124r во всплывающих "
		.."подсказках на карте мира и мини-карте"
	L["Map Pin Selections"] = "Выбор булавки карты"
	L["Gold"] = "Золото"
	L["Red"] = "Красный"
	L["Blue"] = "Синий"
	L["Green"] = "Зеленый"
	L["Ring"] = "Звенеть"
	L["Cross"] = "Крест"
	L["Diamond"] = "Ромб"
	L["Frost"] = "Лед"
	L["Cogwheel"] = "Зубчатое колесо"
	L["White"] = "белый"
	L["Purple"] = "Пурпурный"
	L["Yellow"] = "Желтый"
	L["Grey"] = "Серый"
	L["Mana Orb"] = "Cфера маны"
	L["Phasing"] = "Синхронизация"
	L["Raptor egg"] = "Яйцо ящера"
	L["Stars"] = "Звезды"
	L["Screw"] = "Винт"
	L["Left"] = "Налево"
	L["Right"] = "Направо"
	L["Notes"] = "Примечания"
	L["MinimapMenu"] = "Ярлык для открытия этой панели — через меню надстройки мини-карты, которое находится сразу под значком "
		.."календаря. Просто щелкните мышью\n\n"
	L["ChatCommands"] = "Также поддерживаются сочетания клавиш чата. "
	L["ShowPanel"] = " - Показать эту панель\n"
	L["TryMinimapMenu"] = "Попробуйте меню дополнений на мини-карте (под календарем)"

elseif ns.locale == "zhCN" then
	L["Character"] = "角色"
	L["Account"] = "账号"
	L["Completed"] = "已完成"
	L["Not Completed"] = "未完成"
	L["Try later"] = "目前不可能。稍后再试"
	L["Try again"] = "再试一次。服务器无响应"
	L["ZidormiWrongPhase"] = "你的地图显示区域的时间线不对。如果你现在 在区域内，那么你必须去找希多尔米对话。"								
	L["Options"] = "选项"
	L["Map Pin Size"] = "地图图标大小"
	L["The Map Pin Size"] = "地图图标大小"
	L["Map Pin Alpha"] = "地图图标透明度"
	L["The alpha transparency of the map pins"] = "地图图标透明度"
	L["Show Coordinates"] = "显示坐标"
	L["Show Coordinates Description"] = "在世界地图和小地图上的鼠标提示中显示坐标"
	L["Map Pin Selections"] = "地图图标选择"
	L["Gold"] = "金子"
	L["Red"] = "红"
	L["Blue"] = "蓝"
	L["Green"] = "绿色"
	L["Ring"] = "戒指"
	L["Cross"] = "叉"
	L["Diamond"] = "钻石"
	L["Frost"] = "冰霜"
	L["Cogwheel"] = "齿轮"
	L["White"] = "白色"
	L["Purple"] = "紫色"
	L["Yellow"] = "黄色"
	L["Grey"] = "灰色"
	L["Mana Orb"] = "法力球"
	L["Phasing"] = "同步"
	L["Raptor egg"] = "迅猛龙蛋"
	L["Stars"] = "星星"
	L["Screw"] = "拧"
	L["Left"] = "左"
	L["Right"] = "右"
	L["Notes"] = "简介"
	L["MinimapMenu"] = "打开该界面的快捷方式可以通过原生暴雪小地图插件"
		    .."菜单，它就在原生暴雪日历图标的下方。只需点击鼠标\n\n"
	L["ChatCommands"] = "还支持输入命令打开方式，输入。 "
	L["ShowPanel"] = "- 显示设置界面\n"
	L["TryMinimapMenu"] = "也可以在暴雪原生插件收纳菜单打开（小地图日历图标下方）"

elseif ns.locale == "zhTW" then
	L["Character"] = "角色"
	L["Account"] = "賬號"
	L["Completed"] = "完成"
	L["Not Completed"] = "未完成"
	L["Try again"] = "再試一次。 伺服器無回應"
	L["ZidormiWrongPhase"] = "你的地圖顯示區域的時間線不對。如果你現在 在區域內，那麼你必須去找希多爾米對話。"
	L["Options"] = "選項"
	L["Map Pin Size"] = "地圖圖示大小"
	L["The Map Pin Size"] = "地圖圖示大小"
	L["Map Pin Alpha"] = "地圖圖標透明度"
	L["The alpha transparency of the map pins"] = "地圖圖標透明度"
	L["Show Coordinates"] = "顯示座標"
	L["Show Coordinates Description"] = "在世界地圖和小地圖上的滑鼠提示中顯示座標"
	L["Map Pin Selections"] = "地圖圖示選擇"
	L["Gold"] = "金子"
	L["Red"] = "紅"
	L["Blue"] = "藍"
	L["Green"] = "綠色"
	L["Ring"] = "戒指"
	L["Cross"] = "叉"
	L["Diamond"] = "钻石"
	L["Frost"] = "霜"
	L["Cogwheel"] = "齒輪"
	L["White"] = "白色"
	L["Purple"] = "紫色"
	L["Yellow"] = "黃色"
	L["Grey"] = "灰色"
	L["Mana Orb"] = "法力球"
	L["Phasing"] = "同步"
	L["Raptor egg"] = "迅猛龍蛋"
	L["Stars"] = "星星"
	L["Screw"] = "擰"
	L["Left"] = "左"
	L["Right"] = "右"
	L["Notes"] = "簡介"
	L["MinimapMenu"] = "打開該介面的快捷方式可以通過原生暴雪小地圖外掛程式"
		    .." 功能表，它就在原生暴雪日曆圖示的下方。 只需點擊滑鼠\n\n"
	L["ChatCommands"] = "還支援輸入命令打開方式，輸入。 "
	L["ShowPanel"] = " - 顯示設置介面\n"
	L["TryMinimapMenu"] = "也可以在暴雪原生外掛程式收納功能表打開（小地圖日曆圖示下方）"

else
	L["Try again"] = "Try again. Server no response"
	L["ZidormiWrongPhase"] = "Your map is looking at the wrong time in the zone's history. If you are presently "
		.."in the zone then you must first speak to Zidormi"
	L["Show Coordinates Description"] = "Display coordinates in tooltips on the world map and the mini map"
	L["Grey"] = ( ( ns.locale == "enUS" ) and "Gray" or "Grey" )
	L["MinimapMenu"] = "A shortcut to open this panel is via the Minimap AddOn menu, which is immediately below the "
		.."Calendar icon. Just click your mouse\n\n"
	L["ChatCommands"] = "Chat command shortcuts are also supported. "
	L["ShowPanel"] = " - Show this panel\n"
	L["TryMinimapMenu"] = "Try the Minimap AddOn Menu (below the Calendar)"
end

-- Translations specific to my annual events AddOns
-- RWC = Remove When Complete
if ns.locale == "deDE" then
	L["Achievement"] = "Leistung"
	L["Dailies"] = "Täglich"
	L["Daily"] = "Täglich"
	L["Guide"] = "Führung"
	L["Level"] = "Stufe"
	L["One Time"] = "Einmal"
	L["Quests"] = "Quests"
	L["RWCQuestDailies"] = "Tägliche Quests: Entfernen, wenn %p sie abgeschlossen hat"
	L["RWCQuestOneTime"] = "Einmalige Quests: Entfernen, wenn %p sie abgeschlossen hat"
	L["RWCQuestSeasonal"] = "Saisonale Quests: Entfernen, wenn %p sie abgeschlossen hat"
	L["RWCAchievements"] = "Erfolge: Entfernen, wenn %p sie abgeschlossen hat"
	L["RWCQuestDailiesDesc"] = "Die Kartenmarkierung wird nicht angezeigt, wenn %p die Quest heute abgeschlossen hat"
	L["RWCQuestOneTimeDesc"] = "Die Kartenmarkierung wird nicht angezeigt, wenn %p die Quest abgeschlossen hat"
	L["RWCQuestSeasonalDesc"] = "Die Kartenmarkierung wird nicht angezeigt, wenn %p die Quest in dieser Saison abgeschlossen hat"
	L["RWCAchievementsDesc"] = "Die Kartenmarkierung wird nicht angezeigt, wenn %p den Erfolg abgeschlossen hat"
	L["RWCAchievementsDescAcct"] = "Die Kartenmarkierung wird nicht angezeigt, wenn ein Charakter den Erfolg abgeschlossen hat"
	L["Seasonal"] = "Saisonal"
	L["Special"] = "Besonders"
	L["Vendors"] = "Anbieter"

elseif ns.locale == "esES" or ns.locale == "esMX" then
	L["Achievement"] = "Logro"
	L["Dailies"] = "Diarios"
	L["Daily"] = "Diaria"
	L["Guide"] = "Guía"
	L["Level"] = "Nivel"
	L["One Time"] = "Una vez"
	L["Quests"] = "Misiones"
	L["RWCQuestDailies"] = "Misiones diarias: eliminar cuando las complete %p"
	L["RWCQuestOneTime"] = "Misiones únicas: eliminar cuando las complete %p"
	L["RWCQuestSeasonal"] = "Misiones de temporada: eliminar cuando las complete %p"
	L["RWCAchievements"] = "Logros: Eliminar cuando %p lo complete"
	L["RWCQuestDailiesDesc"] = "El marcador del mapa no aparecerá cuando %p haya completado la misión de hoy"
	L["RWCQuestOneTimeDesc"] = "El marcador del mapa no aparecerá cuando %p haya completado la misión"
	L["RWCQuestSeasonalDesc"] = "El pin del mapa no aparecerá cuando %p haya completado la misión esta temporada"
	L["RWCAchievementsDesc"] = "El marcador del mapa no aparecerá cuando %p haya completado el logro"
	L["RWCAchievementsDescAcct"] = "El marcador del mapa no aparecerá cuando algún personaje haya completado el logro"
	L["Seasonal"] = "Estacional"
	L["Special"] = "Especial"
	L["Vendors"] = "Vendedores"

elseif ns.locale == "frFR" then
	L["Achievement"] = "Réalisation"
	L["Dailies"] = "Journalière"
	L["Daily"] = "Journalière"
	L["Guide"] = "Guide"
	L["Level"] = "Niveau"
	L["One Time"] = "Une fois"
	L["Quests"] = "Quêtes"
	L["RWCQuestDailies"] = "Quêtes quotidiennes : supprimer une fois terminées par %p"
	L["RWCQuestOneTime"] = "Quêtes uniques : supprimer une fois terminées par %p"
	L["RWCQuestSeasonal"] = "Quêtes saisonnières : supprimer une fois terminées par %p"
	L["RWCAchievements"] = "Réalisations : Supprimer une fois terminé par %p"
	L["RWCQuestDailiesDesc"] = "L'épingle de la carte n'apparaîtra pas lorsque %p aura terminé la quête aujourd'hui"
	L["RWCQuestOneTimeDesc"] = "L'épingle de la carte n'apparaîtra pas lorsque %p aura terminé la quête"
	L["RWCQuestSeasonalDesc"] = "L'épingle de la carte n'apparaîtra pas lorsque %p aura terminé la quête cette saison"
	L["RWCAchievementsDesc"] = "L'épingle de la carte n'apparaîtra pas lorsque %p aura terminé le succès"
	L["RWCAchievementsDescAcct"] = "L'épingle de la carte n'apparaîtra pas lorsqu'un personnage aura terminé le succès"
	L["Seasonal"] = "Saisonnier"
	L["Special"] = "Spécial"
	L["Vendors"] = "Vendeurs"

elseif ns.locale == "itIT" then
	L["Achievement"] = "Risultato"
	L["Dailies"] = "Giornaliera"
	L["Daily"] = "Giornaliera"
	L["Guide"] = "Guida"
	L["Level"] = "Livello"
	L["One Time"] = "Una volta"
	L["Quests"] = "Missioni"
	L["RWCQuestDailies"] = "Missioni giornaliere: vengono rimosse una volta completate da %p"
	L["RWCQuestOneTime"] = "Missioni una tantum: vengono rimosse una volta completate da %p"
	L["RWCQuestSeasonal"] = "Missioni stagionali: vengono rimosse una volta completate da %p"
	L["RWCAchievements"] = "Risultati: rimuovi una volta completato da %p"
	L["RWCQuestDailiesDesc"] = "Il segnaposto sulla mappa non apparirà quando %p avrà completato la missione oggi"
	L["RWCQuestOneTimeDesc"] = "Il segnaposto sulla mappa non apparirà quando %p avrà completato la missione"
	L["RWCQuestSeasonalDesc"] = "Il segnaposto sulla mappa non apparirà quando %p avrà completato la missione in questa stagione"
	L["RWCAchievementsDesc"] = "Die Kartenmarkierung wird nicht angezeigt, wenn %p den Erfolg abgeschlossen hat"
	L["RWCAchievementsDesc"] = "Il segnaposto sulla mappa non apparirà quando %p avrà completato l'obiettivo"
	L["RWCAchievementsDescAcct"] = "Il segnaposto sulla mappa non apparirà quando un personaggio avrà completato l'obiettivo"
	L["Seasonal"] = "Stagionale"
	L["Special"] = "Speciale"
	L["Vendors"] = "Venditori"
	
elseif ns.locale == "koKR" then
	L["Achievement"] = "성취"
	L["Dailies"] = "일일"
	L["Daily"] = "일일"
	L["Guide"] = "가이드"
	L["Level"] = "레벨"
	L["One Time"] = "일회"
	L["Quests"] = "퀘스트"
	L["RWCQuestDailies"] = "일일 퀘스트: %p가 완료 시 제거."
	L["RWCQuestOneTime"] = "일회 퀘스트: %p가 완료 시 제거."
	L["RWCQuestSeasonal"] = "계절 퀘스트: %p가 완료하면 제거됩니다."
	L["RWCAchievements"] = "업적: %p가 완료하면 제거됩니다."
	L["RWCQuestDailiesDesc"] = "오늘 %p가 퀘스트를 완료하면 지도 핀이 표시되지 않습니다."
	L["RWCQuestOneTimeDesc"] = "%p가 퀘스트를 완료하면 지도 핀이 표시되지 않습니다."
	L["RWCQuestSeasonalDesc"] = "이번 시즌 %p가 퀘스트를 완료하면 지도 핀이 표시되지 않습니다."
	L["RWCAchievementsDesc"] = "%p가 업적을 완료하면 지도 핀이 표시되지 않습니다."
	L["RWCAchievementsDescAcct"] = "캐릭터가 업적을 완료하면 지도 핀이 표시되지 않습니다."
	L["Seasonal"] = "계절"
	L["Special"] = "특별한"
	L["Vendors"] = "공급업체"

elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	L["Achievement"] = "Conquista"
	L["Dailies"] = "Diários"
	L["Daily"] = "Diário(a)"
	L["Guide"] = "Guia"
	L["Level"] = "Nível"
	L["One Time"] = "Uma vez"
	L["Quests"] = "Missões"
	L["RWCQuestDailies"] = "Missões diárias: Remova quando concluída por %p"
	L["RWCQuestOneTime"] = "Missões únicas: Remova quando concluída por %p"
	L["RWCQuestSeasonal"] = "Missões sazonais: removidas quando concluídas por %p"
	L["RWCAchievements"] = "Conquistas: Remover quando concluído por %p"
	L["RWCQuestDailiesDesc"] = "O pin do mapa não aparecerá quando %p completar a missão hoje"
	L["RWCQuestOneTimeDesc"] = "O pin do mapa não aparecerá quando %p completar a missão"
	L["RWCQuestSeasonalDesc"] = "O pin do mapa não aparecerá quando %p completar a missão nesta temporada"
	L["RWCAchievementsDesc"] = "O pin do mapa não aparecerá quando %p tiver concluído a conquista"
	L["RWCAchievementsDescAcct"] = "O pin do mapa não aparecerá quando algum personagem tiver concluído a conquista"
	L["Seasonal"] = "Sazonal"
	L["Special"] = "Especial"
	L["Vendors"] = "Fornecedores"

elseif ns.locale == "ruRU" then
	L["Achievement"] = "Достижение"
	L["Dailies"] = "Ежедневные газеты"
	L["Daily"] = "Ежедневно"
	L["Guide"] = "Гид"
	L["Level"] = "Уровень"
	L["One Time"] = "Один раз"
	L["Quests"] = "Задания"
	L["RWCQuestDailies"] = "Ежедневные квесты: удаляются после выполнения %p"
	L["RWCQuestOneTime"] = "Одноразовые квесты: удаляются после выполнения %p"
	L["RWCQuestSeasonal"] = "Сезонные квесты: удаляются после выполнения %p"
	L["RWCAchievements"] = "Достижения: удалить после завершения %p"
	L["RWCQuestDailiesDesc"] = "Значок на карте не появится, когда %p завершит квест сегодня"
	L["RWCQuestOneTimeDesc"] = "Значок на карте не появится, когда %p завершит квест"
	L["RWCQuestSeasonalDesc"] = "Значок на карте не появится, когда %p завершит квест в этом сезоне"
	L["RWCAchievementsDesc"] = "Значок на карте не появится, когда %p выполнит достижение"
	L["RWCAchievementsDescAcct"] = "Значок на карте не появится, если какой-либо персонаж выполнит достижение"
	L["Seasonal"] = "Сезонно"
	L["Special"] = "Особенный"
	L["Vendors"] = "Продавцы"

elseif ns.locale == "zhCN" then
	L["Achievement"] = "成就"
	L["Dailies"] = "日常"
	L["Daily"] = "日常"
	L["Guide"] = "指南"
	L["Level"] = "等级"
	L["One Time"] = "一次性"
	L["Quests"] = "任务"
	L["RWCQuestDailies"] = "每日任务：%p 完成后屏蔽显示"
	L["RWCQuestOneTime"] = "一次性任务：%p 完成后屏蔽显示"
	L["RWCQuestSeasonal"] = "季节性任务：%p 完成后屏蔽显示"
	L["RWCAchievements"] = "成就：%p 完成后屏蔽显示"
	L["RWCQuestDailiesDesc"] = "今天 %p 完成任务后，地图图标将不会出现"
	L["RWCQuestOneTimeDesc"] = "%p 完成任务后，地图图标将不会出现"
	L["RWCQuestSeasonalDesc"] = "当 %p 完成本赛季的任务时，地图图标将不会出现"
	L["RWCAchievementsDesc"] = "当 %p 完成成就时，地图图标将不会出现"
	L["RWCAchievementsDescAcct"] = "当任何角色完成成就时，地图图标将不会出现"
	L["Seasonal"] = "季节性"
	L["Special"] = "特殊的"
	L["Vendors"] = "商人"

elseif ns.locale == "zhTW" then
	L["Achievement"] = "成就"
	L["Dailies"] = "日常"
	L["Daily"] = "日常"
	L["Guide"] = "指南"
	L["Level"] = "等級"
	L["One Time"] = "一次性"
	L["Quests"] = "任務"
	L["RWCQuestDailies"] = "每日任務：%p 完成後屏蔽顯示"
	L["RWCQuestOneTime"] = "一次任務：%p 完成後屏蔽顯示"
	L["RWCQuestSeasonal"] = "季節性任務：%p 完成後屏蔽顯示"
	L["RWCAchievements"] = "成就：%p 完成後屏蔽顯示"
	L["RWCQuestDailiesDesc"] = "今天 %p 完成任務後，地圖圖示將不會出現"
	L["RWCQuestOneTimeDesc"] = "%p 完成任務後，地圖圖示將不會出現"
	L["RWCQuestSeasonalDesc"] = "當 %p 完成本賽季的任務時，地圖圖示將不會出現"
	L["RWCAchievementsDesc"] = "當 %p 完成成就時，地圖圖示將不會出現"
	L["RWCAchievementsDescAcct"] = "當任何角色完成成就時，地圖圖示將不會出現"
	L["Seasonal"] = "季節性"
	L["Special"] = "特殊的"
	L["Vendors"] = "商人"

else
	L["RWCQuestDailies"] = "Daily quests: Remove when completed by %p"
	L["RWCQuestOneTime"] = "One Time quests: Remove when completed by %p"
	L["RWCQuestSeasonal"] = "Seasonal quests: Remove when completed by %p"
	L["RWCAchievements"] = "Achievements: Remove when completed by %p"
	L["RWCQuestDailiesDesc"] = "The map pin will not appear when %p has completed the quest today"
	L["RWCQuestOneTimeDesc"] = "The map pin will not appear when %p has completed the quest"
	L["RWCQuestSeasonalDesc"] = "The map pin will not appear when %p has completed the quest this season"
	L["RWCAchievementsDesc"] = "The map pin will not appear when %p has completed the achievement"
	L["RWCAchievementsDescAcct"] = "The map pin will not appear when any character has completed the achievement"
end

-- Translations specific to the Lunar Festival AddOn
if ns.locale == "deDE" then
	L["AddOn Description"] = "%eHilfe für Erfolge und Quests in %sMondfest"
	L["Blue Coin"] = "Blaue Münze"
	L["Crown of... Quests"] = "Krone des... (Quests)"
	L["Crown of Courage"] = "Krone des Mutes"
	L["Crown of Dark Blossoms"] = "Krone der dunklen Blüten"
	L["Crown of Good Fortune"] = "Krone des Glücks"
	L["Crown of Prosperity"] = "Krone des Wohlstands"
	L["Crown of Harvesters"] = "Krone der Ernter"
	L["Deep Green Coin"] = "Tiefgrüne Münze"
	L["Deep Pink Coin"] = "Tiefrosa Münze"
	L["Deep Red Coin"] = "Tiefrote Münze"
	L["Dungeons"] = "Kerker"
	L["Factions"] = "Fraktionen"
	L["Flower of Compassion"] = "Blume des Mitgefühls"
	L["Flower of Felicity"] = "Blume der Glückseligkeit"
	L["Flower of Fortitude"] = "Blume der Standhaftigkeit"
	L["Flower of Generosity"] = "Blume des Großmuts"
	L["Flower of Luck"] = "Blume des Glücks"
	L["Flower of Peace"] = "Blume des Friedens"
	L["Flower of Reflection"] = "Blume der Besinnung"
	L["Flower of Sincerity"] = "Blume der Aufrichtigkeit"
	L["Flower of Solemnity"] = "Blume der Feierlichkeit"
	L["Flower of Thoughtfulness"] = "Blume der Besonnenheit"
	L["Flower of Vigor"] = "Blume der Vitalität"
	L["Flower of Wealth"] = "Blume des Wohlstands"
	L["Green Coin"] = "Grüne Münze"
	L["History"] = "Geschichte"
	L["HonorElders"] = "Respekt vor den Urahnen"
	L["Light Blue Coin"] = "Hellblaue Münze"
	L["Lunar Festival"] = "Mondfest"
	L["Lunar Preservation"] = "Mondschutz"
	L["Not yet begun"] = "Noch nicht begonnen"
	L["Original Coin"] = "Ursprüngliche Münze"
	L["Pink Coin"] = "Rosa Münze"
	L["Purple Coin"] = "Lila Münze"
	L["Ready to turn in"] = "Bereit zur Abgabe"
	L["Teal Coin"] = "Blaugrüne Münze"
	L["Wells so far: "] = "Wells bisher: "
	L["Zones"] = "Gebiete"

elseif ns.locale == "esES" or ns.locale == "esMX" then
	L["AddOn Description"] = "%eAyuda para logros y misiones en %sEl festín del Festival Lunar"
	L["Blue Coin"] = "Moneda Azul"
	L["Crown of... Quests"] = "Corona de... (Misiones)"
	L["Crown of Courage"] = "Corona de coraje"
	L["Crown of Dark Blossoms"] = "Corona de flores oscuras"
	L["Crown of Good Fortune"] = "Corona de buena fortuna"
	L["Crown of Prosperity"] = "Corona de prosperidad"
	L["Crown of Harvesters"] = "Corona de los cosechadores"
	L["Deep Green Coin"] = "Moneda Verde Oscuro"
	L["Deep Pink Coin"] = "Moneda Rosa Oscuro"
	L["Deep Red Coin"] = "Moneda de color Rojo Oscuro"
	L["Dungeons"] = "Mazmorras"
	L["Factions"] = "Facciones"
	L["Flower of Compassion"] = "Flor de compasión"
	L["Flower of Felicity"] = "Flor de felicidad"
	L["Flower of Fortitude"] = "Flor de entereza"
	L["Flower of Generosity"] = "Flor de generosidad"
	L["Flower of Luck"] = "Flor de suerte"
	L["Flower of Peace"] = "Flor de paz"
	L["Flower of Reflection"] = "Flor de reflejo"
	L["Flower of Sincerity"] = "Flor de sinceridad"
	L["Flower of Solemnity"] = "Flor de solemnidad"
	L["Flower of Thoughtfulness"] = "Flor de consideración"
	L["Flower of Vigor"] = "Flor de vigor"
	L["Flower of Wealth"] = "Flor de riqueza"
	L["Green Coin"] = "Moneda Verde"
	L["History"] = "Historia"
	L["HonorElders"] = "Honrar a los ancestros personales"
	L["Light Blue Coin"] = "Moneda Azul Claro"
	L["Lunar Festival"] = "El festín del Festival Lunar"
	L["Lunar Preservation"] = "Preservación Lunar"
	L["Not yet begun"] = "Aún no ha comenzado"
	L["Original Coin"] = "Moneda Original"
	L["Pink Coin"] = "Moneda Rosa"
	L["Purple Coin"] = "Moneda Morada"
	L["Ready to turn in"] = "Listo para entregar"
	L["Teal Coin"] = "Moneda Verde Azulado"
	L["Wells so far: "] = "Pozos hasta ahora: "
	L["Zones"] = "Zonas"

elseif ns.locale == "frFR" then
	L["AddOn Description"] = "%eAide pour les réalisations et les quêtes dans %sFête lunaire"
	L["Blue Coin"] = "Pièce bleue"
	L["Crown of... Quests"] = "Couronne de... (Quêtes)"
	L["Crown of Courage"] = "Couronne de courage"
	L["Crown of Dark Blossoms"] = "Couronne de fleurs sombres"
	L["Crown of Good Fortune"] = "Couronne de bonne fortune"
	L["Crown of Prosperity"] = "Couronne de prospérité"
	L["Crown of Harvesters"] = "La couronne des Moissonneurs"
	L["Deep Green Coin"] = "Pièce vert foncé"
	L["Deep Pink Coin"] = "Pièce rose foncé"
	L["Deep Red Coin"] = "Pièce rouge foncé"
	L["Dungeons"] = "Donjons"
	L["Factions"] = "Factions"
	L["Flower of Compassion"] = "Fleur de compassion"
	L["Flower of Felicity"] = "Fleur de félicité"
	L["Flower of Fortitude"] = "Fleur de robustesse"
	L["Flower of Generosity"] = "Fleur de générosité"
	L["Flower of Luck"] = "Fleur de chance"
	L["Flower of Peace"] = "Fleur de paix"
	L["Flower of Reflection"] = "Fleur de réflexion"
	L["Flower of Sincerity"] = "Fleur de sincérité"
	L["Flower of Solemnity"] = "Fleur de solennité"
	L["Flower of Thoughtfulness"] = "Fleur de prévenance"
	L["Flower of Vigor"] = "Fleur de vigueur"
	L["Flower of Wealth"] = "Fleur de richesse"
	L["Green Coin"] = "Pièce verte"
	L["History"] = "Histoire"
	L["HonorElders"] = "Honorer ses Anciens"
	L["Light Blue Coin"] = "Pièce bleu clair"
	L["Lunar Festival"] = "Fête lunaire"
	L["Lunar Preservation"] = "Préservation Lunaire"
	L["Not yet begun"] = "Pas encore commencé"
	L["Original Coin"] = "Pièce originale"
	L["Pink Coin"] = "Pièce rose"
	L["Purple Coin"] = "Pièce violette"
	L["Ready to turn in"] = "Prêt à se rendre"
	L["Teal Coin"] = "Pièce sarcelle"
	L["Wells so far: "] = "Puits jusqu'à présent: "
	L["Zones"] = "Zones"

elseif ns.locale == "itIT" then
	L["AddOn Description"] = "%eAiuto per obiettivi e missioni in %sCelebrazione della Luna"
	L["Blue Coin"] = "Moneta blu"
	L["Crown of... Quests"] = "Corona di... (Missioni)"
	L["Crown of Courage"] = "Corona del Coraggio"
	L["Crown of Dark Blossoms"] = "Corona di Boccioli Oscuri"
	L["Crown of Good Fortune"] = "Corona della Fortuna"
	L["Crown of Prosperity"] = "Corona della Prosperità"
	L["Crown of Harvesters"] = "La Corona dei Mietitori"
	L["Deep Green Coin"] = "Moneta verde intenso"
	L["Deep Pink Coin"] = "Moneta rosa intenso"
	L["Deep Red Coin"] = "Moneta rosso scuro"
	L["Dungeons"] = "Sotterranee"
	L["Factions"] = "Fazioni"
	L["Flower of Compassion"] = "Fiore della Compassione"
	L["Flower of Felicity"] = "Fiore della Letizia"
	L["Flower of Fortitude"] = "Fiore della Fermezza"
	L["Flower of Generosity"] = "Fiore della Generosità"
	L["Flower of Luck"] = "Fiore della Fortuna"
	L["Flower of Peace"] = "Fiore della Pace"
	L["Flower of Reflection"] = "Fiore della Riflessione"
	L["Flower of Sincerity"] = "Fiore della Sincerità"
	L["Flower of Solemnity"] = "Fiore della Solennità"
	L["Flower of Thoughtfulness"] = "Fiore del Raccoglimento"
	L["Flower of Vigor"] = "Fiore del Vigore"
	L["Flower of Wealth"] = "Fiore della Prosperità"
	L["Green Coin"] = "Moneta verde"
	L["History"] = "Storia"
	L["HonorElders"] = "Onore agli Anziani"
	L["Light Blue Coin"] = "Moneta azzurra"
	L["Lunar Festival"] = "Celebrazione della Luna"
	L["Lunar Preservation"] = "Preservazione Lunare"
	L["Not yet begun"] = "Non ancora iniziato"
	L["Original Coin"] = "Moneta originale"
	L["Pink Coin"] = "Moneta rosa"
	L["Purple Coin"] = "Moneta viola"
	L["Ready to turn in"] = "Pronto per la consegna"
	L["Teal Coin"] = "Moneta verde acqua"
	L["Wells so far: "] = "Moonwell finora: "
	L["Zones"] = "Zone"

elseif ns.locale == "koKR" then
	L["AddOn Description"] = "%s달의 축제%e의 업적 및 퀘스트에 대한 도움말"	
	L["Blue Coin"] = "블루 코인"
	L["Crown of... Quests"] = "왕관... (퀘스트)"
	L["Crown of Courage"] = "용기의 관"
	L["Crown of Dark Blossoms"] = "어둠 꽃의 관"
	L["Crown of Good Fortune"] = "행운의 관"
	L["Crown of Prosperity"] = "번영의 관"
	L["Crown of Harvesters"] = "수확자의 왕관"
	L["Deep Green Coin"] = "딥그린 코인"
	L["Deep Pink Coin"] = "딥 핑크 코인"
	L["Deep Red Coin"] = "딥 레드 코인"
	L["Dungeons"] = "던전"
	L["Factions"] = "진영"
	L["Flower of Compassion"] = "연민의 꽃"
	L["Flower of Felicity"] = "희락의 꽃"
	L["Flower of Fortitude"] = "인내의 꽃"
	L["Flower of Generosity"] = "아량의 꽃"
	L["Flower of Luck"] = "행운의 꽃"
	L["Flower of Peace"] = "평화의 꽃"
	L["Flower of Reflection"] = "비춤의 꽃"
	L["Flower of Sincerity"] = "신실의 꽃"
	L["Flower of Solemnity"] = "장엄의 꽃"
	L["Flower of Thoughtfulness"] = "사색의 꽃"
	L["Flower of Vigor"] = "활력의 꽃"
	L["Flower of Wealth"] = "부귀의 꽃"
	L["Green Coin"] = "그린 코인"
	L["History"] = "역사"
	L["HonorElders"] = "장로 섬기기"
	L["Light Blue Coin"] = "하늘색 동전"
	L["Lunar Festival"] = "달의 축제"
	L["Lunar Preservation"] = "달빛지기"
	L["Not yet begun"] = "아직 시작되지 않았습니다"
	L["Original Coin"] = "원래 동전"
	L["Pink Coin"] = "핑크 코인"
	L["Purple Coin"] = "퍼플 코인"
	L["Ready to turn in"] = "제출 준비 완료"
	L["Teal Coin"] = "틸 코인"
	L["Wells so far: "] = "지금까지 웰스: "
	L["Zones"] = "지역"
		
elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	L["AddOn Description"] = "%eAjuda para conquistas e missões em %sFestival da Lua"
	L["Blue Coin"] = "Moeda azul"
	L["Crown of... Quests"] = "Coroa... (Missões)"
	L["Crown of Courage"] = "Coroa da Coragem"
	L["Crown of Dark Blossoms"] = "Coroa de Flores Sombrias"
	L["Crown of Good Fortune"] = "Coroa da Boa Sorte"
	L["Crown of Prosperity"] = "Coroa da Prosperidade"
	L["Crown of Harvesters"] = "Coroa dos Ceifadores"
	L["Deep Green Coin"] = "moeda verde escuro"
	L["Deep Pink Coin"] = "Moeda rosa escuro"
	L["Deep Red Coin"] = "moeda vermelha escura"
	L["Dungeons"] = "Masmorras"
	L["Factions"] = "Facções"
	L["Flower of Compassion"] = "Flor da Compaixão"
	L["Flower of Felicity"] = "Flor da Felicidade"
	L["Flower of Fortitude"] = "Flor da Fortitude"
	L["Flower of Generosity"] = "Flor da Generosidade"
	L["Flower of Luck"] = "Flor da Sorte"
	L["Flower of Peace"] = "Flor da Paz"
	L["Flower of Reflection"] = "Flor da Reflexão"
	L["Flower of Sincerity"] = "Flor da Sinceridade"
	L["Flower of Solemnity"] = "Flor da Dignidade"
	L["Flower of Thoughtfulness"] = "Flor da Meditação"
	L["Flower of Vigor"] = "Flor do Vigor"
	L["Flower of Wealth"] = "Flor da Riqueza"
	L["Green Coin"] = "moeda verde"
	L["History"] = "História"
	L["HonorElders"] = "Respeito aos mais velhos"
	L["Light Blue Coin"] = "Moeda azul claro"
	L["Lunar Festival"] = "Festival da Lua"
	L["Lunar Preservation"] = "Preservação lunar"
	L["Not yet begun"] = "Ainda não começou"
	L["Original Coin"] = "moeda original"
	L["Pink Coin"] = "moeda rosa"
	L["Purple Coin"] = "moeda roxa"
	L["Ready to turn in"] = "Pronto para entregar"
	L["Teal Coin"] = "moeda azul-petróleo"
	L["Wells so far: "] = "Poços até agora: "
	L["Zones"] = "Zonas"

elseif ns.locale == "ruRU" then
	L["AddOn Description"] = "%eСправка по достижениям и квестам в %sЛунный фестиваль"
	L["Blue Coin"] = "Синяя Монета"
	L["Crown of... Quests"] = "Венок... (Задания)"
	L["Crown of Courage"] = "Венок отваги"
	L["Crown of Dark Blossoms"] = "Венок из темных цветов"
	L["Crown of Good Fortune"] = "Венок удачи"
	L["Crown of Prosperity"] = "Венок процветания"
	L["Crown of Harvesters"] = "Корона Жнецов"
	L["Deep Green Coin"] = "Темно-зеленая Монета"
	L["Deep Pink Coin"] = "Темно-розовая Монета"
	L["Deep Red Coin"] = "Темно-красная Монета"
	L["Dungeons"] = "Подземелья"
	L["Factions"] = "ФракцииФракции"
	L["Flower of Compassion"] = "Цветок сострадания"
	L["Flower of Felicity"] = "Цветок счастья"
	L["Flower of Fortitude"] = "Цветок стойкости"
	L["Flower of Generosity"] = "Цветок щедрости"
	L["Flower of Luck"] = "Цветок удачи"
	L["Flower of Peace"] = "Цветок мира"
	L["Flower of Reflection"] = "Цветок размышлений"
	L["Flower of Sincerity"] = "Цветок искренности"
	L["Flower of Solemnity"] = "Цветок печали"
	L["Flower of Thoughtfulness"] = "Цветок проницательности"
	L["Flower of Vigor"] = "Цветок жизненной силы"
	L["Flower of Wealth"] = "Цветок богатства"
	L["Green Coin"] = "Зеленая Монета"
	L["History"] = "История"
	L["HonorElders"] = "Почтение к предкам"
	L["Light Blue Coin"] = "Голубая Монета"
	L["Lunar Festival"] = "Лунный фестиваль"
	L["Lunar Preservation"] = "Лунная Консервация"
	L["Not yet begun"] = "Еще не началось"
	L["Original Coin"] = "Оригинальная Монета"
	L["Pink Coin"] = "Розовая Монета"
	L["Purple Coin"] = "Фиолетовая Монета"
	L["Ready to turn in"] = "Готов сдать"
	L["Teal Coin"] = "Бирюзовая Монета"
	L["Wells so far: "] = "Лунные колодцы на данный момент: "
	L["Zones"] = "Территории"

elseif ns.locale == "zhCN" then
	L["AddOn Description"] = "%e帮助%s春节%e的成就和任务"
	L["Blue Coin"] = "蓝币"
	L["Crown of... Quests"] = "花冠系列任务"
	L["Crown of Courage"] = "勇气花冠"
	L["Crown of Dark Blossoms"] = "黑色末日花冠"
	L["Crown of Good Fortune"] = "好运花冠"
	L["Crown of Prosperity"] = "繁荣花冠"
	L["Crown of Harvesters"] = "收割者之冠"
	L["Deep Green Coin"] = "深绿币"
	L["Deep Pink Coin"] = "深粉色硬币"
	L["Deep Red Coin"] = "深红硬币"
	L["Dungeons"] = "地下城"
	L["Factions"] = "阵营"
	L["Flower of Compassion"] = "恻隐之花"
	L["Flower of Felicity"] = "幸福之花"
	L["Flower of Fortitude"] = "坚韧之花"
	L["Flower of Generosity"] = "慷慨之花"
	L["Flower of Luck"] = "幸运之花"
	L["Flower of Peace"] = "平和之花"
	L["Flower of Reflection"] = "反思之花"
	L["Flower of Sincerity"] = "诚挚之花"
	L["Flower of Solemnity"] = "庄严之花"
	L["Flower of Thoughtfulness"] = "思绪之花"
	L["Flower of Vigor"] = "活力之花"
	L["Flower of Wealth"] = "财富之花"
	L["Green Coin"] = "绿币"
	L["History"] = "历史"
	L["HonorElders"] = "尊敬长者"
	L["Light Blue Coin"] = "淡蓝色硬币"
	L["Lunar Festival"] = "春节"
	L["Lunar Preservation"] = "月光守护"
	L["Not yet begun"] = "未开始"
	L["Original Coin"] = "原币"
	L["Pink Coin"] = "粉币"
	L["Purple Coin"] = "紫币"
	L["Ready to turn in"] = "准备上交"
	L["Teal Coin"] = "蓝绿色硬币"
	L["Wells so far: "] = "目前的月亮井： "
	L["Zones"] = "地区"

elseif ns.locale == "zhTW" then
	L["AddOn Description"] = "%e幫助%s春節%e的成就和任務"
	L["Blue Coin"] = "藍幣"
	L["Crown of... Quests"] = "花冠系列任務"
	L["Crown of Courage"] = "勇氣花冠"
	L["Crown of Dark Blossoms"] = "黑色末日花冠"
	L["Crown of Good Fortune"] = "好運花冠"
	L["Crown of Prosperity"] = "繁榮花冠"
	L["Crown of Harvesters"] = "收割者之冠"
	L["Deep Green Coin"] = "深綠幣"
	L["Deep Pink Coin"] = "深粉色硬幣"
	L["Deep Red Coin"] = "深紅硬幣"
	L["Dungeons"] = "地下城"
	L["Factions"] = "陣營"
	L["Flower of Compassion"] = "惻隱之花"
	L["Flower of Felicity"] = "幸福之花"
	L["Flower of Fortitude"] = "堅韌之花"
	L["Flower of Generosity"] = "慷慨之花"
	L["Flower of Luck"] = "幸運之花"
	L["Flower of Peace"] = "平和之花"
	L["Flower of Reflection"] = "反思之花"
	L["Flower of Sincerity"] = "誠摯之花"
	L["Flower of Solemnity"] = "莊嚴之花"
	L["Flower of Thoughtfulness"] = "思緒之花"
	L["Flower of Vigor"] = "活力之花"
	L["Flower of Wealth"] = "財富之花"
	L["Green Coin"] = "綠幣"
	L["History"] = "歷史"
	L["HonorElders"] = "尊敬的長者"
	L["Light Blue Coin"] = "淡藍色硬幣"
	L["Lunar Festival"] = "春節"
	L["Lunar Preservation"] = "月光守護"
	L["Not yet begun"] = "未開始"
	L["Original Coin"] = "原幣"
	L["Pink Coin"] = "粉幣"
	L["Purple Coin"] = "紫幣"
	L["Ready to turn in"] = "準備上交"
	L["Teal Coin"] = "藍綠色硬幣"
	L["Wells so far: "] = "目前的月亮井： "
	L["Zones"] = "地區"
	
else
	L["AddOn Description"] = "%eHelp for the %sLunar Festival %eachievements and quests"
	L["HonorElders"] = "To Honor One's Elders"
end