local _, ns = ...

ns.mt = {}
ns.mt.__index = function( table, key )
	return key
end
ns.L = {}
setmetatable( ns.L, ns.mt )

-- Translations I often use in all my AddOns
if ns.locale == "deDE" then
	ns.L["Character"] = "Charakter"
	ns.L["Account"] = "Accountweiter"
	ns.L["Completed"] = "Abgeschlossen"
	ns.L["Not Completed"] = "Nicht Abgeschlossen"
	ns.L["Try again"] = "Versuchen Sie es erneut. Server keine Antwort"
	ns.L["ZidormiWrongPhase"] = "Auf Ihrer Karte wird im Verlauf der Zone der falsche Zeitpunkt angezeigt. Wenn Sie sich derzeit "
		.."in der Zone befinden, müssen Sie zuerst mit Zidormi sprechen"

	ns.L["Options"] = "Optionen"
	ns.L["Map Pin Size"] = "Pin-Größe"
	ns.L["The Map Pin Size"] = "Die Größe der Karten-Pins"
	ns.L["Map Pin Alpha"] = "Kartenpin Alpha"
	ns.L["Alpha Description"] = "Die Alpha-Transparenz der Karten-Pins"
	ns.L["ShowCoordinates"] = "Koordinaten anzeigen"
	ns.L["ShowCoordinatesDesc"] = "Zeigen sie die koordinaten in QuickInfos auf "
		.."der Weltkarte und auf der Minikarte an" ..ns.colour.highlight .."\n(xx.xx,yy.yy)"
	ns.L["ShowContinents"] = "Pins auf den Kontinentkarten anzeigen"
	ns.L["ShowContinentsDesc"] = "Es könnte VIELE Pins auf den Kontinentkarten geben"
	ns.L["ShowAzeroth"] = "Stecknadeln auf der Azeroth-Karte anzeigen"
	ns.L["ShowAzerothDesc"] = "Es wird VIELE Pins auf der Azeroth-Karte geben"
	ns.L["ShowPins"] = "Karten-Pins anzeigen"
	ns.L["ShowPinsDesc"] = "Wenn diese Option deaktiviert ist, wird das Add-On nichts tun. Dies ist der Haupt-Ein-/Ausschalter"
	ns.L["Textures"] = "Texturen"
	ns.L["Pin Texture"] = "Pin-Textur"
	ns.L["SelectionTexture"] = "Wählen Sie eine der immersiven, thematischen Texturen oder vielleicht eine charakteristische, "
		.."farbige generische Textur. Die generischen Texturen sind viel kleiner skaliert"
	ns.L["Left"] = "Links"
	ns.L["Right"] = "Rechts"
	ns.L["Notes"] = "Notizen"
	ns.L["MinimapMenu"] = "Eine Verknüpfung zum Öffnen dieses Bereichs erfolgt über das Minimap-Add-On-Menü, das sich direkt "
		.."unter dem Kalendersymbol befindet. Klicken Sie einfach mit der Maus\n\n"
	ns.L["ChatCommands"] = "Chat-Befehlsverknüpfungen werden ebenfalls unterstützt. "
	ns.L["ShowPanel"] = " - Dieses Panel anzeigen\n"
	ns.L["TryMinimapMenu"] = "Probieren Sie das Minimap-Add-On-Menü (unter dem Kalender) aus"
	
	-- Beware: colours are masculine and feminine as adjectives
	ns.L["Black"] = "Schwarz"
	ns.L["Blue"] = "Blau"
	ns.L["Brown"] = "Braun"
	ns.L["Cyan"] = "Cyan"
	ns.L["Dark Blue"] = "Dunkelblau"
	ns.L["Gold"] = "Gold"
	ns.L["Green"] = "Grün"
	ns.L["Grey"] = "Grau"
	ns.L["Light Blue"] = "Hellblau"
	ns.L["Light Green"] = "Hellgrün"
	ns.L["Magenta"] = "Magenta"
	ns.L["Orange"] = "Orange"
	ns.L["Original"] = "Original"
	ns.L["Pink"] = "Rosa"
	ns.L["Purple"] = "Lila"
	ns.L["Red"] = "Rot"
	ns.L["Teal"] = "Blaugrün"
	ns.L["Turquoise"] = "Türkis"	
	ns.L["White"] = "Weiß"
	ns.L["Yellow"] = "Gelb"

	ns.L["Ring"] = "Ring"
	ns.L["Cross"] = "Kreuz"
	ns.L["Diamond"] = "Diamant"
	ns.L["Frost"] = "Frost"
	ns.L["Cogwheel"] = "Zahnrad"
	ns.L["Mana Orb"] = "Manakugel"
	ns.L["Phasing"] = "Synchronisieren"
	ns.L["Raptor Egg"] = "Raptor-Ei"
	ns.L["Stars"] = "Sternen"
	ns.L["Screw"] = "Schraube"
	
elseif ns.locale == "esES" or ns.locale == "esMX" then
	ns.L["Character"] = "Personaje"
	ns.L["Account"] = "la Cuenta"
	ns.L["Completed"] = "Completado"
	ns.L["Not Completed"] = ( ns.locale == "esES" ) and "Sin Completar" or "Incompleto"
	ns.L["Try again"] = "Intentar otra vez. Servidor sin respuesta"
	ns.L["ZidormiWrongPhase"] = "Tu mapa muestra el momento equivocado en el historial de la zona. Si te encuentras actualmente "
		.."en la zona, primero debes hablar con Zidormi."

	ns.L["Options"] = "Opciones"
	ns.L["Map Pin Size"] = "Tamaño de alfiler"
	ns.L["The Map Pin Size"] = "Tamaño de los pines del mapa"
	ns.L["Map Pin Alpha"] = "Alfa de los pines del mapa"
	ns.L["Alpha Description"] = "La transparencia alfa de los pines del mapa"
	ns.L["ShowCoordinates"] = "Mostrar coordenadas"
	ns.L["ShowCoordinatesDesc"] = "Mostrar coordenadas en información sobre "
		.."herramientas en el mapa del mundo y en el minimapa" ..ns.colour.highlight .."\n(xx.xx,yy.yy)"
	ns.L["ShowContinents"] = "Mostrar marcadores en los mapas continentales"
	ns.L["ShowContinentsDesc"] = "Podría haber muchos marcadores en los mapas continentales"
	ns.L["ShowAzeroth"] = "Mostrar pines en el mapa de Azeroth"
	ns.L["ShowAzerothDesc"] = "Habrá muchos marcadores en el mapa de Azeroth"
	ns.L["ShowPins"] = "Mostrar los pines"
	ns.L["ShowPinsDesc"] = "Si no está marcada, el complemento no hará nada. Este es el interruptor principal "
		.."de encendido y apagado"
	ns.L["Textures"] = "Texturas"
	ns.L["Pin Texture"] = "Textura de alfiler"
	ns.L["SelectionTexture"] = "Seleccione una de las texturas temáticas inmersivas o quizás una textura genérica con un color "
		.."distintivo. Las texturas genéricas se escalan para ser mucho más pequeñas"
	ns.L["Left"] = "Izquierda"
	ns.L["Right"] = "Derecha"
	ns.L["Notes"] = "Notas"
	ns.L["MinimapMenu"] = "Un atajo para abrir este panel es a través del menú adicional Minimap, que se encuentra inmediatamente "
		.."debajo del ícono Calendario. Simplemente haz clic con el mouse\n\n"
	ns.L["ChatCommands"] = "También se admiten atajos de comandos de chat. "
	ns.L["ShowPanel"] = " - Mostrar este panel\n"
	ns.L["TryMinimapMenu"] = "Pruebe el menú complementario Minimap (debajo del Calendario)"

	-- Beware: colours are masculine and feminine
	ns.L["Black"] = "Negro"
	ns.L["Blue"] = "Azul"
	ns.L["Brown"] = "Marrón"
	ns.L["Cyan"] = "Cian"
	ns.L["Dark Blue"] = "Azul oscuro"
	ns.L["Gold"] = "Oro"
	ns.L["Green"] = "Verde"
	ns.L["Grey"] = "Gris"
	ns.L["Light Blue"] = "Azul claro"
	ns.L["Light Green"] = "Verde claro"
	ns.L["Magenta"] = "Magenta"
	ns.L["Orange"] = "Naranja"
	ns.L["Original"] = "Original"
	ns.L["Pink"] = "Rosa"
	ns.L["Purple"] = "Púrpura"
	ns.L["Red"] = "Rojo"
	ns.L["Teal"] = "Verde azulado"
	ns.L["Turquoise"] = "Turquesa"	
	ns.L["White"] = "Blanco"
	ns.L["Yellow"] = "Amarillo"
	
	ns.L["Ring"] = "Anillo"
	ns.L["Cross"] = "Cruz"
	ns.L["Diamond"] = "Diamante"
	ns.L["Frost"] = "Escarcha"
	ns.L["Cogwheel"] = "Rueda dentada"
	ns.L["Mana Orb"] = "Orbe de maná"
	ns.L["Phasing"] = "Sincronización"	
	ns.L["Raptor Egg"] = "Huevo de raptor"	
	ns.L["Stars"] = "Estrellas"
	ns.L["Screw"] = "Tornillo"
	
elseif ns.locale == "frFR" then
	ns.L["Character"] = "Personnage"
	ns.L["Account"] = "le Compte"
	ns.L["Completed"] = "Achevé"
	ns.L["Not Completed"] = "Non achevé"
	ns.L["Try again"] = "Essayer à nouveau. Serveur aucune réponse"
	ns.L["ZidormiWrongPhase"] = "Votre carte affiche le mauvais moment dans l'historique de la zone. Si vous êtes actuellement "
		.."dans la zone, vous devez d'abord parler à Zidormi."

	ns.L["Options"] = "Options"
	ns.L["Map Pin Size"] = "Taille des épingles"
	ns.L["The Map Pin Size"] = "La taille des épingles de carte"
	ns.L["Map Pin Alpha"] = "Alpha des épingles de carte"
	ns.L["Alpha Description"] = "La transparence alpha des épingles de la carte"
	ns.L["ShowCoordinates"] = "Afficher les coordonnées"
	ns.L["ShowCoordinatesDesc"] = "Afficher les coordonnées\124r dans les info-bulles sur "
		.."la carte du monde et la mini-carte" ..ns.colour.highlight .."\n(xx.xx,yy.yy)"
	ns.L["ShowContinents"] = "Afficher les épingles sur les cartes des continents"
	ns.L["ShowContinentsDesc"] = "Il pourrait y avoir beaucoup d'épingles sur les cartes des continents"
	ns.L["ShowAzeroth"] = "Afficher les épingles sur la carte d'Azeroth"
	ns.L["ShowAzerothDesc"] = "Il y aura beaucoup d'épingles sur la carte d'Azeroth"
	ns.L["ShowPins"] = "Afficher les repères"
	ns.L["ShowPinsDesc"] = "Si cette case n'est pas cochée, l'extension ne fera rien. Il s'agit de l'interrupteur "
		.."principal marche/arrêt"
	ns.L["Textures"] = "Textures"
	ns.L["Pin Texture"] = "Texture des épingles"
	ns.L["SelectionTexture"] = "Choisissez l'une des textures thématiques immersives ou une texture générique aux couleurs "
		.."distinctives. Les textures génériques sont réduites."
	ns.L["Left"] = "Gauche"
	ns.L["Right"] = "Droite"
	ns.L["Notes"] = "Remarques"
	ns.L["MinimapMenu"] = "Un raccourci pour ouvrir ce panneau se fait via le menu Minimap AddOn, qui se trouve immédiatement sous "
		.."l'icône du calendrier. Cliquez simplement avec votre souris\n\n"
	ns.L["ChatCommands"] = "Les raccourcis des commandes de chat sont également pris en charge. "
	ns.L["ShowPanel"] = " - Afficher ce panneau\n"
	ns.L["TryMinimapMenu"] = "Essayez le menu complémentaire Minimap (sous le calendrier)"

	-- Beware: colours are masculine and feminine as adjectives
	ns.L["Black"] = "Noir"
	ns.L["Blue"] = "Bleu"
	ns.L["Brown"] = "Marron"
	ns.L["Cyan"] = "Cyan"
	ns.L["Dark Blue"] = "Bleu foncé"
	ns.L["Gold"] = "Or"
	ns.L["Green"] = "Vert"
	ns.L["Grey"] = "Gris"
	ns.L["Light Blue"] = "Bleu clair"
	ns.L["Light Green"] = "Vert clair"
	ns.L["Magenta"] = "Magenta"
	ns.L["Orange"] = "Orange"	ns.L["Pink"] = "Rose"
	ns.L["Original"] = "Originale"
	ns.L["Purple"] = "Violet"
	ns.L["Red"] = "Rouge"
	ns.L["Teal"] = "Bleu sarcelle"
	ns.L["Turquoise"] = "Turquoise"	
	ns.L["White"] = "Blanc"
	ns.L["Yellow"] = "Jaune"

	ns.L["Ring"] = "Bague"
	ns.L["Cross"] = "Traverser"
	ns.L["Diamond"] = "Diamant"
	ns.L["Frost"] = "Givre"
	ns.L["Cogwheel"] = "Roue dentée"
	ns.L["Mana Orb"] = "Orbe de mana"
	ns.L["Phasing"] = "Synchronisation"
	ns.L["Raptor Egg"] = "Œuf de Rapace"
	ns.L["Stars"] = "Étoiles"
	ns.L["Screw"] = "Vis"

elseif ns.locale == "itIT" then
	ns.L["Character"] = "Personaggio"
	ns.L["Account"] = "Account"
	ns.L["Completed"] = "Completo"
	ns.L["Not Completed"] = "Non Compiuto"
	ns.L["Try again"] = "Riprova. Il server nessuna risposta"
	ns.L["ZidormiWrongPhase"] = "La tua mappa sta guardando l'ora sbagliata nella cronologia della zona. Se ti trovi attualmente "
		.."nella zona, devi prima parlare con Zidormi"

	ns.L["Options"] = "Opzioni"
	ns.L["Map Pin Size"] = "Dimensione del pin"
	ns.L["The Map Pin Size"] = "La dimensione dei Pin della mappa"
	ns.L["Map Pin Alpha"] = "Mappa pin alfa"
	ns.L["Alpha Description"] = "La trasparenza alfa dei pin della mappa"
	ns.L["ShowCoordinates"] = "Mostra coordinate"
	ns.L["ShowCoordinatesDesc"] = "Visualizza le coordinate\124r nelle descrizioni "
		.."comandi sulla mappa del mondo e sulla minimappa" ..ns.colour.highlight .."\n(xx.xx,yy.yy)"
	ns.L["ShowContinents"] = "Mostra i pin sulle mappe dei continenti"
	ns.L["ShowContinentsDesc"] = "Potrebbero esserci MOLTI pin sulle mappe dei continenti"
	ns.L["ShowAzeroth"] = "Mostra i pin sulla mappa di Azeroth"
	ns.L["ShowAzerothDesc"] = "Ci saranno MOLTI pin sulla mappa di Azeroth"
	ns.L["ShowPins"] = "Mostra i pin"
	ns.L["ShowPinsDesc"] = "Se non selezionato, l'AddOn non farà nulla. Questo è l'interruttore principale di "
		.."accensione/spegnimento"
	ns.L["Textures"] = "Trame"
	ns.L["Pin Texture"] = "Struttura del perno"
	ns.L["SelectionTexture"] = "Seleziona una delle texture immersive e tematiche o una texture generica con un colore distintivo. "
		.."Le texture generiche sono ridimensionate per essere molto più piccole."
	ns.L["Left"] = "Sinistra"
	ns.L["Right"] = "Destra"
	ns.L["Notes"] = "Note"
	ns.L["MinimapMenu"] = "Una scorciatoia per aprire questo pannello è tramite il menu Minimappa AddOn, che si trova "
		.."immediatamente sotto l'icona del Calendario. Basta fare clic con il mouse\n\n"
	ns.L["ChatCommands"] = "Sono supportate anche le scorciatoie dei comandi di chat. "
	ns.L["ShowPanel"] = " - Mostra questo pannello\n"
	ns.L["TryMinimapMenu"] = "Prova il menu aggiuntivo della minimappa (sotto il calendario)"

	-- Beware: colours are masculine and feminine as adjectives
	ns.L["Black"] = "Nero"
	ns.L["Blue"] = "Blu"
	ns.L["Brown"] = "Marrone"
	ns.L["Cyan"] = "Ciano"
	ns.L["Dark Blue"] = "Blu scuro"
	ns.L["Gold"] = "Oro"
	ns.L["Red"] = "Rosso"
	ns.L["Green"] = "Verde"
	ns.L["Grey"] = "Grigio"
	ns.L["Light Blue"] = "Azzurro"
	ns.L["Light Green"] = "Verde chiaro"
	ns.L["Magenta"] = "Magenta"
	ns.L["Orange"] = "Arancione"
	ns.L["Original"] = "Originale"
	ns.L["Pink"] = "Rosa"
	ns.L["Purple"] = "Viola"
	ns.L["Teal"] = "Verde acqua"
	ns.L["Turquoise"] = "Turchese"	
	ns.L["White"] = "Bianca"
	ns.L["Yellow"] = "Giallo"

	ns.L["Ring"] = "Squillo"
	ns.L["Cross"] = "Attraverso"
	ns.L["Diamond"] = "Diamante"
	ns.L["Frost"] = "Gelo"
	ns.L["Cogwheel"] = "Ruota dentata"
	ns.L["Mana Orb"] = "Globo di Mana"
	ns.L["Phasing"] = "Sincronizzazione"
	ns.L["Raptor Egg"] = "Raptor Uovo"
	ns.L["Stars"] = "Stelle"
	ns.L["Screw"] = "Vite"

elseif ns.locale == "koKR" then
	ns.L["Character"] = "캐릭터"
	ns.L["Account"] = "계정"
	ns.L["Completed"] = "완료"
	ns.L["Not Completed"] = "미완료"
	ns.L["Try again"] = "다시 시도해 보세요. 서버가 응답하지 않습니다"
	ns.L["ZidormiWrongPhase"] = "지도가 해당 구역 기록에서 잘못된 시간을 보고 있습니다. 현재 해당 구역에 있다면 먼저 지도르미와 대화해야 합니다."

	ns.L["Options"] = "설정"
	ns.L["Map Pin Size"] = "지도 핀의 크기"
	ns.L["The Map Pin Size"] = "지도 핀의 크기"
	ns.L["Map Pin Alpha"] = "지도 핀의 알파"
	ns.L["Alpha Description"] = "지도 핀의 알파 투명도"
	ns.L["ShowCoordinates"] = "좌표 표시"
	ns.L["ShowCoordinatesDesc"] = "세계지도 및 미니지도의 도구 설명에 좌표를 표시합니다."
		..ns.colour.highlight .."\n(xx.xx,yy.yy)"
	ns.L["ShowContinents"] = "대륙 지도에 핀을 표시합니다"
	ns.L["ShowContinentsDesc"] = "대륙 지도에 핀이 아주 많을 수 있습니다"
	ns.L["ShowAzeroth"] = "아제로스 지도에 핀 표시"
	ns.L["ShowAzerothDesc"] = "아제로스 지도에도 핀이 아주 많을 것입니다"
	ns.L["ShowPins"] = "핀을 표시합니다"
	ns.L["ShowPinsDesc"] = "선택하지 않으면 애드온이 아무 작업도 수행하지 않습니다. 이 스위치는 마스터 켜기/끄기 스위치입니다."
	ns.L["Textures"] = "텍스처"
	ns.L["Pin Texture"] = "핀 텍스처"
	ns.L["SelectionTexture"] = "몰입감 넘치는 테마별 텍스처 또는 독특한 색상의 일반 텍스처 중 하나를 선택하세요. 일반 텍스처는 훨씬 작게 조정됩니다."
	ns.L["Left"] = "왼쪽"
	ns.L["Right"] = "오른쪽"
	ns.L["Notes"] = "메모"
	ns.L["MinimapMenu"] = "이 패널을 여는 바로가기는 달력 아이콘 바로 아래에 있는 미니맵 애드온 메뉴를 통해 가능합니다. 마우스를 클릭하세요\n\n"
	ns.L["ChatCommands"] = "채팅 명령 단축키도 지원됩니다. "
	ns.L["ShowPanel"] = " - 이 패널 표시\n"
	ns.L["TryMinimapMenu"] = "미니맵 추가 메뉴를 사용해 보세요(캘린더 아래)"

	ns.L["Black"] = "검은"
	ns.L["Blue"] = "푸른"
	ns.L["Brown"] = "갈색"
	ns.L["Cyan"] = "시안"
	ns.L["Dark Blue"] = "진한 파란색"
	ns.L["Gold"] = "금"
	ns.L["Green"] = "녹색"
	ns.L["Grey"] = "회색"
	ns.L["Light Blue"] = "하늘색"
	ns.L["Light Green"] = "라이트 그린"
	ns.L["Magenta"] = "마젠타"
	ns.L["Orange"] = "오렌지"
	ns.L["Original"] = "원래의"
	ns.L["Pink"] = "분홍색"
	ns.L["Purple"] = "보라색"
	ns.L["Red"] = "빨간"
	ns.L["Teal"] = "청록색"
	ns.L["Turquoise"] = "청록색"	
	ns.L["White"] = "화이트"
	ns.L["Yellow"] = "노랑"

	ns.L["Ring"] = "반지"
	ns.L["Cross"] = "십자가"
	ns.L["Diamond"] = "다이아몬드"
	ns.L["Frost"] = "냉기"
	ns.L["Cogwheel"] = "톱니 바퀴"
	ns.L["Mana Orb"] = "마나 보주"
	ns.L["Phasing"] = "동기화 중"
	ns.L["Raptor Egg"] = "랩터의 알"
	ns.L["Stars"] = "별"
	ns.L["Screw"] = "나사"

elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	ns.L["Character"] = "Personagem"
	ns.L["Account"] = "à Conta"
	ns.L["Completed"] = "Concluído"
	ns.L["Not Completed"] = "Não Concluído"
	ns.L["Try again"] = "Tente novamente. Servidor sem resposta"
	ns.L["ZidormiWrongPhase"] = "Seu mapa está na hora errada no histórico da zona. Se você estiver na zona, primeiro você deve "
		.."falar com Zidormi"

	ns.L["Options"] = "Opções"
	ns.L["Map Pin Size"] = "Tamanho do pino"
	ns.L["The Map Pin Size"] = "O tamanho dos pinos do mapa"
	ns.L["Map Pin Alpha"] = "Alfa dos pinos do mapa"
	ns.L["Alpha Description"] = "A transparência alfa dos pinos do mapa"
	ns.L["ShowCoordinates"] = "Mostrar coordenadas"
	ns.L["ShowCoordinatesDesc"] = "Exibir coordenadas\124r em dicas de ferramentas "
		.."no mapa mundial e no minimapa" ..ns.colour.highlight .."\n(xx.xx,yy.yy)"
	ns.L["ShowContinents"] = "Mostrar marcadores nos mapas continentais"
	ns.L["ShowContinentsDesc"] = "Pode haver MUITOS marcadores nos mapas continentais"
	ns.L["ShowAzeroth"] = "Mostrar pinos no mapa de Azeroth"
	ns.L["ShowAzerothDesc"] = "Haverá MUITOS marcadores no mapa de Azeroth"
	ns.L["ShowPins"] = "Mostrar os pinos"
	ns.L["ShowPinsDesc"] = "Se desmarcado, o Add-On não fará nada. Este é o interruptor principal liga/desliga"
	ns.L["Textures"] = "Texturas"
	ns.L["Pin Texture"] = "Textura de alfinete"
	ns.L["SelectionTexture"] = "Selecione uma das texturas temáticas imersivas ou talvez uma textura genérica com cores distintas. "
		.."As texturas genéricas são dimensionadas para serem muito menores."
	ns.L["Left"] = "Esquerda"
	ns.L["Right"] = "Direita"
	ns.L["Notes"] = "Notas"
	ns.L["MinimapMenu"] = "Um atalho para abrir este painel é através do menu Minimap AddOn, que fica imediatamente abaixo do "
		.."ícone do Calendário. Basta clicar com o mouse\n\n"
	ns.L["ChatCommands"] = "Atalhos de comando de bate-papo também são compatíveis. "
	ns.L["ShowPanel"] = " - Mostrar este painel\n"
	ns.L["TryMinimapMenu"] = "Experimente o menu AddOn do Minimapa (abaixo do Calendário)"

	ns.L["Black"] = "Preto"
	ns.L["Blue"] = "Azul"
	ns.L["Brown"] = "Marrom"
	ns.L["Cyan"] = "Ciano"
	ns.L["Dark Blue"] = "Azul-escuro"
	ns.L["Gold"] = "Ouro"
	ns.L["Green"] = "Verde"
	ns.L["Grey"] = "Cinzento"
	ns.L["Light Blue"] = "Azul-claro"
	ns.L["Light Green"] = "Verde Claro"
	ns.L["Magenta"] = "Magenta"
	ns.L["Orange"] = "Laranja"
	ns.L["Original"] = "Original"
	ns.L["Pink"] = "Rosa"
	ns.L["Purple"] = "Roxa"
	ns.L["Red"] = "Vermelho"
	ns.L["Teal"] = "Azul-petróleo"
	ns.L["Turquoise"] = "Turquesa"	
	ns.L["White"] = "Branco"
	ns.L["Yellow"] = "Amarelo"

	ns.L["Ring"] = "Anel"
	ns.L["Cross"] = "Cruz"
	ns.L["Diamond"] = "Diamante"
	ns.L["Frost"] = "Gélido"
	ns.L["Cogwheel"] = "Roda dentada"
	ns.L["Mana Orb"] = "Orbe de Mana"
	ns.L["Phasing"] = "Sincronização"
	ns.L["Raptor Egg"] = "Ovo de raptor"
	ns.L["Stars"] = "Estrelas"
	ns.L["Screw"] = "Parafuso"

elseif ns.locale == "ruRU" then
	ns.L["Character"] = "Персонажа"
	ns.L["Account"] = "Счет"
	ns.L["Completed"] = "Выполнено"
	ns.L["Not Completed"] = "Не Выполнено"
	ns.L["Try again"] = "Попробуйте еще раз. Сервер нет ответа"
	ns.L["ZidormiWrongPhase"] = "Ваша карта смотрит не на то время в истории зоны. Если вы сейчас находитесь в зоне, сначала вам "
		.."необходимо поговорить с Зидорми."

	ns.L["Options"] = "Параметры"
	ns.L["Map Pin Size"] = "Размер булавки"
	ns.L["The Map Pin Size"] = "Размер булавок на карте"
	ns.L["Map Pin Alpha"] = "Альфа булавок карты"
	ns.L["Alpha Description"] = "Альфа-прозрачность булавок карты"
	ns.L["ShowCoordinates"] = "Показать Координаты"
	ns.L["ShowCoordinatesDesc"] = "Отображает координаты\124r во всплывающих "
		.."подсказках на карте мира и мини-карте" ..ns.colour.highlight .."\n(xx.xx,yy.yy)"
	ns.L["ShowContinents"] = "Показывать метки на картах континентов."
	ns.L["ShowContinentsDesc"] = "На картах континентов может быть МНОГО меток."
	ns.L["ShowAzeroth"] = "Показывать метки на карте Азерота"
	ns.L["ShowAzerothDesc"] = "На карте Азерота будет МНОГО меток."
	ns.L["ShowPins"] = "Показывать метки"
	ns.L["ShowPinsDesc"] = "Если флажок не установлен, дополнение не будет выполнять никаких действий. Это главный "
		.."переключатель вкл/выкл"
	ns.L["Textures"] = "Текстуры"
	ns.L["Pin Texture"] = "Текстура булавки"
	ns.L["SelectionTexture"] = "Выберите одну из иммерсивных тематических текстур или, возможно, универсальную текстуру с "
		.."характерным цветом. Упрощённые текстуры значительно уменьшены в размере."
	ns.L["Left"] = "Налево"
	ns.L["Right"] = "Направо"
	ns.L["Notes"] = "Примечания"
	ns.L["MinimapMenu"] = "Ярлык для открытия этой панели — через меню надстройки мини-карты, которое находится сразу под значком "
		.."календаря. Просто щелкните мышью\n\n"
	ns.L["ChatCommands"] = "Также поддерживаются сочетания клавиш чата. "
	ns.L["ShowPanel"] = " - Показать эту панель\n"
	ns.L["TryMinimapMenu"] = "Попробуйте меню дополнений на мини-карте (под календарем)"

	ns.L["Black"] = "Черный"
	ns.L["Blue"] = "Синий"
	ns.L["Brown"] = "Коричневый"
	ns.L["Cyan"] = "Голубой"
	ns.L["Dark Blue"] = "Темно-синий"
	ns.L["Gold"] = "Золотой"
	ns.L["Green"] = "Зеленый"
	ns.L["Grey"] = "Серый"
	ns.L["Light Blue"] = "Светло-голубой"
	ns.L["Light Green"] = "Светло-зеленый"
	ns.L["Magenta"] = "Пурпурный"
	ns.L["Orange"] = "Оранжевый"
	ns.L["Original"] = "Оригинал"
	ns.L["Pink"] = "Розовый"
	ns.L["Purple"] = "Пурпурный"
	ns.L["Red"] = "Красный"
	ns.L["Teal"] = "Голубой бирюзовый"
	ns.L["Turquoise"] = "Бирюзовый"	
	ns.L["White"] = "белый"
	ns.L["Yellow"] = "Желтый"

	ns.L["Ring"] = "Звенеть"
	ns.L["Cross"] = "Крест"
	ns.L["Diamond"] = "Ромб"
	ns.L["Frost"] = "Лед"
	ns.L["Cogwheel"] = "Зубчатое колесо"
	ns.L["Mana Orb"] = "Cфера маны"
	ns.L["Phasing"] = "Синхронизация"
	ns.L["Raptor Egg"] = "Яйцо ящера"
	ns.L["Stars"] = "Звезды"
	ns.L["Screw"] = "Винт"

elseif ns.locale == "zhCN" then
	ns.L["Character"] = "角色"
	ns.L["Account"] = "账号"
	ns.L["Completed"] = "已完成"
	ns.L["Not Completed"] = "未完成"
	ns.L["Try later"] = "目前不可能。稍后再试"
	ns.L["Try again"] = "再试一次。服务器无响应"
	ns.L["ZidormiWrongPhase"] = "你的地图显示区域的时间线不对。如果你现在 在区域内，那么你必须去找希多尔米对话。"								

	ns.L["Options"] = "选项"
	ns.L["Map Pin Size"] = "地图图标大小"
	ns.L["The Map Pin Size"] = "地图图标大小"
	ns.L["Map Pin Alpha"] = "地图图标透明度"
	ns.L["Alpha Description"] = "地图图标透明度"
	ns.L["ShowCoordinates"] = "显示坐标"
	ns.L["ShowCoordinatesDesc"] = "在世界地图和小地图上的鼠标提示中显示坐标" ..ns.colour.highlight .."\n(xx.xx,yy.yy)"
	ns.L["ShowContinents"] = "在大陆地图上显示图钉。"
	ns.L["ShowContinentsDesc"] = "大陆地图上可能会有很多图钉。"
	ns.L["ShowAzeroth"] = "在艾泽拉斯地图上显示图钉"
	ns.L["ShowAzerothDesc"] = "艾泽拉斯地图上也会有很多图钉。"
	ns.L["ShowPins"] = "显示图钉"
	ns.L["ShowPinsDesc"] = "如果未选中，此插件将不执行任何操作。这是主开关"
	ns.L["Textures"] = "纹理"
	ns.L["Pin Texture"] = "针纹理"
	ns.L["SelectionTexture"] = "选择一种沉浸式主题纹理，或者选择一种颜色鲜明的通用纹理。通用纹理的尺寸会缩小很多"
	ns.L["Left"] = "左"
	ns.L["Right"] = "右"
	ns.L["Notes"] = "简介"
	ns.L["MinimapMenu"] = "打开该界面的快捷方式可以通过原生暴雪小地图插件"
		    .."菜单，它就在原生暴雪日历图标的下方。只需点击鼠标\n\n"
	ns.L["ChatCommands"] = "还支持输入命令打开方式，输入。 "
	ns.L["ShowPanel"] = "- 显示设置界面\n"
	ns.L["TryMinimapMenu"] = "也可以在暴雪原生插件收纳菜单打开（小地图日历图标下方）"

	ns.L["Black"] = "黑色"
	ns.L["Blue"] = "蓝色"
	ns.L["Brown"] = "棕色"
	ns.L["Cyan"] = "青色"
	ns.L["Dark Blue"] = "深蓝色"
	ns.L["Gold"] = "金色"
	ns.L["Green"] = "绿色"
	ns.L["Grey"] = "灰色"
	ns.L["Light Blue"] = "浅蓝色"
	ns.L["Light Green"] = "浅绿色"
	ns.L["Magenta"] = "洋红色"
	ns.L["Orange"] = "橙色"
	ns.L["Original"] = "原来的"
	ns.L["Pink"] = "粉色"
	ns.L["Purple"] = "紫色"
	ns.L["Red"] = "红色"
	ns.L["Teal"] = "青绿色"
	ns.L["Turquoise"] = "绿松石色"
	ns.L["White"] = "白色"
	ns.L["Yellow"] = "黄色"

	ns.L["Ring"] = "戒指"
	ns.L["Cross"] = "叉"
	ns.L["Diamond"] = "钻石"
	ns.L["Frost"] = "冰霜"
	ns.L["Cogwheel"] = "齿轮"
	ns.L["Mana Orb"] = "法力球"
	ns.L["Phasing"] = "同步"
	ns.L["Raptor Egg"] = "迅猛龙蛋"
	ns.L["Stars"] = "星星"
	ns.L["Screw"] = "拧"

elseif ns.locale == "zhTW" then
	ns.L["Character"] = "角色"
	ns.L["Account"] = "賬號"
	ns.L["Completed"] = "完成"
	ns.L["Not Completed"] = "未完成"
	ns.L["Try again"] = "再試一次。 伺服器無回應"
	ns.L["ZidormiWrongPhase"] = "你的地圖顯示區域的時間線不對。如果你現在 在區域內，那麼你必須去找希多爾米對話。"

	ns.L["Options"] = "選項"
	ns.L["ShowAzeroth"] = ""
	ns.L["Map Pin Size"] = "地圖圖示大小"
	ns.L["The Map Pin Size"] = "地圖圖示大小"
	ns.L["Map Pin Alpha"] = "地圖圖標透明度"
	ns.L["Alpha Description"] = "地圖圖標透明度"
	ns.L["ShowCoordinates"] = "顯示座標"
	ns.L["ShowCoordinatesDesc"] = "在世界地圖和小地圖上的滑鼠提示中顯示座標" ..ns.colour.highlight .."\n(xx.xx,yy.yy)"
	ns.L["ShowContinents"] = "在大陸地圖上顯示圖釘。"
	ns.L["ShowContinentsDesc"] = "大陸地圖上可能會有很多圖釘。"
	ns.L["ShowAzeroth"] = "在艾澤拉斯地圖上顯示圖釘"
	ns.L["ShowAzerothDesc"] = "艾澤拉斯地圖上也會有很多圖釘。"
	ns.L["ShowPins"] = "顯示圖釘"
	ns.L["ShowPinsDesc"] = "如果未選中，此外掛程式將不執行任何操作。這是主開關"
	ns.L["Textures"] = "紋理"
	ns.L["Pin Texture"] = "針紋理"
	ns.L["SelectionTexture"] = "選擇一種沉浸式主題紋理，或選擇一種色彩鮮明的通用紋理。通用紋理的尺寸會縮小很多"
	ns.L["Left"] = "左"
	ns.L["Right"] = "右"
	ns.L["Notes"] = "簡介"
	ns.L["MinimapMenu"] = "打開該介面的快捷方式可以通過原生暴雪小地圖外掛程式"
		    .." 功能表，它就在原生暴雪日曆圖示的下方。 只需點擊滑鼠\n\n"
	ns.L["ChatCommands"] = "還支援輸入命令打開方式，輸入。 "
	ns.L["ShowPanel"] = " - 顯示設置介面\n"
	ns.L["TryMinimapMenu"] = "也可以在暴雪原生外掛程式收納功能表打開（小地圖日曆圖示下方）"

	ns.L["Black"] = "黑色"
	ns.L["Blue"] = "藍色"
	ns.L["Brown"] = "棕色"
	ns.L["Cyan"] = "青色"
	ns.L["Dark Blue"] = "深藍色"
	ns.L["Gold"] = "金色"
	ns.L["Green"] = "綠色"
	ns.L["Grey"] = "灰色"
	ns.L["Light Blue"] = "淺藍色"
	ns.L["Light Green"] = "淺綠色"
	ns.L["Magenta"] = "洋紅色"
	ns.L["Orange"] = "橘色"
	ns.L["Original"] = "原來的"
	ns.L["Pink"] = "粉紅色的"
	ns.L["Purple"] = "紫色"
	ns.L["Red"] = "紅色"
	ns.L["Teal"] = "青色"
	ns.L["Turquoise"] = "綠松石色"
	ns.L["White"] = "白色"
	ns.L["Yellow"] = "黃色"

	ns.L["Ring"] = "戒指"
	ns.L["Cross"] = "叉"
	ns.L["Diamond"] = "钻石"
	ns.L["Frost"] = "霜"
	ns.L["Cogwheel"] = "齒輪"
	ns.L["Mana Orb"] = "法力球"
	ns.L["Phasing"] = "同步"
	ns.L["Raptor Egg"] = "迅猛龍蛋"
	ns.L["Stars"] = "星星"
	ns.L["Screw"] = "擰"

else
	ns.L["Try again"] = "Try again. Server no response"
	ns.L["ZidormiWrongPhase"] = "Your map is looking at the wrong time in the zone's history. If you are presently in the zone "
		.."then you must first speak to Zidormi"

	ns.L["Alpha Description"] = "The alpha transparency of the map pins"
	ns.L["ShowCoordinates"] = "Show Coordinates"
	ns.L["ShowCoordinatesDesc"] = "Display coordinates in tooltips on the world map and the mini map"
		 ..ns.colour.highlight .."\n(xx.xx,yy.yy)"
	ns.L["ShowContinents"] = "Show pins on the continent maps"
	ns.L["ShowContinentsDesc"] = "There might be a LOT of pins on the continent maps"
	ns.L["ShowAzeroth"] = "Show pins on the Azeroth map"
	ns.L["ShowAzerothDesc"] = "There will be a LOT of pins on the Azeroth map"
	ns.L["ShowPins"] = "Show the pins"
	ns.L["ShowPinsDesc"] = "If unchecked, the AddOn will do nothing. This is the master on/off switch"
	ns.L["SelectionTexture"] = "Select one of the immersive, thematic textures or perhaps a distinctively coloured generic "
		.."texture. The generic textures are scaled to be much smaller"
	ns.L["MinimapMenu"] = "A shortcut to open this panel is via the Minimap AddOn menu, which is immediately below the Calendar "
		.."icon. Just click your mouse\n\n"
	ns.L["ChatCommands"] = "Chat command shortcuts are also supported. "
	ns.L["ShowPanel"] = " - Show this panel\n"
	ns.L["TryMinimapMenu"] = "Try the Minimap AddOn Menu (below the Calendar)"

	ns.L["Grey"] = ( ( ns.locale == "enUS" ) and "Gray" or "Grey" )
end