--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.
    
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("ArmoryGuildBank", "deDE");
if ( not L ) then 
    return;
end

L["ARMORY_CMD_DELETE_GUILD"] = "gb"
L["ARMORY_CMD_DELETE_GUILD_MSG"] = "Die Gildenbank von \"%1$s\" auf Realm \"%2$s\" wurde aus der Datenbank entfernt."
L["ARMORY_CMD_DELETE_GUILD_NOT_FOUND"] = "Die Gildenbank von \"%1$s\" auf Realm \"%2$s\" konnte nicht gefunden werden."
L["ARMORY_CMD_DELETE_GUILD_PARAMS_TEXT"] = "[Gilde] [Realm]"
L["ARMORY_CMD_DELETE_GUILD_TEXT"] = "Lösche Gildenbankeintrag"
L["ARMORY_CMD_GUILDBANK"] = "gildenbank|gb"
L["ARMORY_CMD_GUILDBANK_MENUTEXT"] = "Gildenbank umschalten"
L["ARMORY_CMD_GUILDBANK_TEXT"] = "Schaltet die Anzeige der Gildenbank an oder aus" -- Needs review
L["ARMORY_CMD_SET_AGBCOUNTALL_MENUTEXT"] = "Alle Realms in die Aufzählung einbeziehen"
L["ARMORY_CMD_SET_AGBCOUNTALL_TEXT"] = "Alle Realms in der Gegenstandszählung berücksichtigen" -- Needs review
L["ARMORY_CMD_SET_AGBCOUNTALL_TOOLTIP"] = [=[Aktiv: Gildenbanksummen werden für alle Realms angezeigt
Inaktiv: Gildenbanksummen werden nur für den aktuellen Realm angezeigt]=]
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_MENUTEXT"] = "Nur die aktuelle Gilde einbeziehen" -- Needs review
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TEXT"] = "Anzahl der Gegenstände nur für die aktuelle Gilde einbeziehen" -- Needs review
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TOOLTIP"] = "Aktiv: Anzahl der Gegenstände in der Gildenbank wird nur für die Gilde des aktuellen und ausgewählten Charakters angezeigt." -- Needs review
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_MENUTEXT"] = "Alle Fraktionen einbeziehen"
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TEXT"] = "alle Fraktionen bei der Zählung berücksichtigen" -- Needs review
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TOOLTIP"] = [=[Aktiv: Gildenbankanzahl wird für alle Fraktionen angezeigt
Inaktiv: nur die eigene Fraktion wird berücksichtigt (Allianz oder Horde)]=]
L["ARMORY_CMD_SET_AGBFIND_MENUTEXT"] = "In \"/ar suche Gegenstand|alle\" aufnehmen" -- Needs review
L["ARMORY_CMD_SET_AGBFIND_TEXT"] = "In der Suche nach Gegenständen einbeziehen" -- Needs review
L["ARMORY_CMD_SET_AGBFIND_TOOLTIP"] = [=[Aktiv: sucht in Gildenbanken
Inaktiv: sucht nicht in Gildenbanken]=]
L["ARMORY_CMD_SET_AGBINTEGRATE_MENUTEXT"] = "Ins Inventar integrieren"
L["ARMORY_CMD_SET_AGBINTEGRATE_TEXT"] = "Gildenbank im Armoryinventar anzeigen" -- Needs review
L["ARMORY_CMD_SET_AGBINTEGRATE_TOOLTIP"] = [=[Aktiv: Gildenbank wird als zusätzlicher Tab dem Inventar hinzugefügt
Inaktiv: keine Gildenbankanzeige im Inventar]=]
L["ARMORY_CMD_SET_AGBITEMCOUNT_MENUTEXT"] = "Anzeige im Anzahltooltip"
L["ARMORY_CMD_SET_AGBITEMCOUNT_TEXT"] = "Anzahl auf der Gildenbank im Tooltip anzeigen" -- Needs review
L["ARMORY_CMD_SET_AGBITEMCOUNT_TOOLTIP"] = [=[Aktiv: Gildenbankgesamtanzahl wird im Tooltip angezeigt
Inaktiv: Gildenbankgesamtanzahl wird nicht im Tooltip angezeigt]=]
L["ARMORY_CMD_SET_AGBUNICOLOR_MENUTEXT"] = "Armory Farben verwenden"
L["ARMORY_CMD_SET_AGBUNICOLOR_TEXT"] = "Für Zahlen in Tooltips dieselbe Farbe wie in Armory verwenden" -- Needs review
L["ARMORY_CMD_SET_AGBUNICOLOR_TOOLTIP"] = [=[Aktiv: alle Gegenstandsanzahlen verwenden die selbe Farbe.
Inaktiv: bunter]=]
L["ARMORY_GUILDBANK_ABORTING"] = "Abbruch ..."
L["ARMORY_GUILDBANK_NO_DATA"] = "Es stehen keine Gildenbankdaten zur Verfügung."
L["ARMORY_GUILDBANK_NO_TABS"] = "Besuche eine Bank und öffne alle Bankfächer..." -- Needs review
L["ARMORY_GUILDBANK_SUBTEXT"] = "Diese Optionen erlauben dir das Verhalten der Armory Gildenbank zu verändern."
L["ARMORY_GUILDBANK_TITLE"] = "Gildenbank"
L["BINDING_NAME_ARMORYGUILDBANK_TOGGLE"] = "Gildenbank ein-/ausschalten" -- Needs review

