--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.
    
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("ArmoryGuildBank", "enUS", true);

L["ARMORY_CMD_DELETE_GUILD"] = "gb"
L["ARMORY_CMD_DELETE_GUILD_MSG"] = "Guild bank of '%1$s' in realm '%2$s' has been removed."
L["ARMORY_CMD_DELETE_GUILD_NOT_FOUND"] = "Guild bank of '%1$s' in realm '%2$s' not found!"
L["ARMORY_CMD_DELETE_GUILD_PARAMS_TEXT"] = "[guild] [realm]"
L["ARMORY_CMD_DELETE_GUILD_TEXT"] = "delete guild bank"
L["ARMORY_CMD_GUILDBANK"] = "guildbank|gb"
L["ARMORY_CMD_GUILDBANK_MENUTEXT"] = "Toggle Guild Bank"
L["ARMORY_CMD_GUILDBANK_TEXT"] = "toggles the Guild Bank on or off"
L["ARMORY_CMD_SET_AGBCOUNTALL_MENUTEXT"] = "Include all realms in counts"
L["ARMORY_CMD_SET_AGBCOUNTALL_TEXT"] = "include item counts for all realms"
L["ARMORY_CMD_SET_AGBCOUNTALL_TOOLTIP"] = "If enabled, Guild Bank totals are shown for all realms; otherwise only for the current realm."
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_MENUTEXT"] = "Include all factions in counts"
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TEXT"] = "include item counts for all factions"
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TOOLTIP"] = "If enabled, Guild Bank totals are shown for all factions; otherwise only for the current faction."
L["ARMORY_CMD_SET_AGBFIND_MENUTEXT"] = "Include in '/ar find item|all'"
L["ARMORY_CMD_SET_AGBFIND_TEXT"] = "include when searching for items"
L["ARMORY_CMD_SET_AGBFIND_TOOLTIP"] = "If enabled, the Guild Bank will also be searched when performing a database lookup with '/ar find item|all'."
L["ARMORY_CMD_SET_AGBINTEGRATE_MENUTEXT"] = "Integrate with inventory"
L["ARMORY_CMD_SET_AGBINTEGRATE_TEXT"] = "integrate with Armory's inventory"
L["ARMORY_CMD_SET_AGBINTEGRATE_TOOLTIP"] = "If enabled, the selected character's Guild Bank will be added as an extra tab in the inventory sheet."
L["ARMORY_CMD_SET_AGBITEMCOUNT_MENUTEXT"] = "Show tooltip item counts"
L["ARMORY_CMD_SET_AGBITEMCOUNT_TEXT"] = "show item counts in tooltips"
L["ARMORY_CMD_SET_AGBITEMCOUNT_TOOLTIP"] = "If enabled, item tooltips will show Guild Bank totals."
L["ARMORY_CMD_SET_AGBUNICOLOR_MENUTEXT"] = "Use Armory's color"
L["ARMORY_CMD_SET_AGBUNICOLOR_TEXT"] = "link to Armory's item count color"
L["ARMORY_CMD_SET_AGBUNICOLOR_TOOLTIP"] = "If enabled, the same color will be used for all item counts shown in tooltips."
L["ARMORY_GUILDBANK_ABORTING"] = "Aborting..."
L["ARMORY_GUILDBANK_NO_DATA"] = "There is no Guild Bank data available."
L["ARMORY_GUILDBANK_NO_TABS"] = "Please visit the bank and open all tabs..."
L["ARMORY_GUILDBANK_SUBTEXT"] = "These options allow you to modify Armory Guild Bank's behavior."
L["ARMORY_GUILDBANK_TITLE"] = "Guild Bank"
L["BINDING_NAME_ARMORYGUILDBANK_TOGGLE"] = "Toggle Armory Guild Bank"

