--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.
    
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("ArmoryGuildBank", "esES");
if ( not L ) then 
    return;
end

L["ARMORY_CMD_DELETE_GUILD"] = "bh"
L["ARMORY_CMD_DELETE_GUILD_MSG"] = "El banco de hermandad de '%1$s' en el reino '%2$s' ha sido borrado."
L["ARMORY_CMD_DELETE_GUILD_NOT_FOUND"] = "¡Banco de hermandad de '%1$s' en el reino '%2$s' no encontrado!"
L["ARMORY_CMD_DELETE_GUILD_PARAMS_TEXT"] = "[hermandad] [reino]"
L["ARMORY_CMD_DELETE_GUILD_TEXT"] = "borrar banco de hermandad"
L["ARMORY_CMD_GUILDBANK"] = "bancohermandad|bh"
L["ARMORY_CMD_GUILDBANK_MENUTEXT"] = "Abrir/cerrar Banco Hermandad"
L["ARMORY_CMD_GUILDBANK_TEXT"] = "Abre o cierra el banco de hermandad"
L["ARMORY_CMD_SET_AGBCOUNTALL_MENUTEXT"] = "Incluir todos los reinos en los conteos"
L["ARMORY_CMD_SET_AGBCOUNTALL_TEXT"] = "incluir conteo de objetos para todos los reinos"
L["ARMORY_CMD_SET_AGBCOUNTALL_TOOLTIP"] = "Si se activa, los totales de Banco de Hermandad son mostrados para todos los reinos; de lo contrario, solo se muestran los del reino actual."
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_MENUTEXT"] = "Incluir hermandad actual solamente"
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TEXT"] = "incluir conteos de objetos para la hermandad actual solamente"
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TOOLTIP"] = "Si se activa, los totales de Banco de Hermandad se muestran únicamente para la hermandad del personaje actual."
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_MENUTEXT"] = "Incluir todas las facciones en los conteos"
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TEXT"] = "incluir conteos para todas las facciones"
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TOOLTIP"] = "Si se activa, los totales de Banco de Hermandad se mostrarán para todas las facciones; de lo contrario, solo para la facción actual."
L["ARMORY_CMD_SET_AGBFIND_MENUTEXT"] = "Incluir en '/ar encontrar objeto|todo'"
L["ARMORY_CMD_SET_AGBFIND_TEXT"] = "incluir cuando se están buscando objetos"
L["ARMORY_CMD_SET_AGBFIND_TOOLTIP"] = "Si se activa, el Banco de Hermandad será incluido en la búsqueda cuando se esté realizando una búsqueda en la base de datos con '/ar encontrar objeto|todo'"
L["ARMORY_CMD_SET_AGBINTEGRATE_MENUTEXT"] = "Integrar con el inventario"
L["ARMORY_CMD_SET_AGBINTEGRATE_TEXT"] = "integrar con el inventario de Armory"
L["ARMORY_CMD_SET_AGBINTEGRATE_TOOLTIP"] = "Si se activa, el Banco de Hermandad del personaje seleccionado será añadido como una pestaña extra a la hoja de inventario."
L["ARMORY_CMD_SET_AGBITEMCOUNT_MENUTEXT"] = "Mostrar descripciones emergentes de conteos de objetos"
L["ARMORY_CMD_SET_AGBITEMCOUNT_TEXT"] = "mostrar conteos de objetos en las descripciones emergentes"
L["ARMORY_CMD_SET_AGBITEMCOUNT_TOOLTIP"] = "Si se activa, las descripciones emergentes de objetos mostrarán los totales de Banco de Hermandad."
L["ARMORY_CMD_SET_AGBUNICOLOR_MENUTEXT"] = "Usar el color de Armory"
L["ARMORY_CMD_SET_AGBUNICOLOR_TEXT"] = "vincular al color de conteo de objetos de Armory"
L["ARMORY_CMD_SET_AGBUNICOLOR_TOOLTIP"] = "Si se activa, se usará el mismo color para todos los conteos de objetos que se muestran en las descripciones emergentes."
L["ARMORY_GUILDBANK_ABORTING"] = "Abortando..."
L["ARMORY_GUILDBANK_NO_DATA"] = "No existen datos de Banco de Hermandad disponibles."
L["ARMORY_GUILDBANK_NO_TABS"] = "Por favor, visite el banco y abra todas las pestañas..."
L["ARMORY_GUILDBANK_SUBTEXT"] = "Estas opciones te permiten modificar el comportamiento del Banco de Hermnadad de Amory."
L["ARMORY_GUILDBANK_TITLE"] = "Banco de Hermandad"
L["BINDING_NAME_ARMORYGUILDBANK_TOGGLE"] = "Abrir/cerrar Banco de hermandad de Armory"

