--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.
    
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("ArmoryGuildBank", "frFR");
if ( not L ) then 
    return;
end

L["ARMORY_CMD_DELETE_GUILD"] = "gb"
L["ARMORY_CMD_DELETE_GUILD_MSG"] = "La banque de guilde de \"'%1$s\" du royaume de \"%2$s\" a été supprimée."
L["ARMORY_CMD_DELETE_GUILD_NOT_FOUND"] = "La banque de guilde de \"'%1$s\" du royaume de \"%2$s\" est introuvable !"
L["ARMORY_CMD_DELETE_GUILD_PARAMS_TEXT"] = "[guilde] [royaume]"
L["ARMORY_CMD_DELETE_GUILD_TEXT"] = "Efface les données de la banque de guilde"
L["ARMORY_CMD_GUILDBANK"] = "guildbank|gb"
L["ARMORY_CMD_GUILDBANK_MENUTEXT"] = "Affiche Guild Bank"
L["ARMORY_CMD_GUILDBANK_TEXT"] = "Interrupteur pour Guild Bank"
L["ARMORY_CMD_SET_AGBCOUNTALL_MENUTEXT"] = "Inclure tous les royaumes dans les décomptes"
L["ARMORY_CMD_SET_AGBCOUNTALL_TEXT"] = "Inclut tous les royaumes dans le décompte des objets"
L["ARMORY_CMD_SET_AGBCOUNTALL_TOOLTIP"] = "Si activé, les totaux de Guild Bank comprennent tous les royaumes, sinon seulement ceux du royaume courant."
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_MENUTEXT"] = "Inclure toutes les factions dans les décomptes"
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TEXT"] = "inclure les décomptes pour toutes les factions"
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TOOLTIP"] = "Si activé, les totaux de la banque de guilde incluront toutes les factions ; sinon seulement la faction courante."
L["ARMORY_CMD_SET_AGBFIND_MENUTEXT"] = "Inclure dans la commande \"/ar find item|all\""
L["ARMORY_CMD_SET_AGBFIND_TEXT"] = "Inclut Guild Bank dans les recherches d'objets"
L["ARMORY_CMD_SET_AGBFIND_TOOLTIP"] = "Si activé, Guild Bank sera inclus lors des recherches dans la base de données effectuées avec la commande \"/ar find item|all\"."
L["ARMORY_CMD_SET_AGBINTEGRATE_MENUTEXT"] = "Inclure dans l'inventaire"
L["ARMORY_CMD_SET_AGBINTEGRATE_TEXT"] = "S'intègre avec l'inventaire d'Armory"
L["ARMORY_CMD_SET_AGBINTEGRATE_TOOLTIP"] = "Si activé, la Guild Bank du personnage sélectionné sera ajoutée à sa page d'inventaire via un onglet supplémentaire."
L["ARMORY_CMD_SET_AGBITEMCOUNT_MENUTEXT"] = "Afficher le décompte des objets dans l'infobulle"
L["ARMORY_CMD_SET_AGBITEMCOUNT_TEXT"] = "Afficher le décompte des objets dans l'infobulle"
L["ARMORY_CMD_SET_AGBITEMCOUNT_TOOLTIP"] = "Si activé, l'infobulle des objets affichera les décomptes de Guild Bank."
L["ARMORY_CMD_SET_AGBUNICOLOR_MENUTEXT"] = "Utiliser les couleurs d'Armory"
L["ARMORY_CMD_SET_AGBUNICOLOR_TEXT"] = "Utiliser la couleur d'Armory pour les décomptes d'objets"
L["ARMORY_CMD_SET_AGBUNICOLOR_TOOLTIP"] = "Si activé, la même couleur sera utilisée pour les décomptes dans les infobulles des objets"
L["ARMORY_GUILDBANK_ABORTING"] = "Annulation..."
L["ARMORY_GUILDBANK_NO_DATA"] = "Aucune donnée Guild Bank disponible."
L["ARMORY_GUILDBANK_NO_TABS"] = "Allez à la banque et ouvrez tous les onglets..."
L["ARMORY_GUILDBANK_SUBTEXT"] = "Ces options permettent de modifier le fonctionnement de Armory Guild Bank"
L["ARMORY_GUILDBANK_TITLE"] = "Banque de guilde"
L["BINDING_NAME_ARMORYGUILDBANK_TOGGLE"] = "Armory Guild Bank"

