--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.

    Original translators: 한글화 TalksWind (PaperTiger), 덫붙임 Hellguard
    
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("ArmoryGuildBank", "koKR");
if ( not L ) then 
    return;
end

L["ARMORY_CMD_DELETE_GUILD"] = "길은"
L["ARMORY_CMD_DELETE_GUILD_MSG"] = "'%2$s'서버의 '%1$s'길드은행 정보가 삭제되었습니다."
L["ARMORY_CMD_DELETE_GUILD_NOT_FOUND"] = "'%2$s'서버의 '%1$s'길드은행 정보를 찾을 수 없습니다!"
L["ARMORY_CMD_DELETE_GUILD_PARAMS_TEXT"] = "[guild] [realm]"
L["ARMORY_CMD_DELETE_GUILD_TEXT"] = "길드은행 삭제"
L["ARMORY_CMD_GUILDBANK"] = "길드은행|길은"
L["ARMORY_CMD_GUILDBANK_MENUTEXT"] = "길드은행 전환"
L["ARMORY_CMD_GUILDBANK_TEXT"] = "길드은행 켜고 끄기를 전환 합니다."
L["ARMORY_CMD_SET_AGBCOUNTALL_MENUTEXT"] = "아이템 수량에 모든 서버의 것을 포함"
L["ARMORY_CMD_SET_AGBCOUNTALL_TEXT"] = "모든 서버내의 아이템수량 포함"
L["ARMORY_CMD_SET_AGBCOUNTALL_TOOLTIP"] = "활성화 하면, 길드은행의 총합은 모든 서버의 것이 보여지게 됩니다. 그렇지 않다면 단지 현재의 서버의 것만 보여지게 됩니다."
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_MENUTEXT"] = "Include current guild only" -- Requires localization
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TEXT"] = "include item counts for the current guild only" -- Requires localization
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TOOLTIP"] = "If enabled, Guild Bank totals are shown for the current and selected character's guild only." -- Requires localization
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_MENUTEXT"] = "모든 진영의 아이템 갯수 포함"
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TEXT"] = "모든 진영에 대해 아이템 갯수를 포함시킵니다."
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TOOLTIP"] = "활성화 하면, 길드은행의 아이템 총합은 모든 진영의 것까지 보여줍니다; 그렇지 않다면 현재 진영의 케릭터에 해당하는 길드은행의 아이템 갯수만 표시할 것 입니다."
L["ARMORY_CMD_SET_AGBFIND_MENUTEXT"] = "'/ar find item|all'에 포함하기'"
L["ARMORY_CMD_SET_AGBFIND_TEXT"] = "아이템에 대해 검색시 포함하기"
L["ARMORY_CMD_SET_AGBFIND_TOOLTIP"] = "활성화하면, 아모리 길드은행은 명령어 '/ar find item|all'로 데이타베이스 살펴보기를 수행할 경우에 검색하게 됩니다."
L["ARMORY_CMD_SET_AGBINTEGRATE_MENUTEXT"] = "인벤토리에 병합"
L["ARMORY_CMD_SET_AGBINTEGRATE_TEXT"] = "Armory 인벤토리 창에 병합"
L["ARMORY_CMD_SET_AGBINTEGRATE_TOOLTIP"] = "활성화하면, 선택된 케릭터의 길드은행 인벤토리 창에 별도의 탭이 추가될 것 입니다."
L["ARMORY_CMD_SET_AGBITEMCOUNT_MENUTEXT"] = "툴팁에 아이템 갯수 보이기"
L["ARMORY_CMD_SET_AGBITEMCOUNT_TEXT"] = "툴팁에 아이템 갯수를 보여줍니다."
L["ARMORY_CMD_SET_AGBITEMCOUNT_TOOLTIP"] = "활성화하면, 아이템 툴팁은 길드 은행을 통틀어 보여주게 됩니다."
L["ARMORY_CMD_SET_AGBUNICOLOR_MENUTEXT"] = "Armory의 색상 사용"
L["ARMORY_CMD_SET_AGBUNICOLOR_TEXT"] = "Armory가 링크한 아이템 수량 색상"
L["ARMORY_CMD_SET_AGBUNICOLOR_TOOLTIP"] = "활성화 하면, 툴팁에서 보여지는 모든 아이템 수량을 위해 동일한 색상을 사용하게 됩니다."
L["ARMORY_GUILDBANK_ABORTING"] = "중지합니다..."
L["ARMORY_GUILDBANK_NO_DATA"] = "확인 가능한 길드은행에 대한 자료가 없습니다."
L["ARMORY_GUILDBANK_NO_TABS"] = "은행에 방문하셔서 모든 탭을 여시기 바랍니다.."
L["ARMORY_GUILDBANK_SUBTEXT"] = "|cFF00FFFF이 옵션들은 아모리길드뱅크의 동작을 변경할 수 있도록 합니다 ."
L["ARMORY_GUILDBANK_TITLE"] = "길드은행"
L["BINDING_NAME_ARMORYGUILDBANK_TOGGLE"] = "아모리 길드은행 전환"

