if GetLocale() == "ptBR" then
qcLocalize = {
	ABYSSALDEPTHS = "Profundezas Abissais", -- Needs review
	AHNKAHETTHEOLDKINGDOM = "Ahn'kahet: O Velho Reino", -- Needs review
	AHNQIRAJ = "Ahn'Qiraj", -- Needs review
	AHNQIRAJTHEFALLENKINGDOM = "Ahn'Qiraj: O Reino Derrotado", -- Needs review
	ALCHEMY = "Alquimia", -- Needs review
	ALTERACVALLEY = "Vale Alterac", -- Needs review
	ARATHIBASIN = "Bacia Arathi", -- Needs review
	ARATHIHIGHLANDS = "Planalto Arathi", -- Needs review
	ARCHAEOLOGY = "Arqueologia", -- Needs review
	ASHENVALE = "Vale Gris", -- Needs review
	AUCHENAICRYPTS = "Catacumbas Auchenai", -- Needs review
	AUCHINDOUN = "Auchenai", -- Needs review
	AZJOLNERUB = "Azjol-Nerub", -- Needs review
	AZSHARA = "Azshara", -- Needs review
	AZUREMYSTISLE = "Ilha Névoa Lazúli", -- Needs review
	BADLANDS = "Ermos", -- Needs review
	BARADINHOLD = "Baradin Hold", -- Requires localization
	BATTLEGROUNDS = "Battlegrounds", -- Requires localization
	BATTLEPETS = "Battle Pets", -- Requires localization
	BLACKFATHOMDEEPS = "Blackfathom Deeps", -- Requires localization
	BLACKROCKCAVERNS = "Blackrock Caverns", -- Requires localization
	BLACKROCKDEPTHS = "Blackrock Depths", -- Requires localization
	BLACKROCKSPIRE = "Blackrock Spire", -- Requires localization
	BLACKSMITHING = "Blacksmithing", -- Requires localization
	BLACKTEMPLE = "Black Temple", -- Requires localization
	BLACKWINGDESCENT = "Blackwing Descent", -- Requires localization
	BLACKWINGLAIR = "Blackwing Lair", -- Requires localization
	BLADESEDGEMOUNTAINS = "Montanhas da Lâmina Afiada", -- Needs review
	BLASTEDLANDS = "Barreira do Inferno", -- Needs review
	BLOODMYSTISLE = "Ilha Névoa Rubra", -- Needs review
	BOREANTUNDRA = "Tundra Boreana", -- Needs review
	BREWFEST = "Brewfest", -- Requires localization
	BURNINGSTEPPES = "Estepes Ardentes", -- Needs review
	CAVERNSOFTIME = "Caverns of Time", -- Requires localization
	CHILDRENSWEEK = "Children's Week", -- Requires localization
	CLASSES = "Classes", -- Requires localization
	CLASSQUESTS = "Class Quests", -- Requires localization
	CLEARUPDATECACHE = "Clear Update Cache...", -- Requires localization
	COILFANGRESERVOIR = "Coilfang Reservoir", -- Requires localization
	COMBINEDMAPANDQUESTFILTERS = "Combined Map & Quest List Filters", -- Requires localization
	CONFIGSUBTITLE = "These options allow you to change the way that Quest Completist handles and filters its data.", -- Requires localization
	CONFIGTITLE = "Quest Completist - Configuration", -- Requires localization
	CONTINENTS = "Continents", -- Requires localization
	COOKING = "Cooking", -- Requires localization
	CRYSTALSONGFOREST = "Crystalsong Forest", -- Needs review
	DALARAN = "Dalaran", -- Needs review
	DARKMOONFAIRE = "Darkmoon Faire", -- Requires localization
	DARKSHORE = "Costa Negra", -- Needs review
	DARNASSUS = "Darnassus", -- Needs review
	DAYOFTHEDEAD = "Day of the Dead", -- Requires localization
	DEADWINDPASS = "Trilha do Vento Morto", -- Needs review
	DEATHKNIGHT = "Death Knight", -- Requires localization
	DEEPHOLM = "Geodomo", -- Needs review
	DEEPRUNTRAM = "Metrô Correfundo", -- Needs review
	DESOLACE = "Desolação", -- Needs review
	DIREMAUL = "Dire Maul", -- Requires localization
	DRAGONBLIGHT = "Ermo das Serpes", -- Needs review
	DRAGONSOUL = "Dragon Soul", -- Requires localization
	DRAKTHARONKEEP = "Drak'Tharon Keep", -- Requires localization
	DREADWASTES = "Dread Wastes", -- Requires localization
	DRUID = "Druid", -- Requires localization
	DUNGEONSANDRAIDS = "Dungeons & Raids", -- Requires localization
	DUNMOROGH = "Dun Morogh", -- Needs review
	DUROTAR = "Durotar", -- Needs review
	DUSKWOOD = "Floresta do Crepúsculo", -- Needs review
	DUSTWALLOWMARSH = "Pântano Vadeoso", -- Needs review
	EASTERNKINGDOMS = "Reinos do Leste", -- Needs review
	EASTERNPLAGUELANDS = "Terras Pestilentas Orientais", -- Needs review
	ELEMENTALBONDS = "Elemental Bonds", -- Requires localization
	ELWYNNFOREST = "Floresta de Elwynn", -- Needs review
	ENCHANTING = "Enchanting", -- Requires localization
	ENDTIME = "End Time", -- Requires localization
	ENGINEERING = "Engineering", -- Requires localization
	EVERSONGWOODS = "Floresta do Canto Eterno", -- Needs review
	EYEOFTHESTORM = "Eye of the Storm", -- Requires localization
	FELWOOD = "Selva Maleva", -- Needs review
	FERALAS = "Feralas", -- Needs review
	FIRELANDS = "Firelands", -- Requires localization
	FIRELANDSINVASION = "Firelands Invasion", -- Requires localization
	FIRSTAID = "First Aid", -- Requires localization
	FISHING = "Fishing", -- Requires localization
	GHOSTLANDS = "Terra Fantasma", -- Needs review
	GILNEAS = "Gilneas", -- Requires localization
	GILNEASCITY = "Gilneas City", -- Requires localization
	GNOMEREGAN = "Gnomeregan", -- Requires localization
	GRIMBATOL = "Grim Batol", -- Requires localization
	GRIZZLYHILLS = "Serra Gris", -- Needs review
	GRUULSLAIR = "Gruul's Lair", -- Requires localization
	GUNDRAK = "Gundrak", -- Requires localization
	HALLOWSEND = "Hallow's End", -- Requires localization
	HALLSOFLIGHTNING = "Halls of Lightning", -- Requires localization
	HALLSOFORIGINATION = "Halls of Origination", -- Requires localization
	HALLSOFREFLECTION = "Halls of Reflection", -- Requires localization
	HALLSOFSTONE = "Halls of Stone", -- Requires localization
	HARVESTFESTIVAL = "Harvest Festival", -- Requires localization
	HELLFIRECITADEL = "Hellfire Citadel", -- Requires localization
	HELLFIREPENINSULA = "Península Fogo do Inferno", -- Needs review
	HELLFIRERAMPARTS = "Hellfire Ramparts", -- Requires localization
	HERBALISM = "Herbalism", -- Requires localization
	HIDECOMPLETEDQUESTS = "Hide Completed Quests", -- Requires localization
	HIDEINPROGRESSQUESTS = "Hide In-Progress Quests", -- Requires localization
	HIDELOWLEVELQUESTS = "Hide Low Level Quests", -- Requires localization
	HIDENONACTIVESEASONALQUESTS = "Hide Non-Active Seasonal Quests", -- Requires localization
	HIDEOTHERFACTIONQUESTS = "Hide Other Faction Quests", -- Requires localization
	HIDEOTHERPROFESSIONQUESTS = "Hide Other Profession Quests", -- Requires localization
	HIDEOTHERRACEANDCLASSQUESTS = "Hide Other Race & Class Quests", -- Requires localization
	HILLSBRADFOOTHILLS = "Contraforte de Eira dos Montes", -- Needs review
	HOUROFTWILIGHT = "Hour of Twilight", -- Requires localization
	HOWLINGFJORD = "Fiorde Uivante", -- Needs review
	HROTHGARSLANDING = "Porto de Hrothgar", -- Needs review
	HUNTER = "Hunter", -- Requires localization
	HYJALSUMMIT = "Hyjal Summit", -- Requires localization
	ICECROWN = "Coroa de Gelo", -- Needs review
	ICECROWNCITADEL = "Icecrown Citadel", -- Requires localization
	INSCRIPTION = "Inscription", -- Requires localization
	IRONFORGE = "Altaforja", -- Needs review
	ISLEOFCONQUEST = "Isle of Conquest", -- Requires localization
	ISLEOFQUELDANAS = "Ilha de Quel'Danas", -- Needs review
	JEWELCRAFTING = "Jewelcrafting", -- Requires localization
	KALIMDOR = "Kalimdor", -- Needs review
	KARAZHAN = "Karazhan", -- Requires localization
	KELPTHARFOREST = "Floresta Kelp'thar", -- Needs review
	KEZAN = "Kezan", -- Needs review
	KRASARANGWILDS = "Krasarang Wilds", -- Requires localization
	KUNLAISUMMIT = "Kun-Lai Summit", -- Requires localization
	LEATHERWORKING = "Leatherworking", -- Requires localization
	LEGENDARY = "Legendary", -- Requires localization
	LOCHMODAN = "Loch Modan", -- Needs review
	LOSTCITYOFTHETOLVIR = "Lost City of the Tol'vir", -- Requires localization
	LOVEISINTHEAIR = "Love is in the Air", -- Requires localization
	LUNARFESTIVAL = "Lunar Festival", -- Requires localization
	MAGE = "Mage", -- Requires localization
	MAGISTERSTERRACE = "Magisters' Terrace", -- Requires localization
	MAGTHERIDONSLAIR = "Magtheridon's Lair", -- Requires localization
	MANATOMBS = "Mana-Tombs", -- Requires localization
	MAPFILTERS = "Map Filters", -- Requires localization
	MARAUDON = "Maraudon", -- Requires localization
	MIDSUMMERFIREFESTIVAL = "Midsummer Fire Festival", -- Requires localization
	MINING = "Mining", -- Requires localization
	MISCELLANEOUS = "Miscellaneous", -- Requires localization
	MOGUSHANVAULTS = "Mogu'shan Vaults", -- Requires localization
	MOLTENCORE = "Molten Core", -- Requires localization
	MOLTENFRONT = "Front Ígneo", -- Needs review
	MONK = "Monk", -- Requires localization
	MOONGLADE = "Clareira da Lua", -- Needs review
	MOUNTHYJAL = "Monte Hyjal", -- Needs review
	MULGORE = "Mulgore", -- Needs review
	NAGRAND = "Nagrand", -- Needs review
	NAXXRAMAS = "Naxxramas", -- Requires localization
	NETHERSTORM = "Eternévoa", -- Needs review
	NEWYEARSEVE = "New Year's Eve", -- Requires localization
	NOBLEGARDEN = "Noblegarden", -- Requires localization
	NORTHERNBARRENS = "Sertões Setentrionais", -- Needs review
	NORTHERNSTRANGLETHORN = "Northern Stranglethorn", -- Requires localization
	NORTHREND = "Nortúndria", -- Needs review
	OLDHILLSBRADFOOTHILLS = "Old Hillsbrad Foothills", -- Requires localization
	ONYXIASLAIR = "Onyxia's Lair", -- Requires localization
	OPTIONS = "Options", -- Requires localization
	ORGRIMMAR = "Orgrimmar", -- Needs review
	OUTLAND = "Terralém", -- Needs review
	PALACEOFTHEHEAVENS = "Palace of the Heavens", -- Requires localization
	PALADIN = "Paladin", -- Requires localization
	PANDARIA = "Pandaria", -- Needs review
	PERFORMSERVERQUERY = "Perform Server Query...", -- Requires localization
	PILGRIMSBOUNTY = "Pilgrim's Bounty", -- Requires localization
	PITOFSARON = "Pit of Saron", -- Requires localization
	PRIEST = "Priest", -- Requires localization
	PROFESSIONS = "Professions", -- Requires localization
	QUERYREQUESTED = "A server query has been requested...", -- Requires localization
	QUESTLISTFILTERS = "Quest List Filters", -- Requires localization
	QUESTSFOUND = "%d Quests Found", -- Requires localization
	RAGEFIRECHASM = "Ragefire Chasm", -- Requires localization
	RAIDS = "Raids", -- Requires localization
	RAZORFENDOWNS = "Razorfen Downs", -- Requires localization
	RAZORFENKRAUL = "Razorfen Kraul", -- Requires localization
	REDRIDGEMOUNTAINS = "Redridge Mountains", -- Requires localization
	ROGUE = "Rogue", -- Requires localization
	RUINSOFAHNQIRAJ = "Ruins of Ahn'Qiraj", -- Requires localization
	RUINSOFGILNEAS = "Ruínas de Guilnéas", -- Needs review
	RUINSOFGILNEASCITY = "Ruins of Gilneas City", -- Requires localization
	SCARLETMONASTERY = "Scarlet Monastery", -- Requires localization
	SCHOLOMANCE = "Scholomance", -- Requires localization
	SEARINGGORGE = "Searing Gorge", -- Requires localization
	SEASONAL = "Seasonal", -- Requires localization
	SERPENTSHRINECAVERN = "Serpentshrine Cavern", -- Requires localization
	SETHEKKHALLS = "Sethekk Halls", -- Requires localization
	SHADOPANMONASTERY = "Shado-pan Monastery", -- Requires localization
	SHADOWFANGKEEP = "Shadowfang Keep", -- Requires localization
	SHADOWLABYRINTH = "Shadow Labyrinth", -- Requires localization
	SHADOWMOONVALLEY = "Shadowmoon Valley", -- Requires localization
	SHAMAN = "Shaman", -- Requires localization
	SHATTRATHCITY = "Shattrath City", -- Requires localization
	SHIMMERINGEXPANSE = "Shimmering Expanse", -- Requires localization
	SHOLAZARBASIN = "Sholazar Basin", -- Requires localization
	SHOWMAPICONS = "Show Map Icons", -- Requires localization
	SIEGEOFNIUZAOTEMPLE = "Siege of Niuzao Temple", -- Requires localization
	SILITHUS = "Silithus", -- Needs review
	SILVERMOONCITY = "Silvermoon City", -- Requires localization
	SILVERPINEFOREST = "Silverpine Forest", -- Requires localization
	SILVERSHARDMINES = "Silver Shard Mines", -- Requires localization
	SKINNING = "Skinning", -- Requires localization
	SORTALPHA = "Sort: Alphabetically", -- Requires localization
	SORTLEVEL = "Sort: Level", -- Requires localization
	SOUTHERNBARRENS = "Sertões Meridionais", -- Needs review
	SPECIAL = "Special", -- Requires localization
	SPECIALS = "Specials", -- Requires localization
	STONETALONMOUNTAINS = "Cordilheira das Torres de Pedra", -- Needs review
	STORMSTOUTBREWERY = "Stormstout Brewery", -- Requires localization
	STORMWINDCITY = "Stormwind City", -- Requires localization
	STRANDOFTHEANCIENTS = "Strand of the Ancients", -- Requires localization
	STRANGLETHORNVALE = "Stranglethorn Vale", -- Requires localization
	STRATHOLME = "Stratholme", -- Requires localization
	SUNKENTEMPLE = "Sunken Temple", -- Requires localization
	SUNWELLPLATEAU = "Sunwell Plateau", -- Requires localization
	SWAMPOFSORROWS = "Swamp of Sorrows", -- Requires localization
	TAILORING = "Tailoring", -- Requires localization
	TANARIS = "Tanaris", -- Needs review
	TELDRASSIL = "Teldrassil", -- Needs review
	TEMPESTKEEP = "Tempest Keep", -- Requires localization
	TEMPLEOFAHNQIRAJ = "Temple of Ahn'Qiraj", -- Requires localization
	TEMPLEOFKOTMOGU = "Temple of Kotmogu", -- Requires localization
	TEMPLEOFTHEREDCRANE = "Temple of the Red Crane", -- Requires localization
	TEROKKARFOREST = "Terokkar Forest", -- Requires localization
	THEARCATRAZ = "The Arcatraz", -- Requires localization
	THEBASTIONOFTWILIGHT = "The Bastion of Twilight", -- Requires localization
	THEBATTLEFORGILNEAS = "The Battle for Gilneas", -- Requires localization
	THEBLACKMORASS = "The Black Morass", -- Requires localization
	THEBLOODFURNACE = "The Blood Furnace", -- Requires localization
	THEBOTANICA = "The Botanica", -- Requires localization
	THECAPEOFSTRANGLETHORN = "The Cape of Stranglethorn", -- Requires localization
	THECULLINGOFSTRATHOLME = "The Culling of Stratholme", -- Requires localization
	THEDEADMINES = "The Deadmines", -- Requires localization
	THEEXODAR = "Exodar", -- Needs review
	THEEYE = "The Eye", -- Requires localization
	THEEYEOFETERNITY = "The Eye of Eternity", -- Requires localization
	THEFORGEOFSOULS = "The Forge of Souls", -- Requires localization
	THEGATEOFTHESETTINGSUN = "The Gate of the Setting Sun", -- Requires localization
	THEHALFHILLMARKET = "The Halfhill Market", -- Requires localization
	THEHINTERLANDS = "The Hinterlands", -- Requires localization
	THEJADEFOREST = "The Jade Forest", -- Requires localization
	THELOSTISLES = "The Lost Isles", -- Requires localization
	THEMAELSTROM = "The Maelstrom", -- Requires localization
	THEMECHANAR = "The Mechanar", -- Requires localization
	THENEXUS = "The Nexus", -- Requires localization
	THEOBSIDIANSANCTUM = "The Obsidian Sanctum", -- Requires localization
	THEOCULUS = "The Oculus", -- Requires localization
	THERUBYSANCTUM = "The Ruby Sanctum", -- Requires localization
	THESHATTEREDHALLS = "The Shattered Halls", -- Requires localization
	THESLAVEPENS = "The Slave Pens", -- Requires localization
	THESTEAMVAULT = "The Steamvault", -- Requires localization
	THESTOCKADE = "The Stockade", -- Requires localization
	THESTONECORE = "The Stonecore", -- Requires localization
	THESTORMPEAKS = "The Storm Peaks", -- Requires localization
	THETEMPLEOFTHEJADESERPENT = "The Temple of the Jade Serpent", -- Requires localization
	THEUNDERBOG = "The Underbog", -- Requires localization
	THEVEILEDSTAIR = "The Veiled Stair", -- Requires localization
	THEVIOLETHOLD = "The Violet Hold", -- Requires localization
	THEVORTEXPINNACLE = "The Vortex Pinnacle", -- Requires localization
	THEWANDERINGISLE = "The Wandering Isle", -- Requires localization
	THEZANDALARI = "The Zandalari", -- Requires localization
	THOUSANDNEEDLES = "Mil Agulhas", -- Needs review
	THRONEOFTHEFOURWINDS = "Throne of the Four Winds", -- Requires localization
	THRONEOFTHETIDES = "Throne of the Tides", -- Requires localization
	THUNDERBLUFF = "Penhasco do Trovão", -- Needs review
	TIRISFALGLADES = "Tirisfal Glades", -- Requires localization
	TOLBARAD = "Tol Barad", -- Requires localization
	TOLBARADPENINSULA = "Tol Barad Peninsula", -- Requires localization
	TOURNAMENT = "Tournament", -- Requires localization
	TOWNLONGSTEPPES = "Townlong Steppes", -- Requires localization
	TRIALOFTHECHAMPION = "Trial of the Champion", -- Requires localization
	TRIALOFTHECRUSADER = "Trial of the Crusader", -- Requires localization
	TWILIGHTHIGHLANDS = "Twilight Highlands", -- Requires localization
	TWINPEAKS = "Twin Peaks", -- Requires localization
	ULDAMAN = "Uldaman", -- Requires localization
	ULDUAR = "Ulduar", -- Requires localization
	ULDUM = "Uldum", -- Needs review
	UNDERCITY = "Undercity", -- Requires localization
	UNGOROCRATER = "Cratera Un'Goro", -- Needs review
	UTGARDEKEEP = "Utgarde Keep", -- Requires localization
	UTGARDEPINNACLE = "Utgarde Pinnacle", -- Requires localization
	VALEOFETERNALBLOSSOMS = "Vale of Eternal Blossoms", -- Requires localization
	VALLEYOFTHEFOURWINDS = "Valley of the Four Winds", -- Requires localization
	VASHJIR = "Vashj'ir", -- Requires localization
	VAULTOFARCHAVON = "Vault of Archavon", -- Requires localization
	WAILINGCAVERNS = "Wailing Caverns", -- Requires localization
	WARLOCK = "Warlock", -- Requires localization
	WARRIOR = "Warrior", -- Requires localization
	WARSONGGULCH = "Warsong Gulch", -- Requires localization
	WELLOFETERNITY = "Well of Eternity", -- Requires localization
	WESTERNPLAGUELANDS = "Western Plaguelands", -- Requires localization
	WESTFALL = "Westfall", -- Requires localization
	WETLANDS = "Wetlands", -- Requires localization
	WINTERGRASP = "Wintergrasp", -- Requires localization
	WINTERSPRING = "Hibérnia", -- Needs review
	WINTERVEIL = "Winter Veil", -- Requires localization
	WORLDEVENTS = "World Events", -- Requires localization
	ZANGARMARSH = "Zangarmarsh", -- Requires localization
	ZULAMAN = "Zul'Aman", -- Requires localization
	ZULDRAK = "Zul'Drak", -- Requires localization
	ZULFARRAK = "Zul'Farrak", -- Requires localization
	ZULGURUB = "Zul'Gurub", -- Requires localization
}
end