if GetLocale() == "koKR" then
qcLocalize = {
	ABYSSALDEPTHS = "심연의 나락", -- Needs review
	AHNKAHETTHEOLDKINGDOM = "안카헤트: 고대 왕국",
	AHNQIRAJ = "안퀴라즈",
	AHNQIRAJTHEFALLENKINGDOM = "안퀴라즈: 무너진 왕국", -- Needs review
	ALCHEMY = "연금술", -- Needs review
	ALTERACVALLEY = "알터랙 계곡",
	ARATHIBASIN = "아라시 분지",
	ARATHIHIGHLANDS = "아라시 고원", -- Needs review
	ARCHAEOLOGY = "고고학", -- Needs review
	ASHENVALE = "잿빛 골짜기", -- Needs review
	AUCHENAICRYPTS = "아키나이 납골당",
	AUCHINDOUN = "아킨둔",
	AZJOLNERUB = "아졸네룹",
	AZSHARA = "아즈샤라", -- Needs review
	AZUREMYSTISLE = "하늘안개 섬", -- Needs review
	BADLANDS = "황야의 땅", -- Needs review
	BARADINHOLD = "바라딘 요새",
	BATTLEGROUNDS = "전장", -- Needs review
	BATTLEPETS = "Battle Pets", -- Requires localization
	BLACKFATHOMDEEPS = "검은심연 나락",
	BLACKROCKCAVERNS = "검은바위 동굴",
	BLACKROCKDEPTHS = "검은바위 나락",
	BLACKROCKSPIRE = "검은바위 첨탑",
	BLACKSMITHING = "대장기술", -- Needs review
	BLACKTEMPLE = "검은 사원",
	BLACKWINGDESCENT = "검은날개 강림지",
	BLACKWINGLAIR = "검은날개 둥지",
	BLADESEDGEMOUNTAINS = "칼날 산맥", -- Needs review
	BLASTEDLANDS = "저주받은 땅", -- Needs review
	BLOODMYSTISLE = "핏빛안개 섬", -- Needs review
	BOREANTUNDRA = "북풍의 땅", -- Needs review
	BREWFEST = "가을 축제", -- Needs review
	BURNINGSTEPPES = "불타는 평원", -- Needs review
	CAVERNSOFTIME = "시간의 동굴",
	CHILDRENSWEEK = "어린이 주간", -- Needs review
	CLASSES = "Classes", -- Requires localization
	CLASSQUESTS = "Class Quests", -- Requires localization
	CLEARUPDATECACHE = "Clear Update Cache...", -- Requires localization
	COILFANGRESERVOIR = "Coilfang Reservoir", -- Requires localization
	COMBINEDMAPANDQUESTFILTERS = "Combined Map & Quest List Filters", -- Requires localization
	CONFIGSUBTITLE = "These options allow you to change the way that Quest Completist handles and filters its data.", -- Requires localization
	CONFIGTITLE = "Quest Completist - Configuration", -- Requires localization
	CONTINENTS = "Continents", -- Requires localization
	COOKING = "요리", -- Needs review
	CRYSTALSONGFOREST = "수정노래 숲", -- Needs review
	DALARAN = "달라란", -- Needs review
	DARKMOONFAIRE = "다크문 축제", -- Needs review
	DARKSHORE = "어둠해안", -- Needs review
	DARNASSUS = "다르나서스", -- Needs review
	DAYOFTHEDEAD = "Day of the Dead", -- Requires localization
	DEADWINDPASS = "저승바람 고개", -- Needs review
	DEATHKNIGHT = "죽음의 기사", -- Needs review
	DEEPHOLM = "심원의 영지", -- Needs review
	DEEPRUNTRAM = "깊은굴 지하철", -- Needs review
	DESOLACE = "잊혀진 땅", -- Needs review
	DIREMAUL = "혈투의 전장",
	DRAGONBLIGHT = "용의 안식처", -- Needs review
	DRAGONSOUL = "용의 영혼",
	DRAKTHARONKEEP = "드락타론 성채",
	DREADWASTES = "공포의 황무지", -- Needs review
	DRUID = "드루이드", -- Needs review
	DUNGEONSANDRAIDS = "Dungeons & Raids", -- Requires localization
	DUNMOROGH = "던 모로", -- Needs review
	DUROTAR = "듀로타", -- Needs review
	DUSKWOOD = "그늘숲", -- Needs review
	DUSTWALLOWMARSH = "먼지진흙 습지대", -- Needs review
	EASTERNKINGDOMS = "동부 왕국", -- Needs review
	EASTERNPLAGUELANDS = "동부 역병지대", -- Needs review
	ELEMENTALBONDS = "Elemental Bonds", -- Requires localization
	ELWYNNFOREST = "엘윈 숲", -- Needs review
	ENCHANTING = "마법부여", -- Needs review
	ENDTIME = "시간의 끝",
	ENGINEERING = "기계공학", -- Needs review
	EVERSONGWOODS = "영원노래 숲", -- Needs review
	EYEOFTHESTORM = "폭풍의 눈",
	FELWOOD = "악령숲", -- Needs review
	FERALAS = "페랄라스", -- Needs review
	FIRELANDS = "불의 땅",
	FIRELANDSINVASION = "Firelands Invasion", -- Requires localization
	FIRSTAID = "응급치료", -- Needs review
	FISHING = "낚시", -- Needs review
	GHOSTLANDS = "유령의 땅", -- Needs review
	GILNEAS = "길니아스",
	GILNEASCITY = "길니아스 시",
	GNOMEREGAN = "놈리건",
	GRIMBATOL = "그림 바톨",
	GRIZZLYHILLS = "회색 구릉지", -- Needs review
	GRUULSLAIR = "그룰의 둥지",
	GUNDRAK = "군드락",
	HALLOWSEND = "Hallow's End", -- Requires localization
	HALLSOFLIGHTNING = "번개의 전당",
	HALLSOFORIGINATION = "시초의 전당",
	HALLSOFREFLECTION = "투영의 전당",
	HALLSOFSTONE = "돌의 전당",
	HARVESTFESTIVAL = "Harvest Festival", -- Requires localization
	HELLFIRECITADEL = "Hellfire Citadel", -- Requires localization
	HELLFIREPENINSULA = "지옥불 반도", -- Needs review
	HELLFIRERAMPARTS = "지옥불 성루",
	HERBALISM = "약초채집", -- Needs review
	HIDECOMPLETEDQUESTS = "Hide Completed Quests", -- Requires localization
	HIDEINPROGRESSQUESTS = "Hide In-Progress Quests", -- Requires localization
	HIDELOWLEVELQUESTS = "Hide Low Level Quests", -- Requires localization
	HIDENONACTIVESEASONALQUESTS = "Hide Non-Active Seasonal Quests", -- Requires localization
	HIDEOTHERFACTIONQUESTS = "Hide Other Faction Quests", -- Requires localization
	HIDEOTHERPROFESSIONQUESTS = "Hide Other Profession Quests", -- Requires localization
	HIDEOTHERRACEANDCLASSQUESTS = "Hide Other Race & Class Quests", -- Requires localization
	HILLSBRADFOOTHILLS = "언덕마루 구릉지", -- Needs review
	HOUROFTWILIGHT = "황혼의 시간",
	HOWLINGFJORD = "울부짖는 협만", -- Needs review
	HROTHGARSLANDING = "호로스가르 상륙지", -- Needs review
	HUNTER = "사냥꾼", -- Needs review
	HYJALSUMMIT = "하이잘 정상",
	ICECROWN = "얼음왕관", -- Needs review
	ICECROWNCITADEL = "얼음왕관 성채",
	INSCRIPTION = "주문각인", -- Needs review
	IRONFORGE = "아이언포지", -- Needs review
	ISLEOFCONQUEST = "정복의 섬",
	ISLEOFQUELDANAS = "쿠엘다나스 섬", -- Needs review
	JEWELCRAFTING = "보석세공", -- Needs review
	KALIMDOR = "칼림도어", -- Needs review
	KARAZHAN = "카라잔",
	KELPTHARFOREST = "켈프타르 숲", -- Needs review
	KEZAN = "케잔", -- Needs review
	KRASARANGWILDS = "크라사랑 밀림",
	KUNLAISUMMIT = "쿤라이 봉우리",
	LEATHERWORKING = "가죽세공", -- Needs review
	LEGENDARY = "Legendary", -- Requires localization
	LOCHMODAN = "모단 호수",
	LOSTCITYOFTHETOLVIR = "톨비르의 잃어버린 도시",
	LOVEISINTHEAIR = "Love is in the Air", -- Requires localization
	LUNARFESTIVAL = "달의 축제", -- Needs review
	MAGE = "마법사", -- Needs review
	MAGISTERSTERRACE = "마법학자의 정원",
	MAGTHERIDONSLAIR = "마그테리돈의 둥지",
	MANATOMBS = "마나 무덤",
	MAPFILTERS = "Map Filters", -- Requires localization
	MARAUDON = "마라우돈",
	MIDSUMMERFIREFESTIVAL = "Midsummer Fire Festival", -- Requires localization
	MINING = "채광", -- Needs review
	MISCELLANEOUS = "Miscellaneous", -- Requires localization
	MOGUSHANVAULTS = "모구샨 금고",
	MOLTENCORE = "화산 심장부",
	MOLTENFRONT = "녹아내린 전초지",
	MONK = "Monk", -- Requires localization
	MOONGLADE = "달숲", -- Needs review
	MOUNTHYJAL = "하이잘 산", -- Needs review
	MULGORE = "멀고어", -- Needs review
	NAGRAND = "나그란드",
	NAXXRAMAS = "낙스라마스",
	NETHERSTORM = "황천의 폭풍",
	NEWYEARSEVE = "New Year's Eve", -- Requires localization
	NOBLEGARDEN = "귀족의 정원", -- Needs review
	NORTHERNBARRENS = "북부 불모의 땅", -- Needs review
	NORTHERNSTRANGLETHORN = "북부 가시덤불", -- Needs review
	NORTHREND = "노스렌드", -- Needs review
	OLDHILLSBRADFOOTHILLS = "옛 언덕마루 구릉지",
	ONYXIASLAIR = "오닉시아의 둥지",
	OPTIONS = "Options", -- Requires localization
	ORGRIMMAR = "오그리마", -- Needs review
	OUTLAND = "아웃랜드", -- Needs review
	PALACEOFTHEHEAVENS = "Palace of the Heavens", -- Requires localization
	PALADIN = "성기사", -- Needs review
	PANDARIA = "판다리아", -- Needs review
	PERFORMSERVERQUERY = "Perform Server Query...", -- Requires localization
	PILGRIMSBOUNTY = "Pilgrim's Bounty", -- Requires localization
	PITOFSARON = "사론의 구덩이",
	PRIEST = "사제", -- Needs review
	PROFESSIONS = "Professions", -- Requires localization
	QUERYREQUESTED = "A server query has been requested...", -- Requires localization
	QUESTLISTFILTERS = "Quest List Filters", -- Requires localization
	QUESTSFOUND = "%d Quests Found", -- Requires localization
	RAGEFIRECHASM = "성난불길 협곡",
	RAIDS = "Raids", -- Requires localization
	RAZORFENDOWNS = "가시덩굴 구릉",
	RAZORFENKRAUL = "가시덩굴 우리",
	REDRIDGEMOUNTAINS = "붉은마루 산맥",
	ROGUE = "도적", -- Needs review
	RUINSOFAHNQIRAJ = "안퀴라즈 폐허",
	RUINSOFGILNEAS = "길니아스 폐허",
	RUINSOFGILNEASCITY = "길니아스 시 폐허",
	SCARLETMONASTERY = "붉은십자군 수도원",
	SCHOLOMANCE = "스칼로맨스",
	SEARINGGORGE = "이글거리는 협곡",
	SEASONAL = "Seasonal", -- Requires localization
	SERPENTSHRINECAVERN = "불뱀 제단",
	SETHEKKHALLS = "세데크 전당",
	SHADOPANMONASTERY = "Shado-pan Monastery", -- Requires localization
	SHADOWFANGKEEP = "그림자송곳니 성채",
	SHADOWLABYRINTH = "어둠의 미궁",
	SHADOWMOONVALLEY = "어둠달 골짜기",
	SHAMAN = "주술사", -- Needs review
	SHATTRATHCITY = "샤트라스",
	SHIMMERINGEXPANSE = "흐린빛 벌판", -- Needs review
	SHOLAZARBASIN = "숄라자르 분지",
	SHOWMAPICONS = "Show Map Icons", -- Requires localization
	SIEGEOFNIUZAOTEMPLE = "니우짜오 사원 탈환",
	SILITHUS = "실리더스", -- Needs review
	SILVERMOONCITY = "실버문",
	SILVERPINEFOREST = "은빛소나무 숲",
	SILVERSHARDMINES = "Silver Shard Mines", -- Requires localization
	SKINNING = "Skinning", -- Requires localization
	SORTALPHA = "Sort: Alphabetically", -- Requires localization
	SORTLEVEL = "Sort: Level", -- Requires localization
	SOUTHERNBARRENS = "남부 불모의 땅", -- Needs review
	SPECIAL = "Special", -- Requires localization
	SPECIALS = "Specials", -- Requires localization
	STONETALONMOUNTAINS = "돌발톱 산맥", -- Needs review
	STORMSTOUTBREWERY = "스톰스타우트 양조장",
	STORMWINDCITY = "스톰윈드",
	STRANDOFTHEANCIENTS = "고대의 해안",
	STRANGLETHORNVALE = "가시덤불 골짜기",
	STRATHOLME = "스트라솔름",
	SUNKENTEMPLE = "가라앉은 사원",
	SUNWELLPLATEAU = "태양샘 고원",
	SWAMPOFSORROWS = "슬픔의 늪",
	TAILORING = "재봉술", -- Needs review
	TANARIS = "타나리스", -- Needs review
	TELDRASSIL = "텔드랏실", -- Needs review
	TEMPESTKEEP = "폭풍우 요새",
	TEMPLEOFAHNQIRAJ = "안퀴라즈 사원", -- Needs review
	TEMPLEOFKOTMOGU = "코트모구 사원",
	TEMPLEOFTHEREDCRANE = "Temple of the Red Crane", -- Requires localization
	TEROKKARFOREST = "테로카르 숲",
	THEARCATRAZ = "알카트라즈",
	THEBASTIONOFTWILIGHT = "황혼의 요새",
	THEBATTLEFORGILNEAS = "길니아스 전투지",
	THEBLACKMORASS = "검은늪",
	THEBLOODFURNACE = "피의 용광로",
	THEBOTANICA = "신록의 정원",
	THECAPEOFSTRANGLETHORN = "가시덤불 곶", -- Needs review
	THECULLINGOFSTRATHOLME = "옛 스트라솔름",
	THEDEADMINES = "죽음의 폐광",
	THEEXODAR = "엑소다르", -- Needs review
	THEEYE = "The Eye", -- Requires localization
	THEEYEOFETERNITY = "영원의 눈",
	THEFORGEOFSOULS = "영혼의 제련소",
	THEGATEOFTHESETTINGSUN = "The Gate of the Setting Sun", -- Requires localization
	THEHALFHILLMARKET = "The Halfhill Market", -- Requires localization
	THEHINTERLANDS = "동부 내륙지",
	THEJADEFOREST = "옥림",
	THELOSTISLES = "잃어버린 섬",
	THEMAELSTROM = "혼돈의 소용돌이",
	THEMECHANAR = "메카나르",
	THENEXUS = "마력의 탑",
	THEOBSIDIANSANCTUM = "흑요석 성소",
	THEOCULUS = "마력의 눈",
	THERUBYSANCTUM = "루비 성소",
	THESHATTEREDHALLS = "으스러진 손의 전당",
	THESLAVEPENS = "강제 노역소",
	THESTEAMVAULT = "증기 저장고",
	THESTOCKADE = "스톰윈드 지하감옥",
	THESTONECORE = "바위심장부",
	THESTORMPEAKS = "폭풍우 봉우리",
	THETEMPLEOFTHEJADESERPENT = "The Temple of the Jade Serpent", -- Requires localization
	THEUNDERBOG = "지하수렁",
	THEVEILEDSTAIR = "The Veiled Stair", -- Requires localization
	THEVIOLETHOLD = "보랏빛 요새",
	THEVORTEXPINNACLE = "소용돌이 누각",
	THEWANDERINGISLE = "유랑도",
	THEZANDALARI = "The Zandalari", -- Requires localization
	THOUSANDNEEDLES = "버섯구름 봉우리", -- Needs review
	THRONEOFTHEFOURWINDS = "네 바람의 왕좌",
	THRONEOFTHETIDES = "파도의 왕좌",
	THUNDERBLUFF = "썬더 블러프", -- Needs review
	TIRISFALGLADES = "티리스팔 숲",
	TOLBARAD = "톨 바라드",
	TOLBARADPENINSULA = "톨 바라드 반도",
	TOURNAMENT = "Tournament", -- Requires localization
	TOWNLONGSTEPPES = "탕랑 평원",
	TRIALOFTHECHAMPION = "용사의 시험장",
	TRIALOFTHECRUSADER = "십자군의 시험장",
	TWILIGHTHIGHLANDS = "황혼의 고원",
	TWINPEAKS = "쌍둥이 봉우리",
	ULDAMAN = "울다만",
	ULDUAR = "울두아르",
	ULDUM = "울둠", -- Needs review
	UNDERCITY = "언더시티",
	UNGOROCRATER = "운고로 분화구", -- Needs review
	UTGARDEKEEP = "우트가드 성채",
	UTGARDEPINNACLE = "우트가드 첨탑",
	VALEOFETERNALBLOSSOMS = "영원꽃 골짜기",
	VALLEYOFTHEFOURWINDS = "네 바람의 계곡",
	VASHJIR = "바쉬르",
	VAULTOFARCHAVON = "아카본 석실",
	WAILINGCAVERNS = "통곡의 동굴",
	WARLOCK = "흑마법사", -- Needs review
	WARRIOR = "전사", -- Needs review
	WARSONGGULCH = "전쟁노래 협곡",
	WELLOFETERNITY = "영원의 샘",
	WESTERNPLAGUELANDS = "서부 역병지대",
	WESTFALL = "서부 몰락지대",
	WETLANDS = "저습지",
	WINTERGRASP = "겨울손아귀 호수",
	WINTERSPRING = "여명의 설원", -- Needs review
	WINTERVEIL = "Winter Veil", -- Requires localization
	WORLDEVENTS = "World Events", -- Requires localization
	ZANGARMARSH = "장가르 습지대",
	ZULAMAN = "줄아만",
	ZULDRAK = "줄드락",
	ZULFARRAK = "줄파락",
	ZULGURUB = "줄구룹",
}
end