if GetLocale() == "frFR" then
qcLocalize = {
	ABYSSALDEPTHS = "Profondeurs Abyssales",
	AHNKAHETTHEOLDKINGDOM = "Ahn'kahet : l'Ancien royaume",
	AHNQIRAJ = "Ahn'Qiraj", -- Needs review
	AHNQIRAJTHEFALLENKINGDOM = "Ahn'Qiraj : le royaume Déchu",
	ALCHEMY = "Alchimie",
	ALTERACVALLEY = "Vallée d'Alterac",
	ARATHIBASIN = "Bassin Arathi",
	ARATHIHIGHLANDS = "Hautes-terres Arathies",
	ARCHAEOLOGY = "Archéologie",
	ASHENVALE = "Orneval",
	AUCHENAICRYPTS = "Cryptes Auchenaï",
	AUCHINDOUN = "Auchindoun",
	AZJOLNERUB = "Azjol-Nérub",
	AZSHARA = "Azshara",
	AZUREMYSTISLE = "Île de Brume-Azur",
	BADLANDS = "Terres Ingrates",
	BARADINHOLD = "Bastion de Baradin",
	BATTLEGROUNDS = "Champs de bataille",
	BATTLEPETS = "Battle Pets", -- Requires localization
	BLACKFATHOMDEEPS = "Profondeurs de Brassenoire",
	BLACKROCKCAVERNS = "Cavernes de Rochenoire",
	BLACKROCKDEPTHS = "Profondeurs de Rochenoire",
	BLACKROCKSPIRE = "Pic Rochenoire",
	BLACKSMITHING = "Forge",
	BLACKTEMPLE = "Temple Noir",
	BLACKWINGDESCENT = "Descente de l'Aile Noire",
	BLACKWINGLAIR = "Repaire de l'Aile Noire",
	BLADESEDGEMOUNTAINS = "Les Tranchantes",
	BLASTEDLANDS = "Terres Foudroyées",
	BLOODMYSTISLE = "Île de Brume-Sang",
	BOREANTUNDRA = "Toundra Boréenne",
	BREWFEST = "Fête des Brasseurs",
	BURNINGSTEPPES = "Steppes Ardentes",
	CAVERNSOFTIME = "Les Grottes du temps",
	CHILDRENSWEEK = "Semaine des enfants",
	CLASSES = "Classes",
	CLASSQUESTS = "Quêtes de classe",
	CLEARUPDATECACHE = "Clear Update Cache...", -- Needs review
	COILFANGRESERVOIR = "Le Réservoir de Glisseroc",
	COMBINEDMAPANDQUESTFILTERS = "Combined Map & Quest List Filters", -- Needs review
	CONFIGSUBTITLE = "Ces options vous permettent de changer la façon dont Quest Completist gère et filtre les données.",
	CONFIGTITLE = "Quest Completist - Configuration",
	CONTINENTS = "Continents",
	COOKING = "Cuisine",
	CRYSTALSONGFOREST = "Forêt du Chant de cristal",
	DALARAN = "Dalaran",
	DARKMOONFAIRE = "Foire de Sombrelune",
	DARKSHORE = "Sombrivage",
	DARNASSUS = "Darnassus",
	DAYOFTHEDEAD = "Jour des morts",
	DEADWINDPASS = "Défilé de Deuillevent",
	DEATHKNIGHT = "Chevalier de la mort",
	DEEPHOLM = "Le Tréfonds",
	DEEPRUNTRAM = "Tram des profondeurs",
	DESOLACE = "Désolace",
	DIREMAUL = "Hache-Tripes",
	DRAGONBLIGHT = "Désolation des dragons",
	DRAGONSOUL = "Âme des dragons ", -- Needs review
	DRAKTHARONKEEP = "Donjon de Drak'Tharon",
	DREADWASTES = "Terres de l'Angoisse",
	DRUID = "Druide",
	DUNGEONSANDRAIDS = "Donjons et raids",
	DUNMOROGH = "Dun Morogh",
	DUROTAR = "Durotar",
	DUSKWOOD = "Bois de la Pénombre",
	DUSTWALLOWMARSH = "Marécage d'Âprefange",
	EASTERNKINGDOMS = "Royaumes de l'Est",
	EASTERNPLAGUELANDS = "Maleterres de l'Est",
	ELEMENTALBONDS = "Liens élémentaires",
	ELWYNNFOREST = "Forêt d'Elwynn",
	ENCHANTING = "Enchantement",
	ENDTIME = "La Fin des Temps", -- Needs review
	ENGINEERING = "Ingénierie",
	EVERSONGWOODS = "Bois des Chants éternels",
	EYEOFTHESTORM = "L'Œil du cyclone",
	FELWOOD = "Gangrebois",
	FERALAS = "Féralas",
	FIRELANDS = "Terres de Feu ", -- Needs review
	FIRELANDSINVASION = "Invasion des terres de Feu",
	FIRSTAID = "Secourisme",
	FISHING = "Pêche",
	GHOSTLANDS = "Les terres Fantômes",
	GILNEAS = "Gilneas", -- Needs review
	GILNEASCITY = "Gilneas City", -- Needs review
	GNOMEREGAN = "Gnomeregan",
	GRIMBATOL = "Grim Batol",
	GRIZZLYHILLS = "Les Grisonnes",
	GRUULSLAIR = "Repaire de Grull",
	GUNDRAK = "Gundrak", -- Needs review
	HALLOWSEND = "Sanssaint",
	HALLSOFLIGHTNING = "Les salles de Foudre", -- Needs review
	HALLSOFORIGINATION = "Salles de l'Origine", -- Needs review
	HALLSOFREFLECTION = "Salles des Reflets", -- Needs review
	HALLSOFSTONE = "Les salles de Pierre",
	HARVESTFESTIVAL = "Fête des moissons",
	HELLFIRECITADEL = "Citadelle des Flammes infernales",
	HELLFIREPENINSULA = "Péninsule des Flammes infernales",
	HELLFIRERAMPARTS = "Remparts des Flammes infernales",
	HERBALISM = "Herboristerie",
	HIDECOMPLETEDQUESTS = "Masquer les quêtes achevées",
	HIDEINPROGRESSQUESTS = "Masquer les quêtes en cours",
	HIDELOWLEVELQUESTS = "Masquer les quêtes de bas niveau",
	HIDENONACTIVESEASONALQUESTS = [=[Masquer les quêtes non-saisonnière 
]=],
	HIDEOTHERFACTIONQUESTS = "Masquer les quêtes des autres faction",
	HIDEOTHERPROFESSIONQUESTS = "Masquer les quêtes des autres métiers ",
	HIDEOTHERRACEANDCLASSQUESTS = "Masquer les quêtes des autres race & classe",
	HILLSBRADFOOTHILLS = "Contreforts de Hautebrande",
	HOUROFTWILIGHT = "L’Heure du Crépuscule",
	HOWLINGFJORD = "Fjord Hurlant",
	HROTHGARSLANDING = "Accostage de Hrothgar",
	HUNTER = "Chasseur",
	HYJALSUMMIT = "Sommet d'Hyjal",
	ICECROWN = "La Couronne de glace",
	ICECROWNCITADEL = "Citadelle de la Couronne de glace",
	INSCRIPTION = "Inscription",
	IRONFORGE = "Forgefer",
	ISLEOFCONQUEST = "Île des Conquérants",
	ISLEOFQUELDANAS = "Île de Quel'Danas",
	JEWELCRAFTING = "Joaillerie",
	KALIMDOR = "Kalimdor",
	KARAZHAN = "Karazhan",
	KELPTHARFOREST = "Forêt de Varech'thar",
	KEZAN = "Kezan",
	KRASARANGWILDS = "Étendues sauvages de Krasarang",
	KUNLAISUMMIT = "Le sommet Kun-Lai",
	LEATHERWORKING = "Travail du cuir",
	LEGENDARY = "Légendaire",
	LOCHMODAN = "Loch Modan",
	LOSTCITYOFTHETOLVIR = "Cité perdue des Tol'vir",
	LOVEISINTHEAIR = "De l'amour dans l'air",
	LUNARFESTIVAL = "Fête lunaire",
	MAGE = "Mage",
	MAGISTERSTERRACE = "Terrasse des Magistères",
	MAGTHERIDONSLAIR = "Le repaire de Magtheridon",
	MANATOMBS = "Tombes-mana", -- Needs review
	MAPFILTERS = "Filtres - Carte",
	MARAUDON = "Maraudon", -- Needs review
	MIDSUMMERFIREFESTIVAL = "Fête du Feu du solstice d'été",
	MINING = "Minage",
	MISCELLANEOUS = "Divers",
	MOGUSHANVAULTS = "Caveaux de Mogu'shan", -- Needs review
	MOLTENCORE = "Cœur du Magma", -- Needs review
	MOLTENFRONT = "Front du Magma",
	MONK = "Moine",
	MOONGLADE = "Reflet-de-Lune",
	MOUNTHYJAL = "Mont Hyjal",
	MULGORE = "Mulgore",
	NAGRAND = "Nagrand",
	NAXXRAMAS = "Naxxramas", -- Needs review
	NETHERSTORM = "Raz-de-Néant",
	NEWYEARSEVE = "Saint-Sylvestre",
	NOBLEGARDEN = "Le Jardin des nobles",
	NORTHERNBARRENS = "Tarides du Nord",
	NORTHERNSTRANGLETHORN = "Strangleronce septentrionale",
	NORTHREND = "Norfendre",
	OLDHILLSBRADFOOTHILLS = "Contreforts de Hautebrande d'antan", -- Needs review
	ONYXIASLAIR = "Repaire d'Onyxia", -- Needs review
	OPTIONS = "Options",
	ORGRIMMAR = "Orgrimmar",
	OUTLAND = "Outreterre",
	PALACEOFTHEHEAVENS = "Palace of the Heavens", -- Requires localization
	PALADIN = "Paladin",
	PANDARIA = "Pandarie",
	PERFORMSERVERQUERY = "Requêtes serveur en cours...",
	PILGRIMSBOUNTY = "Les Bienfaits du pèlerin",
	PITOFSARON = "Fosse de Saron", -- Needs review
	PRIEST = "Prêtre",
	PROFESSIONS = "Métiers",
	QUERYREQUESTED = "Une requête du serveur a été demandé ...",
	QUESTLISTFILTERS = "Filtres - liste de quêtes",
	QUESTSFOUND = "%d Quêtes trouvé",
	RAGEFIRECHASM = "Gouffre de Ragefeu", -- Needs review
	RAIDS = "Raids",
	RAZORFENDOWNS = "Souilles de Tranchebauge", -- Needs review
	RAZORFENKRAUL = "Kraal de Tranchebauge", -- Needs review
	REDRIDGEMOUNTAINS = "Les Carmines",
	ROGUE = "Voleur",
	RUINSOFAHNQIRAJ = "Ruines d'Ahn'Qiraj", -- Needs review
	RUINSOFGILNEAS = "Ruines de Gilnéas",
	RUINSOFGILNEASCITY = "Ruines de Gilnéas",
	SCARLETMONASTERY = "Monastère Écarlate", -- Needs review
	SCHOLOMANCE = "Scholomance", -- Needs review
	SEARINGGORGE = "Gorge des Vents brûlants",
	SEASONAL = "Saisonnier",
	SERPENTSHRINECAVERN = "Caverne du sanctuaire du Serpent", -- Needs review
	SETHEKKHALLS = "Les salles des Sethekk", -- Needs review
	SHADOPANMONASTERY = "Monastère des Pandashan", -- Needs review
	SHADOWFANGKEEP = "Donjon d'Ombrecroc", -- Needs review
	SHADOWLABYRINTH = "Labyrinthe des Ombres", -- Needs review
	SHADOWMOONVALLEY = "Vallée d'Ombrelune",
	SHAMAN = "Chaman",
	SHATTRATHCITY = "Shattrath",
	SHIMMERINGEXPANSE = "Étendues Chatoyantes",
	SHOLAZARBASIN = "Bassin de Sholazar",
	SHOWMAPICONS = "Show Map Icons", -- Needs review
	SIEGEOFNIUZAOTEMPLE = "Siège du Temple de Niuzao", -- Needs review
	SILITHUS = "Silithus",
	SILVERMOONCITY = "Lune-d'argent",
	SILVERPINEFOREST = "Forêt des Pins-Argentés",
	SILVERSHARDMINES = "Silver Shard Mines", -- Needs review
	SKINNING = "Dépeçage",
	SORTALPHA = "Trier: Par ordre alphabétique",
	SORTLEVEL = "Trier: Par niveau",
	SOUTHERNBARRENS = "Tarides du Sud",
	SPECIAL = "Special",
	SPECIALS = "Specials",
	STONETALONMOUNTAINS = "Les Serres-Rocheuses",
	STORMSTOUTBREWERY = "Brasserie Brune-d'orage", -- Needs review
	STORMWINDCITY = "Hurlevent",
	STRANDOFTHEANCIENTS = "Rivage des Anciens",
	STRANGLETHORNVALE = "Vallée de Strangleronce",
	STRATHOLME = "Stratholme", -- Needs review
	SUNKENTEMPLE = "Temple englouti", -- Needs review
	SUNWELLPLATEAU = "Plateau du Puits de soleil", -- Needs review
	SWAMPOFSORROWS = "Marais des Chagrins",
	TAILORING = "Couture",
	TANARIS = "Tanaris",
	TELDRASSIL = "Teldrassil",
	TEMPESTKEEP = "Donjon de la Tempête", -- Needs review
	TEMPLEOFAHNQIRAJ = "Temple d'Ahn'qiraj", -- Needs review
	TEMPLEOFKOTMOGU = "Temple de Kotmogu",
	TEMPLEOFTHEREDCRANE = "Temple du Crâne Rouge", -- Needs review
	TEROKKARFOREST = "Forêt de Terokkar",
	THEARCATRAZ = "L'Alcatraz", -- Needs review
	THEBASTIONOFTWILIGHT = "Le Bastion du Crépuscule", -- Needs review
	THEBATTLEFORGILNEAS = "La bataille de Gilnéas",
	THEBLACKMORASS = "Le Noir Marécage", -- Needs review
	THEBLOODFURNACE = "La Fournaise du sang", -- Needs review
	THEBOTANICA = "La Botanica", -- Needs review
	THECAPEOFSTRANGLETHORN = "Cap Strangleronce",
	THECULLINGOFSTRATHOLME = "L'épration de Stratholme", -- Needs review
	THEDEADMINES = "Les Mortemines", -- Needs review
	THEEXODAR = "L'Exodar",
	THEEYE = "Donjon de la Tempête", -- Needs review
	THEEYEOFETERNITY = "L'Oeil de l'Eternité", -- Needs review
	THEFORGEOFSOULS = "La Forges des Ames", -- Needs review
	THEGATEOFTHESETTINGSUN = "Porte du Soleil couchant", -- Needs review
	THEHALFHILLMARKET = "The Halfhill Market", -- Requires localization
	THEHINTERLANDS = "Les Hinterlands",
	THEJADEFOREST = "La forêt de Jade",
	THELOSTISLES = "Les îles Perdues",
	THEMAELSTROM = "Le Maelström",
	THEMECHANAR = "Le Méchanar", -- Needs review
	THENEXUS = "Le Nexus", -- Needs review
	THEOBSIDIANSANCTUM = "Le Sanctum Obsidien", -- Needs review
	THEOCULUS = "L'Oculus", -- Needs review
	THERUBYSANCTUM = "Le sanctum Rubis", -- Needs review
	THESHATTEREDHALLS = "Les salles Brisées", -- Needs review
	THESLAVEPENS = "Les enclos aux esclaves", -- Needs review
	THESTEAMVAULT = "Le caveau de la Vapeur", -- Needs review
	THESTOCKADE = "La Prison", -- Needs review
	THESTONECORE = "Le Cœur-de-Pierre", -- Needs review
	THESTORMPEAKS = "Les pics Foudroyés",
	THETEMPLEOFTHEJADESERPENT = "Temple du Serpent de Jade", -- Needs review
	THEUNDERBOG = "La Basse-tourbière", -- Needs review
	THEVEILEDSTAIR = "The Veiled Stair", -- Requires localization
	THEVIOLETHOLD = "Le fort Pourpre", -- Needs review
	THEVORTEXPINNACLE = "La cime du Vortex", -- Needs review
	THEWANDERINGISLE = "L'Île Vagabonde", -- Needs review
	THEZANDALARI = "Les Zandalari",
	THOUSANDNEEDLES = "Mille pointes",
	THRONEOFTHEFOURWINDS = "Trône des quatre vents", -- Needs review
	THRONEOFTHETIDES = "Trône des marées", -- Needs review
	THUNDERBLUFF = "Les Pitons-du-Tonnerre",
	TIRISFALGLADES = "Clairières de Tirisfal",
	TOLBARAD = "Tol Barad",
	TOLBARADPENINSULA = "Péninsule de Tol Barad",
	TOURNAMENT = "Tournoi",
	TOWNLONGSTEPPES = "Le désert de Tanglong",
	TRIALOFTHECHAMPION = "L'épreuve du champion", -- Needs review
	TRIALOFTHECRUSADER = "L'épreuve du croisé", -- Needs review
	TWILIGHTHIGHLANDS = "Hautes-terres du Crépuscule",
	TWINPEAKS = "Pics-Jumeaux",
	ULDAMAN = "Uldaman", -- Needs review
	ULDUAR = "Ulduar", -- Needs review
	ULDUM = "Uldum",
	UNDERCITY = "Fossoyeuse",
	UNGOROCRATER = "Cratère d'Un'Goro",
	UTGARDEKEEP = "Donjon d'Utgarde", -- Needs review
	UTGARDEPINNACLE = "Cime d'Utgarde", -- Needs review
	VALEOFETERNALBLOSSOMS = "La vallée de l'Éternel printemps",
	VALLEYOFTHEFOURWINDS = "La vallée des Quatre vents",
	VASHJIR = "Vashj'ir",
	VAULTOFARCHAVON = "Caveau d'Archavon", -- Needs review
	WAILINGCAVERNS = "Cavernes des Lamentations", -- Needs review
	WARLOCK = "Démoniste",
	WARRIOR = "Guerrier",
	WARSONGGULCH = "Goulet des Chanteguerres",
	WELLOFETERNITY = "Puits d’éternité", -- Needs review
	WESTERNPLAGUELANDS = "Maleterres de l'Ouest",
	WESTFALL = "Marche de l'Ouest",
	WETLANDS = "Les Paluns",
	WINTERGRASP = "Joug-d'hiver",
	WINTERSPRING = "Berceau-de-l'Hiver",
	WINTERVEIL = "Voile d'hiver",
	WORLDEVENTS = "Evénements Mondiaux",
	ZANGARMARSH = "Marécage de Zangar",
	ZULAMAN = "Zul'Aman", -- Needs review
	ZULDRAK = "Zul'Drak",
	ZULFARRAK = "Zul'Farrak", -- Needs review
	ZULGURUB = "Zul'Gurub", -- Needs review
}
end