if GetLocale() == "esES" then
qcLocalize = {
	ABYSSALDEPTHS = "Profundidades Abisales",
	AHNKAHETTHEOLDKINGDOM = "Ahn'Kalet: El Antiguo Reino", -- Needs review
	AHNQIRAJ = "Ahn'Qiraj", -- Needs review
	AHNQIRAJTHEFALLENKINGDOM = "Ahn'Qiraj: el Reino Caído",
	ALCHEMY = "Alquimia",
	ALTERACVALLEY = "Valle de Alterac",
	ARATHIBASIN = "Cuenca de Arathi", -- Needs review
	ARATHIHIGHLANDS = "Tierras Altas de Arathi",
	ARCHAEOLOGY = "Arqueología", -- Needs review
	ASHENVALE = "Vallefresno",
	AUCHENAICRYPTS = "Criptas Auchenai", -- Needs review
	AUCHINDOUN = "Auchindoun", -- Needs review
	AZJOLNERUB = "Azjol-Nerub", -- Needs review
	AZSHARA = "Azshara",
	AZUREMYSTISLE = "Isla Bruma Azur",
	BADLANDS = "Tierras Inhóspitas",
	BARADINHOLD = "Bastión de Baradin", -- Needs review
	BATTLEGROUNDS = "Campos de Batalla",
	BATTLEPETS = "Battle Pets", -- Requires localization
	BLACKFATHOMDEEPS = "Cavernas de Brazanegra", -- Needs review
	BLACKROCKCAVERNS = "Cavernas de Roca Negra", -- Needs review
	BLACKROCKDEPTHS = "Profundidades de Roca Negra", -- Needs review
	BLACKROCKSPIRE = "Cumbre de Roca Negra", -- Needs review
	BLACKSMITHING = "Herrería", -- Needs review
	BLACKTEMPLE = "Templo oscuro", -- Needs review
	BLACKWINGDESCENT = "Descenso de Alanegra", -- Needs review
	BLACKWINGLAIR = "Guarida de Alanegra", -- Needs review
	BLADESEDGEMOUNTAINS = "Montañas Filospada",
	BLASTEDLANDS = "Tierras Devastadas",
	BLOODMYSTISLE = "Isla Bruma de Sangre",
	BOREANTUNDRA = "Tundra Boreal",
	BREWFEST = "Fiesta de la Cerveza", -- Needs review
	BURNINGSTEPPES = "Estepas Ardientes",
	CAVERNSOFTIME = "Cavernas del tiempo", -- Needs review
	CHILDRENSWEEK = "Semana de los niños",
	CLASSES = "Clases",
	CLASSQUESTS = "Misiones de clase",
	CLEARUPDATECACHE = "Borrar caché de actualización", -- Needs review
	COILFANGRESERVOIR = "Reserva Colmillo Torcido", -- Needs review
	COMBINEDMAPANDQUESTFILTERS = "Filtros combinados de misiones y mapas", -- Needs review
	CONFIGSUBTITLE = "Estas opciones permiten modificar cómo Quest Completist maneja y filtra los datos", -- Needs review
	CONFIGTITLE = "Quest Completist - Configuración", -- Needs review
	CONTINENTS = "Continentes", -- Needs review
	COOKING = "Cocina",
	CRYSTALSONGFOREST = "Bosque Canto de Cristal",
	DALARAN = "Dalaran",
	DARKMOONFAIRE = "Feria de la Luna Negra", -- Needs review
	DARKSHORE = "Costa Oscura",
	DARNASSUS = "Darnassus",
	DAYOFTHEDEAD = "Festividad de los Muertos", -- Needs review
	DEADWINDPASS = "Paso de la Muerte",
	DEATHKNIGHT = "Caballero de la Muerte",
	DEEPHOLM = "Infralar",
	DEEPRUNTRAM = "Tranvía Subterráneo", -- Needs review
	DESOLACE = "Desolace",
	DIREMAUL = "La Masacre", -- Needs review
	DRAGONBLIGHT = "Cementerio de Dragones",
	DRAGONSOUL = "Alma de Dragón", -- Needs review
	DRAKTHARONKEEP = "Fortaleza de Drak'Tharon", -- Needs review
	DREADWASTES = "Desierto del Pavor", -- Needs review
	DRUID = "Druida",
	DUNGEONSANDRAIDS = "Mazmorras y Bandas", -- Needs review
	DUNMOROGH = "Dun Morogh",
	DUROTAR = "Durotar",
	DUSKWOOD = "Bosque Oscuro",
	DUSTWALLOWMARSH = "Marjal Revolcafango", -- Needs review
	EASTERNKINGDOMS = "Reinos del Este",
	EASTERNPLAGUELANDS = "Tierras de la Peste del Este",
	ELEMENTALBONDS = "Vínculos elementales", -- Needs review
	ELWYNNFOREST = "Bosque de Elwynn",
	ENCHANTING = "Encantamiento",
	ENDTIME = "Fin de los tiempos", -- Needs review
	ENGINEERING = "Ingenieria",
	EVERSONGWOODS = "Bosque Canción Eterna",
	EYEOFTHESTORM = "Ojo de la Tormenta", -- Needs review
	FELWOOD = "Frondavil", -- Needs review
	FERALAS = "Feralas", -- Needs review
	FIRELANDS = "Tierras de Fuego", -- Needs review
	FIRELANDSINVASION = "Invasión de las Tierras de Fuego", -- Needs review
	FIRSTAID = "Primeros Auxilios",
	FISHING = "Pesca",
	GHOSTLANDS = "Tierras Fantasma",
	GILNEAS = "Gilneas", -- Needs review
	GILNEASCITY = "Ciudad de Gilneas",
	GNOMEREGAN = "Gnomeregan", -- Needs review
	GRIMBATOL = "Grim Batol", -- Needs review
	GRIZZLYHILLS = "Colinas Pardas",
	GRUULSLAIR = "Guarida de Gruul", -- Needs review
	GUNDRAK = "Gundrak", -- Needs review
	HALLOWSEND = "Halloween", -- Needs review
	HALLSOFLIGHTNING = "Cámaras de Relámpagos", -- Needs review
	HALLSOFORIGINATION = "Cámaras de los Orígenes", -- Needs review
	HALLSOFREFLECTION = "Cámaras de Reflexión", -- Needs review
	HALLSOFSTONE = "Cámaras de Piedra", -- Needs review
	HARVESTFESTIVAL = "Festival de la Cosecha",
	HELLFIRECITADEL = "Ciudadela del Fuego Infernal", -- Needs review
	HELLFIREPENINSULA = "Península del Fuego Infernal",
	HELLFIRERAMPARTS = "Murallas del Fuego Infernal", -- Needs review
	HERBALISM = "Herboristería", -- Needs review
	HIDECOMPLETEDQUESTS = "Ocultar misiones completadas", -- Needs review
	HIDEINPROGRESSQUESTS = "Ocultar misiones en curso", -- Needs review
	HIDELOWLEVELQUESTS = "Ocultar misiones de nivel bajo", -- Needs review
	HIDENONACTIVESEASONALQUESTS = "Esconder misiones de eventos inactivos", -- Needs review
	HIDEOTHERFACTIONQUESTS = "Esconder otras misiones de facción", -- Needs review
	HIDEOTHERPROFESSIONQUESTS = "Esconder otras misiones de profesión", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "Esconder otras misiones de clase/raza", -- Needs review
	HILLSBRADFOOTHILLS = "Laderas de Trabalomas",
	HOUROFTWILIGHT = "Hora del Crepusculo", -- Needs review
	HOWLINGFJORD = "Fiordo Aquilonal", -- Needs review
	HROTHGARSLANDING = "Desembarco de Hrothgar", -- Needs review
	HUNTER = "Cazador",
	HYJALSUMMIT = "Cima Hyjal", -- Needs review
	ICECROWN = "Corona de Hielo", -- Needs review
	ICECROWNCITADEL = "Ciudadela de la Corona de Hielo", -- Needs review
	INSCRIPTION = "Inscripción", -- Needs review
	IRONFORGE = "Forjaz", -- Needs review
	ISLEOFCONQUEST = "Isla de la Conquista",
	ISLEOFQUELDANAS = "Isla de Quel'Danas", -- Needs review
	JEWELCRAFTING = "Joyería", -- Needs review
	KALIMDOR = "Kalimdor",
	KARAZHAN = "Karazhan", -- Needs review
	KELPTHARFOREST = "Bosque Kelp'thar", -- Needs review
	KEZAN = "Kezan", -- Needs review
	KRASARANGWILDS = "Espesura Krasarang", -- Needs review
	KUNLAISUMMIT = "Cima Kun-Lai", -- Needs review
	LEATHERWORKING = "Peleteria", -- Needs review
	LEGENDARY = "Legendario", -- Needs review
	LOCHMODAN = "Loch Modan", -- Needs review
	LOSTCITYOFTHETOLVIR = "Ciudad Perdida de los Tol'vir", -- Needs review
	LOVEISINTHEAIR = "El amor esta en el aire", -- Needs review
	LUNARFESTIVAL = "Festival Lunar", -- Needs review
	MAGE = "Mago", -- Needs review
	MAGISTERSTERRACE = "Bancal del Magíster", -- Needs review
	MAGTHERIDONSLAIR = "Guarida de Magtheridon", -- Needs review
	MANATOMBS = "Tumbas de Maná", -- Needs review
	MAPFILTERS = "Filtros de mapa", -- Needs review
	MARAUDON = "Maraudon", -- Needs review
	MIDSUMMERFIREFESTIVAL = "Festival de Fuego del Solsticio de Verano", -- Needs review
	MINING = "Minería", -- Needs review
	MISCELLANEOUS = "Varios", -- Needs review
	MOGUSHANVAULTS = "Cámaras Mogu'shan", -- Needs review
	MOLTENCORE = "Núcleo de Magma", -- Needs review
	MOLTENFRONT = "Frente de Magma", -- Needs review
	MONK = "Monje", -- Needs review
	MOONGLADE = "Claro de la Luna", -- Needs review
	MOUNTHYJAL = "Monte Hyjal", -- Needs review
	MULGORE = "Mulgore",
	NAGRAND = "Nagrand", -- Needs review
	NAXXRAMAS = "Naxxramas", -- Needs review
	NETHERSTORM = "Tormenta Abisal", -- Needs review
	NEWYEARSEVE = "Nochevieja", -- Needs review
	NOBLEGARDEN = "Jardín Noble", -- Needs review
	NORTHERNBARRENS = "Baldíos del Norte",
	NORTHERNSTRANGLETHORN = "Norte de la Vega de Tuercespina", -- Needs review
	NORTHREND = "Rasganorte",
	OLDHILLSBRADFOOTHILLS = "Antiguas Laderas de Trabalomas", -- Needs review
	ONYXIASLAIR = "Guarida de Onyxia", -- Needs review
	OPTIONS = "Opciones", -- Needs review
	ORGRIMMAR = "Orgrimmar",
	OUTLAND = "Terrallende",
	PALACEOFTHEHEAVENS = "Palacio de los Cielos", -- Needs review
	PALADIN = "Paladín", -- Needs review
	PANDARIA = "Pandaria", -- Needs review
	PERFORMSERVERQUERY = "Enviar consulta al servidor...", -- Needs review
	PILGRIMSBOUNTY = "Generosidad del Peregrino", -- Needs review
	PITOFSARON = "Foso de Saron", -- Needs review
	PRIEST = "Sacerdote", -- Needs review
	PROFESSIONS = "Profesiones", -- Needs review
	QUERYREQUESTED = "Se ha enviado una consulta al servidor...", -- Needs review
	QUESTLISTFILTERS = "Filtros de lista de misiones", -- Needs review
	QUESTSFOUND = "%d misiones encontradas", -- Needs review
	RAGEFIRECHASM = "Sima Ígnea", -- Needs review
	RAIDS = "Bandas", -- Needs review
	RAZORFENDOWNS = "Zahúrda Rajacieno", -- Needs review
	RAZORFENKRAUL = "Horado Rajacieno", -- Needs review
	REDRIDGEMOUNTAINS = "Montañas Crestagrana", -- Needs review
	ROGUE = "Picaro", -- Needs review
	RUINSOFAHNQIRAJ = "Ruinas de Ahn'Qiraj", -- Needs review
	RUINSOFGILNEAS = "Ruinas de Gilneas", -- Needs review
	RUINSOFGILNEASCITY = "Ruinas de la Ciudad de Gilneas", -- Needs review
	SCARLETMONASTERY = "Monasterio Escarlata", -- Needs review
	SCHOLOMANCE = "Scholomance", -- Needs review
	SEARINGGORGE = "Garganta de Fuego", -- Needs review
	SEASONAL = "Vacacionales", -- Needs review
	SERPENTSHRINECAVERN = "Caverna Santuario Serpiente", -- Needs review
	SETHEKKHALLS = "Salas Sethekk", -- Needs review
	SHADOPANMONASTERY = "Monasterio Shado-Pan", -- Needs review
	SHADOWFANGKEEP = "Castillo del Colmillo Oscuro", -- Needs review
	SHADOWLABYRINTH = "Laberinto de las Sombras", -- Needs review
	SHADOWMOONVALLEY = "Valle Sombraluna", -- Needs review
	SHAMAN = "Chamán", -- Needs review
	SHATTRATHCITY = "Ciudad de Shattrath", -- Needs review
	SHIMMERINGEXPANSE = "Extensión Bruñida", -- Needs review
	SHOLAZARBASIN = "Cuenca de Sholazar", -- Needs review
	SHOWMAPICONS = "Mostrar iconos del mapa", -- Needs review
	SIEGEOFNIUZAOTEMPLE = "Asedio del Templo Niuzao", -- Needs review
	SILITHUS = "Silithus",
	SILVERMOONCITY = "Ciudad de Lunargenta", -- Needs review
	SILVERPINEFOREST = "Bosque de Argénteos", -- Needs review
	SILVERSHARDMINES = "Mina de Lonjaplata", -- Needs review
	SKINNING = "Desuello", -- Needs review
	SORTALPHA = "Ordenar: alfabéticamente", -- Needs review
	SORTLEVEL = "Ordenar: por nivel", -- Needs review
	SOUTHERNBARRENS = "Baldíos del Sur", -- Needs review
	SPECIAL = "Especial", -- Needs review
	SPECIALS = "Especiales", -- Needs review
	STONETALONMOUNTAINS = "Sierra Espolón", -- Needs review
	STORMSTOUTBREWERY = "Taberna Cerveza de Trueno", -- Needs review
	STORMWINDCITY = "Ciudad de Ventormenta", -- Needs review
	STRANDOFTHEANCIENTS = "Playa de los Ancestros", -- Needs review
	STRANGLETHORNVALE = "Vega de Tuercespina", -- Needs review
	STRATHOLME = "Stratholme", -- Needs review
	SUNKENTEMPLE = "Templo Sumergido", -- Needs review
	SUNWELLPLATEAU = "Meseta de La Fuente del Sol", -- Needs review
	SWAMPOFSORROWS = "Pantano de las Penas", -- Needs review
	TAILORING = "Sastrería", -- Needs review
	TANARIS = "Tanaris", -- Needs review
	TELDRASSIL = "Teldrassil", -- Needs review
	TEMPESTKEEP = "Castillo de la Tempestad", -- Needs review
	TEMPLEOFAHNQIRAJ = "Templo de Ahn'Qiraj", -- Needs review
	TEMPLEOFKOTMOGU = "Templo de Kotmogu", -- Needs review
	TEMPLEOFTHEREDCRANE = "Templo de la Grulla Roja", -- Needs review
	TEROKKARFOREST = "Bosque de Terokkar", -- Needs review
	THEARCATRAZ = "El Arcatraz", -- Needs review
	THEBASTIONOFTWILIGHT = "Bastión del Crepúsculo", -- Needs review
	THEBATTLEFORGILNEAS = "La Batalla por Gilneas", -- Needs review
	THEBLACKMORASS = "La Ciénaga Negra", -- Needs review
	THEBLOODFURNACE = "El Horno de Sangre", -- Needs review
	THEBOTANICA = "El Invernáculo", -- Needs review
	THECAPEOFSTRANGLETHORN = "El Cabo de Tuercespina", -- Needs review
	THECULLINGOFSTRATHOLME = "La Matanza de Stratholme", -- Needs review
	THEDEADMINES = "Las Minas de la Muerte", -- Needs review
	THEEXODAR = "El Exodar", -- Needs review
	THEEYE = "El Ojo", -- Needs review
	THEEYEOFETERNITY = "El Ojo de la Eternidad", -- Needs review
	THEFORGEOFSOULS = "La Forja de Almas", -- Needs review
	THEGATEOFTHESETTINGSUN = "Puerta del Sol Poniente", -- Needs review
	THEHALFHILLMARKET = "The Halfhill Market", -- Requires localization
	THEHINTERLANDS = "Tierras del Interior", -- Needs review
	THEJADEFOREST = "Bosque de Jade", -- Needs review
	THELOSTISLES = "Las Islas Perdidas", -- Needs review
	THEMAELSTROM = "La Vorágine", -- Needs review
	THEMECHANAR = "El Mechanar", -- Needs review
	THENEXUS = "El Nexo", -- Needs review
	THEOBSIDIANSANCTUM = "El Sagrario Obsidiana", -- Needs review
	THEOCULUS = "El Oculus", -- Needs review
	THERUBYSANCTUM = "El Sagrario Rubí", -- Needs review
	THESHATTEREDHALLS = "Las Salas Arrasadas", -- Needs review
	THESLAVEPENS = "Recinto de los Esclavos", -- Needs review
	THESTEAMVAULT = "La Cámara de Vapor", -- Needs review
	THESTOCKADE = "Las Mazmorras", -- Needs review
	THESTONECORE = "Núcleo Pétreo", -- Needs review
	THESTORMPEAKS = "Cumbres Tormentosas", -- Needs review
	THETEMPLEOFTHEJADESERPENT = "Templo del Dragón de Jade", -- Needs review
	THEUNDERBOG = "La Sotiénaga", -- Needs review
	THEVEILEDSTAIR = "The Veiled Stair", -- Requires localization
	THEVIOLETHOLD = "Bastión Violeta", -- Needs review
	THEVORTEXPINNACLE = "Cumbre del Vórtice", -- Needs review
	THEWANDERINGISLE = "La Isla Errante", -- Needs review
	THEZANDALARI = "Los Zandalari", -- Needs review
	THOUSANDNEEDLES = "Mil Agujas",
	THRONEOFTHEFOURWINDS = "Trono de los Cuatro Vientos", -- Needs review
	THRONEOFTHETIDES = "Trono de las Mareas", -- Needs review
	THUNDERBLUFF = "Cima del Trueno",
	TIRISFALGLADES = "Claros de Tirisfal", -- Needs review
	TOLBARAD = "Tol Barad", -- Needs review
	TOLBARADPENINSULA = "Península de Tol Barad", -- Needs review
	TOURNAMENT = "Torneo", -- Needs review
	TOWNLONGSTEPPES = "Desierto de Tong Long", -- Needs review
	TRIALOFTHECHAMPION = "Prueba del Campeón", -- Needs review
	TRIALOFTHECRUSADER = "Prueba del Cruzado", -- Needs review
	TWILIGHTHIGHLANDS = "Tierras Altas Crepusculares", -- Needs review
	TWINPEAKS = "Cumbres Gemelas", -- Needs review
	ULDAMAN = "Uldaman", -- Needs review
	ULDUAR = "Ulduar", -- Needs review
	ULDUM = "Uldum",
	UNDERCITY = "Entrañas", -- Needs review
	UNGOROCRATER = "Cráter de Un'Goro",
	UTGARDEKEEP = "Fortaleza de Utgarde", -- Needs review
	UTGARDEPINNACLE = "Pináculo de Utgarde", -- Needs review
	VALEOFETERNALBLOSSOMS = "Valle Flor Eterna", -- Needs review
	VALLEYOFTHEFOURWINDS = "Valle de los Cuatro Vientos", -- Needs review
	VASHJIR = "Vashj'ir", -- Needs review
	VAULTOFARCHAVON = "Cámara de Archavon", -- Needs review
	WAILINGCAVERNS = "Cuevas de los Lamentos", -- Needs review
	WARLOCK = "Brujo",
	WARRIOR = "Guerrero",
	WARSONGGULCH = "Garganta Grito de Guerra",
	WELLOFETERNITY = "Pozo de la Eternidad", -- Needs review
	WESTERNPLAGUELANDS = "Tierras de la Peste del Oeste", -- Needs review
	WESTFALL = "Páramos de Poniente", -- Needs review
	WETLANDS = "Los Humedales", -- Needs review
	WINTERGRASP = "Conquista del Invierno", -- Needs review
	WINTERSPRING = "Cuna del Invierno",
	WINTERVEIL = "Festival de Invierno", -- Needs review
	WORLDEVENTS = "Eventos del Mundo", -- Needs review
	ZANGARMARSH = "Marisma de Zangar", -- Needs review
	ZULAMAN = "Zul'Aman", -- Needs review
	ZULDRAK = "Zul'Drak", -- Needs review
	ZULFARRAK = "Zul'Farrak", -- Needs review
	ZULGURUB = "Zul'Gurub", -- Needs review
}
end