local _, ns = ...

-- Translations specific to the Chidlren's Week AddOn
if ns.locale == "deDE" then
	ns.L["AddOn Description"] = "%eHilfe für Erfolge und Quests in %sKinderwoche"
	ns.L["Bad Example"] = "Schlechtes Vorbild"
	ns.L["Cupcake"] = "Cupcake"
	ns.L["Flavour"] = "Geschmack"
	ns.L["For the Children"] = "Ein Herz für Kinder"
	ns.L["Icecream Cone"] = "Eistüte"
	ns.L["Children's Week"] = "Kinderwoche"
	ns.L["Orphan"] = "Waise"
	ns.L["Pet Parade"] = "Haustierparade"
	ns.L["Related"] = "Verwandte Themen"
	ns.L["Teddy Bear"] = "Teddybär"
	ns.L["Toy Train"] = "Spielzeugeisenbahn"

elseif ns.locale == "esES" or ns.locale == "esMX" then
	ns.L["AddOn Description"] = "%eAyuda para logros y misiones en %sSemana de los Niños"
	ns.L["Bad Example"] = "Mal ejemplo"
	ns.L["Cupcake"] = "Magdalena"
	ns.L["Children's Week"] = "Semana de los Niños"
	ns.L["Flavour"] = "Sabor"
	ns.L["For the Children"] = "Para los niños"
	ns.L["Icecream Cone"] = "Cono de helado"
	ns.L["Orphan"] = "Huérfano"
	ns.L["Pet Parade"] = "Desfile de Mascotas"
	ns.L["Related"] = "Relacionado"
	ns.L["Teddy Bear"] = "Oso de peluche"
	ns.L["Toy Train"] = "Tren de juguete"

elseif ns.locale == "frFR" then
	ns.L["AddOn Description"] = "%eAide pour les réalisations et les quêtes dans %sSemaine des enfantss"
	ns.L["Bad Example"] = "Montrer le mauvais exemple"
	ns.L["Cupcake"] = "Cupcake"
	ns.L["Children's Week"] = "Semaine des enfants"
	ns.L["Flavour"] = "Saveur"
	ns.L["For the Children"] = "Les enfants d'abord"
	ns.L["Icecream Cone"] = "Cornet de glace"
	ns.L["Orphan"] = "Orphelin"
	ns.L["Pet Parade"] = "arade d'animaux"
	ns.L["Related"] = "Connexes"
	ns.L["Teddy Bear"] = "Ours en peluche"
	ns.L["Toy Train"] = "Petit train"

elseif ns.locale == "itIT" then
	ns.L["AddOn Description"] = "%eAiuto per obiettivi e missioni in %sSettimana dei Bambini"
	ns.L["Bad Example"] = "Cattivo esempio"
	ns.L["Cupcake"] = "Cupcake"
	ns.L["Children's Week"] = "Settimana dei Bambini"
	ns.L["Flavour"] = "Gusto"
	ns.L["For the Children"] = "Per i bambini"
	ns.L["Icecream Cone"] = "Cono gelato"
	ns.L["Orphan"] = "Orfano"
	ns.L["Pet Parade"] = "Parata di animali domestici"
	ns.L["Related"] = "Correlati"
	ns.L["Teddy Bear"] = "Orsacchiotto"
	ns.L["Toy Train"] = "Trenino"

elseif ns.locale == "koKR" then
	ns.L["AddOn Description"] = "%s어린이 주간정원%e 업적 및 퀘스트에 대한 도움말"	
	ns.L["Bad Example"] = "나쁜 본보기"
	ns.L["Cupcake"] = "컵케이크"
	ns.L["Children's Week"] = "어린이 주간"
	ns.L["Flavour"] = "맛"
	ns.L["For the Children"] = "어린이는 우리의 희망"
	ns.L["Icecream Cone"] = "아이스크림 콘"
	ns.L["Orphan"] = "고아"
	ns.L["Pet Parade"] = "펫 퍼레이드"
	ns.L["Related"] = "관련"
	ns.L["Teddy Bear"] = "테디베어"
	ns.L["Toy Train"] = "장난감 기차"
	ns.L["Utgarde"] = "우트가드"
		
elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	ns.L["AddOn Description"] = "%eAjuda para conquistas e missões em %sSemana das Crianças"
	ns.L["Bad Example"] = "Mau exemplo"
	ns.L["Cupcake"] = "Cupcake"
	ns.L["Children's Week"] = "Semana das Crianças"
	ns.L["Flavour"] = "Sabor"
	ns.L["For the Children"] = "Pelas criancinhas"
	ns.L["Icecream Cone"] = "Casquinha de sorvete"
	ns.L["Orphan"] = "Órfão"
	ns.L["Pet Parade"] = "Desfile de Animais de Estimação"
	ns.L["Related"] = "Relacionado"
	ns.L["Teddy Bear"] = "Ursinho de pelúcia"
	ns.L["Toy Train"] = "Trem de brinquedo"

elseif ns.locale == "ruRU" then
	ns.ns.L["AddOn Description"] = "%eСправка по достижениям и квестам в %sДетская неделя"
	ns.L["Bad Example"] = "Дурной пример"
	ns.L["Cupcake"] = "Кекс"
	ns.L["Children's Week"] = "Детская неделя"
	ns.L["Flavour"] = "Вкус"
	ns.L["For the Children"] = "Все лучшее – детям"
	ns.L["Icecream Cone"] = "Мороженое в рожке"
	ns.L["Orphan"] = "Сирота"
	ns.L["Pet Parade"] = "Парад домашних животных"
	ns.L["Related"] = "Связанный"
	ns.L["Teddy Bear"] = "Плюшевый мишка"
	ns.L["Toy Train"] = "Игрушечный поезд"
	ns.L["Utgarde"] = "Утгард"

elseif ns.locale == "zhCN" then
	ns.L["AddOn Description"] = "%e帮助%s儿童周%e的成就和任务"
	ns.L["Bad Example"] = "坏榜样"
	ns.L["Cupcake"] = "纸杯蛋糕"
	ns.L["Children's Week"] = "儿童周"
	ns.L["Flavour"] = "口味"
	ns.L["For the Children"] = "为了孩子"
	ns.L["Icecream Cone"] = "冰淇淋蛋筒"
	ns.L["Orphan"] = "孤儿"
	ns.L["Pet Parade"] = "宠物游行"
	ns.L["Related"] = "相关"
	ns.L["Teddy Bear"] = "泰迪熊"
	ns.L["Toy Train"] = "玩具火车"
	ns.L["Utgarde"] = "乌特加德"

elseif ns.locale == "zhTW" then
	ns.L["AddOn Description"] = "%e幫助%s兒童週%e的成就和任務"
	ns.L["Bad Example"] = "壞榜樣"
	ns.L["Cupcake"] = "紙杯蛋糕"
	ns.L["Children's Week"] = "兒童週"
	ns.L["Flavour"] = "味道"
	ns.L["For the Children"] = "為了孩子們"
	ns.L["Icecream Cone"] = "冰淇淋蛋筒"
	ns.L["Orphan"] = "孤兒"
	ns.L["Pet Parade"] = "寵物遊行"
	ns.L["Related"] = "有關的"
	ns.L["Teddy Bear"] = "玩具熊"
	ns.L["Toy Train"] = "玩具火車"
	ns.L["Utgarde"] = "俄特加德"
	
else
	ns.L["AddOn Description"] = "%eHelp for the %sChildren's Week%e achievements and quests"
end