-- (c) 2007 Nymbia.  see LGPLv2.1.txt for full details.
--DO NOT MAKE CHANGES TO THIS FILE BEFORE READING THE WIKI PAGE REGARDING CHANGING THESE FILES
if not LibStub("LibPeriodicTable-3.1", true) then error("PT3 must be loaded before data") end
LibStub("LibPeriodicTable-3.1"):AddData("TradeskillResultMats", gsub("$Rev: 436 $", "(%d+)", function(n) return n+90000 end), {
	["TradeskillResultMats.Forward.Alchemy"]="",
	["TradeskillResultMats.Forward.Blacksmithing"]="",
	["TradeskillResultMats.Forward.Cooking.Basic"]="",
	["TradeskillResultMats.Forward.Cooking.Way of the Brew"]="",
	["TradeskillResultMats.Forward.Cooking.Way of the Grill"]="",
	["TradeskillResultMats.Forward.Cooking.Way of the Oven"]="",
	["TradeskillResultMats.Forward.Cooking.Way of the Pot"]="",
	["TradeskillResultMats.Forward.Cooking.Way of the Steamer"]="",
	["TradeskillResultMats.Forward.Cooking.Way of the Wok"]="",
	["TradeskillResultMats.Forward.Enchanting"]="",
	["TradeskillResultMats.Forward.Engineering.Basic"]="",
	["TradeskillResultMats.Forward.Engineering.Gnomish"]="",
	["TradeskillResultMats.Forward.Engineering.Goblin"]="",
	["TradeskillResultMats.Forward.First Aid"]="",
	["TradeskillResultMats.Forward.Inscription"]="",
	["TradeskillResultMats.Forward.Jewelcrafting"]="",
	["TradeskillResultMats.Forward.Leatherworking"]="",
	["TradeskillResultMats.Forward.Smelting"]="",
	["TradeskillResultMats.Forward.Tailoring"]="",

	["TradeskillResultMats.Reverse.Alchemy"]="",
	["TradeskillResultMats.Reverse.Blacksmithing"]="",
	["TradeskillResultMats.Reverse.Cooking.Basic"]="",
	["TradeskillResultMats.Reverse.Cooking.Way of the Brew"]="",
	["TradeskillResultMats.Reverse.Cooking.Way of the Grill"]="",
	["TradeskillResultMats.Reverse.Cooking.Way of the Oven"]="",
	["TradeskillResultMats.Reverse.Cooking.Way of the Pot"]="",
	["TradeskillResultMats.Reverse.Cooking.Way of the Steamer"]="",
	["TradeskillResultMats.Reverse.Cooking.Way of the Wok"]="",
	["TradeskillResultMats.Reverse.Enchanting"]="",
	["TradeskillResultMats.Reverse.Engineering.Basic"]="",
	["TradeskillResultMats.Reverse.Engineering.Gnomish"]="",
	["TradeskillResultMats.Reverse.Engineering.Goblin"]="",
	["TradeskillResultMats.Reverse.First Aid"]="",
	["TradeskillResultMats.Reverse.Inscription"]="",
	["TradeskillResultMats.Reverse.Jewelcrafting"]="",
	["TradeskillResultMats.Reverse.Leatherworking"]="",
	["TradeskillResultMats.Reverse.Smelting"]="",
	["TradeskillResultMats.Reverse.Tailoring"]="",
})
