--[[
************************************************************************
itIT.lua
itIT localization strings for Ackis Recipe List
************************************************************************
File date: 2012-08-18T04:52:05Z 
File revision: @file-revision@ 
Project revision: @project-revision@
Project version: 2.4
************************************************************************
Original translated by: Pettigrow
Currently maintained by:
http://www.wowace.com/addons/arl/localization/translators/

Please update http://www.wowace.com/addons/arl/localization/itIT/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.

Please make sure you update the ToC file with any translations.
************************************************************************
Please see http://www.wowace.com/addons/arl/ for more information.
************************************************************************
These translations are released under the Public Domain.
************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Ackis Recipe List", "itIT", false)

if not L then return end

L["Quest"] = "Missione"
