local AL = LibStub:GetLibrary("AchievementLocations-1.0")
local function A(row) AL:AddLocation(row) end

-- World Events: Pilgrim
A{"SethekkHalls", 3478, 0.3260, 0.2760, criterion=11272, floor=2, season="Pilgrim's Bounty", trivia={criteria="Terokkar Turkey Time", module="seasonal_pilgrim", category="World Events", name="Pilgrim", description="Complete the Pilgrim's Bounty achievements listed below.", mapID="SethekkHalls_HallsOfMourning", uiMapID=259, points=10, type="achievement"}}
A{"unknown", 3478, criterion=11266, season="Pilgrim's Bounty", trivia={criteria="\"FOOD FIGHT!\"", module="seasonal_pilgrim", category="World Events", name="Pilgrim", description="Complete the Pilgrim's Bounty achievements listed below.", points=10, type="achievement"}}
A{"unknown", 3478, criterion=11271, season="Pilgrim's Bounty", trivia={criteria="Sharing is Caring", module="seasonal_pilgrim", category="World Events", name="Pilgrim", description="Complete the Pilgrim's Bounty achievements listed below.", points=10, type="achievement"}}
A{"unknown", 3478, criterion=11273, season="Pilgrim's Bounty", trivia={criteria="The Turkinator", module="seasonal_pilgrim", category="World Events", name="Pilgrim", description="Complete the Pilgrim's Bounty achievements listed below.", points=10, type="achievement"}}
A{"unknown", 3478, criterion=11274, season="Pilgrim's Bounty", trivia={criteria="Turkey Lurkey", module="seasonal_pilgrim", category="World Events", name="Pilgrim", description="Complete the Pilgrim's Bounty achievements listed below.", points=10, type="achievement"}}
A{"unknown", 3478, criterion=11267, season="Pilgrim's Bounty", trivia={criteria="Now We're Cookin'", module="seasonal_pilgrim", category="World Events", name="Pilgrim", description="Complete the Pilgrim's Bounty achievements listed below.", points=10, type="achievement"}}
A{"unknown", 3478, criterion=11259, season="Pilgrim's Bounty", trivia={criteria="Pilgrim's Paunch", module="seasonal_pilgrim", category="World Events", name="Pilgrim", description="Complete the Pilgrim's Bounty achievements listed below.", points=10, type="achievement"}}
A{"unknown", 3478, criterion=11260, season="Pilgrim's Bounty", trivia={criteria="Pilgrim's Peril", module="seasonal_pilgrim", category="World Events", name="Pilgrim", description="Complete the Pilgrim's Bounty achievements listed below.", points=10, type="achievement"}}
A{"unknown", 3478, criterion=11261, season="Pilgrim's Bounty", trivia={criteria="Pilgrim's Progress", module="seasonal_pilgrim", category="World Events", name="Pilgrim", description="Complete the Pilgrim's Bounty achievements listed below.", points=10, type="achievement"}}

-- World Events/Pilgrim's Bounty: Pilgrim's Paunch
A{"unknown", 3556, criterion=11080, side="alliance", season="Pilgrim's Bounty", trivia={criteria="The Exodar", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Paunch", description="Acquire the Spirit of Sharing from a complete Bountiful Table feast at every Alliance capital.", points=10, parent="World Events", type=69}}
A{"unknown", 3556, criterion=11081, side="alliance", season="Pilgrim's Bounty", trivia={criteria="Stormwind", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Paunch", description="Acquire the Spirit of Sharing from a complete Bountiful Table feast at every Alliance capital.", points=10, parent="World Events", type=69}}
A{"unknown", 3556, criterion=11078, side="alliance", season="Pilgrim's Bounty", trivia={criteria="Darnassus", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Paunch", description="Acquire the Spirit of Sharing from a complete Bountiful Table feast at every Alliance capital.", points=10, parent="World Events", type=69}}
A{"unknown", 3556, criterion=11079, side="alliance", season="Pilgrim's Bounty", trivia={criteria="Ironforge", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Paunch", description="Acquire the Spirit of Sharing from a complete Bountiful Table feast at every Alliance capital.", points=10, parent="World Events", type=69}}

-- World Events/Pilgrim's Bounty: Pilgrim's Paunch
A{"unknown", 3557, criterion=11085, side="horde", season="Pilgrim's Bounty", trivia={criteria="Undercity", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Paunch", description="Acquire the Spirit of Sharing from a complete Bountiful Table feast at every Horde capital.", points=10, parent="World Events", type=69}}
A{"unknown", 3557, criterion=11084, side="horde", season="Pilgrim's Bounty", trivia={criteria="Thunder Bluff", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Paunch", description="Acquire the Spirit of Sharing from a complete Bountiful Table feast at every Horde capital.", points=10, parent="World Events", type=69}}
A{"unknown", 3557, criterion=11082, side="horde", season="Pilgrim's Bounty", trivia={criteria="Orgrimmar", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Paunch", description="Acquire the Spirit of Sharing from a complete Bountiful Table feast at every Horde capital.", points=10, parent="World Events", type=69}}
A{"unknown", 3557, criterion=11083, side="horde", season="Pilgrim's Bounty", trivia={criteria="Silvermoon City", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Paunch", description="Acquire the Spirit of Sharing from a complete Bountiful Table feast at every Horde capital.", points=10, parent="World Events", type=69}}

-- World Events/Pilgrim's Bounty: Sharing is Caring
A{"unknown", 3558, criterion=11167, season="Pilgrim's Bounty", trivia={criteria="Cranberry Chutney", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Sharing is Caring", description="Pass one of every dish at a Bountiful Table.", points=10, parent="World Events", type=29}}
A{"unknown", 3558, criterion=11086, season="Pilgrim's Bounty", trivia={criteria="Candied Sweet Potatoes", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Sharing is Caring", description="Pass one of every dish at a Bountiful Table.", points=10, parent="World Events", type=29}}
A{"unknown", 3558, criterion=11088, season="Pilgrim's Bounty", trivia={criteria="Pumpkin Pie", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Sharing is Caring", description="Pass one of every dish at a Bountiful Table.", points=10, parent="World Events", type=29}}
A{"unknown", 3558, criterion=11089, season="Pilgrim's Bounty", trivia={criteria="Slow-Roasted Turkey", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Sharing is Caring", description="Pass one of every dish at a Bountiful Table.", points=10, parent="World Events", type=29}}
A{"unknown", 3558, criterion=11090, season="Pilgrim's Bounty", trivia={criteria="Spice Bread Stuffing", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Sharing is Caring", description="Pass one of every dish at a Bountiful Table.", points=10, parent="World Events", type=29}}

-- World Events/Pilgrim's Bounty: Turkey Lurkey
A{"unknown", 3559, criterion=11158, season="Pilgrim's Bounty", trivia={criteria="Human Rogue", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Turkey Lurkey", description="Blast those dirty, sneaking Rogues with your Turkey Shooter.", points=10, parent="World Events", type=110}}
A{"unknown", 3559, criterion=11160, season="Pilgrim's Bounty", trivia={criteria="Orc Rogue", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Turkey Lurkey", description="Blast those dirty, sneaking Rogues with your Turkey Shooter.", points=10, parent="World Events", type=110}}
A{"unknown", 3559, criterion=11161, season="Pilgrim's Bounty", trivia={criteria="Troll Rogue", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Turkey Lurkey", description="Blast those dirty, sneaking Rogues with your Turkey Shooter.", points=10, parent="World Events", type=110}}
A{"unknown", 3559, criterion=11162, season="Pilgrim's Bounty", trivia={criteria="Undead Rogue", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Turkey Lurkey", description="Blast those dirty, sneaking Rogues with your Turkey Shooter.", points=10, parent="World Events", type=110}}
A{"unknown", 3559, criterion=11164, season="Pilgrim's Bounty", trivia={criteria="Dwarf Rogue", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Turkey Lurkey", description="Blast those dirty, sneaking Rogues with your Turkey Shooter.", points=10, parent="World Events", type=110}}
A{"unknown", 3559, criterion=11165, season="Pilgrim's Bounty", trivia={criteria="Gnome Rogue", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Turkey Lurkey", description="Blast those dirty, sneaking Rogues with your Turkey Shooter.", points=10, parent="World Events", type=110}}
A{"unknown", 3559, criterion=11159, season="Pilgrim's Bounty", trivia={criteria="Night Elf Rogue", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Turkey Lurkey", description="Blast those dirty, sneaking Rogues with your Turkey Shooter.", points=10, parent="World Events", type=110}}
A{"unknown", 3559, criterion=11163, season="Pilgrim's Bounty", trivia={criteria="Blood Elf Rogue", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Turkey Lurkey", description="Blast those dirty, sneaking Rogues with your Turkey Shooter.", points=10, parent="World Events", type=110}}
A{"unknown", 3559, criterion=18394, season="Pilgrim's Bounty", trivia={criteria="Goblin Rogue", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Turkey Lurkey", description="Blast those dirty, sneaking Rogues with your Turkey Shooter.", points=10, parent="World Events", type=110}}
A{"unknown", 3559, criterion=18395, season="Pilgrim's Bounty", trivia={criteria="Worgen Rogue", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Turkey Lurkey", description="Blast those dirty, sneaking Rogues with your Turkey Shooter.", points=10, parent="World Events", type=110}}

-- World Events/Pilgrim's Bounty: Now We're Cookin'
A{"unknown", 3576, criterion=11118, side="alliance", season="Pilgrim's Bounty", trivia={criteria="Cranberry Chutney", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Now We're Cookin'", description="Cook up one of every Pilgrim's Bounty dish.", points=10, parent="World Events", type=29}}
A{"unknown", 3576, criterion=11119, side="alliance", season="Pilgrim's Bounty", trivia={criteria="Candied Sweet Potato", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Now We're Cookin'", description="Cook up one of every Pilgrim's Bounty dish.", points=10, parent="World Events", type=29}}
A{"unknown", 3576, criterion=11120, side="alliance", season="Pilgrim's Bounty", trivia={criteria="Pumpkin Pie", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Now We're Cookin'", description="Cook up one of every Pilgrim's Bounty dish.", points=10, parent="World Events", type=29}}
A{"unknown", 3576, criterion=11121, side="alliance", season="Pilgrim's Bounty", trivia={criteria="Slow-Roasted Turkey", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Now We're Cookin'", description="Cook up one of every Pilgrim's Bounty dish.", points=10, parent="World Events", type=29}}
A{"unknown", 3576, criterion=11122, side="alliance", season="Pilgrim's Bounty", trivia={criteria="Spice Bread Stuffing", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Now We're Cookin'", description="Cook up one of every Pilgrim's Bounty dish.", points=10, parent="World Events", type=29}}

-- World Events/Pilgrim's Bounty: Now We're Cookin'
A{"unknown", 3577, criterion=11123, side="horde", season="Pilgrim's Bounty", trivia={criteria="Candied Sweet Potato", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Now We're Cookin'", description="Cook up one of every Pilgrim's Bounty dish.", points=10, parent="World Events", type=29}}
A{"unknown", 3577, criterion=11124, side="horde", season="Pilgrim's Bounty", trivia={criteria="Cranberry Chutney", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Now We're Cookin'", description="Cook up one of every Pilgrim's Bounty dish.", points=10, parent="World Events", type=29}}
A{"unknown", 3577, criterion=11125, side="horde", season="Pilgrim's Bounty", trivia={criteria="Pumpkin Pie", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Now We're Cookin'", description="Cook up one of every Pilgrim's Bounty dish.", points=10, parent="World Events", type=29}}
A{"unknown", 3577, criterion=11126, side="horde", season="Pilgrim's Bounty", trivia={criteria="Slow-Roasted Turkey", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Now We're Cookin'", description="Cook up one of every Pilgrim's Bounty dish.", points=10, parent="World Events", type=29}}
A{"unknown", 3577, criterion=11127, side="horde", season="Pilgrim's Bounty", trivia={criteria="Spice Bread Stuffing", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Now We're Cookin'", description="Cook up one of every Pilgrim's Bounty dish.", points=10, parent="World Events", type=29}}

-- World Events/Pilgrim's Bounty: The Turkinator
A{"unknown", 3578, season="Pilgrim's Bounty", trivia={module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="The Turkinator", description="Hunt enough Wild Turkeys quickly enough to gain Turkey Triumph.", points=10, parent="World Events"}}

-- World Events/Pilgrim's Bounty: "FOOD FIGHT!"
A{"unknown", 3579, season="Pilgrim's Bounty", trivia={module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="\"FOOD FIGHT!\"", description="Bounce food off a fellow feaster's head at a Bountiful Table.", points=10, parent="World Events"}}

-- World Events/Pilgrim's Bounty: Pilgrim's Peril
A{"unknown", 3580, criterion=11134, side="alliance", season="Pilgrim's Bounty", trivia={criteria="Orgrimmar", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Peril", description="While wearing either a Pilgrim's Dress, Robe, or Attire, take a seat at each enemy capital's Bountiful Table.", points=10, parent="World Events", type=69}}
A{"unknown", 3580, criterion=11135, side="alliance", season="Pilgrim's Bounty", trivia={criteria="Silvermoon City", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Peril", description="While wearing either a Pilgrim's Dress, Robe, or Attire, take a seat at each enemy capital's Bountiful Table.", points=10, parent="World Events", type=69}}
A{"unknown", 3580, criterion=11136, side="alliance", season="Pilgrim's Bounty", trivia={criteria="Thunder Bluff", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Peril", description="While wearing either a Pilgrim's Dress, Robe, or Attire, take a seat at each enemy capital's Bountiful Table.", points=10, parent="World Events", type=69}}
A{"unknown", 3580, criterion=11137, side="alliance", season="Pilgrim's Bounty", trivia={criteria="Undercity", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Peril", description="While wearing either a Pilgrim's Dress, Robe, or Attire, take a seat at each enemy capital's Bountiful Table.", points=10, parent="World Events", type=69}}

-- World Events/Pilgrim's Bounty: Pilgrim's Peril
A{"unknown", 3581, criterion=11138, side="horde", season="Pilgrim's Bounty", trivia={criteria="The Exodar", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Peril", description="While wearing either a Pilgrim's Dress, Robe, or Attire, take a seat at each enemy capital's Bountiful Table.", points=10, parent="World Events", type=69}}
A{"unknown", 3581, criterion=11139, side="horde", season="Pilgrim's Bounty", trivia={criteria="Darnassus", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Peril", description="While wearing either a Pilgrim's Dress, Robe, or Attire, take a seat at each enemy capital's Bountiful Table.", points=10, parent="World Events", type=69}}
A{"unknown", 3581, criterion=11140, side="horde", season="Pilgrim's Bounty", trivia={criteria="Ironforge", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Peril", description="While wearing either a Pilgrim's Dress, Robe, or Attire, take a seat at each enemy capital's Bountiful Table.", points=10, parent="World Events", type=69}}
A{"unknown", 3581, criterion=11141, side="horde", season="Pilgrim's Bounty", trivia={criteria="Stormwind", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Peril", description="While wearing either a Pilgrim's Dress, Robe, or Attire, take a seat at each enemy capital's Bountiful Table.", points=10, parent="World Events", type=69}}

-- World Events/Pilgrim's Bounty: Terokkar Turkey Time
A{"unknown", 3582, season="Pilgrim's Bounty", trivia={module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Terokkar Turkey Time", description="Defeat Talon King Ikiss while wearing a Pilgrim's Hat and either a Pilgrim's Dress, Robe, or Attire.", points=10, parent="World Events"}}

-- World Events/Pilgrim's Bounty: Pilgrim's Progress
A{"unknown", 3596, criterion=11202, side="alliance", season="Pilgrim's Bounty", trivia={criteria="Easy As Pie", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Progress", description="Complete each of the Pilgrim's Bounty dailies.", points=10, parent="World Events", type="quest"}}
A{"unknown", 3596, criterion=11198, side="alliance", season="Pilgrim's Bounty", trivia={criteria="She Says Potato", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Progress", description="Complete each of the Pilgrim's Bounty dailies.", points=10, parent="World Events", type="quest"}}
A{"unknown", 3596, criterion=11199, side="alliance", season="Pilgrim's Bounty", trivia={criteria="We're Out of Cranberry Chutney Again?", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Progress", description="Complete each of the Pilgrim's Bounty dailies.", points=10, parent="World Events", type="quest"}}
A{"unknown", 3596, criterion=11200, side="alliance", season="Pilgrim's Bounty", trivia={criteria="Don't Forget The Stuffing!", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Progress", description="Complete each of the Pilgrim's Bounty dailies.", points=10, parent="World Events", type="quest"}}
A{"unknown", 3596, criterion=11201, side="alliance", season="Pilgrim's Bounty", trivia={criteria="Can't Get Enough Turkey", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Progress", description="Complete each of the Pilgrim's Bounty dailies.", points=10, parent="World Events", type="quest"}}

-- World Events/Pilgrim's Bounty: Pilgrim's Progress
A{"unknown", 3597, criterion=11203, side="horde", season="Pilgrim's Bounty", trivia={criteria="Can't Get Enough Turkey", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Progress", description="Complete each of the Pilgrim's Bounty dailies.", points=10, parent="World Events", type="quest"}}
A{"unknown", 3597, criterion=11204, side="horde", season="Pilgrim's Bounty", trivia={criteria="Don't Forget The Stuffing!", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Progress", description="Complete each of the Pilgrim's Bounty dailies.", points=10, parent="World Events", type="quest"}}
A{"unknown", 3597, criterion=11205, side="horde", season="Pilgrim's Bounty", trivia={criteria="Easy As Pie", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Progress", description="Complete each of the Pilgrim's Bounty dailies.", points=10, parent="World Events", type="quest"}}
A{"unknown", 3597, criterion=11206, side="horde", season="Pilgrim's Bounty", trivia={criteria="She Says Potato", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Progress", description="Complete each of the Pilgrim's Bounty dailies.", points=10, parent="World Events", type="quest"}}
A{"unknown", 3597, criterion=11207, side="horde", season="Pilgrim's Bounty", trivia={criteria="We're Out of Cranberry Chutney Again?", module="seasonal_pilgrim", category="World Events/Pilgrim's Bounty", name="Pilgrim's Progress", description="Complete each of the Pilgrim's Bounty dailies.", points=10, parent="World Events", type="quest"}}
